;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
tuck - f69 1
tuck - f67 1
tuck - f65 1
tuck - f63 1
tuck - f61 1
tuck - f59 1
tuck - f57 1
tuck - f55 1
tuck - f53 1
tuck - f51 1
tuck - f49 1
tuck - f47 1
tuck - f45 1
tuck - f43 1
tuck - f41 1
drop f41
drop f43
drop f45
drop f47
drop f49
drop f51
drop f53
drop f55
drop f57
drop f59
drop f61
drop f63
drop f65
drop f67
drop f69
tuck - f40 1
miss + f40 1
tuck - f40 1
miss - f39 1
tuck + f39 1
miss - f39 1
miss - f38 1
tuck + f38 1
miss - f38 1
miss - f37 1
tuck + f37 1
miss - f37 1
miss - f36 1
tuck + f36 1
miss - f36 1
miss - f35 1
tuck + f35 1
miss - f35 1
miss - f34 1
tuck + f34 1
miss - f34 1
miss - f33 1
tuck + f33 1
miss - f33 1
miss - f32 1
tuck + f32 1
miss - f32 1
miss - f31 1
tuck + f31 1
miss - f31 1
miss - f30 1
tuck + f30 1
miss - f30 1
miss - f29 1
tuck + f29 1
miss - f29 1
miss - f28 1
tuck + f28 1
miss - f28 1
miss - f27 1
tuck + f27 1
miss - f27 1
miss - f26 1
tuck + f26 1
miss - f26 1
miss - f25 1
tuck + f25 1
miss - f25 1
miss - f24 1
tuck + f24 1
miss - f24 1
miss - f23 1
tuck + f23 1
miss - f23 1
miss - f22 1
tuck + f22 1
miss - f22 1
miss - f21 1
tuck + f21 1
miss - f21 1
miss - f20 1
tuck + f20 1
miss - f20 1
miss - f19 1
tuck + f19 1
miss - f19 1
miss - f18 1
tuck + f18 1
miss - f18 1
miss - f17 1
tuck + f17 1
miss - f17 1
miss - f16 1
tuck + f16 1
miss - f16 1
miss - f15 1
tuck + f15 1
miss - f15 1
miss - f14 1
tuck + f14 1
miss - f14 1
miss - f13 1
tuck + f13 1
miss - f13 1
miss - f12 1
tuck + f12 1
miss - f12 1
miss - f11 1
tuck + f11 1
miss - f11 1
miss - f10 1
tuck + f10 1
miss - f10 1
miss - f9 1
tuck + f9 1
miss - f9 1
miss - f8 1
tuck + f8 1
miss - f8 1
miss - f7 1
tuck + f7 1
miss - f7 1
miss - f6 1
tuck + f6 1
miss - f6 1
miss - f5 1
tuck + f5 1
miss - f5 1
miss - f4 1
tuck + f4 1
miss - f4 1
miss - f3 1
tuck + f3 1
miss - f3 1
miss - f2 1
tuck + f2 1
miss - f2 1
miss - f1 1
tuck + f1 1
miss - f1 1
miss - f0 1
tuck + f0 1
miss - f0 1
;KS: Cast on 41loops from f40to f0
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
releasehook 1
xfer f35 b35
xfer f23 b23
xfer f11 b11
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b29 f29
xfer b17 f17
xfer b5 f5
xfer f35 b35
xfer f23 b23
xfer f11 b11
xfer f27 b27
xfer f15 b15
xfer f3 b3
xfer f33 b33
xfer f21 b21
xfer f9 b9
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f16 b15
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b15 f15
xfer b3 f3
xfer b33 f33
xfer b21 f21
xfer b9 f9
xfer f31 b31
xfer f19 b19
xfer f7 b7
xfer f37 b37
xfer f25 b25
xfer f13 b13
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f18 b19
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
xfer f24 b25
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b19 f19
xfer b7 f7
xfer b37 f37
xfer b25 f25
xfer b13 f13
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f24 b23
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f18 b17
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b17 f17
xfer b5 f5
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
tuck - f36 1
knit - b35 1
tuck - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
tuck - f30 1
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - b23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
split + f5 b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
split + b11 f11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
split + f17 b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
split + b23 f23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
split + f29 b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
split + b35 f35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b35 f35
xfer b29 f29
xfer b23 f23
xfer b17 f17
xfer b11 f11
xfer b5 f5
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
knit - f39 1
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
knit - f38 1
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
knit - f37 1
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
knit - f36 1
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
knit - f35 1
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
knit - f34 1
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
knit - f33 1
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
knit - f32 1
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
knit - f31 1
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
knit - f30 1
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
knit - f29 1
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
knit - f28 1
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
knit - f27 1
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
knit - f26 1
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
knit - f25 1
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
knit - f24 1
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
knit - f23 1
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
xfer b22 f22
knit - f22 1
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit - f21 1
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
knit - f20 1
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
knit - f19 1
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
knit - f18 1
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
knit - f17 1
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
knit - f16 1
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
knit - f15 1
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
knit - f14 1
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
knit - f13 1
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
knit - f12 1
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
knit - f11 1
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
knit - f10 1
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
knit - f9 1
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
knit - f8 1
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
knit - f7 1
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
knit - f6 1
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
knit - f5 1
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f4 1
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
knit - f3 1
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
knit - f2 1
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit - f1 1
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
knit - f0 1
;KS: Spare knitting on [f0]
knit + f0 1
outhook 1;Cutting active yarn on 1
