;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 6;Activating carrier 6
;KS: Cast on 10loops from 0to 10
tuck - f9 6
tuck - f7 6
tuck - f5 6
tuck - f3 6
tuck - f1 6
tuck + f0 6
tuck + f2 6
tuck + f4 6
tuck + f6 6
tuck + f8 6
tuck - f9 6
tuck - f7 6
tuck - f5 6
tuck - f3 6
tuck - f1 6
tuck + f0 6
tuck + f2 6
tuck + f4 6
tuck + f6 6
tuck + f8 6
releasehook 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - f6 6
knit - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - f6 6
knit - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
inhook 5;Activating carrier 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f9 6
knit - f8 6
knit - f7 6
tuck - f5 5
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 6
knit - f8 6
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 6
knit - f7 6
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 6
knit - f6 6
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 6
knit - f5 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 6
knit - f4 6
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 6
knit - f3 6
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 6
knit - f2 6
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 6
knit - f1 6
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 6
knit - f0 6
;KS: Spare knitting on [b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 6
knit + b1 6
knit + b2 6
knit + b3 6
knit + b4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + b8 6
releasehook 5;Release inserting hook before cutting all yarns
outhook 5;Cutting active yarn on 5
outhook 6;Cutting active yarn on 6
