;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 4;Activating carrier 4
tuck - f31 4
miss + f31 4
tuck - f31 4
miss - f30 4
tuck + f30 4
miss - f30 4
miss - f29 4
tuck + f29 4
miss - f29 4
miss - f28 4
tuck + f28 4
miss - f28 4
miss - f27 4
tuck + f27 4
miss - f27 4
miss - f26 4
tuck + f26 4
miss - f26 4
miss - f25 4
tuck + f25 4
miss - f25 4
miss - f24 4
tuck + f24 4
miss - f24 4
miss - f23 4
tuck + f23 4
miss - f23 4
miss - f22 4
tuck + f22 4
miss - f22 4
miss - f21 4
tuck + f21 4
miss - f21 4
miss - f20 4
tuck + f20 4
miss - f20 4
miss - f19 4
tuck + f19 4
miss - f19 4
miss - f18 4
tuck + f18 4
miss - f18 4
miss - f17 4
tuck + f17 4
miss - f17 4
miss - f16 4
tuck + f16 4
miss - f16 4
miss - f15 4
tuck + f15 4
miss - f15 4
miss - f14 4
tuck + f14 4
miss - f14 4
miss - f13 4
tuck + f13 4
miss - f13 4
miss - f12 4
tuck + f12 4
miss - f12 4
miss - f11 4
tuck + f11 4
miss - f11 4
miss - f10 4
tuck + f10 4
miss - f10 4
miss - f9 4
tuck + f9 4
miss - f9 4
miss - f8 4
tuck + f8 4
miss - f8 4
miss - f7 4
tuck + f7 4
miss - f7 4
miss - f6 4
tuck + f6 4
miss - f6 4
miss - f5 4
tuck + f5 4
miss - f5 4
miss - f4 4
tuck + f4 4
miss - f4 4
miss - f3 4
tuck + f3 4
miss - f3 4
miss - f2 4
tuck + f2 4
miss - f2 4
miss - f1 4
tuck + f1 4
miss - f1 4
miss - f0 4
tuck + f0 4
miss - f0 4
;KS: Cast on 32loops from f30to f0
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit + f30 4
knit - f30 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit + f30 4
releasehook 4
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f28 b27
xfer f26 b25
xfer f24 b23
xfer f22 b21
xfer f20 b19
xfer f18 b17
xfer f16 b15
xfer f14 b13
xfer f12 b11
xfer f10 b9
xfer f8 b7
xfer f6 b5
xfer f4 b3
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
inhook 9;Activating carrier 9
tuck - b30 9
drop b30
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
releasehook 9
;KS: 0
;KS: +
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 4
tuck + b13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 4
tuck + b15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 1
;KS: -
knit - f31 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit - f0 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: 2
;KS: +
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 4
tuck + b13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 4
tuck + b15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 3
;KS: -
knit - f31 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit - f0 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: 4
;KS: +
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 4
tuck + b13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 4
tuck + b15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 5
;KS: -
knit - f31 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit - f0 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: 6
;KS: +
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 4
tuck + b13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 4
tuck + b15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 7
;KS: -
knit - f31 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit - f0 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: 8
;KS: +
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 4
tuck + b13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 4
tuck + b15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 9
;KS: -
knit - f31 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit - f0 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: 10
;KS: +
xfer b15 f15
rack -1;Rack to -1 at 1 gauge
xfer f13 b14
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b14 f15
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
tuck + b13 4
knit + f15 4
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
knit + b13 9
tuck + f15 9
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 11
;KS: -
knit - f31 4
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
split - f15 b15 4
rack -2;Rack to -2 at 1 gauge
xfer b15 f13
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b15 4
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
knit - f0 4
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: inc
;KS: 12
;KS: +
knit + f0 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
knit + f1 4
tuck + b1 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 4
tuck + b3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 4
tuck + b5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 4
tuck + b7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 4
tuck + b9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 4
tuck + b11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 4
tuck + b13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 4
tuck + b15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 4
tuck + b17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 4
tuck + b19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 4
tuck + b21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 4
tuck + b23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 4
tuck + b25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 4
tuck + b27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 4
tuck + b29 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit + f31 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
;KS: 12
;KS: -
knit - f31 4
;KS: 1
rack 0.25;All Needle racking 0.0 to right
tuck - b29 4
knit - f29 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 4
knit - f27 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 4
knit - f25 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 4
knit - f23 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 4
knit - f21 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 4
knit - f19 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 4
knit - f17 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 4
knit - f15 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 4
knit - f13 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 4
knit - f11 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 4
knit - f9 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 4
knit - f7 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 4
knit - f5 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 4
knit - f3 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 4
knit - f1 4
rack 0.0;Reset rack from all_needle
;KS: 2
knit - f0 4
;KS: 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
;KS: 13
;KS: -
outhook 4;Cutting active yarn on 4
outhook 9;Cutting active yarn on 9
;Long float  of carrier 4 (i.e., >20) of 31 between 0 and f31
