;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 5;Activating carrier 5
;KS: Cast on 50loops from 0to 50
tuck - f49 5
tuck - f47 5
tuck - f45 5
tuck - f43 5
tuck - f41 5
tuck - f39 5
tuck - f37 5
tuck - f35 5
tuck - f33 5
tuck - f31 5
tuck - f29 5
tuck - f27 5
tuck - f25 5
tuck - f23 5
tuck - f21 5
tuck - f19 5
tuck - f17 5
tuck - f15 5
tuck - f13 5
tuck - f11 5
tuck - f9 5
tuck - f7 5
tuck - f5 5
tuck - f3 5
tuck - f1 5
tuck + f0 5
tuck + f2 5
tuck + f4 5
tuck + f6 5
tuck + f8 5
tuck + f10 5
tuck + f12 5
tuck + f14 5
tuck + f16 5
tuck + f18 5
tuck + f20 5
tuck + f22 5
tuck + f24 5
tuck + f26 5
tuck + f28 5
tuck + f30 5
tuck + f32 5
tuck + f34 5
tuck + f36 5
tuck + f38 5
tuck + f40 5
tuck + f42 5
tuck + f44 5
tuck + f46 5
tuck + f48 5
tuck - f49 5
tuck - f47 5
tuck - f45 5
tuck - f43 5
tuck - f41 5
tuck - f39 5
tuck - f37 5
tuck - f35 5
tuck - f33 5
tuck - f31 5
tuck - f29 5
tuck - f27 5
tuck - f25 5
tuck - f23 5
tuck - f21 5
tuck - f19 5
tuck - f17 5
tuck - f15 5
tuck - f13 5
tuck - f11 5
tuck - f9 5
tuck - f7 5
tuck - f5 5
tuck - f3 5
tuck - f1 5
tuck + f0 5
tuck + f2 5
tuck + f4 5
tuck + f6 5
tuck + f8 5
tuck + f10 5
tuck + f12 5
tuck + f14 5
tuck + f16 5
tuck + f18 5
tuck + f20 5
tuck + f22 5
tuck + f24 5
tuck + f26 5
tuck + f28 5
tuck + f30 5
tuck + f32 5
tuck + f34 5
tuck + f36 5
tuck + f38 5
tuck + f40 5
tuck + f42 5
tuck + f44 5
tuck + f46 5
tuck + f48 5
releasehook 5
knit - f49 5
knit - f48 5
knit - f47 5
knit - f46 5
knit - f45 5
knit - f44 5
knit - f43 5
knit - f42 5
knit - f41 5
knit - f40 5
knit - f39 5
knit - f38 5
knit - f37 5
knit - f36 5
knit - f35 5
knit - f34 5
knit - f33 5
knit - f32 5
knit - f31 5
knit - f30 5
knit - f29 5
knit - f28 5
knit - f27 5
knit - f26 5
knit - f25 5
knit - f24 5
knit - f23 5
knit - f22 5
knit - f21 5
knit - f20 5
knit - f19 5
knit - f18 5
knit - f17 5
knit - f16 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f16 5
knit + f17 5
knit + f18 5
knit + f19 5
knit + f20 5
knit + f21 5
knit + f22 5
knit + f23 5
knit + f24 5
knit + f25 5
knit + f26 5
knit + f27 5
knit + f28 5
knit + f29 5
knit + f30 5
knit + f31 5
knit + f32 5
knit + f33 5
knit + f34 5
knit + f35 5
knit + f36 5
knit + f37 5
knit + f38 5
knit + f39 5
knit + f40 5
knit + f41 5
knit + f42 5
knit + f43 5
knit + f44 5
knit + f45 5
knit + f46 5
knit + f47 5
knit + f48 5
knit + f49 5
knit - f49 5
knit - f48 5
knit - f47 5
knit - f46 5
knit - f45 5
knit - f44 5
knit - f43 5
knit - f42 5
knit - f41 5
knit - f40 5
knit - f39 5
knit - f38 5
knit - f37 5
knit - f36 5
knit - f35 5
knit - f34 5
knit - f33 5
knit - f32 5
knit - f31 5
knit - f30 5
knit - f29 5
knit - f28 5
knit - f27 5
knit - f26 5
knit - f25 5
knit - f24 5
knit - f23 5
knit - f22 5
knit - f21 5
knit - f20 5
knit - f19 5
knit - f18 5
knit - f17 5
knit - f16 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f16 5
knit + f17 5
knit + f18 5
knit + f19 5
knit + f20 5
knit + f21 5
knit + f22 5
knit + f23 5
knit + f24 5
knit + f25 5
knit + f26 5
knit + f27 5
knit + f28 5
knit + f29 5
knit + f30 5
knit + f31 5
knit + f32 5
knit + f33 5
knit + f34 5
knit + f35 5
knit + f36 5
knit + f37 5
knit + f38 5
knit + f39 5
knit + f40 5
knit + f41 5
knit + f42 5
knit + f43 5
knit + f44 5
knit + f45 5
knit + f46 5
knit + f47 5
knit + f48 5
knit + f49 5
knit - f49 5
knit - f48 5
knit - f47 5
knit - f46 5
knit - f45 5
knit - f44 5
knit - f43 5
knit - f42 5
knit - f41 5
knit - f40 5
knit - f39 5
knit - f38 5
knit - f37 5
knit - f36 5
knit - f35 5
knit - f34 5
knit - f33 5
knit - f32 5
knit - f31 5
knit - f30 5
knit - f29 5
knit - f28 5
knit - f27 5
knit - f26 5
knit - f25 5
knit - f24 5
knit - f23 5
knit - f22 5
knit - f21 5
knit - f20 5
knit - f19 5
knit - f18 5
knit - f17 5
knit - f16 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f16 5
knit + f17 5
knit + f18 5
knit + f19 5
knit + f20 5
knit + f21 5
knit + f22 5
knit + f23 5
knit + f24 5
knit + f25 5
knit + f26 5
knit + f27 5
knit + f28 5
knit + f29 5
knit + f30 5
knit + f31 5
knit + f32 5
knit + f33 5
knit + f34 5
knit + f35 5
knit + f36 5
knit + f37 5
knit + f38 5
knit + f39 5
knit + f40 5
knit + f41 5
knit + f42 5
knit + f43 5
knit + f44 5
knit + f45 5
knit + f46 5
knit + f47 5
knit + f48 5
knit + f49 5
inhook 2;Activating carrier 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
rack -3;Rack to -3 at 1 gauge
xfer f49 b52
xfer f48 b51
xfer f47 b50
xfer f46 b49
xfer f45 b48
xfer f44 b47
xfer f43 b46
xfer f42 b45
xfer f41 b44
xfer f40 b43
xfer f39 b42
xfer f38 b41
xfer f37 b40
xfer f36 b39
xfer f35 b38
xfer f34 b37
xfer f33 b36
xfer f32 b35
xfer f31 b34
xfer f30 b33
xfer f29 b32
xfer f28 b31
xfer f27 b30
xfer f26 b29
xfer f25 b28
xfer f24 b27
xfer f23 b26
xfer f22 b25
xfer f21 b24
xfer f20 b23
xfer f19 b22
xfer f18 b21
xfer f17 b20
xfer f16 b19
xfer f15 b18
xfer f14 b17
xfer f13 b16
xfer f12 b15
xfer f11 b14
xfer f10 b13
xfer f9 b12
xfer f8 b11
xfer f7 b10
xfer f6 b9
xfer f5 b8
xfer f4 b7
xfer f3 b6
xfer f2 b5
xfer f1 b4
xfer f0 b3
rack 0.0;Rack to 0.0 at 1 gauge
knit - b52 5
knit - b51 5
knit - b50 5
knit - b49 5
knit - b48 5
knit - b47 5
knit - b46 5
knit - b45 5
knit - b44 5
knit - b43 5
knit - b42 5
knit - b41 5
knit - b40 5
knit - b39 5
knit - b38 5
knit - b37 5
knit - b36 5
knit - b35 5
knit - b34 5
knit - b33 5
knit - b32 5
knit - b31 5
knit - b30 5
knit - b29 5
knit - b28 5
knit - b27 5
knit - b26 5
knit - b25 5
knit - b24 5
knit - b23 5
knit - b22 5
knit - b21 5
knit - b20 5
knit - b19 5
knit - b18 5
knit - b17 5
knit - b16 5
knit - b15 5
knit - b14 5
knit - b13 5
knit - b12 5
knit - b11 5
knit - b10 5
knit - b9 5
knit - b8 5
knit - b7 5
knit - b6 5
knit - b5 5
knit - b4 5
knit - b3 5
knit + b3 5
knit + b4 5
knit + b5 5
knit + b6 5
knit + b7 5
knit + b8 5
knit + b9 5
knit + b10 5
knit + b11 5
knit + b12 5
knit + b13 5
knit + b14 5
knit + b15 5
knit + b16 5
knit + b17 5
knit + b18 5
knit + b19 5
knit + b20 5
knit + b21 5
knit + b22 5
knit + b23 5
knit + b24 5
knit + b25 5
knit + b26 5
knit + b27 5
knit + b28 5
knit + b29 5
knit + b30 5
knit + b31 5
knit + b32 5
knit + b33 5
knit + b34 5
knit + b35 5
knit + b36 5
knit + b37 5
knit + b38 5
knit + b39 5
knit + b40 5
knit + b41 5
knit + b42 5
knit + b43 5
knit + b44 5
knit + b45 5
knit + b46 5
knit + b47 5
knit + b48 5
knit + b49 5
knit + b50 5
knit + b51 5
knit + b52 5
rack -3;Rack to -3 at 1 gauge
xfer b52 f49
xfer b51 f48
xfer b50 f47
xfer b49 f46
xfer b48 f45
xfer b47 f44
xfer b46 f43
xfer b45 f42
xfer b44 f41
xfer b43 f40
xfer b42 f39
xfer b41 f38
xfer b40 f37
xfer b39 f36
xfer b38 f35
xfer b37 f34
xfer b36 f33
xfer b35 f32
xfer b34 f31
xfer b33 f30
xfer b32 f29
xfer b31 f28
xfer b30 f27
xfer b29 f26
xfer b28 f25
xfer b27 f24
xfer b26 f23
xfer b25 f22
xfer b24 f21
xfer b23 f20
xfer b22 f19
xfer b21 f18
xfer b20 f17
xfer b19 f16
xfer b18 f15
xfer b17 f14
xfer b16 f13
xfer b15 f12
xfer b14 f11
xfer b13 f10
xfer b12 f9
xfer b11 f8
xfer b10 f7
xfer b9 f6
xfer b8 f5
xfer b7 f4
xfer b6 f3
xfer b5 f2
xfer b4 f1
xfer b3 f0
rack 0.0;Rack to 0.0 at 1 gauge
knit - f49 5
knit - f48 5
knit - f47 5
knit - f46 5
knit - f45 5
knit - f44 5
knit - f43 5
knit - f42 5
knit - f41 5
knit - f40 5
knit - f39 5
knit - f38 5
knit - f37 5
knit - f36 5
knit - f35 5
knit - f34 5
knit - f33 5
knit - f32 5
knit - f31 5
knit - f30 5
knit - f29 5
knit - f28 5
knit - f27 5
knit - f26 5
knit - f25 5
knit - f24 5
knit - f23 5
knit - f22 5
knit - f21 5
knit - f20 5
knit - f19 5
knit - f18 5
knit - f17 5
knit - f16 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f16 5
knit + f17 5
knit + f18 5
knit + f19 5
knit + f20 5
knit + f21 5
knit + f22 5
knit + f23 5
knit + f24 5
knit + f25 5
knit + f26 5
knit + f27 5
knit + f28 5
knit + f29 5
knit + f30 5
knit + f31 5
knit + f32 5
knit + f33 5
knit + f34 5
knit + f35 5
knit + f36 5
knit + f37 5
knit + f38 5
knit + f39 5
knit + f40 5
knit + f41 5
knit + f42 5
knit + f43 5
knit + f44 5
knit + f45 5
knit + f46 5
knit + f47 5
knit + f48 5
knit + f49 5
releasehook 2;Release inserting hook before cutting all yarns
outhook 2;Cutting active yarn on 2
outhook 5;Cutting active yarn on 5
