;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
;KS: Cast on 30loops from 0to 30
tuck - f58 1
tuck - f54 1
tuck - f50 1
tuck - f46 1
tuck - f42 1
tuck - f38 1
tuck - f34 1
tuck - f30 1
tuck - f26 1
tuck - f22 1
tuck - f18 1
tuck - f14 1
tuck - f10 1
tuck - f6 1
tuck - f2 1
tuck + f0 1
tuck + f4 1
tuck + f8 1
tuck + f12 1
tuck + f16 1
tuck + f20 1
tuck + f24 1
tuck + f28 1
tuck + f32 1
tuck + f36 1
tuck + f40 1
tuck + f44 1
tuck + f48 1
tuck + f52 1
tuck + f56 1
tuck - f58 1
tuck - f54 1
tuck - f50 1
tuck - f46 1
tuck - f42 1
tuck - f38 1
tuck - f34 1
tuck - f30 1
tuck - f26 1
tuck - f22 1
tuck - f18 1
tuck - f14 1
tuck - f10 1
tuck - f6 1
tuck - f2 1
tuck + f0 1
tuck + f4 1
tuck + f8 1
tuck + f12 1
tuck + f16 1
tuck + f20 1
tuck + f24 1
tuck + f28 1
tuck + f32 1
tuck + f36 1
tuck + f40 1
tuck + f44 1
tuck + f48 1
tuck + f52 1
tuck + f56 1
releasehook 1
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;KS: Cast on 30loops from 0to 30
tuck - f59 1
tuck - f55 1
tuck - f51 1
tuck - f47 1
tuck - f43 1
tuck - f39 1
tuck - f35 1
tuck - f31 1
tuck - f27 1
tuck - f23 1
tuck - f19 1
tuck - f15 1
tuck - f11 1
tuck - f7 1
tuck - f3 1
tuck + f1 1
tuck + f5 1
tuck + f9 1
tuck + f13 1
tuck + f17 1
tuck + f21 1
tuck + f25 1
tuck + f29 1
tuck + f33 1
tuck + f37 1
tuck + f41 1
tuck + f45 1
tuck + f49 1
tuck + f53 1
tuck + f57 1
tuck - f59 1
tuck - f55 1
tuck - f51 1
tuck - f47 1
tuck - f43 1
tuck - f39 1
tuck - f35 1
tuck - f31 1
tuck - f27 1
tuck - f23 1
tuck - f19 1
tuck - f15 1
tuck - f11 1
tuck - f7 1
tuck - f3 1
tuck + f1 1
tuck + f5 1
tuck + f9 1
tuck + f13 1
tuck + f17 1
tuck + f21 1
tuck + f25 1
tuck + f29 1
tuck + f33 1
tuck + f37 1
tuck + f41 1
tuck + f45 1
tuck + f49 1
tuck + f53 1
tuck + f57 1
;no-op. Releasehook with no hooked carriers
knit - f59 1
knit - f57 1
knit - f55 1
knit - f53 1
knit - f51 1
knit - f49 1
knit - f47 1
knit - f45 1
knit - f43 1
knit - f41 1
knit - f39 1
knit - f37 1
knit - f35 1
knit - f33 1
knit - f31 1
knit - f29 1
knit - f27 1
knit - f25 1
knit - f23 1
knit - f21 1
knit - f19 1
knit - f17 1
knit - f15 1
knit - f13 1
knit - f11 1
knit - f9 1
knit - f7 1
knit - f5 1
knit - f3 1
knit - f1 1
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
knit - f59 1
knit - f57 1
knit - f55 1
knit - f53 1
knit - f51 1
knit - f49 1
knit - f47 1
knit - f45 1
knit - f43 1
knit - f41 1
knit - f39 1
knit - f37 1
knit - f35 1
knit - f33 1
knit - f31 1
knit - f29 1
knit - f27 1
knit - f25 1
knit - f23 1
knit - f21 1
knit - f19 1
knit - f17 1
knit - f15 1
knit - f13 1
knit - f11 1
knit - f9 1
knit - f7 1
knit - f5 1
knit - f3 1
knit - f1 1
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [330 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [331 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [332 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [333 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [334 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [335 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [336 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [337 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [338 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [339 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [340 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [341 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [342 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [343 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [344 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [345 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [346 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [347 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [348 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [349 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [350 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [351 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [352 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [353 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [354 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [355 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [356 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [357 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [358 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [359 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [330 on yarn 1]
xfer b3 f3;return loops [331 on yarn 1]
xfer b5 f5;return loops [332 on yarn 1]
xfer b7 f7;return loops [333 on yarn 1]
xfer b9 f9;return loops [334 on yarn 1]
xfer b11 f11;return loops [335 on yarn 1]
xfer b13 f13;return loops [336 on yarn 1]
xfer b15 f15;return loops [337 on yarn 1]
xfer b17 f17;return loops [338 on yarn 1]
xfer b19 f19;return loops [339 on yarn 1]
xfer b21 f21;return loops [340 on yarn 1]
xfer b23 f23;return loops [341 on yarn 1]
xfer b25 f25;return loops [342 on yarn 1]
xfer b27 f27;return loops [343 on yarn 1]
xfer b29 f29;return loops [344 on yarn 1]
xfer b31 f31;return loops [345 on yarn 1]
xfer b33 f33;return loops [346 on yarn 1]
xfer b35 f35;return loops [347 on yarn 1]
xfer b37 f37;return loops [348 on yarn 1]
xfer b39 f39;return loops [349 on yarn 1]
xfer b41 f41;return loops [350 on yarn 1]
xfer b43 f43;return loops [351 on yarn 1]
xfer b45 f45;return loops [352 on yarn 1]
xfer b47 f47;return loops [353 on yarn 1]
xfer b49 f49;return loops [354 on yarn 1]
xfer b51 f51;return loops [355 on yarn 1]
xfer b53 f53;return loops [356 on yarn 1]
xfer b55 f55;return loops [357 on yarn 1]
xfer b57 f57;return loops [358 on yarn 1]
xfer b59 f59;return loops [359 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [390 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [391 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [392 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [393 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [394 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [395 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [396 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [397 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [398 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [399 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [400 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [401 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [402 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [403 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [404 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [405 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [406 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [407 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [408 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [409 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [410 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [411 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [412 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [413 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [414 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [415 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [416 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [417 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [418 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [419 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [390 on yarn 1]
xfer b3 f3;return loops [391 on yarn 1]
xfer b5 f5;return loops [392 on yarn 1]
xfer b7 f7;return loops [393 on yarn 1]
xfer b9 f9;return loops [394 on yarn 1]
xfer b11 f11;return loops [395 on yarn 1]
xfer b13 f13;return loops [396 on yarn 1]
xfer b15 f15;return loops [397 on yarn 1]
xfer b17 f17;return loops [398 on yarn 1]
xfer b19 f19;return loops [399 on yarn 1]
xfer b21 f21;return loops [400 on yarn 1]
xfer b23 f23;return loops [401 on yarn 1]
xfer b25 f25;return loops [402 on yarn 1]
xfer b27 f27;return loops [403 on yarn 1]
xfer b29 f29;return loops [404 on yarn 1]
xfer b31 f31;return loops [405 on yarn 1]
xfer b33 f33;return loops [406 on yarn 1]
xfer b35 f35;return loops [407 on yarn 1]
xfer b37 f37;return loops [408 on yarn 1]
xfer b39 f39;return loops [409 on yarn 1]
xfer b41 f41;return loops [410 on yarn 1]
xfer b43 f43;return loops [411 on yarn 1]
xfer b45 f45;return loops [412 on yarn 1]
xfer b47 f47;return loops [413 on yarn 1]
xfer b49 f49;return loops [414 on yarn 1]
xfer b51 f51;return loops [415 on yarn 1]
xfer b53 f53;return loops [416 on yarn 1]
xfer b55 f55;return loops [417 on yarn 1]
xfer b57 f57;return loops [418 on yarn 1]
xfer b59 f59;return loops [419 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [450 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [451 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [452 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [453 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [454 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [455 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [456 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [457 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [458 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [459 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [460 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [461 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [462 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [463 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [464 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [465 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [466 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [467 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [468 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [469 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [470 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [471 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [472 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [473 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [474 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [475 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [476 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [477 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [478 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [479 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [450 on yarn 1]
xfer b3 f3;return loops [451 on yarn 1]
xfer b5 f5;return loops [452 on yarn 1]
xfer b7 f7;return loops [453 on yarn 1]
xfer b9 f9;return loops [454 on yarn 1]
xfer b11 f11;return loops [455 on yarn 1]
xfer b13 f13;return loops [456 on yarn 1]
xfer b15 f15;return loops [457 on yarn 1]
xfer b17 f17;return loops [458 on yarn 1]
xfer b19 f19;return loops [459 on yarn 1]
xfer b21 f21;return loops [460 on yarn 1]
xfer b23 f23;return loops [461 on yarn 1]
xfer b25 f25;return loops [462 on yarn 1]
xfer b27 f27;return loops [463 on yarn 1]
xfer b29 f29;return loops [464 on yarn 1]
xfer b31 f31;return loops [465 on yarn 1]
xfer b33 f33;return loops [466 on yarn 1]
xfer b35 f35;return loops [467 on yarn 1]
xfer b37 f37;return loops [468 on yarn 1]
xfer b39 f39;return loops [469 on yarn 1]
xfer b41 f41;return loops [470 on yarn 1]
xfer b43 f43;return loops [471 on yarn 1]
xfer b45 f45;return loops [472 on yarn 1]
xfer b47 f47;return loops [473 on yarn 1]
xfer b49 f49;return loops [474 on yarn 1]
xfer b51 f51;return loops [475 on yarn 1]
xfer b53 f53;return loops [476 on yarn 1]
xfer b55 f55;return loops [477 on yarn 1]
xfer b57 f57;return loops [478 on yarn 1]
xfer b59 f59;return loops [479 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [510 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [511 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [512 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [513 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [514 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [515 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [516 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [517 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [518 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [519 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [520 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [521 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [522 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [523 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [524 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [525 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [526 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [527 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [528 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [529 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [530 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [531 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [532 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [533 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [534 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [535 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [536 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [537 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [538 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [539 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [510 on yarn 1]
xfer b3 f3;return loops [511 on yarn 1]
xfer b5 f5;return loops [512 on yarn 1]
xfer b7 f7;return loops [513 on yarn 1]
xfer b9 f9;return loops [514 on yarn 1]
xfer b11 f11;return loops [515 on yarn 1]
xfer b13 f13;return loops [516 on yarn 1]
xfer b15 f15;return loops [517 on yarn 1]
xfer b17 f17;return loops [518 on yarn 1]
xfer b19 f19;return loops [519 on yarn 1]
xfer b21 f21;return loops [520 on yarn 1]
xfer b23 f23;return loops [521 on yarn 1]
xfer b25 f25;return loops [522 on yarn 1]
xfer b27 f27;return loops [523 on yarn 1]
xfer b29 f29;return loops [524 on yarn 1]
xfer b31 f31;return loops [525 on yarn 1]
xfer b33 f33;return loops [526 on yarn 1]
xfer b35 f35;return loops [527 on yarn 1]
xfer b37 f37;return loops [528 on yarn 1]
xfer b39 f39;return loops [529 on yarn 1]
xfer b41 f41;return loops [530 on yarn 1]
xfer b43 f43;return loops [531 on yarn 1]
xfer b45 f45;return loops [532 on yarn 1]
xfer b47 f47;return loops [533 on yarn 1]
xfer b49 f49;return loops [534 on yarn 1]
xfer b51 f51;return loops [535 on yarn 1]
xfer b53 f53;return loops [536 on yarn 1]
xfer b55 f55;return loops [537 on yarn 1]
xfer b57 f57;return loops [538 on yarn 1]
xfer b59 f59;return loops [539 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [570 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [571 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [572 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [573 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [574 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [575 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [576 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [577 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [578 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [579 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [580 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [581 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [582 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [583 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [584 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [585 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [586 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [587 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [588 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [589 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [590 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [591 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [592 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [593 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [594 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [595 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [596 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [597 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [598 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [599 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [570 on yarn 1]
xfer b3 f3;return loops [571 on yarn 1]
xfer b5 f5;return loops [572 on yarn 1]
xfer b7 f7;return loops [573 on yarn 1]
xfer b9 f9;return loops [574 on yarn 1]
xfer b11 f11;return loops [575 on yarn 1]
xfer b13 f13;return loops [576 on yarn 1]
xfer b15 f15;return loops [577 on yarn 1]
xfer b17 f17;return loops [578 on yarn 1]
xfer b19 f19;return loops [579 on yarn 1]
xfer b21 f21;return loops [580 on yarn 1]
xfer b23 f23;return loops [581 on yarn 1]
xfer b25 f25;return loops [582 on yarn 1]
xfer b27 f27;return loops [583 on yarn 1]
xfer b29 f29;return loops [584 on yarn 1]
xfer b31 f31;return loops [585 on yarn 1]
xfer b33 f33;return loops [586 on yarn 1]
xfer b35 f35;return loops [587 on yarn 1]
xfer b37 f37;return loops [588 on yarn 1]
xfer b39 f39;return loops [589 on yarn 1]
xfer b41 f41;return loops [590 on yarn 1]
xfer b43 f43;return loops [591 on yarn 1]
xfer b45 f45;return loops [592 on yarn 1]
xfer b47 f47;return loops [593 on yarn 1]
xfer b49 f49;return loops [594 on yarn 1]
xfer b51 f51;return loops [595 on yarn 1]
xfer b53 f53;return loops [596 on yarn 1]
xfer b55 f55;return loops [597 on yarn 1]
xfer b57 f57;return loops [598 on yarn 1]
xfer b59 f59;return loops [599 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [630 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [631 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [632 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [633 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [634 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [635 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [636 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [637 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [638 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [639 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [640 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [641 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [642 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [643 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [644 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [645 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [646 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [647 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [648 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [649 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [650 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [651 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [652 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [653 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [654 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [655 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [656 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [657 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [658 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [659 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [630 on yarn 1]
xfer b3 f3;return loops [631 on yarn 1]
xfer b5 f5;return loops [632 on yarn 1]
xfer b7 f7;return loops [633 on yarn 1]
xfer b9 f9;return loops [634 on yarn 1]
xfer b11 f11;return loops [635 on yarn 1]
xfer b13 f13;return loops [636 on yarn 1]
xfer b15 f15;return loops [637 on yarn 1]
xfer b17 f17;return loops [638 on yarn 1]
xfer b19 f19;return loops [639 on yarn 1]
xfer b21 f21;return loops [640 on yarn 1]
xfer b23 f23;return loops [641 on yarn 1]
xfer b25 f25;return loops [642 on yarn 1]
xfer b27 f27;return loops [643 on yarn 1]
xfer b29 f29;return loops [644 on yarn 1]
xfer b31 f31;return loops [645 on yarn 1]
xfer b33 f33;return loops [646 on yarn 1]
xfer b35 f35;return loops [647 on yarn 1]
xfer b37 f37;return loops [648 on yarn 1]
xfer b39 f39;return loops [649 on yarn 1]
xfer b41 f41;return loops [650 on yarn 1]
xfer b43 f43;return loops [651 on yarn 1]
xfer b45 f45;return loops [652 on yarn 1]
xfer b47 f47;return loops [653 on yarn 1]
xfer b49 f49;return loops [654 on yarn 1]
xfer b51 f51;return loops [655 on yarn 1]
xfer b53 f53;return loops [656 on yarn 1]
xfer b55 f55;return loops [657 on yarn 1]
xfer b57 f57;return loops [658 on yarn 1]
xfer b59 f59;return loops [659 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [690 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [691 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [692 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [693 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [694 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [695 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [696 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [697 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [698 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [699 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [700 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [701 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [702 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [703 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [704 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [705 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [706 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [707 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [708 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [709 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [710 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [711 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [712 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [713 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [714 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [715 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [716 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [717 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [718 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [719 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [690 on yarn 1]
xfer b3 f3;return loops [691 on yarn 1]
xfer b5 f5;return loops [692 on yarn 1]
xfer b7 f7;return loops [693 on yarn 1]
xfer b9 f9;return loops [694 on yarn 1]
xfer b11 f11;return loops [695 on yarn 1]
xfer b13 f13;return loops [696 on yarn 1]
xfer b15 f15;return loops [697 on yarn 1]
xfer b17 f17;return loops [698 on yarn 1]
xfer b19 f19;return loops [699 on yarn 1]
xfer b21 f21;return loops [700 on yarn 1]
xfer b23 f23;return loops [701 on yarn 1]
xfer b25 f25;return loops [702 on yarn 1]
xfer b27 f27;return loops [703 on yarn 1]
xfer b29 f29;return loops [704 on yarn 1]
xfer b31 f31;return loops [705 on yarn 1]
xfer b33 f33;return loops [706 on yarn 1]
xfer b35 f35;return loops [707 on yarn 1]
xfer b37 f37;return loops [708 on yarn 1]
xfer b39 f39;return loops [709 on yarn 1]
xfer b41 f41;return loops [710 on yarn 1]
xfer b43 f43;return loops [711 on yarn 1]
xfer b45 f45;return loops [712 on yarn 1]
xfer b47 f47;return loops [713 on yarn 1]
xfer b49 f49;return loops [714 on yarn 1]
xfer b51 f51;return loops [715 on yarn 1]
xfer b53 f53;return loops [716 on yarn 1]
xfer b55 f55;return loops [717 on yarn 1]
xfer b57 f57;return loops [718 on yarn 1]
xfer b59 f59;return loops [719 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [750 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [751 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [752 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [753 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [754 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [755 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [756 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [757 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [758 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [759 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [760 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [761 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [762 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [763 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [764 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [765 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [766 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [767 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [768 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [769 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [770 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [771 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [772 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [773 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [774 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [775 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [776 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [777 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [778 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [779 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [750 on yarn 1]
xfer b3 f3;return loops [751 on yarn 1]
xfer b5 f5;return loops [752 on yarn 1]
xfer b7 f7;return loops [753 on yarn 1]
xfer b9 f9;return loops [754 on yarn 1]
xfer b11 f11;return loops [755 on yarn 1]
xfer b13 f13;return loops [756 on yarn 1]
xfer b15 f15;return loops [757 on yarn 1]
xfer b17 f17;return loops [758 on yarn 1]
xfer b19 f19;return loops [759 on yarn 1]
xfer b21 f21;return loops [760 on yarn 1]
xfer b23 f23;return loops [761 on yarn 1]
xfer b25 f25;return loops [762 on yarn 1]
xfer b27 f27;return loops [763 on yarn 1]
xfer b29 f29;return loops [764 on yarn 1]
xfer b31 f31;return loops [765 on yarn 1]
xfer b33 f33;return loops [766 on yarn 1]
xfer b35 f35;return loops [767 on yarn 1]
xfer b37 f37;return loops [768 on yarn 1]
xfer b39 f39;return loops [769 on yarn 1]
xfer b41 f41;return loops [770 on yarn 1]
xfer b43 f43;return loops [771 on yarn 1]
xfer b45 f45;return loops [772 on yarn 1]
xfer b47 f47;return loops [773 on yarn 1]
xfer b49 f49;return loops [774 on yarn 1]
xfer b51 f51;return loops [775 on yarn 1]
xfer b53 f53;return loops [776 on yarn 1]
xfer b55 f55;return loops [777 on yarn 1]
xfer b57 f57;return loops [778 on yarn 1]
xfer b59 f59;return loops [779 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [810 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [811 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [812 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [813 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [814 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [815 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [816 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [817 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [818 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [819 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [820 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [821 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [822 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [823 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [824 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [825 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [826 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [827 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [828 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [829 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [830 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [831 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [832 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [833 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [834 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [835 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [836 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [837 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [838 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [839 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [810 on yarn 1]
xfer b3 f3;return loops [811 on yarn 1]
xfer b5 f5;return loops [812 on yarn 1]
xfer b7 f7;return loops [813 on yarn 1]
xfer b9 f9;return loops [814 on yarn 1]
xfer b11 f11;return loops [815 on yarn 1]
xfer b13 f13;return loops [816 on yarn 1]
xfer b15 f15;return loops [817 on yarn 1]
xfer b17 f17;return loops [818 on yarn 1]
xfer b19 f19;return loops [819 on yarn 1]
xfer b21 f21;return loops [820 on yarn 1]
xfer b23 f23;return loops [821 on yarn 1]
xfer b25 f25;return loops [822 on yarn 1]
xfer b27 f27;return loops [823 on yarn 1]
xfer b29 f29;return loops [824 on yarn 1]
xfer b31 f31;return loops [825 on yarn 1]
xfer b33 f33;return loops [826 on yarn 1]
xfer b35 f35;return loops [827 on yarn 1]
xfer b37 f37;return loops [828 on yarn 1]
xfer b39 f39;return loops [829 on yarn 1]
xfer b41 f41;return loops [830 on yarn 1]
xfer b43 f43;return loops [831 on yarn 1]
xfer b45 f45;return loops [832 on yarn 1]
xfer b47 f47;return loops [833 on yarn 1]
xfer b49 f49;return loops [834 on yarn 1]
xfer b51 f51;return loops [835 on yarn 1]
xfer b53 f53;return loops [836 on yarn 1]
xfer b55 f55;return loops [837 on yarn 1]
xfer b57 f57;return loops [838 on yarn 1]
xfer b59 f59;return loops [839 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [870 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [871 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [872 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [873 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [874 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [875 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [876 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [877 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [878 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [879 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [880 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [881 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [882 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [883 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [884 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [885 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [886 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [887 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [888 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [889 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [890 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [891 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [892 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [893 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [894 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [895 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [896 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [897 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [898 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [899 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [870 on yarn 1]
xfer b3 f3;return loops [871 on yarn 1]
xfer b5 f5;return loops [872 on yarn 1]
xfer b7 f7;return loops [873 on yarn 1]
xfer b9 f9;return loops [874 on yarn 1]
xfer b11 f11;return loops [875 on yarn 1]
xfer b13 f13;return loops [876 on yarn 1]
xfer b15 f15;return loops [877 on yarn 1]
xfer b17 f17;return loops [878 on yarn 1]
xfer b19 f19;return loops [879 on yarn 1]
xfer b21 f21;return loops [880 on yarn 1]
xfer b23 f23;return loops [881 on yarn 1]
xfer b25 f25;return loops [882 on yarn 1]
xfer b27 f27;return loops [883 on yarn 1]
xfer b29 f29;return loops [884 on yarn 1]
xfer b31 f31;return loops [885 on yarn 1]
xfer b33 f33;return loops [886 on yarn 1]
xfer b35 f35;return loops [887 on yarn 1]
xfer b37 f37;return loops [888 on yarn 1]
xfer b39 f39;return loops [889 on yarn 1]
xfer b41 f41;return loops [890 on yarn 1]
xfer b43 f43;return loops [891 on yarn 1]
xfer b45 f45;return loops [892 on yarn 1]
xfer b47 f47;return loops [893 on yarn 1]
xfer b49 f49;return loops [894 on yarn 1]
xfer b51 f51;return loops [895 on yarn 1]
xfer b53 f53;return loops [896 on yarn 1]
xfer b55 f55;return loops [897 on yarn 1]
xfer b57 f57;return loops [898 on yarn 1]
xfer b59 f59;return loops [899 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [930 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [931 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [932 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [933 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [934 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [935 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [936 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [937 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [938 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [939 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [940 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [941 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [942 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [943 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [944 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [945 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [946 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [947 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [948 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [949 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [950 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [951 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [952 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [953 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [954 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [955 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [956 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [957 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [958 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [959 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [930 on yarn 1]
xfer b3 f3;return loops [931 on yarn 1]
xfer b5 f5;return loops [932 on yarn 1]
xfer b7 f7;return loops [933 on yarn 1]
xfer b9 f9;return loops [934 on yarn 1]
xfer b11 f11;return loops [935 on yarn 1]
xfer b13 f13;return loops [936 on yarn 1]
xfer b15 f15;return loops [937 on yarn 1]
xfer b17 f17;return loops [938 on yarn 1]
xfer b19 f19;return loops [939 on yarn 1]
xfer b21 f21;return loops [940 on yarn 1]
xfer b23 f23;return loops [941 on yarn 1]
xfer b25 f25;return loops [942 on yarn 1]
xfer b27 f27;return loops [943 on yarn 1]
xfer b29 f29;return loops [944 on yarn 1]
xfer b31 f31;return loops [945 on yarn 1]
xfer b33 f33;return loops [946 on yarn 1]
xfer b35 f35;return loops [947 on yarn 1]
xfer b37 f37;return loops [948 on yarn 1]
xfer b39 f39;return loops [949 on yarn 1]
xfer b41 f41;return loops [950 on yarn 1]
xfer b43 f43;return loops [951 on yarn 1]
xfer b45 f45;return loops [952 on yarn 1]
xfer b47 f47;return loops [953 on yarn 1]
xfer b49 f49;return loops [954 on yarn 1]
xfer b51 f51;return loops [955 on yarn 1]
xfer b53 f53;return loops [956 on yarn 1]
xfer b55 f55;return loops [957 on yarn 1]
xfer b57 f57;return loops [958 on yarn 1]
xfer b59 f59;return loops [959 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [990 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [991 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [992 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [993 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [994 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [995 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [996 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [997 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [998 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [999 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1000 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1001 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1002 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1003 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1004 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1005 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1006 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1007 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1008 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1009 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1010 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1011 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1012 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1013 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1014 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1015 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1016 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1017 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1018 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1019 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [990 on yarn 1]
xfer b3 f3;return loops [991 on yarn 1]
xfer b5 f5;return loops [992 on yarn 1]
xfer b7 f7;return loops [993 on yarn 1]
xfer b9 f9;return loops [994 on yarn 1]
xfer b11 f11;return loops [995 on yarn 1]
xfer b13 f13;return loops [996 on yarn 1]
xfer b15 f15;return loops [997 on yarn 1]
xfer b17 f17;return loops [998 on yarn 1]
xfer b19 f19;return loops [999 on yarn 1]
xfer b21 f21;return loops [1000 on yarn 1]
xfer b23 f23;return loops [1001 on yarn 1]
xfer b25 f25;return loops [1002 on yarn 1]
xfer b27 f27;return loops [1003 on yarn 1]
xfer b29 f29;return loops [1004 on yarn 1]
xfer b31 f31;return loops [1005 on yarn 1]
xfer b33 f33;return loops [1006 on yarn 1]
xfer b35 f35;return loops [1007 on yarn 1]
xfer b37 f37;return loops [1008 on yarn 1]
xfer b39 f39;return loops [1009 on yarn 1]
xfer b41 f41;return loops [1010 on yarn 1]
xfer b43 f43;return loops [1011 on yarn 1]
xfer b45 f45;return loops [1012 on yarn 1]
xfer b47 f47;return loops [1013 on yarn 1]
xfer b49 f49;return loops [1014 on yarn 1]
xfer b51 f51;return loops [1015 on yarn 1]
xfer b53 f53;return loops [1016 on yarn 1]
xfer b55 f55;return loops [1017 on yarn 1]
xfer b57 f57;return loops [1018 on yarn 1]
xfer b59 f59;return loops [1019 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1050 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1051 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1052 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1053 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1054 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1055 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1056 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1057 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1058 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1059 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1060 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1061 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1062 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1063 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1064 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1065 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1066 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1067 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1068 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1069 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1070 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1071 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1072 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1073 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1074 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1075 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1076 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1077 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1078 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1079 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1050 on yarn 1]
xfer b3 f3;return loops [1051 on yarn 1]
xfer b5 f5;return loops [1052 on yarn 1]
xfer b7 f7;return loops [1053 on yarn 1]
xfer b9 f9;return loops [1054 on yarn 1]
xfer b11 f11;return loops [1055 on yarn 1]
xfer b13 f13;return loops [1056 on yarn 1]
xfer b15 f15;return loops [1057 on yarn 1]
xfer b17 f17;return loops [1058 on yarn 1]
xfer b19 f19;return loops [1059 on yarn 1]
xfer b21 f21;return loops [1060 on yarn 1]
xfer b23 f23;return loops [1061 on yarn 1]
xfer b25 f25;return loops [1062 on yarn 1]
xfer b27 f27;return loops [1063 on yarn 1]
xfer b29 f29;return loops [1064 on yarn 1]
xfer b31 f31;return loops [1065 on yarn 1]
xfer b33 f33;return loops [1066 on yarn 1]
xfer b35 f35;return loops [1067 on yarn 1]
xfer b37 f37;return loops [1068 on yarn 1]
xfer b39 f39;return loops [1069 on yarn 1]
xfer b41 f41;return loops [1070 on yarn 1]
xfer b43 f43;return loops [1071 on yarn 1]
xfer b45 f45;return loops [1072 on yarn 1]
xfer b47 f47;return loops [1073 on yarn 1]
xfer b49 f49;return loops [1074 on yarn 1]
xfer b51 f51;return loops [1075 on yarn 1]
xfer b53 f53;return loops [1076 on yarn 1]
xfer b55 f55;return loops [1077 on yarn 1]
xfer b57 f57;return loops [1078 on yarn 1]
xfer b59 f59;return loops [1079 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1110 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1111 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1112 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1113 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1114 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1115 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1116 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1117 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1118 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1119 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1120 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1121 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1122 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1123 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1124 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1125 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1126 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1127 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1128 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1129 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1130 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1131 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1132 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1133 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1134 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1135 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1136 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1137 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1138 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1139 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1110 on yarn 1]
xfer b3 f3;return loops [1111 on yarn 1]
xfer b5 f5;return loops [1112 on yarn 1]
xfer b7 f7;return loops [1113 on yarn 1]
xfer b9 f9;return loops [1114 on yarn 1]
xfer b11 f11;return loops [1115 on yarn 1]
xfer b13 f13;return loops [1116 on yarn 1]
xfer b15 f15;return loops [1117 on yarn 1]
xfer b17 f17;return loops [1118 on yarn 1]
xfer b19 f19;return loops [1119 on yarn 1]
xfer b21 f21;return loops [1120 on yarn 1]
xfer b23 f23;return loops [1121 on yarn 1]
xfer b25 f25;return loops [1122 on yarn 1]
xfer b27 f27;return loops [1123 on yarn 1]
xfer b29 f29;return loops [1124 on yarn 1]
xfer b31 f31;return loops [1125 on yarn 1]
xfer b33 f33;return loops [1126 on yarn 1]
xfer b35 f35;return loops [1127 on yarn 1]
xfer b37 f37;return loops [1128 on yarn 1]
xfer b39 f39;return loops [1129 on yarn 1]
xfer b41 f41;return loops [1130 on yarn 1]
xfer b43 f43;return loops [1131 on yarn 1]
xfer b45 f45;return loops [1132 on yarn 1]
xfer b47 f47;return loops [1133 on yarn 1]
xfer b49 f49;return loops [1134 on yarn 1]
xfer b51 f51;return loops [1135 on yarn 1]
xfer b53 f53;return loops [1136 on yarn 1]
xfer b55 f55;return loops [1137 on yarn 1]
xfer b57 f57;return loops [1138 on yarn 1]
xfer b59 f59;return loops [1139 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1170 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1171 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1172 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1173 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1174 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1175 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1176 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1177 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1178 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1179 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1180 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1181 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1182 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1183 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1184 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1185 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1186 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1187 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1188 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1189 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1190 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1191 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1192 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1193 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1194 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1195 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1196 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1197 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1198 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1199 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1170 on yarn 1]
xfer b3 f3;return loops [1171 on yarn 1]
xfer b5 f5;return loops [1172 on yarn 1]
xfer b7 f7;return loops [1173 on yarn 1]
xfer b9 f9;return loops [1174 on yarn 1]
xfer b11 f11;return loops [1175 on yarn 1]
xfer b13 f13;return loops [1176 on yarn 1]
xfer b15 f15;return loops [1177 on yarn 1]
xfer b17 f17;return loops [1178 on yarn 1]
xfer b19 f19;return loops [1179 on yarn 1]
xfer b21 f21;return loops [1180 on yarn 1]
xfer b23 f23;return loops [1181 on yarn 1]
xfer b25 f25;return loops [1182 on yarn 1]
xfer b27 f27;return loops [1183 on yarn 1]
xfer b29 f29;return loops [1184 on yarn 1]
xfer b31 f31;return loops [1185 on yarn 1]
xfer b33 f33;return loops [1186 on yarn 1]
xfer b35 f35;return loops [1187 on yarn 1]
xfer b37 f37;return loops [1188 on yarn 1]
xfer b39 f39;return loops [1189 on yarn 1]
xfer b41 f41;return loops [1190 on yarn 1]
xfer b43 f43;return loops [1191 on yarn 1]
xfer b45 f45;return loops [1192 on yarn 1]
xfer b47 f47;return loops [1193 on yarn 1]
xfer b49 f49;return loops [1194 on yarn 1]
xfer b51 f51;return loops [1195 on yarn 1]
xfer b53 f53;return loops [1196 on yarn 1]
xfer b55 f55;return loops [1197 on yarn 1]
xfer b57 f57;return loops [1198 on yarn 1]
xfer b59 f59;return loops [1199 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1230 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1231 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1232 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1233 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1234 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1235 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1236 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1237 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1238 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1239 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1240 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1241 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1242 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1243 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1244 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1245 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1246 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1247 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1248 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1249 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1250 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1251 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1252 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1253 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1254 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1255 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1256 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1257 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1258 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1259 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1230 on yarn 1]
xfer b3 f3;return loops [1231 on yarn 1]
xfer b5 f5;return loops [1232 on yarn 1]
xfer b7 f7;return loops [1233 on yarn 1]
xfer b9 f9;return loops [1234 on yarn 1]
xfer b11 f11;return loops [1235 on yarn 1]
xfer b13 f13;return loops [1236 on yarn 1]
xfer b15 f15;return loops [1237 on yarn 1]
xfer b17 f17;return loops [1238 on yarn 1]
xfer b19 f19;return loops [1239 on yarn 1]
xfer b21 f21;return loops [1240 on yarn 1]
xfer b23 f23;return loops [1241 on yarn 1]
xfer b25 f25;return loops [1242 on yarn 1]
xfer b27 f27;return loops [1243 on yarn 1]
xfer b29 f29;return loops [1244 on yarn 1]
xfer b31 f31;return loops [1245 on yarn 1]
xfer b33 f33;return loops [1246 on yarn 1]
xfer b35 f35;return loops [1247 on yarn 1]
xfer b37 f37;return loops [1248 on yarn 1]
xfer b39 f39;return loops [1249 on yarn 1]
xfer b41 f41;return loops [1250 on yarn 1]
xfer b43 f43;return loops [1251 on yarn 1]
xfer b45 f45;return loops [1252 on yarn 1]
xfer b47 f47;return loops [1253 on yarn 1]
xfer b49 f49;return loops [1254 on yarn 1]
xfer b51 f51;return loops [1255 on yarn 1]
xfer b53 f53;return loops [1256 on yarn 1]
xfer b55 f55;return loops [1257 on yarn 1]
xfer b57 f57;return loops [1258 on yarn 1]
xfer b59 f59;return loops [1259 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1290 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1291 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1292 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1293 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1294 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1295 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1296 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1297 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1298 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1299 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1300 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1301 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1302 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1303 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1304 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1305 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1306 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1307 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1308 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1309 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1310 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1311 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1312 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1313 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1314 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1315 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1316 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1317 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1318 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1319 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1290 on yarn 1]
xfer b3 f3;return loops [1291 on yarn 1]
xfer b5 f5;return loops [1292 on yarn 1]
xfer b7 f7;return loops [1293 on yarn 1]
xfer b9 f9;return loops [1294 on yarn 1]
xfer b11 f11;return loops [1295 on yarn 1]
xfer b13 f13;return loops [1296 on yarn 1]
xfer b15 f15;return loops [1297 on yarn 1]
xfer b17 f17;return loops [1298 on yarn 1]
xfer b19 f19;return loops [1299 on yarn 1]
xfer b21 f21;return loops [1300 on yarn 1]
xfer b23 f23;return loops [1301 on yarn 1]
xfer b25 f25;return loops [1302 on yarn 1]
xfer b27 f27;return loops [1303 on yarn 1]
xfer b29 f29;return loops [1304 on yarn 1]
xfer b31 f31;return loops [1305 on yarn 1]
xfer b33 f33;return loops [1306 on yarn 1]
xfer b35 f35;return loops [1307 on yarn 1]
xfer b37 f37;return loops [1308 on yarn 1]
xfer b39 f39;return loops [1309 on yarn 1]
xfer b41 f41;return loops [1310 on yarn 1]
xfer b43 f43;return loops [1311 on yarn 1]
xfer b45 f45;return loops [1312 on yarn 1]
xfer b47 f47;return loops [1313 on yarn 1]
xfer b49 f49;return loops [1314 on yarn 1]
xfer b51 f51;return loops [1315 on yarn 1]
xfer b53 f53;return loops [1316 on yarn 1]
xfer b55 f55;return loops [1317 on yarn 1]
xfer b57 f57;return loops [1318 on yarn 1]
xfer b59 f59;return loops [1319 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1350 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1351 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1352 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1353 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1354 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1355 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1356 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1357 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1358 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1359 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1360 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1361 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1362 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1363 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1364 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1365 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1366 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1367 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1368 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1369 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1370 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1371 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1372 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1373 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1374 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1375 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1376 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1377 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1378 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1379 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1350 on yarn 1]
xfer b3 f3;return loops [1351 on yarn 1]
xfer b5 f5;return loops [1352 on yarn 1]
xfer b7 f7;return loops [1353 on yarn 1]
xfer b9 f9;return loops [1354 on yarn 1]
xfer b11 f11;return loops [1355 on yarn 1]
xfer b13 f13;return loops [1356 on yarn 1]
xfer b15 f15;return loops [1357 on yarn 1]
xfer b17 f17;return loops [1358 on yarn 1]
xfer b19 f19;return loops [1359 on yarn 1]
xfer b21 f21;return loops [1360 on yarn 1]
xfer b23 f23;return loops [1361 on yarn 1]
xfer b25 f25;return loops [1362 on yarn 1]
xfer b27 f27;return loops [1363 on yarn 1]
xfer b29 f29;return loops [1364 on yarn 1]
xfer b31 f31;return loops [1365 on yarn 1]
xfer b33 f33;return loops [1366 on yarn 1]
xfer b35 f35;return loops [1367 on yarn 1]
xfer b37 f37;return loops [1368 on yarn 1]
xfer b39 f39;return loops [1369 on yarn 1]
xfer b41 f41;return loops [1370 on yarn 1]
xfer b43 f43;return loops [1371 on yarn 1]
xfer b45 f45;return loops [1372 on yarn 1]
xfer b47 f47;return loops [1373 on yarn 1]
xfer b49 f49;return loops [1374 on yarn 1]
xfer b51 f51;return loops [1375 on yarn 1]
xfer b53 f53;return loops [1376 on yarn 1]
xfer b55 f55;return loops [1377 on yarn 1]
xfer b57 f57;return loops [1378 on yarn 1]
xfer b59 f59;return loops [1379 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1410 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1411 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1412 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1413 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1414 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1415 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1416 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1417 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1418 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1419 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1420 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1421 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1422 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1423 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1424 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1425 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1426 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1427 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1428 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1429 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1430 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1431 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1432 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1433 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1434 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1435 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1436 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1437 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1438 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1439 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1410 on yarn 1]
xfer b3 f3;return loops [1411 on yarn 1]
xfer b5 f5;return loops [1412 on yarn 1]
xfer b7 f7;return loops [1413 on yarn 1]
xfer b9 f9;return loops [1414 on yarn 1]
xfer b11 f11;return loops [1415 on yarn 1]
xfer b13 f13;return loops [1416 on yarn 1]
xfer b15 f15;return loops [1417 on yarn 1]
xfer b17 f17;return loops [1418 on yarn 1]
xfer b19 f19;return loops [1419 on yarn 1]
xfer b21 f21;return loops [1420 on yarn 1]
xfer b23 f23;return loops [1421 on yarn 1]
xfer b25 f25;return loops [1422 on yarn 1]
xfer b27 f27;return loops [1423 on yarn 1]
xfer b29 f29;return loops [1424 on yarn 1]
xfer b31 f31;return loops [1425 on yarn 1]
xfer b33 f33;return loops [1426 on yarn 1]
xfer b35 f35;return loops [1427 on yarn 1]
xfer b37 f37;return loops [1428 on yarn 1]
xfer b39 f39;return loops [1429 on yarn 1]
xfer b41 f41;return loops [1430 on yarn 1]
xfer b43 f43;return loops [1431 on yarn 1]
xfer b45 f45;return loops [1432 on yarn 1]
xfer b47 f47;return loops [1433 on yarn 1]
xfer b49 f49;return loops [1434 on yarn 1]
xfer b51 f51;return loops [1435 on yarn 1]
xfer b53 f53;return loops [1436 on yarn 1]
xfer b55 f55;return loops [1437 on yarn 1]
xfer b57 f57;return loops [1438 on yarn 1]
xfer b59 f59;return loops [1439 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1470 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1471 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1472 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1473 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1474 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1475 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1476 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1477 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1478 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1479 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1480 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1481 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1482 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1483 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1484 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1485 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1486 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1487 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1488 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1489 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1490 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1491 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1492 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1493 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1494 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1495 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1496 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1497 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1498 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1499 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1470 on yarn 1]
xfer b3 f3;return loops [1471 on yarn 1]
xfer b5 f5;return loops [1472 on yarn 1]
xfer b7 f7;return loops [1473 on yarn 1]
xfer b9 f9;return loops [1474 on yarn 1]
xfer b11 f11;return loops [1475 on yarn 1]
xfer b13 f13;return loops [1476 on yarn 1]
xfer b15 f15;return loops [1477 on yarn 1]
xfer b17 f17;return loops [1478 on yarn 1]
xfer b19 f19;return loops [1479 on yarn 1]
xfer b21 f21;return loops [1480 on yarn 1]
xfer b23 f23;return loops [1481 on yarn 1]
xfer b25 f25;return loops [1482 on yarn 1]
xfer b27 f27;return loops [1483 on yarn 1]
xfer b29 f29;return loops [1484 on yarn 1]
xfer b31 f31;return loops [1485 on yarn 1]
xfer b33 f33;return loops [1486 on yarn 1]
xfer b35 f35;return loops [1487 on yarn 1]
xfer b37 f37;return loops [1488 on yarn 1]
xfer b39 f39;return loops [1489 on yarn 1]
xfer b41 f41;return loops [1490 on yarn 1]
xfer b43 f43;return loops [1491 on yarn 1]
xfer b45 f45;return loops [1492 on yarn 1]
xfer b47 f47;return loops [1493 on yarn 1]
xfer b49 f49;return loops [1494 on yarn 1]
xfer b51 f51;return loops [1495 on yarn 1]
xfer b53 f53;return loops [1496 on yarn 1]
xfer b55 f55;return loops [1497 on yarn 1]
xfer b57 f57;return loops [1498 on yarn 1]
xfer b59 f59;return loops [1499 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1530 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1531 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1532 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1533 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1534 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1535 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1536 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1537 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1538 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1539 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1540 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1541 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1542 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1543 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1544 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1545 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1546 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1547 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1548 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1549 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1550 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1551 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1552 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1553 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1554 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1555 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1556 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1557 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1558 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1559 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1530 on yarn 1]
xfer b3 f3;return loops [1531 on yarn 1]
xfer b5 f5;return loops [1532 on yarn 1]
xfer b7 f7;return loops [1533 on yarn 1]
xfer b9 f9;return loops [1534 on yarn 1]
xfer b11 f11;return loops [1535 on yarn 1]
xfer b13 f13;return loops [1536 on yarn 1]
xfer b15 f15;return loops [1537 on yarn 1]
xfer b17 f17;return loops [1538 on yarn 1]
xfer b19 f19;return loops [1539 on yarn 1]
xfer b21 f21;return loops [1540 on yarn 1]
xfer b23 f23;return loops [1541 on yarn 1]
xfer b25 f25;return loops [1542 on yarn 1]
xfer b27 f27;return loops [1543 on yarn 1]
xfer b29 f29;return loops [1544 on yarn 1]
xfer b31 f31;return loops [1545 on yarn 1]
xfer b33 f33;return loops [1546 on yarn 1]
xfer b35 f35;return loops [1547 on yarn 1]
xfer b37 f37;return loops [1548 on yarn 1]
xfer b39 f39;return loops [1549 on yarn 1]
xfer b41 f41;return loops [1550 on yarn 1]
xfer b43 f43;return loops [1551 on yarn 1]
xfer b45 f45;return loops [1552 on yarn 1]
xfer b47 f47;return loops [1553 on yarn 1]
xfer b49 f49;return loops [1554 on yarn 1]
xfer b51 f51;return loops [1555 on yarn 1]
xfer b53 f53;return loops [1556 on yarn 1]
xfer b55 f55;return loops [1557 on yarn 1]
xfer b57 f57;return loops [1558 on yarn 1]
xfer b59 f59;return loops [1559 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1590 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1591 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1592 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1593 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1594 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1595 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1596 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1597 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1598 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1599 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1600 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1601 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1602 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1603 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1604 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1605 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1606 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1607 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1608 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1609 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1610 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1611 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1612 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1613 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1614 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1615 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1616 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1617 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1618 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1619 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1590 on yarn 1]
xfer b3 f3;return loops [1591 on yarn 1]
xfer b5 f5;return loops [1592 on yarn 1]
xfer b7 f7;return loops [1593 on yarn 1]
xfer b9 f9;return loops [1594 on yarn 1]
xfer b11 f11;return loops [1595 on yarn 1]
xfer b13 f13;return loops [1596 on yarn 1]
xfer b15 f15;return loops [1597 on yarn 1]
xfer b17 f17;return loops [1598 on yarn 1]
xfer b19 f19;return loops [1599 on yarn 1]
xfer b21 f21;return loops [1600 on yarn 1]
xfer b23 f23;return loops [1601 on yarn 1]
xfer b25 f25;return loops [1602 on yarn 1]
xfer b27 f27;return loops [1603 on yarn 1]
xfer b29 f29;return loops [1604 on yarn 1]
xfer b31 f31;return loops [1605 on yarn 1]
xfer b33 f33;return loops [1606 on yarn 1]
xfer b35 f35;return loops [1607 on yarn 1]
xfer b37 f37;return loops [1608 on yarn 1]
xfer b39 f39;return loops [1609 on yarn 1]
xfer b41 f41;return loops [1610 on yarn 1]
xfer b43 f43;return loops [1611 on yarn 1]
xfer b45 f45;return loops [1612 on yarn 1]
xfer b47 f47;return loops [1613 on yarn 1]
xfer b49 f49;return loops [1614 on yarn 1]
xfer b51 f51;return loops [1615 on yarn 1]
xfer b53 f53;return loops [1616 on yarn 1]
xfer b55 f55;return loops [1617 on yarn 1]
xfer b57 f57;return loops [1618 on yarn 1]
xfer b59 f59;return loops [1619 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1650 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1651 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1652 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1653 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1654 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1655 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1656 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1657 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1658 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1659 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1660 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1661 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1662 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1663 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1664 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1665 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1666 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1667 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1668 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1669 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1670 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1671 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1672 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1673 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1674 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1675 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1676 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1677 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1678 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1679 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1650 on yarn 1]
xfer b3 f3;return loops [1651 on yarn 1]
xfer b5 f5;return loops [1652 on yarn 1]
xfer b7 f7;return loops [1653 on yarn 1]
xfer b9 f9;return loops [1654 on yarn 1]
xfer b11 f11;return loops [1655 on yarn 1]
xfer b13 f13;return loops [1656 on yarn 1]
xfer b15 f15;return loops [1657 on yarn 1]
xfer b17 f17;return loops [1658 on yarn 1]
xfer b19 f19;return loops [1659 on yarn 1]
xfer b21 f21;return loops [1660 on yarn 1]
xfer b23 f23;return loops [1661 on yarn 1]
xfer b25 f25;return loops [1662 on yarn 1]
xfer b27 f27;return loops [1663 on yarn 1]
xfer b29 f29;return loops [1664 on yarn 1]
xfer b31 f31;return loops [1665 on yarn 1]
xfer b33 f33;return loops [1666 on yarn 1]
xfer b35 f35;return loops [1667 on yarn 1]
xfer b37 f37;return loops [1668 on yarn 1]
xfer b39 f39;return loops [1669 on yarn 1]
xfer b41 f41;return loops [1670 on yarn 1]
xfer b43 f43;return loops [1671 on yarn 1]
xfer b45 f45;return loops [1672 on yarn 1]
xfer b47 f47;return loops [1673 on yarn 1]
xfer b49 f49;return loops [1674 on yarn 1]
xfer b51 f51;return loops [1675 on yarn 1]
xfer b53 f53;return loops [1676 on yarn 1]
xfer b55 f55;return loops [1677 on yarn 1]
xfer b57 f57;return loops [1678 on yarn 1]
xfer b59 f59;return loops [1679 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1710 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1711 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1712 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1713 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1714 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1715 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1716 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1717 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1718 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1719 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1720 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1721 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1722 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1723 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1724 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1725 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1726 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1727 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1728 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1729 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1730 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1731 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1732 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1733 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1734 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1735 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1736 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1737 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1738 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1739 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1710 on yarn 1]
xfer b3 f3;return loops [1711 on yarn 1]
xfer b5 f5;return loops [1712 on yarn 1]
xfer b7 f7;return loops [1713 on yarn 1]
xfer b9 f9;return loops [1714 on yarn 1]
xfer b11 f11;return loops [1715 on yarn 1]
xfer b13 f13;return loops [1716 on yarn 1]
xfer b15 f15;return loops [1717 on yarn 1]
xfer b17 f17;return loops [1718 on yarn 1]
xfer b19 f19;return loops [1719 on yarn 1]
xfer b21 f21;return loops [1720 on yarn 1]
xfer b23 f23;return loops [1721 on yarn 1]
xfer b25 f25;return loops [1722 on yarn 1]
xfer b27 f27;return loops [1723 on yarn 1]
xfer b29 f29;return loops [1724 on yarn 1]
xfer b31 f31;return loops [1725 on yarn 1]
xfer b33 f33;return loops [1726 on yarn 1]
xfer b35 f35;return loops [1727 on yarn 1]
xfer b37 f37;return loops [1728 on yarn 1]
xfer b39 f39;return loops [1729 on yarn 1]
xfer b41 f41;return loops [1730 on yarn 1]
xfer b43 f43;return loops [1731 on yarn 1]
xfer b45 f45;return loops [1732 on yarn 1]
xfer b47 f47;return loops [1733 on yarn 1]
xfer b49 f49;return loops [1734 on yarn 1]
xfer b51 f51;return loops [1735 on yarn 1]
xfer b53 f53;return loops [1736 on yarn 1]
xfer b55 f55;return loops [1737 on yarn 1]
xfer b57 f57;return loops [1738 on yarn 1]
xfer b59 f59;return loops [1739 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1770 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1771 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1772 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1773 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1774 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1775 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1776 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1777 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1778 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1779 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1780 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1781 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1782 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1783 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1784 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1785 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1786 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1787 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1788 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1789 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1790 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1791 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1792 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1793 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1794 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1795 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1796 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1797 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1798 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1799 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1770 on yarn 1]
xfer b3 f3;return loops [1771 on yarn 1]
xfer b5 f5;return loops [1772 on yarn 1]
xfer b7 f7;return loops [1773 on yarn 1]
xfer b9 f9;return loops [1774 on yarn 1]
xfer b11 f11;return loops [1775 on yarn 1]
xfer b13 f13;return loops [1776 on yarn 1]
xfer b15 f15;return loops [1777 on yarn 1]
xfer b17 f17;return loops [1778 on yarn 1]
xfer b19 f19;return loops [1779 on yarn 1]
xfer b21 f21;return loops [1780 on yarn 1]
xfer b23 f23;return loops [1781 on yarn 1]
xfer b25 f25;return loops [1782 on yarn 1]
xfer b27 f27;return loops [1783 on yarn 1]
xfer b29 f29;return loops [1784 on yarn 1]
xfer b31 f31;return loops [1785 on yarn 1]
xfer b33 f33;return loops [1786 on yarn 1]
xfer b35 f35;return loops [1787 on yarn 1]
xfer b37 f37;return loops [1788 on yarn 1]
xfer b39 f39;return loops [1789 on yarn 1]
xfer b41 f41;return loops [1790 on yarn 1]
xfer b43 f43;return loops [1791 on yarn 1]
xfer b45 f45;return loops [1792 on yarn 1]
xfer b47 f47;return loops [1793 on yarn 1]
xfer b49 f49;return loops [1794 on yarn 1]
xfer b51 f51;return loops [1795 on yarn 1]
xfer b53 f53;return loops [1796 on yarn 1]
xfer b55 f55;return loops [1797 on yarn 1]
xfer b57 f57;return loops [1798 on yarn 1]
xfer b59 f59;return loops [1799 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1830 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1831 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1832 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1833 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1834 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1835 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1836 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1837 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1838 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1839 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1840 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1841 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1842 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1843 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1844 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1845 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1846 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1847 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1848 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1849 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1850 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1851 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1852 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1853 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1854 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1855 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1856 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1857 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1858 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1859 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1830 on yarn 1]
xfer b3 f3;return loops [1831 on yarn 1]
xfer b5 f5;return loops [1832 on yarn 1]
xfer b7 f7;return loops [1833 on yarn 1]
xfer b9 f9;return loops [1834 on yarn 1]
xfer b11 f11;return loops [1835 on yarn 1]
xfer b13 f13;return loops [1836 on yarn 1]
xfer b15 f15;return loops [1837 on yarn 1]
xfer b17 f17;return loops [1838 on yarn 1]
xfer b19 f19;return loops [1839 on yarn 1]
xfer b21 f21;return loops [1840 on yarn 1]
xfer b23 f23;return loops [1841 on yarn 1]
xfer b25 f25;return loops [1842 on yarn 1]
xfer b27 f27;return loops [1843 on yarn 1]
xfer b29 f29;return loops [1844 on yarn 1]
xfer b31 f31;return loops [1845 on yarn 1]
xfer b33 f33;return loops [1846 on yarn 1]
xfer b35 f35;return loops [1847 on yarn 1]
xfer b37 f37;return loops [1848 on yarn 1]
xfer b39 f39;return loops [1849 on yarn 1]
xfer b41 f41;return loops [1850 on yarn 1]
xfer b43 f43;return loops [1851 on yarn 1]
xfer b45 f45;return loops [1852 on yarn 1]
xfer b47 f47;return loops [1853 on yarn 1]
xfer b49 f49;return loops [1854 on yarn 1]
xfer b51 f51;return loops [1855 on yarn 1]
xfer b53 f53;return loops [1856 on yarn 1]
xfer b55 f55;return loops [1857 on yarn 1]
xfer b57 f57;return loops [1858 on yarn 1]
xfer b59 f59;return loops [1859 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1890 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1891 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1892 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1893 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1894 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1895 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1896 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1897 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1898 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1899 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1900 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1901 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1902 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1903 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1904 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1905 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1906 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1907 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1908 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1909 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1910 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1911 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1912 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1913 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1914 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1915 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1916 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1917 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1918 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1919 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1890 on yarn 1]
xfer b3 f3;return loops [1891 on yarn 1]
xfer b5 f5;return loops [1892 on yarn 1]
xfer b7 f7;return loops [1893 on yarn 1]
xfer b9 f9;return loops [1894 on yarn 1]
xfer b11 f11;return loops [1895 on yarn 1]
xfer b13 f13;return loops [1896 on yarn 1]
xfer b15 f15;return loops [1897 on yarn 1]
xfer b17 f17;return loops [1898 on yarn 1]
xfer b19 f19;return loops [1899 on yarn 1]
xfer b21 f21;return loops [1900 on yarn 1]
xfer b23 f23;return loops [1901 on yarn 1]
xfer b25 f25;return loops [1902 on yarn 1]
xfer b27 f27;return loops [1903 on yarn 1]
xfer b29 f29;return loops [1904 on yarn 1]
xfer b31 f31;return loops [1905 on yarn 1]
xfer b33 f33;return loops [1906 on yarn 1]
xfer b35 f35;return loops [1907 on yarn 1]
xfer b37 f37;return loops [1908 on yarn 1]
xfer b39 f39;return loops [1909 on yarn 1]
xfer b41 f41;return loops [1910 on yarn 1]
xfer b43 f43;return loops [1911 on yarn 1]
xfer b45 f45;return loops [1912 on yarn 1]
xfer b47 f47;return loops [1913 on yarn 1]
xfer b49 f49;return loops [1914 on yarn 1]
xfer b51 f51;return loops [1915 on yarn 1]
xfer b53 f53;return loops [1916 on yarn 1]
xfer b55 f55;return loops [1917 on yarn 1]
xfer b57 f57;return loops [1918 on yarn 1]
xfer b59 f59;return loops [1919 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1950 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [1951 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [1952 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [1953 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [1954 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [1955 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [1956 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [1957 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [1958 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [1959 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [1960 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [1961 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [1962 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [1963 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [1964 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [1965 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [1966 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [1967 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [1968 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [1969 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [1970 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [1971 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [1972 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [1973 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [1974 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [1975 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [1976 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [1977 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [1978 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [1979 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1950 on yarn 1]
xfer b3 f3;return loops [1951 on yarn 1]
xfer b5 f5;return loops [1952 on yarn 1]
xfer b7 f7;return loops [1953 on yarn 1]
xfer b9 f9;return loops [1954 on yarn 1]
xfer b11 f11;return loops [1955 on yarn 1]
xfer b13 f13;return loops [1956 on yarn 1]
xfer b15 f15;return loops [1957 on yarn 1]
xfer b17 f17;return loops [1958 on yarn 1]
xfer b19 f19;return loops [1959 on yarn 1]
xfer b21 f21;return loops [1960 on yarn 1]
xfer b23 f23;return loops [1961 on yarn 1]
xfer b25 f25;return loops [1962 on yarn 1]
xfer b27 f27;return loops [1963 on yarn 1]
xfer b29 f29;return loops [1964 on yarn 1]
xfer b31 f31;return loops [1965 on yarn 1]
xfer b33 f33;return loops [1966 on yarn 1]
xfer b35 f35;return loops [1967 on yarn 1]
xfer b37 f37;return loops [1968 on yarn 1]
xfer b39 f39;return loops [1969 on yarn 1]
xfer b41 f41;return loops [1970 on yarn 1]
xfer b43 f43;return loops [1971 on yarn 1]
xfer b45 f45;return loops [1972 on yarn 1]
xfer b47 f47;return loops [1973 on yarn 1]
xfer b49 f49;return loops [1974 on yarn 1]
xfer b51 f51;return loops [1975 on yarn 1]
xfer b53 f53;return loops [1976 on yarn 1]
xfer b55 f55;return loops [1977 on yarn 1]
xfer b57 f57;return loops [1978 on yarn 1]
xfer b59 f59;return loops [1979 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2010 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [2011 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [2012 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2013 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [2014 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [2015 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2016 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [2017 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [2018 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2019 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [2020 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [2021 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2022 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [2023 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [2024 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2025 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [2026 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [2027 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2028 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [2029 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [2030 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2031 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [2032 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [2033 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2034 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [2035 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [2036 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2037 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [2038 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [2039 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [2010 on yarn 1]
xfer b3 f3;return loops [2011 on yarn 1]
xfer b5 f5;return loops [2012 on yarn 1]
xfer b7 f7;return loops [2013 on yarn 1]
xfer b9 f9;return loops [2014 on yarn 1]
xfer b11 f11;return loops [2015 on yarn 1]
xfer b13 f13;return loops [2016 on yarn 1]
xfer b15 f15;return loops [2017 on yarn 1]
xfer b17 f17;return loops [2018 on yarn 1]
xfer b19 f19;return loops [2019 on yarn 1]
xfer b21 f21;return loops [2020 on yarn 1]
xfer b23 f23;return loops [2021 on yarn 1]
xfer b25 f25;return loops [2022 on yarn 1]
xfer b27 f27;return loops [2023 on yarn 1]
xfer b29 f29;return loops [2024 on yarn 1]
xfer b31 f31;return loops [2025 on yarn 1]
xfer b33 f33;return loops [2026 on yarn 1]
xfer b35 f35;return loops [2027 on yarn 1]
xfer b37 f37;return loops [2028 on yarn 1]
xfer b39 f39;return loops [2029 on yarn 1]
xfer b41 f41;return loops [2030 on yarn 1]
xfer b43 f43;return loops [2031 on yarn 1]
xfer b45 f45;return loops [2032 on yarn 1]
xfer b47 f47;return loops [2033 on yarn 1]
xfer b49 f49;return loops [2034 on yarn 1]
xfer b51 f51;return loops [2035 on yarn 1]
xfer b53 f53;return loops [2036 on yarn 1]
xfer b55 f55;return loops [2037 on yarn 1]
xfer b57 f57;return loops [2038 on yarn 1]
xfer b59 f59;return loops [2039 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2070 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [2071 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [2072 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2073 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [2074 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [2075 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2076 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [2077 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [2078 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2079 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [2080 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [2081 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2082 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [2083 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [2084 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2085 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [2086 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [2087 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2088 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [2089 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [2090 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2091 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [2092 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [2093 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2094 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [2095 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [2096 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2097 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [2098 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [2099 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [2070 on yarn 1]
xfer b3 f3;return loops [2071 on yarn 1]
xfer b5 f5;return loops [2072 on yarn 1]
xfer b7 f7;return loops [2073 on yarn 1]
xfer b9 f9;return loops [2074 on yarn 1]
xfer b11 f11;return loops [2075 on yarn 1]
xfer b13 f13;return loops [2076 on yarn 1]
xfer b15 f15;return loops [2077 on yarn 1]
xfer b17 f17;return loops [2078 on yarn 1]
xfer b19 f19;return loops [2079 on yarn 1]
xfer b21 f21;return loops [2080 on yarn 1]
xfer b23 f23;return loops [2081 on yarn 1]
xfer b25 f25;return loops [2082 on yarn 1]
xfer b27 f27;return loops [2083 on yarn 1]
xfer b29 f29;return loops [2084 on yarn 1]
xfer b31 f31;return loops [2085 on yarn 1]
xfer b33 f33;return loops [2086 on yarn 1]
xfer b35 f35;return loops [2087 on yarn 1]
xfer b37 f37;return loops [2088 on yarn 1]
xfer b39 f39;return loops [2089 on yarn 1]
xfer b41 f41;return loops [2090 on yarn 1]
xfer b43 f43;return loops [2091 on yarn 1]
xfer b45 f45;return loops [2092 on yarn 1]
xfer b47 f47;return loops [2093 on yarn 1]
xfer b49 f49;return loops [2094 on yarn 1]
xfer b51 f51;return loops [2095 on yarn 1]
xfer b53 f53;return loops [2096 on yarn 1]
xfer b55 f55;return loops [2097 on yarn 1]
xfer b57 f57;return loops [2098 on yarn 1]
xfer b59 f59;return loops [2099 on yarn 1]
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
knit + f31 1
knit + f33 1
knit + f35 1
knit + f37 1
knit + f39 1
knit + f41 1
knit + f43 1
knit + f45 1
knit + f47 1
knit + f49 1
knit + f51 1
knit + f53 1
knit + f55 1
knit + f57 1
knit + f59 1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [2130 on yarn 1] from s1 relative to s0
xfer f3 b3;peel loops [2131 on yarn 1] from s1 relative to s0
xfer f5 b5;peel loops [2132 on yarn 1] from s1 relative to s0
xfer f7 b7;peel loops [2133 on yarn 1] from s1 relative to s0
xfer f9 b9;peel loops [2134 on yarn 1] from s1 relative to s0
xfer f11 b11;peel loops [2135 on yarn 1] from s1 relative to s0
xfer f13 b13;peel loops [2136 on yarn 1] from s1 relative to s0
xfer f15 b15;peel loops [2137 on yarn 1] from s1 relative to s0
xfer f17 b17;peel loops [2138 on yarn 1] from s1 relative to s0
xfer f19 b19;peel loops [2139 on yarn 1] from s1 relative to s0
xfer f21 b21;peel loops [2140 on yarn 1] from s1 relative to s0
xfer f23 b23;peel loops [2141 on yarn 1] from s1 relative to s0
xfer f25 b25;peel loops [2142 on yarn 1] from s1 relative to s0
xfer f27 b27;peel loops [2143 on yarn 1] from s1 relative to s0
xfer f29 b29;peel loops [2144 on yarn 1] from s1 relative to s0
xfer f31 b31;peel loops [2145 on yarn 1] from s1 relative to s0
xfer f33 b33;peel loops [2146 on yarn 1] from s1 relative to s0
xfer f35 b35;peel loops [2147 on yarn 1] from s1 relative to s0
xfer f37 b37;peel loops [2148 on yarn 1] from s1 relative to s0
xfer f39 b39;peel loops [2149 on yarn 1] from s1 relative to s0
xfer f41 b41;peel loops [2150 on yarn 1] from s1 relative to s0
xfer f43 b43;peel loops [2151 on yarn 1] from s1 relative to s0
xfer f45 b45;peel loops [2152 on yarn 1] from s1 relative to s0
xfer f47 b47;peel loops [2153 on yarn 1] from s1 relative to s0
xfer f49 b49;peel loops [2154 on yarn 1] from s1 relative to s0
xfer f51 b51;peel loops [2155 on yarn 1] from s1 relative to s0
xfer f53 b53;peel loops [2156 on yarn 1] from s1 relative to s0
xfer f55 b55;peel loops [2157 on yarn 1] from s1 relative to s0
xfer f57 b57;peel loops [2158 on yarn 1] from s1 relative to s0
xfer f59 b59;peel loops [2159 on yarn 1] from s1 relative to s0
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
rack -2;Rack to -1 at 2 gauge
xfer f0 b2
rack 0.0;Rack to 0.0 at 2 gauge
split - b2 f2 1
knit + f2 1
rack -2;Rack to -1 at 2 gauge
xfer f2 b4
rack 0.0;Rack to 0.0 at 2 gauge
split - b4 f4 1
knit + f4 1
rack -2;Rack to -1 at 2 gauge
xfer f4 b6
rack 0.0;Rack to 0.0 at 2 gauge
split - b6 f6 1
knit + f6 1
rack -2;Rack to -1 at 2 gauge
xfer f6 b8
rack 0.0;Rack to 0.0 at 2 gauge
split - b8 f8 1
knit + f8 1
rack -2;Rack to -1 at 2 gauge
xfer f8 b10
rack 0.0;Rack to 0.0 at 2 gauge
split - b10 f10 1
knit + f10 1
rack -2;Rack to -1 at 2 gauge
xfer f10 b12
rack 0.0;Rack to 0.0 at 2 gauge
split - b12 f12 1
knit + f12 1
rack -2;Rack to -1 at 2 gauge
xfer f12 b14
rack 0.0;Rack to 0.0 at 2 gauge
split - b14 f14 1
knit + f14 1
rack -2;Rack to -1 at 2 gauge
xfer f14 b16
rack 0.0;Rack to 0.0 at 2 gauge
split - b16 f16 1
knit + f16 1
rack -2;Rack to -1 at 2 gauge
xfer f16 b18
rack 0.0;Rack to 0.0 at 2 gauge
split - b18 f18 1
knit + f18 1
rack -2;Rack to -1 at 2 gauge
xfer f18 b20
rack 0.0;Rack to 0.0 at 2 gauge
split - b20 f20 1
knit + f20 1
rack -2;Rack to -1 at 2 gauge
xfer f20 b22
rack 0.0;Rack to 0.0 at 2 gauge
split - b22 f22 1
knit + f22 1
rack -2;Rack to -1 at 2 gauge
xfer f22 b24
rack 0.0;Rack to 0.0 at 2 gauge
split - b24 f24 1
knit + f24 1
rack -2;Rack to -1 at 2 gauge
xfer f24 b26
rack 0.0;Rack to 0.0 at 2 gauge
split - b26 f26 1
knit + f26 1
rack -2;Rack to -1 at 2 gauge
xfer f26 b28
rack 0.0;Rack to 0.0 at 2 gauge
split - b28 f28 1
knit + f28 1
rack -2;Rack to -1 at 2 gauge
xfer f28 b30
rack 0.0;Rack to 0.0 at 2 gauge
split - b30 f30 1
knit + f30 1
rack -2;Rack to -1 at 2 gauge
xfer f30 b32
rack 0.0;Rack to 0.0 at 2 gauge
split - b32 f32 1
knit + f32 1
rack -2;Rack to -1 at 2 gauge
xfer f32 b34
rack 0.0;Rack to 0.0 at 2 gauge
split - b34 f34 1
knit + f34 1
rack -2;Rack to -1 at 2 gauge
xfer f34 b36
rack 0.0;Rack to 0.0 at 2 gauge
split - b36 f36 1
knit + f36 1
rack -2;Rack to -1 at 2 gauge
xfer f36 b38
rack 0.0;Rack to 0.0 at 2 gauge
split - b38 f38 1
knit + f38 1
rack -2;Rack to -1 at 2 gauge
xfer f38 b40
rack 0.0;Rack to 0.0 at 2 gauge
split - b40 f40 1
knit + f40 1
rack -2;Rack to -1 at 2 gauge
xfer f40 b42
rack 0.0;Rack to 0.0 at 2 gauge
split - b42 f42 1
knit + f42 1
rack -2;Rack to -1 at 2 gauge
xfer f42 b44
rack 0.0;Rack to 0.0 at 2 gauge
split - b44 f44 1
knit + f44 1
rack -2;Rack to -1 at 2 gauge
xfer f44 b46
rack 0.0;Rack to 0.0 at 2 gauge
split - b46 f46 1
knit + f46 1
rack -2;Rack to -1 at 2 gauge
xfer f46 b48
rack 0.0;Rack to 0.0 at 2 gauge
split - b48 f48 1
knit + f48 1
rack -2;Rack to -1 at 2 gauge
xfer f48 b50
rack 0.0;Rack to 0.0 at 2 gauge
split - b50 f50 1
knit + f50 1
rack -2;Rack to -1 at 2 gauge
xfer f50 b52
rack 0.0;Rack to 0.0 at 2 gauge
split - b52 f52 1
knit + f52 1
rack -2;Rack to -1 at 2 gauge
xfer f52 b54
rack 0.0;Rack to 0.0 at 2 gauge
split - b54 f54 1
knit + f54 1
rack -2;Rack to -1 at 2 gauge
xfer f54 b56
rack 0.0;Rack to 0.0 at 2 gauge
split - b56 f56 1
knit + f56 1
rack -2;Rack to -1 at 2 gauge
xfer f56 b58
rack 0.0;Rack to 0.0 at 2 gauge
split - b58 f58 1
knit + f58 1
;KS: Spare knitting on [b2, b4, b6, b8, b10, b12, b14, b16, b18, b20, b22, b24, b26, b28, b30, b32, b34, b36, b38, b40, b42, b44, b46, b48, b50, b52, b54, b56, b58]
knit - b58 1
knit - b56 1
knit - b54 1
knit - b52 1
knit - b50 1
knit - b48 1
knit - b46 1
knit - b44 1
knit - b42 1
knit - b40 1
knit - b38 1
knit - b36 1
knit - b34 1
knit - b32 1
knit - b30 1
knit - b28 1
knit - b26 1
knit - b24 1
knit - b22 1
knit - b20 1
knit - b18 1
knit - b16 1
knit - b14 1
knit - b12 1
knit - b10 1
knit - b8 1
knit - b6 1
knit - b4 1
knit - b2 1
outhook 1;Cutting active yarn on 1
