;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 7;Activating carrier 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
;KS: Cast on 20loops from 0to 20
tuck - f38 7
tuck - f34 7
tuck - f30 7
tuck - f26 7
tuck - f22 7
tuck - f18 7
tuck - f14 7
tuck - f10 7
tuck - f6 7
tuck - f2 7
tuck + f0 7
tuck + f4 7
tuck + f8 7
tuck + f12 7
tuck + f16 7
tuck + f20 7
tuck + f24 7
tuck + f28 7
tuck + f32 7
tuck + f36 7
tuck - f38 7
tuck - f34 7
tuck - f30 7
tuck - f26 7
tuck - f22 7
tuck - f18 7
tuck - f14 7
tuck - f10 7
tuck - f6 7
tuck - f2 7
tuck + f0 7
tuck + f4 7
tuck + f8 7
tuck + f12 7
tuck + f16 7
tuck + f20 7
tuck + f24 7
tuck + f28 7
tuck + f32 7
tuck + f36 7
releasehook 7
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
knit + f0 7
knit + f2 7
knit + f4 7
knit + f6 7
knit + f8 7
knit + f10 7
knit + f12 7
knit + f14 7
knit + f16 7
knit + f18 7
knit + f20 7
knit + f22 7
knit + f24 7
knit + f26 7
knit + f28 7
knit + f30 7
knit + f32 7
knit + f34 7
knit + f36 7
knit + f38 7
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
knit + f0 7
knit + f2 7
knit + f4 7
knit + f6 7
knit + f8 7
knit + f10 7
knit + f12 7
knit + f14 7
knit + f16 7
knit + f18 7
knit + f20 7
knit + f22 7
knit + f24 7
knit + f26 7
knit + f28 7
knit + f30 7
knit + f32 7
knit + f34 7
knit + f36 7
knit + f38 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
;KS: Cast on 20loops from 0to 20
tuck - f39 7
tuck - f35 7
tuck - f31 7
tuck - f27 7
tuck - f23 7
tuck - f19 7
tuck - f15 7
tuck - f11 7
tuck - f7 7
tuck - f3 7
tuck + f1 7
tuck + f5 7
tuck + f9 7
tuck + f13 7
tuck + f17 7
tuck + f21 7
tuck + f25 7
tuck + f29 7
tuck + f33 7
tuck + f37 7
tuck - f39 7
tuck - f35 7
tuck - f31 7
tuck - f27 7
tuck - f23 7
tuck - f19 7
tuck - f15 7
tuck - f11 7
tuck - f7 7
tuck - f3 7
tuck + f1 7
tuck + f5 7
tuck + f9 7
tuck + f13 7
tuck + f17 7
tuck + f21 7
tuck + f25 7
tuck + f29 7
tuck + f33 7
tuck + f37 7
;no-op. Releasehook with no hooked carriers
knit - f39 7
knit - f37 7
knit - f35 7
knit - f33 7
knit - f31 7
knit - f29 7
knit - f27 7
knit - f25 7
knit - f23 7
knit - f21 7
knit - f19 7
knit - f17 7
knit - f15 7
knit - f13 7
knit - f11 7
knit - f9 7
knit - f7 7
knit - f5 7
knit - f3 7
knit - f1 7
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
knit - f39 7
knit - f37 7
knit - f35 7
knit - f33 7
knit - f31 7
knit - f29 7
knit - f27 7
knit - f25 7
knit - f23 7
knit - f21 7
knit - f19 7
knit - f17 7
knit - f15 7
knit - f13 7
knit - f11 7
knit - f9 7
knit - f7 7
knit - f5 7
knit - f3 7
knit - f1 7
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [220 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [221 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [222 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [223 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [224 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [225 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [226 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [227 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [228 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [229 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [230 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [231 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [232 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [233 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [234 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [235 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [236 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [237 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [238 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [239 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [220 on yarn 7]
xfer b3 f3;return loops [221 on yarn 7]
xfer b5 f5;return loops [222 on yarn 7]
xfer b7 f7;return loops [223 on yarn 7]
xfer b9 f9;return loops [224 on yarn 7]
xfer b11 f11;return loops [225 on yarn 7]
xfer b13 f13;return loops [226 on yarn 7]
xfer b15 f15;return loops [227 on yarn 7]
xfer b17 f17;return loops [228 on yarn 7]
xfer b19 f19;return loops [229 on yarn 7]
xfer b21 f21;return loops [230 on yarn 7]
xfer b23 f23;return loops [231 on yarn 7]
xfer b25 f25;return loops [232 on yarn 7]
xfer b27 f27;return loops [233 on yarn 7]
xfer b29 f29;return loops [234 on yarn 7]
xfer b31 f31;return loops [235 on yarn 7]
xfer b33 f33;return loops [236 on yarn 7]
xfer b35 f35;return loops [237 on yarn 7]
xfer b37 f37;return loops [238 on yarn 7]
xfer b39 f39;return loops [239 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [260 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [261 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [262 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [263 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [264 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [265 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [266 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [267 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [268 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [269 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [270 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [271 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [272 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [273 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [274 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [275 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [276 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [277 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [278 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [279 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [260 on yarn 7]
xfer b3 f3;return loops [261 on yarn 7]
xfer b5 f5;return loops [262 on yarn 7]
xfer b7 f7;return loops [263 on yarn 7]
xfer b9 f9;return loops [264 on yarn 7]
xfer b11 f11;return loops [265 on yarn 7]
xfer b13 f13;return loops [266 on yarn 7]
xfer b15 f15;return loops [267 on yarn 7]
xfer b17 f17;return loops [268 on yarn 7]
xfer b19 f19;return loops [269 on yarn 7]
xfer b21 f21;return loops [270 on yarn 7]
xfer b23 f23;return loops [271 on yarn 7]
xfer b25 f25;return loops [272 on yarn 7]
xfer b27 f27;return loops [273 on yarn 7]
xfer b29 f29;return loops [274 on yarn 7]
xfer b31 f31;return loops [275 on yarn 7]
xfer b33 f33;return loops [276 on yarn 7]
xfer b35 f35;return loops [277 on yarn 7]
xfer b37 f37;return loops [278 on yarn 7]
xfer b39 f39;return loops [279 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [300 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [301 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [302 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [303 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [304 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [305 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [306 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [307 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [308 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [309 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [310 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [311 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [312 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [313 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [314 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [315 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [316 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [317 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [318 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [319 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [300 on yarn 7]
xfer b3 f3;return loops [301 on yarn 7]
xfer b5 f5;return loops [302 on yarn 7]
xfer b7 f7;return loops [303 on yarn 7]
xfer b9 f9;return loops [304 on yarn 7]
xfer b11 f11;return loops [305 on yarn 7]
xfer b13 f13;return loops [306 on yarn 7]
xfer b15 f15;return loops [307 on yarn 7]
xfer b17 f17;return loops [308 on yarn 7]
xfer b19 f19;return loops [309 on yarn 7]
xfer b21 f21;return loops [310 on yarn 7]
xfer b23 f23;return loops [311 on yarn 7]
xfer b25 f25;return loops [312 on yarn 7]
xfer b27 f27;return loops [313 on yarn 7]
xfer b29 f29;return loops [314 on yarn 7]
xfer b31 f31;return loops [315 on yarn 7]
xfer b33 f33;return loops [316 on yarn 7]
xfer b35 f35;return loops [317 on yarn 7]
xfer b37 f37;return loops [318 on yarn 7]
xfer b39 f39;return loops [319 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [340 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [341 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [342 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [343 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [344 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [345 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [346 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [347 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [348 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [349 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [350 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [351 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [352 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [353 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [354 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [355 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [356 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [357 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [358 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [359 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [340 on yarn 7]
xfer b3 f3;return loops [341 on yarn 7]
xfer b5 f5;return loops [342 on yarn 7]
xfer b7 f7;return loops [343 on yarn 7]
xfer b9 f9;return loops [344 on yarn 7]
xfer b11 f11;return loops [345 on yarn 7]
xfer b13 f13;return loops [346 on yarn 7]
xfer b15 f15;return loops [347 on yarn 7]
xfer b17 f17;return loops [348 on yarn 7]
xfer b19 f19;return loops [349 on yarn 7]
xfer b21 f21;return loops [350 on yarn 7]
xfer b23 f23;return loops [351 on yarn 7]
xfer b25 f25;return loops [352 on yarn 7]
xfer b27 f27;return loops [353 on yarn 7]
xfer b29 f29;return loops [354 on yarn 7]
xfer b31 f31;return loops [355 on yarn 7]
xfer b33 f33;return loops [356 on yarn 7]
xfer b35 f35;return loops [357 on yarn 7]
xfer b37 f37;return loops [358 on yarn 7]
xfer b39 f39;return loops [359 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [380 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [381 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [382 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [383 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [384 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [385 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [386 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [387 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [388 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [389 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [390 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [391 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [392 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [393 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [394 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [395 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [396 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [397 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [398 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [399 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [380 on yarn 7]
xfer b3 f3;return loops [381 on yarn 7]
xfer b5 f5;return loops [382 on yarn 7]
xfer b7 f7;return loops [383 on yarn 7]
xfer b9 f9;return loops [384 on yarn 7]
xfer b11 f11;return loops [385 on yarn 7]
xfer b13 f13;return loops [386 on yarn 7]
xfer b15 f15;return loops [387 on yarn 7]
xfer b17 f17;return loops [388 on yarn 7]
xfer b19 f19;return loops [389 on yarn 7]
xfer b21 f21;return loops [390 on yarn 7]
xfer b23 f23;return loops [391 on yarn 7]
xfer b25 f25;return loops [392 on yarn 7]
xfer b27 f27;return loops [393 on yarn 7]
xfer b29 f29;return loops [394 on yarn 7]
xfer b31 f31;return loops [395 on yarn 7]
xfer b33 f33;return loops [396 on yarn 7]
xfer b35 f35;return loops [397 on yarn 7]
xfer b37 f37;return loops [398 on yarn 7]
xfer b39 f39;return loops [399 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
inhook 6;Activating carrier 6
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [420 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [421 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [422 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [423 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [424 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [425 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [426 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [427 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [428 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [429 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [430 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [431 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [432 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [433 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [434 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [435 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [436 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [437 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [438 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [439 on yarn 7] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [420 on yarn 7]
xfer b3 f3;return loops [421 on yarn 7]
xfer b5 f5;return loops [422 on yarn 7]
xfer b7 f7;return loops [423 on yarn 7]
xfer b9 f9;return loops [424 on yarn 7]
xfer b11 f11;return loops [425 on yarn 7]
xfer b13 f13;return loops [426 on yarn 7]
xfer b15 f15;return loops [427 on yarn 7]
xfer b17 f17;return loops [428 on yarn 7]
xfer b19 f19;return loops [429 on yarn 7]
xfer b21 f21;return loops [430 on yarn 7]
xfer b23 f23;return loops [431 on yarn 7]
xfer b25 f25;return loops [432 on yarn 7]
xfer b27 f27;return loops [433 on yarn 7]
xfer b29 f29;return loops [434 on yarn 7]
xfer b31 f31;return loops [435 on yarn 7]
xfer b33 f33;return loops [436 on yarn 7]
xfer b35 f35;return loops [437 on yarn 7]
xfer b37 f37;return loops [438 on yarn 7]
xfer b39 f39;return loops [439 on yarn 7]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
releasehook 6
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [460 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [461 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [462 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [463 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [464 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [465 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [466 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [467 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [468 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [469 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [470 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [471 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [472 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [473 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [474 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [475 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [476 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [477 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [478 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [479 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [460 on yarn 6]
xfer b3 f3;return loops [461 on yarn 6]
xfer b5 f5;return loops [462 on yarn 6]
xfer b7 f7;return loops [463 on yarn 6]
xfer b9 f9;return loops [464 on yarn 6]
xfer b11 f11;return loops [465 on yarn 6]
xfer b13 f13;return loops [466 on yarn 6]
xfer b15 f15;return loops [467 on yarn 6]
xfer b17 f17;return loops [468 on yarn 6]
xfer b19 f19;return loops [469 on yarn 6]
xfer b21 f21;return loops [470 on yarn 6]
xfer b23 f23;return loops [471 on yarn 6]
xfer b25 f25;return loops [472 on yarn 6]
xfer b27 f27;return loops [473 on yarn 6]
xfer b29 f29;return loops [474 on yarn 6]
xfer b31 f31;return loops [475 on yarn 6]
xfer b33 f33;return loops [476 on yarn 6]
xfer b35 f35;return loops [477 on yarn 6]
xfer b37 f37;return loops [478 on yarn 6]
xfer b39 f39;return loops [479 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [500 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [501 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [502 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [503 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [504 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [505 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [506 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [507 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [508 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [509 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [510 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [511 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [512 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [513 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [514 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [515 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [516 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [517 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [518 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [519 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [500 on yarn 6]
xfer b3 f3;return loops [501 on yarn 6]
xfer b5 f5;return loops [502 on yarn 6]
xfer b7 f7;return loops [503 on yarn 6]
xfer b9 f9;return loops [504 on yarn 6]
xfer b11 f11;return loops [505 on yarn 6]
xfer b13 f13;return loops [506 on yarn 6]
xfer b15 f15;return loops [507 on yarn 6]
xfer b17 f17;return loops [508 on yarn 6]
xfer b19 f19;return loops [509 on yarn 6]
xfer b21 f21;return loops [510 on yarn 6]
xfer b23 f23;return loops [511 on yarn 6]
xfer b25 f25;return loops [512 on yarn 6]
xfer b27 f27;return loops [513 on yarn 6]
xfer b29 f29;return loops [514 on yarn 6]
xfer b31 f31;return loops [515 on yarn 6]
xfer b33 f33;return loops [516 on yarn 6]
xfer b35 f35;return loops [517 on yarn 6]
xfer b37 f37;return loops [518 on yarn 6]
xfer b39 f39;return loops [519 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [540 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [541 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [542 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [543 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [544 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [545 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [546 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [547 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [548 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [549 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [550 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [551 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [552 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [553 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [554 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [555 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [556 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [557 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [558 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [559 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [540 on yarn 6]
xfer b3 f3;return loops [541 on yarn 6]
xfer b5 f5;return loops [542 on yarn 6]
xfer b7 f7;return loops [543 on yarn 6]
xfer b9 f9;return loops [544 on yarn 6]
xfer b11 f11;return loops [545 on yarn 6]
xfer b13 f13;return loops [546 on yarn 6]
xfer b15 f15;return loops [547 on yarn 6]
xfer b17 f17;return loops [548 on yarn 6]
xfer b19 f19;return loops [549 on yarn 6]
xfer b21 f21;return loops [550 on yarn 6]
xfer b23 f23;return loops [551 on yarn 6]
xfer b25 f25;return loops [552 on yarn 6]
xfer b27 f27;return loops [553 on yarn 6]
xfer b29 f29;return loops [554 on yarn 6]
xfer b31 f31;return loops [555 on yarn 6]
xfer b33 f33;return loops [556 on yarn 6]
xfer b35 f35;return loops [557 on yarn 6]
xfer b37 f37;return loops [558 on yarn 6]
xfer b39 f39;return loops [559 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [580 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [581 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [582 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [583 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [584 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [585 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [586 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [587 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [588 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [589 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [590 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [591 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [592 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [593 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [594 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [595 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [596 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [597 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [598 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [599 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [580 on yarn 6]
xfer b3 f3;return loops [581 on yarn 6]
xfer b5 f5;return loops [582 on yarn 6]
xfer b7 f7;return loops [583 on yarn 6]
xfer b9 f9;return loops [584 on yarn 6]
xfer b11 f11;return loops [585 on yarn 6]
xfer b13 f13;return loops [586 on yarn 6]
xfer b15 f15;return loops [587 on yarn 6]
xfer b17 f17;return loops [588 on yarn 6]
xfer b19 f19;return loops [589 on yarn 6]
xfer b21 f21;return loops [590 on yarn 6]
xfer b23 f23;return loops [591 on yarn 6]
xfer b25 f25;return loops [592 on yarn 6]
xfer b27 f27;return loops [593 on yarn 6]
xfer b29 f29;return loops [594 on yarn 6]
xfer b31 f31;return loops [595 on yarn 6]
xfer b33 f33;return loops [596 on yarn 6]
xfer b35 f35;return loops [597 on yarn 6]
xfer b37 f37;return loops [598 on yarn 6]
xfer b39 f39;return loops [599 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [620 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [621 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [622 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [623 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [624 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [625 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [626 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [627 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [628 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [629 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [630 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [631 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [632 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [633 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [634 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [635 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [636 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [637 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [638 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [639 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [620 on yarn 6]
xfer b3 f3;return loops [621 on yarn 6]
xfer b5 f5;return loops [622 on yarn 6]
xfer b7 f7;return loops [623 on yarn 6]
xfer b9 f9;return loops [624 on yarn 6]
xfer b11 f11;return loops [625 on yarn 6]
xfer b13 f13;return loops [626 on yarn 6]
xfer b15 f15;return loops [627 on yarn 6]
xfer b17 f17;return loops [628 on yarn 6]
xfer b19 f19;return loops [629 on yarn 6]
xfer b21 f21;return loops [630 on yarn 6]
xfer b23 f23;return loops [631 on yarn 6]
xfer b25 f25;return loops [632 on yarn 6]
xfer b27 f27;return loops [633 on yarn 6]
xfer b29 f29;return loops [634 on yarn 6]
xfer b31 f31;return loops [635 on yarn 6]
xfer b33 f33;return loops [636 on yarn 6]
xfer b35 f35;return loops [637 on yarn 6]
xfer b37 f37;return loops [638 on yarn 6]
xfer b39 f39;return loops [639 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [660 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [661 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [662 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [663 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [664 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [665 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [666 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [667 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [668 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [669 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [670 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [671 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [672 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [673 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [674 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [675 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [676 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [677 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [678 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [679 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [660 on yarn 6]
xfer b3 f3;return loops [661 on yarn 6]
xfer b5 f5;return loops [662 on yarn 6]
xfer b7 f7;return loops [663 on yarn 6]
xfer b9 f9;return loops [664 on yarn 6]
xfer b11 f11;return loops [665 on yarn 6]
xfer b13 f13;return loops [666 on yarn 6]
xfer b15 f15;return loops [667 on yarn 6]
xfer b17 f17;return loops [668 on yarn 6]
xfer b19 f19;return loops [669 on yarn 6]
xfer b21 f21;return loops [670 on yarn 6]
xfer b23 f23;return loops [671 on yarn 6]
xfer b25 f25;return loops [672 on yarn 6]
xfer b27 f27;return loops [673 on yarn 6]
xfer b29 f29;return loops [674 on yarn 6]
xfer b31 f31;return loops [675 on yarn 6]
xfer b33 f33;return loops [676 on yarn 6]
xfer b35 f35;return loops [677 on yarn 6]
xfer b37 f37;return loops [678 on yarn 6]
xfer b39 f39;return loops [679 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [700 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [701 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [702 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [703 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [704 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [705 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [706 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [707 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [708 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [709 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [710 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [711 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [712 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [713 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [714 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [715 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [716 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [717 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [718 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [719 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [700 on yarn 6]
xfer b3 f3;return loops [701 on yarn 6]
xfer b5 f5;return loops [702 on yarn 6]
xfer b7 f7;return loops [703 on yarn 6]
xfer b9 f9;return loops [704 on yarn 6]
xfer b11 f11;return loops [705 on yarn 6]
xfer b13 f13;return loops [706 on yarn 6]
xfer b15 f15;return loops [707 on yarn 6]
xfer b17 f17;return loops [708 on yarn 6]
xfer b19 f19;return loops [709 on yarn 6]
xfer b21 f21;return loops [710 on yarn 6]
xfer b23 f23;return loops [711 on yarn 6]
xfer b25 f25;return loops [712 on yarn 6]
xfer b27 f27;return loops [713 on yarn 6]
xfer b29 f29;return loops [714 on yarn 6]
xfer b31 f31;return loops [715 on yarn 6]
xfer b33 f33;return loops [716 on yarn 6]
xfer b35 f35;return loops [717 on yarn 6]
xfer b37 f37;return loops [718 on yarn 6]
xfer b39 f39;return loops [719 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [740 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [741 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [742 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [743 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [744 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [745 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [746 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [747 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [748 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [749 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [750 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [751 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [752 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [753 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [754 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [755 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [756 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [757 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [758 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [759 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [740 on yarn 6]
xfer b3 f3;return loops [741 on yarn 6]
xfer b5 f5;return loops [742 on yarn 6]
xfer b7 f7;return loops [743 on yarn 6]
xfer b9 f9;return loops [744 on yarn 6]
xfer b11 f11;return loops [745 on yarn 6]
xfer b13 f13;return loops [746 on yarn 6]
xfer b15 f15;return loops [747 on yarn 6]
xfer b17 f17;return loops [748 on yarn 6]
xfer b19 f19;return loops [749 on yarn 6]
xfer b21 f21;return loops [750 on yarn 6]
xfer b23 f23;return loops [751 on yarn 6]
xfer b25 f25;return loops [752 on yarn 6]
xfer b27 f27;return loops [753 on yarn 6]
xfer b29 f29;return loops [754 on yarn 6]
xfer b31 f31;return loops [755 on yarn 6]
xfer b33 f33;return loops [756 on yarn 6]
xfer b35 f35;return loops [757 on yarn 6]
xfer b37 f37;return loops [758 on yarn 6]
xfer b39 f39;return loops [759 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [780 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [781 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [782 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [783 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [784 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [785 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [786 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [787 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [788 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [789 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [790 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [791 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [792 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [793 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [794 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [795 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [796 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [797 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [798 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [799 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [780 on yarn 6]
xfer b3 f3;return loops [781 on yarn 6]
xfer b5 f5;return loops [782 on yarn 6]
xfer b7 f7;return loops [783 on yarn 6]
xfer b9 f9;return loops [784 on yarn 6]
xfer b11 f11;return loops [785 on yarn 6]
xfer b13 f13;return loops [786 on yarn 6]
xfer b15 f15;return loops [787 on yarn 6]
xfer b17 f17;return loops [788 on yarn 6]
xfer b19 f19;return loops [789 on yarn 6]
xfer b21 f21;return loops [790 on yarn 6]
xfer b23 f23;return loops [791 on yarn 6]
xfer b25 f25;return loops [792 on yarn 6]
xfer b27 f27;return loops [793 on yarn 6]
xfer b29 f29;return loops [794 on yarn 6]
xfer b31 f31;return loops [795 on yarn 6]
xfer b33 f33;return loops [796 on yarn 6]
xfer b35 f35;return loops [797 on yarn 6]
xfer b37 f37;return loops [798 on yarn 6]
xfer b39 f39;return loops [799 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [820 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [821 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [822 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [823 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [824 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [825 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [826 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [827 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [828 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [829 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [830 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [831 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [832 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [833 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [834 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [835 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [836 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [837 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [838 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [839 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [820 on yarn 6]
xfer b3 f3;return loops [821 on yarn 6]
xfer b5 f5;return loops [822 on yarn 6]
xfer b7 f7;return loops [823 on yarn 6]
xfer b9 f9;return loops [824 on yarn 6]
xfer b11 f11;return loops [825 on yarn 6]
xfer b13 f13;return loops [826 on yarn 6]
xfer b15 f15;return loops [827 on yarn 6]
xfer b17 f17;return loops [828 on yarn 6]
xfer b19 f19;return loops [829 on yarn 6]
xfer b21 f21;return loops [830 on yarn 6]
xfer b23 f23;return loops [831 on yarn 6]
xfer b25 f25;return loops [832 on yarn 6]
xfer b27 f27;return loops [833 on yarn 6]
xfer b29 f29;return loops [834 on yarn 6]
xfer b31 f31;return loops [835 on yarn 6]
xfer b33 f33;return loops [836 on yarn 6]
xfer b35 f35;return loops [837 on yarn 6]
xfer b37 f37;return loops [838 on yarn 6]
xfer b39 f39;return loops [839 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [860 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [861 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [862 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [863 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [864 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [865 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [866 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [867 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [868 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [869 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [870 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [871 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [872 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [873 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [874 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [875 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [876 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [877 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [878 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [879 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [860 on yarn 6]
xfer b3 f3;return loops [861 on yarn 6]
xfer b5 f5;return loops [862 on yarn 6]
xfer b7 f7;return loops [863 on yarn 6]
xfer b9 f9;return loops [864 on yarn 6]
xfer b11 f11;return loops [865 on yarn 6]
xfer b13 f13;return loops [866 on yarn 6]
xfer b15 f15;return loops [867 on yarn 6]
xfer b17 f17;return loops [868 on yarn 6]
xfer b19 f19;return loops [869 on yarn 6]
xfer b21 f21;return loops [870 on yarn 6]
xfer b23 f23;return loops [871 on yarn 6]
xfer b25 f25;return loops [872 on yarn 6]
xfer b27 f27;return loops [873 on yarn 6]
xfer b29 f29;return loops [874 on yarn 6]
xfer b31 f31;return loops [875 on yarn 6]
xfer b33 f33;return loops [876 on yarn 6]
xfer b35 f35;return loops [877 on yarn 6]
xfer b37 f37;return loops [878 on yarn 6]
xfer b39 f39;return loops [879 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [900 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [901 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [902 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [903 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [904 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [905 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [906 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [907 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [908 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [909 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [910 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [911 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [912 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [913 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [914 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [915 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [916 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [917 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [918 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [919 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [900 on yarn 6]
xfer b3 f3;return loops [901 on yarn 6]
xfer b5 f5;return loops [902 on yarn 6]
xfer b7 f7;return loops [903 on yarn 6]
xfer b9 f9;return loops [904 on yarn 6]
xfer b11 f11;return loops [905 on yarn 6]
xfer b13 f13;return loops [906 on yarn 6]
xfer b15 f15;return loops [907 on yarn 6]
xfer b17 f17;return loops [908 on yarn 6]
xfer b19 f19;return loops [909 on yarn 6]
xfer b21 f21;return loops [910 on yarn 6]
xfer b23 f23;return loops [911 on yarn 6]
xfer b25 f25;return loops [912 on yarn 6]
xfer b27 f27;return loops [913 on yarn 6]
xfer b29 f29;return loops [914 on yarn 6]
xfer b31 f31;return loops [915 on yarn 6]
xfer b33 f33;return loops [916 on yarn 6]
xfer b35 f35;return loops [917 on yarn 6]
xfer b37 f37;return loops [918 on yarn 6]
xfer b39 f39;return loops [919 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [940 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [941 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [942 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [943 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [944 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [945 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [946 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [947 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [948 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [949 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [950 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [951 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [952 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [953 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [954 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [955 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [956 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [957 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [958 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [959 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [940 on yarn 6]
xfer b3 f3;return loops [941 on yarn 6]
xfer b5 f5;return loops [942 on yarn 6]
xfer b7 f7;return loops [943 on yarn 6]
xfer b9 f9;return loops [944 on yarn 6]
xfer b11 f11;return loops [945 on yarn 6]
xfer b13 f13;return loops [946 on yarn 6]
xfer b15 f15;return loops [947 on yarn 6]
xfer b17 f17;return loops [948 on yarn 6]
xfer b19 f19;return loops [949 on yarn 6]
xfer b21 f21;return loops [950 on yarn 6]
xfer b23 f23;return loops [951 on yarn 6]
xfer b25 f25;return loops [952 on yarn 6]
xfer b27 f27;return loops [953 on yarn 6]
xfer b29 f29;return loops [954 on yarn 6]
xfer b31 f31;return loops [955 on yarn 6]
xfer b33 f33;return loops [956 on yarn 6]
xfer b35 f35;return loops [957 on yarn 6]
xfer b37 f37;return loops [958 on yarn 6]
xfer b39 f39;return loops [959 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [980 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [981 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [982 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [983 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [984 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [985 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [986 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [987 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [988 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [989 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [990 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [991 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [992 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [993 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [994 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [995 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [996 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [997 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [998 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [999 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [980 on yarn 6]
xfer b3 f3;return loops [981 on yarn 6]
xfer b5 f5;return loops [982 on yarn 6]
xfer b7 f7;return loops [983 on yarn 6]
xfer b9 f9;return loops [984 on yarn 6]
xfer b11 f11;return loops [985 on yarn 6]
xfer b13 f13;return loops [986 on yarn 6]
xfer b15 f15;return loops [987 on yarn 6]
xfer b17 f17;return loops [988 on yarn 6]
xfer b19 f19;return loops [989 on yarn 6]
xfer b21 f21;return loops [990 on yarn 6]
xfer b23 f23;return loops [991 on yarn 6]
xfer b25 f25;return loops [992 on yarn 6]
xfer b27 f27;return loops [993 on yarn 6]
xfer b29 f29;return loops [994 on yarn 6]
xfer b31 f31;return loops [995 on yarn 6]
xfer b33 f33;return loops [996 on yarn 6]
xfer b35 f35;return loops [997 on yarn 6]
xfer b37 f37;return loops [998 on yarn 6]
xfer b39 f39;return loops [999 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1020 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1021 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1022 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1023 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1024 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1025 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1026 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1027 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1028 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1029 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1030 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1031 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1032 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1033 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1034 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1035 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1036 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1037 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1038 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1039 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1020 on yarn 6]
xfer b3 f3;return loops [1021 on yarn 6]
xfer b5 f5;return loops [1022 on yarn 6]
xfer b7 f7;return loops [1023 on yarn 6]
xfer b9 f9;return loops [1024 on yarn 6]
xfer b11 f11;return loops [1025 on yarn 6]
xfer b13 f13;return loops [1026 on yarn 6]
xfer b15 f15;return loops [1027 on yarn 6]
xfer b17 f17;return loops [1028 on yarn 6]
xfer b19 f19;return loops [1029 on yarn 6]
xfer b21 f21;return loops [1030 on yarn 6]
xfer b23 f23;return loops [1031 on yarn 6]
xfer b25 f25;return loops [1032 on yarn 6]
xfer b27 f27;return loops [1033 on yarn 6]
xfer b29 f29;return loops [1034 on yarn 6]
xfer b31 f31;return loops [1035 on yarn 6]
xfer b33 f33;return loops [1036 on yarn 6]
xfer b35 f35;return loops [1037 on yarn 6]
xfer b37 f37;return loops [1038 on yarn 6]
xfer b39 f39;return loops [1039 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1060 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1061 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1062 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1063 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1064 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1065 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1066 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1067 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1068 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1069 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1070 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1071 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1072 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1073 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1074 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1075 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1076 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1077 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1078 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1079 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1060 on yarn 6]
xfer b3 f3;return loops [1061 on yarn 6]
xfer b5 f5;return loops [1062 on yarn 6]
xfer b7 f7;return loops [1063 on yarn 6]
xfer b9 f9;return loops [1064 on yarn 6]
xfer b11 f11;return loops [1065 on yarn 6]
xfer b13 f13;return loops [1066 on yarn 6]
xfer b15 f15;return loops [1067 on yarn 6]
xfer b17 f17;return loops [1068 on yarn 6]
xfer b19 f19;return loops [1069 on yarn 6]
xfer b21 f21;return loops [1070 on yarn 6]
xfer b23 f23;return loops [1071 on yarn 6]
xfer b25 f25;return loops [1072 on yarn 6]
xfer b27 f27;return loops [1073 on yarn 6]
xfer b29 f29;return loops [1074 on yarn 6]
xfer b31 f31;return loops [1075 on yarn 6]
xfer b33 f33;return loops [1076 on yarn 6]
xfer b35 f35;return loops [1077 on yarn 6]
xfer b37 f37;return loops [1078 on yarn 6]
xfer b39 f39;return loops [1079 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1100 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1101 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1102 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1103 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1104 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1105 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1106 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1107 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1108 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1109 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1110 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1111 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1112 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1113 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1114 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1115 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1116 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1117 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1118 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1119 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1100 on yarn 6]
xfer b3 f3;return loops [1101 on yarn 6]
xfer b5 f5;return loops [1102 on yarn 6]
xfer b7 f7;return loops [1103 on yarn 6]
xfer b9 f9;return loops [1104 on yarn 6]
xfer b11 f11;return loops [1105 on yarn 6]
xfer b13 f13;return loops [1106 on yarn 6]
xfer b15 f15;return loops [1107 on yarn 6]
xfer b17 f17;return loops [1108 on yarn 6]
xfer b19 f19;return loops [1109 on yarn 6]
xfer b21 f21;return loops [1110 on yarn 6]
xfer b23 f23;return loops [1111 on yarn 6]
xfer b25 f25;return loops [1112 on yarn 6]
xfer b27 f27;return loops [1113 on yarn 6]
xfer b29 f29;return loops [1114 on yarn 6]
xfer b31 f31;return loops [1115 on yarn 6]
xfer b33 f33;return loops [1116 on yarn 6]
xfer b35 f35;return loops [1117 on yarn 6]
xfer b37 f37;return loops [1118 on yarn 6]
xfer b39 f39;return loops [1119 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1140 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1141 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1142 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1143 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1144 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1145 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1146 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1147 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1148 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1149 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1150 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1151 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1152 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1153 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1154 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1155 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1156 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1157 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1158 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1159 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1140 on yarn 6]
xfer b3 f3;return loops [1141 on yarn 6]
xfer b5 f5;return loops [1142 on yarn 6]
xfer b7 f7;return loops [1143 on yarn 6]
xfer b9 f9;return loops [1144 on yarn 6]
xfer b11 f11;return loops [1145 on yarn 6]
xfer b13 f13;return loops [1146 on yarn 6]
xfer b15 f15;return loops [1147 on yarn 6]
xfer b17 f17;return loops [1148 on yarn 6]
xfer b19 f19;return loops [1149 on yarn 6]
xfer b21 f21;return loops [1150 on yarn 6]
xfer b23 f23;return loops [1151 on yarn 6]
xfer b25 f25;return loops [1152 on yarn 6]
xfer b27 f27;return loops [1153 on yarn 6]
xfer b29 f29;return loops [1154 on yarn 6]
xfer b31 f31;return loops [1155 on yarn 6]
xfer b33 f33;return loops [1156 on yarn 6]
xfer b35 f35;return loops [1157 on yarn 6]
xfer b37 f37;return loops [1158 on yarn 6]
xfer b39 f39;return loops [1159 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1180 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1181 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1182 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1183 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1184 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1185 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1186 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1187 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1188 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1189 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1190 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1191 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1192 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1193 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1194 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1195 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1196 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1197 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1198 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1199 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1180 on yarn 6]
xfer b3 f3;return loops [1181 on yarn 6]
xfer b5 f5;return loops [1182 on yarn 6]
xfer b7 f7;return loops [1183 on yarn 6]
xfer b9 f9;return loops [1184 on yarn 6]
xfer b11 f11;return loops [1185 on yarn 6]
xfer b13 f13;return loops [1186 on yarn 6]
xfer b15 f15;return loops [1187 on yarn 6]
xfer b17 f17;return loops [1188 on yarn 6]
xfer b19 f19;return loops [1189 on yarn 6]
xfer b21 f21;return loops [1190 on yarn 6]
xfer b23 f23;return loops [1191 on yarn 6]
xfer b25 f25;return loops [1192 on yarn 6]
xfer b27 f27;return loops [1193 on yarn 6]
xfer b29 f29;return loops [1194 on yarn 6]
xfer b31 f31;return loops [1195 on yarn 6]
xfer b33 f33;return loops [1196 on yarn 6]
xfer b35 f35;return loops [1197 on yarn 6]
xfer b37 f37;return loops [1198 on yarn 6]
xfer b39 f39;return loops [1199 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1220 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1221 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1222 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1223 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1224 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1225 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1226 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1227 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1228 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1229 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1230 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1231 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1232 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1233 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1234 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1235 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1236 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1237 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1238 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1239 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1220 on yarn 6]
xfer b3 f3;return loops [1221 on yarn 6]
xfer b5 f5;return loops [1222 on yarn 6]
xfer b7 f7;return loops [1223 on yarn 6]
xfer b9 f9;return loops [1224 on yarn 6]
xfer b11 f11;return loops [1225 on yarn 6]
xfer b13 f13;return loops [1226 on yarn 6]
xfer b15 f15;return loops [1227 on yarn 6]
xfer b17 f17;return loops [1228 on yarn 6]
xfer b19 f19;return loops [1229 on yarn 6]
xfer b21 f21;return loops [1230 on yarn 6]
xfer b23 f23;return loops [1231 on yarn 6]
xfer b25 f25;return loops [1232 on yarn 6]
xfer b27 f27;return loops [1233 on yarn 6]
xfer b29 f29;return loops [1234 on yarn 6]
xfer b31 f31;return loops [1235 on yarn 6]
xfer b33 f33;return loops [1236 on yarn 6]
xfer b35 f35;return loops [1237 on yarn 6]
xfer b37 f37;return loops [1238 on yarn 6]
xfer b39 f39;return loops [1239 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1260 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1261 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1262 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1263 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1264 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1265 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1266 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1267 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1268 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1269 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1270 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1271 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1272 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1273 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1274 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1275 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1276 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1277 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1278 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1279 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1260 on yarn 6]
xfer b3 f3;return loops [1261 on yarn 6]
xfer b5 f5;return loops [1262 on yarn 6]
xfer b7 f7;return loops [1263 on yarn 6]
xfer b9 f9;return loops [1264 on yarn 6]
xfer b11 f11;return loops [1265 on yarn 6]
xfer b13 f13;return loops [1266 on yarn 6]
xfer b15 f15;return loops [1267 on yarn 6]
xfer b17 f17;return loops [1268 on yarn 6]
xfer b19 f19;return loops [1269 on yarn 6]
xfer b21 f21;return loops [1270 on yarn 6]
xfer b23 f23;return loops [1271 on yarn 6]
xfer b25 f25;return loops [1272 on yarn 6]
xfer b27 f27;return loops [1273 on yarn 6]
xfer b29 f29;return loops [1274 on yarn 6]
xfer b31 f31;return loops [1275 on yarn 6]
xfer b33 f33;return loops [1276 on yarn 6]
xfer b35 f35;return loops [1277 on yarn 6]
xfer b37 f37;return loops [1278 on yarn 6]
xfer b39 f39;return loops [1279 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1300 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1301 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1302 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1303 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1304 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1305 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1306 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1307 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1308 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1309 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1310 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1311 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1312 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1313 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1314 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1315 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1316 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1317 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1318 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1319 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1300 on yarn 6]
xfer b3 f3;return loops [1301 on yarn 6]
xfer b5 f5;return loops [1302 on yarn 6]
xfer b7 f7;return loops [1303 on yarn 6]
xfer b9 f9;return loops [1304 on yarn 6]
xfer b11 f11;return loops [1305 on yarn 6]
xfer b13 f13;return loops [1306 on yarn 6]
xfer b15 f15;return loops [1307 on yarn 6]
xfer b17 f17;return loops [1308 on yarn 6]
xfer b19 f19;return loops [1309 on yarn 6]
xfer b21 f21;return loops [1310 on yarn 6]
xfer b23 f23;return loops [1311 on yarn 6]
xfer b25 f25;return loops [1312 on yarn 6]
xfer b27 f27;return loops [1313 on yarn 6]
xfer b29 f29;return loops [1314 on yarn 6]
xfer b31 f31;return loops [1315 on yarn 6]
xfer b33 f33;return loops [1316 on yarn 6]
xfer b35 f35;return loops [1317 on yarn 6]
xfer b37 f37;return loops [1318 on yarn 6]
xfer b39 f39;return loops [1319 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1340 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1341 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1342 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1343 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1344 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1345 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1346 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1347 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1348 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1349 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1350 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1351 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1352 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1353 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1354 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1355 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1356 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1357 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1358 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1359 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1340 on yarn 6]
xfer b3 f3;return loops [1341 on yarn 6]
xfer b5 f5;return loops [1342 on yarn 6]
xfer b7 f7;return loops [1343 on yarn 6]
xfer b9 f9;return loops [1344 on yarn 6]
xfer b11 f11;return loops [1345 on yarn 6]
xfer b13 f13;return loops [1346 on yarn 6]
xfer b15 f15;return loops [1347 on yarn 6]
xfer b17 f17;return loops [1348 on yarn 6]
xfer b19 f19;return loops [1349 on yarn 6]
xfer b21 f21;return loops [1350 on yarn 6]
xfer b23 f23;return loops [1351 on yarn 6]
xfer b25 f25;return loops [1352 on yarn 6]
xfer b27 f27;return loops [1353 on yarn 6]
xfer b29 f29;return loops [1354 on yarn 6]
xfer b31 f31;return loops [1355 on yarn 6]
xfer b33 f33;return loops [1356 on yarn 6]
xfer b35 f35;return loops [1357 on yarn 6]
xfer b37 f37;return loops [1358 on yarn 6]
xfer b39 f39;return loops [1359 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1380 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1381 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1382 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1383 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1384 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1385 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1386 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1387 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1388 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1389 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1390 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1391 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1392 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1393 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1394 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1395 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1396 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1397 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1398 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1399 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1380 on yarn 6]
xfer b3 f3;return loops [1381 on yarn 6]
xfer b5 f5;return loops [1382 on yarn 6]
xfer b7 f7;return loops [1383 on yarn 6]
xfer b9 f9;return loops [1384 on yarn 6]
xfer b11 f11;return loops [1385 on yarn 6]
xfer b13 f13;return loops [1386 on yarn 6]
xfer b15 f15;return loops [1387 on yarn 6]
xfer b17 f17;return loops [1388 on yarn 6]
xfer b19 f19;return loops [1389 on yarn 6]
xfer b21 f21;return loops [1390 on yarn 6]
xfer b23 f23;return loops [1391 on yarn 6]
xfer b25 f25;return loops [1392 on yarn 6]
xfer b27 f27;return loops [1393 on yarn 6]
xfer b29 f29;return loops [1394 on yarn 6]
xfer b31 f31;return loops [1395 on yarn 6]
xfer b33 f33;return loops [1396 on yarn 6]
xfer b35 f35;return loops [1397 on yarn 6]
xfer b37 f37;return loops [1398 on yarn 6]
xfer b39 f39;return loops [1399 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1420 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1421 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1422 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1423 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1424 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1425 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1426 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1427 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1428 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1429 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1430 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1431 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1432 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1433 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1434 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1435 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1436 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1437 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1438 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1439 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1420 on yarn 6]
xfer b3 f3;return loops [1421 on yarn 6]
xfer b5 f5;return loops [1422 on yarn 6]
xfer b7 f7;return loops [1423 on yarn 6]
xfer b9 f9;return loops [1424 on yarn 6]
xfer b11 f11;return loops [1425 on yarn 6]
xfer b13 f13;return loops [1426 on yarn 6]
xfer b15 f15;return loops [1427 on yarn 6]
xfer b17 f17;return loops [1428 on yarn 6]
xfer b19 f19;return loops [1429 on yarn 6]
xfer b21 f21;return loops [1430 on yarn 6]
xfer b23 f23;return loops [1431 on yarn 6]
xfer b25 f25;return loops [1432 on yarn 6]
xfer b27 f27;return loops [1433 on yarn 6]
xfer b29 f29;return loops [1434 on yarn 6]
xfer b31 f31;return loops [1435 on yarn 6]
xfer b33 f33;return loops [1436 on yarn 6]
xfer b35 f35;return loops [1437 on yarn 6]
xfer b37 f37;return loops [1438 on yarn 6]
xfer b39 f39;return loops [1439 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1460 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1461 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1462 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1463 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1464 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1465 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1466 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1467 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1468 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1469 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1470 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1471 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1472 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1473 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1474 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1475 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1476 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1477 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1478 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1479 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1460 on yarn 6]
xfer b3 f3;return loops [1461 on yarn 6]
xfer b5 f5;return loops [1462 on yarn 6]
xfer b7 f7;return loops [1463 on yarn 6]
xfer b9 f9;return loops [1464 on yarn 6]
xfer b11 f11;return loops [1465 on yarn 6]
xfer b13 f13;return loops [1466 on yarn 6]
xfer b15 f15;return loops [1467 on yarn 6]
xfer b17 f17;return loops [1468 on yarn 6]
xfer b19 f19;return loops [1469 on yarn 6]
xfer b21 f21;return loops [1470 on yarn 6]
xfer b23 f23;return loops [1471 on yarn 6]
xfer b25 f25;return loops [1472 on yarn 6]
xfer b27 f27;return loops [1473 on yarn 6]
xfer b29 f29;return loops [1474 on yarn 6]
xfer b31 f31;return loops [1475 on yarn 6]
xfer b33 f33;return loops [1476 on yarn 6]
xfer b35 f35;return loops [1477 on yarn 6]
xfer b37 f37;return loops [1478 on yarn 6]
xfer b39 f39;return loops [1479 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1500 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1501 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1502 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1503 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1504 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1505 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1506 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1507 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1508 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1509 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1510 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1511 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1512 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1513 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1514 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1515 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1516 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1517 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1518 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1519 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1500 on yarn 6]
xfer b3 f3;return loops [1501 on yarn 6]
xfer b5 f5;return loops [1502 on yarn 6]
xfer b7 f7;return loops [1503 on yarn 6]
xfer b9 f9;return loops [1504 on yarn 6]
xfer b11 f11;return loops [1505 on yarn 6]
xfer b13 f13;return loops [1506 on yarn 6]
xfer b15 f15;return loops [1507 on yarn 6]
xfer b17 f17;return loops [1508 on yarn 6]
xfer b19 f19;return loops [1509 on yarn 6]
xfer b21 f21;return loops [1510 on yarn 6]
xfer b23 f23;return loops [1511 on yarn 6]
xfer b25 f25;return loops [1512 on yarn 6]
xfer b27 f27;return loops [1513 on yarn 6]
xfer b29 f29;return loops [1514 on yarn 6]
xfer b31 f31;return loops [1515 on yarn 6]
xfer b33 f33;return loops [1516 on yarn 6]
xfer b35 f35;return loops [1517 on yarn 6]
xfer b37 f37;return loops [1518 on yarn 6]
xfer b39 f39;return loops [1519 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1540 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1541 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1542 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1543 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1544 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1545 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1546 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1547 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1548 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1549 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1550 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1551 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1552 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1553 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1554 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1555 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1556 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1557 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1558 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1559 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1540 on yarn 6]
xfer b3 f3;return loops [1541 on yarn 6]
xfer b5 f5;return loops [1542 on yarn 6]
xfer b7 f7;return loops [1543 on yarn 6]
xfer b9 f9;return loops [1544 on yarn 6]
xfer b11 f11;return loops [1545 on yarn 6]
xfer b13 f13;return loops [1546 on yarn 6]
xfer b15 f15;return loops [1547 on yarn 6]
xfer b17 f17;return loops [1548 on yarn 6]
xfer b19 f19;return loops [1549 on yarn 6]
xfer b21 f21;return loops [1550 on yarn 6]
xfer b23 f23;return loops [1551 on yarn 6]
xfer b25 f25;return loops [1552 on yarn 6]
xfer b27 f27;return loops [1553 on yarn 6]
xfer b29 f29;return loops [1554 on yarn 6]
xfer b31 f31;return loops [1555 on yarn 6]
xfer b33 f33;return loops [1556 on yarn 6]
xfer b35 f35;return loops [1557 on yarn 6]
xfer b37 f37;return loops [1558 on yarn 6]
xfer b39 f39;return loops [1559 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1580 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1581 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1582 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1583 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1584 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1585 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1586 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1587 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1588 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1589 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1590 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1591 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1592 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1593 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1594 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1595 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1596 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1597 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1598 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1599 on yarn 6] from s1 relative to s0
knit - f38 6
knit - f36 6
knit - f34 6
knit - f32 6
knit - f30 6
knit - f28 6
knit - f26 6
knit - f24 6
knit - f22 6
knit - f20 6
knit - f18 6
knit - f16 6
knit - f14 6
knit - f12 6
knit - f10 6
knit - f8 6
knit - f6 6
knit - f4 6
knit - f2 6
knit - f0 6
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1580 on yarn 6]
xfer b3 f3;return loops [1581 on yarn 6]
xfer b5 f5;return loops [1582 on yarn 6]
xfer b7 f7;return loops [1583 on yarn 6]
xfer b9 f9;return loops [1584 on yarn 6]
xfer b11 f11;return loops [1585 on yarn 6]
xfer b13 f13;return loops [1586 on yarn 6]
xfer b15 f15;return loops [1587 on yarn 6]
xfer b17 f17;return loops [1588 on yarn 6]
xfer b19 f19;return loops [1589 on yarn 6]
xfer b21 f21;return loops [1590 on yarn 6]
xfer b23 f23;return loops [1591 on yarn 6]
xfer b25 f25;return loops [1592 on yarn 6]
xfer b27 f27;return loops [1593 on yarn 6]
xfer b29 f29;return loops [1594 on yarn 6]
xfer b31 f31;return loops [1595 on yarn 6]
xfer b33 f33;return loops [1596 on yarn 6]
xfer b35 f35;return loops [1597 on yarn 6]
xfer b37 f37;return loops [1598 on yarn 6]
xfer b39 f39;return loops [1599 on yarn 6]
knit + f1 6
knit + f3 6
knit + f5 6
knit + f7 6
knit + f9 6
knit + f11 6
knit + f13 6
knit + f15 6
knit + f17 6
knit + f19 6
knit + f21 6
knit + f23 6
knit + f25 6
knit + f27 6
knit + f29 6
knit + f31 6
knit + f33 6
knit + f35 6
knit + f37 6
knit + f39 6
;no-op. Releasehook with no hooked carriers
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1620 on yarn 6] from s1 relative to s0
xfer f3 b3;peel loops [1621 on yarn 6] from s1 relative to s0
xfer f5 b5;peel loops [1622 on yarn 6] from s1 relative to s0
xfer f7 b7;peel loops [1623 on yarn 6] from s1 relative to s0
xfer f9 b9;peel loops [1624 on yarn 6] from s1 relative to s0
xfer f11 b11;peel loops [1625 on yarn 6] from s1 relative to s0
xfer f13 b13;peel loops [1626 on yarn 6] from s1 relative to s0
xfer f15 b15;peel loops [1627 on yarn 6] from s1 relative to s0
xfer f17 b17;peel loops [1628 on yarn 6] from s1 relative to s0
xfer f19 b19;peel loops [1629 on yarn 6] from s1 relative to s0
xfer f21 b21;peel loops [1630 on yarn 6] from s1 relative to s0
xfer f23 b23;peel loops [1631 on yarn 6] from s1 relative to s0
xfer f25 b25;peel loops [1632 on yarn 6] from s1 relative to s0
xfer f27 b27;peel loops [1633 on yarn 6] from s1 relative to s0
xfer f29 b29;peel loops [1634 on yarn 6] from s1 relative to s0
xfer f31 b31;peel loops [1635 on yarn 6] from s1 relative to s0
xfer f33 b33;peel loops [1636 on yarn 6] from s1 relative to s0
xfer f35 b35;peel loops [1637 on yarn 6] from s1 relative to s0
xfer f37 b37;peel loops [1638 on yarn 6] from s1 relative to s0
xfer f39 b39;peel loops [1639 on yarn 6] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1620 on yarn 6]
xfer b3 f3;return loops [1621 on yarn 6]
xfer b5 f5;return loops [1622 on yarn 6]
xfer b7 f7;return loops [1623 on yarn 6]
xfer b9 f9;return loops [1624 on yarn 6]
xfer b11 f11;return loops [1625 on yarn 6]
xfer b13 f13;return loops [1626 on yarn 6]
xfer b15 f15;return loops [1627 on yarn 6]
xfer b17 f17;return loops [1628 on yarn 6]
xfer b19 f19;return loops [1629 on yarn 6]
xfer b21 f21;return loops [1630 on yarn 6]
xfer b23 f23;return loops [1631 on yarn 6]
xfer b25 f25;return loops [1632 on yarn 6]
xfer b27 f27;return loops [1633 on yarn 6]
xfer b29 f29;return loops [1634 on yarn 6]
xfer b31 f31;return loops [1635 on yarn 6]
xfer b33 f33;return loops [1636 on yarn 6]
xfer b35 f35;return loops [1637 on yarn 6]
xfer b37 f37;return loops [1638 on yarn 6]
xfer b39 f39;return loops [1639 on yarn 6]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1660 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [1661 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [1662 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [1663 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [1664 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [1665 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [1666 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [1667 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [1668 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [1669 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [1670 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [1671 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [1672 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [1673 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [1674 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [1675 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [1676 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [1677 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [1678 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [1679 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1660 on yarn 7]
xfer b3 f3;return loops [1661 on yarn 7]
xfer b5 f5;return loops [1662 on yarn 7]
xfer b7 f7;return loops [1663 on yarn 7]
xfer b9 f9;return loops [1664 on yarn 7]
xfer b11 f11;return loops [1665 on yarn 7]
xfer b13 f13;return loops [1666 on yarn 7]
xfer b15 f15;return loops [1667 on yarn 7]
xfer b17 f17;return loops [1668 on yarn 7]
xfer b19 f19;return loops [1669 on yarn 7]
xfer b21 f21;return loops [1670 on yarn 7]
xfer b23 f23;return loops [1671 on yarn 7]
xfer b25 f25;return loops [1672 on yarn 7]
xfer b27 f27;return loops [1673 on yarn 7]
xfer b29 f29;return loops [1674 on yarn 7]
xfer b31 f31;return loops [1675 on yarn 7]
xfer b33 f33;return loops [1676 on yarn 7]
xfer b35 f35;return loops [1677 on yarn 7]
xfer b37 f37;return loops [1678 on yarn 7]
xfer b39 f39;return loops [1679 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1700 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [1701 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [1702 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [1703 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [1704 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [1705 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [1706 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [1707 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [1708 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [1709 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [1710 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [1711 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [1712 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [1713 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [1714 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [1715 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [1716 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [1717 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [1718 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [1719 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1700 on yarn 7]
xfer b3 f3;return loops [1701 on yarn 7]
xfer b5 f5;return loops [1702 on yarn 7]
xfer b7 f7;return loops [1703 on yarn 7]
xfer b9 f9;return loops [1704 on yarn 7]
xfer b11 f11;return loops [1705 on yarn 7]
xfer b13 f13;return loops [1706 on yarn 7]
xfer b15 f15;return loops [1707 on yarn 7]
xfer b17 f17;return loops [1708 on yarn 7]
xfer b19 f19;return loops [1709 on yarn 7]
xfer b21 f21;return loops [1710 on yarn 7]
xfer b23 f23;return loops [1711 on yarn 7]
xfer b25 f25;return loops [1712 on yarn 7]
xfer b27 f27;return loops [1713 on yarn 7]
xfer b29 f29;return loops [1714 on yarn 7]
xfer b31 f31;return loops [1715 on yarn 7]
xfer b33 f33;return loops [1716 on yarn 7]
xfer b35 f35;return loops [1717 on yarn 7]
xfer b37 f37;return loops [1718 on yarn 7]
xfer b39 f39;return loops [1719 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1740 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [1741 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [1742 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [1743 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [1744 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [1745 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [1746 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [1747 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [1748 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [1749 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [1750 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [1751 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [1752 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [1753 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [1754 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [1755 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [1756 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [1757 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [1758 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [1759 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1740 on yarn 7]
xfer b3 f3;return loops [1741 on yarn 7]
xfer b5 f5;return loops [1742 on yarn 7]
xfer b7 f7;return loops [1743 on yarn 7]
xfer b9 f9;return loops [1744 on yarn 7]
xfer b11 f11;return loops [1745 on yarn 7]
xfer b13 f13;return loops [1746 on yarn 7]
xfer b15 f15;return loops [1747 on yarn 7]
xfer b17 f17;return loops [1748 on yarn 7]
xfer b19 f19;return loops [1749 on yarn 7]
xfer b21 f21;return loops [1750 on yarn 7]
xfer b23 f23;return loops [1751 on yarn 7]
xfer b25 f25;return loops [1752 on yarn 7]
xfer b27 f27;return loops [1753 on yarn 7]
xfer b29 f29;return loops [1754 on yarn 7]
xfer b31 f31;return loops [1755 on yarn 7]
xfer b33 f33;return loops [1756 on yarn 7]
xfer b35 f35;return loops [1757 on yarn 7]
xfer b37 f37;return loops [1758 on yarn 7]
xfer b39 f39;return loops [1759 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1780 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [1781 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [1782 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [1783 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [1784 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [1785 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [1786 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [1787 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [1788 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [1789 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [1790 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [1791 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [1792 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [1793 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [1794 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [1795 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [1796 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [1797 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [1798 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [1799 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1780 on yarn 7]
xfer b3 f3;return loops [1781 on yarn 7]
xfer b5 f5;return loops [1782 on yarn 7]
xfer b7 f7;return loops [1783 on yarn 7]
xfer b9 f9;return loops [1784 on yarn 7]
xfer b11 f11;return loops [1785 on yarn 7]
xfer b13 f13;return loops [1786 on yarn 7]
xfer b15 f15;return loops [1787 on yarn 7]
xfer b17 f17;return loops [1788 on yarn 7]
xfer b19 f19;return loops [1789 on yarn 7]
xfer b21 f21;return loops [1790 on yarn 7]
xfer b23 f23;return loops [1791 on yarn 7]
xfer b25 f25;return loops [1792 on yarn 7]
xfer b27 f27;return loops [1793 on yarn 7]
xfer b29 f29;return loops [1794 on yarn 7]
xfer b31 f31;return loops [1795 on yarn 7]
xfer b33 f33;return loops [1796 on yarn 7]
xfer b35 f35;return loops [1797 on yarn 7]
xfer b37 f37;return loops [1798 on yarn 7]
xfer b39 f39;return loops [1799 on yarn 7]
knit + f1 7
knit + f3 7
knit + f5 7
knit + f7 7
knit + f9 7
knit + f11 7
knit + f13 7
knit + f15 7
knit + f17 7
knit + f19 7
knit + f21 7
knit + f23 7
knit + f25 7
knit + f27 7
knit + f29 7
knit + f31 7
knit + f33 7
knit + f35 7
knit + f37 7
knit + f39 7
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1820 on yarn 7] from s1 relative to s0
xfer f3 b3;peel loops [1821 on yarn 7] from s1 relative to s0
xfer f5 b5;peel loops [1822 on yarn 7] from s1 relative to s0
xfer f7 b7;peel loops [1823 on yarn 7] from s1 relative to s0
xfer f9 b9;peel loops [1824 on yarn 7] from s1 relative to s0
xfer f11 b11;peel loops [1825 on yarn 7] from s1 relative to s0
xfer f13 b13;peel loops [1826 on yarn 7] from s1 relative to s0
xfer f15 b15;peel loops [1827 on yarn 7] from s1 relative to s0
xfer f17 b17;peel loops [1828 on yarn 7] from s1 relative to s0
xfer f19 b19;peel loops [1829 on yarn 7] from s1 relative to s0
xfer f21 b21;peel loops [1830 on yarn 7] from s1 relative to s0
xfer f23 b23;peel loops [1831 on yarn 7] from s1 relative to s0
xfer f25 b25;peel loops [1832 on yarn 7] from s1 relative to s0
xfer f27 b27;peel loops [1833 on yarn 7] from s1 relative to s0
xfer f29 b29;peel loops [1834 on yarn 7] from s1 relative to s0
xfer f31 b31;peel loops [1835 on yarn 7] from s1 relative to s0
xfer f33 b33;peel loops [1836 on yarn 7] from s1 relative to s0
xfer f35 b35;peel loops [1837 on yarn 7] from s1 relative to s0
xfer f37 b37;peel loops [1838 on yarn 7] from s1 relative to s0
xfer f39 b39;peel loops [1839 on yarn 7] from s1 relative to s0
knit - f38 7
knit - f36 7
knit - f34 7
knit - f32 7
knit - f30 7
knit - f28 7
knit - f26 7
knit - f24 7
knit - f22 7
knit - f20 7
knit - f18 7
knit - f16 7
knit - f14 7
knit - f12 7
knit - f10 7
knit - f8 7
knit - f6 7
knit - f4 7
knit - f2 7
knit - f0 7
outhook 6;Cutting active yarn on 6
outhook 7;Cutting active yarn on 7
