;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 3;Activating carrier 3
tuck - f68 3
tuck - f66 3
tuck - f64 3
tuck - f62 3
tuck - f60 3
tuck - f58 3
tuck - f56 3
tuck - f54 3
tuck - f52 3
tuck - f50 3
tuck - f48 3
tuck - f46 3
tuck - f44 3
tuck - f42 3
tuck - f40 3
tuck - f39 3
miss + f39 3
tuck - f39 3
miss - f38 3
tuck + f38 3
miss - f38 3
miss - f37 3
tuck + f37 3
miss - f37 3
miss - f36 3
tuck + f36 3
miss - f36 3
miss - f35 3
tuck + f35 3
miss - f35 3
miss - f34 3
tuck + f34 3
miss - f34 3
miss - f33 3
tuck + f33 3
miss - f33 3
miss - f32 3
tuck + f32 3
miss - f32 3
miss - f31 3
tuck + f31 3
miss - f31 3
miss - f30 3
tuck + f30 3
miss - f30 3
miss - f29 3
tuck + f29 3
miss - f29 3
miss - f28 3
tuck + f28 3
miss - f28 3
miss - f27 3
tuck + f27 3
miss - f27 3
miss - f26 3
tuck + f26 3
miss - f26 3
miss - f25 3
tuck + f25 3
miss - f25 3
miss - f24 3
tuck + f24 3
miss - f24 3
miss - f23 3
tuck + f23 3
miss - f23 3
miss - f22 3
tuck + f22 3
miss - f22 3
miss - f21 3
tuck + f21 3
miss - f21 3
miss - f20 3
tuck + f20 3
miss - f20 3
miss - f19 3
tuck + f19 3
miss - f19 3
miss - f18 3
tuck + f18 3
miss - f18 3
miss - f17 3
tuck + f17 3
miss - f17 3
miss - f16 3
tuck + f16 3
miss - f16 3
miss - f15 3
tuck + f15 3
miss - f15 3
miss - f14 3
tuck + f14 3
miss - f14 3
miss - f13 3
tuck + f13 3
miss - f13 3
miss - f12 3
tuck + f12 3
miss - f12 3
miss - f11 3
tuck + f11 3
miss - f11 3
miss - f10 3
tuck + f10 3
miss - f10 3
miss - f9 3
tuck + f9 3
miss - f9 3
miss - f8 3
tuck + f8 3
miss - f8 3
miss - f7 3
tuck + f7 3
miss - f7 3
miss - f6 3
tuck + f6 3
miss - f6 3
miss - f5 3
tuck + f5 3
miss - f5 3
miss - f4 3
tuck + f4 3
miss - f4 3
miss - f3 3
tuck + f3 3
miss - f3 3
miss - f2 3
tuck + f2 3
miss - f2 3
miss - f1 3
tuck + f1 3
miss - f1 3
miss - f0 3
tuck + f0 3
miss - f0 3
;KS: Cast on 55loops from f39to f0
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3
knit + f31 3
knit + f32 3
knit + f33 3
knit + f34 3
knit + f35 3
knit + f36 3
knit + f37 3
knit + f38 3
knit + f39 3
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3
knit + f31 3
knit + f32 3
knit + f33 3
knit + f34 3
knit + f35 3
knit + f36 3
knit + f37 3
knit + f38 3
knit + f39 3
releasehook 3
;no-op. Releasehook with no hooked carriers
drop f40
drop f42
drop f44
drop f46
drop f48
drop f50
drop f52
drop f54
drop f56
drop f58
drop f60
drop f62
drop f64
drop f66
drop f68
drop f40
drop f42
drop f44
drop f46
drop f48
drop f50
drop f52
drop f54
drop f56
drop f58
drop f60
drop f62
drop f64
drop f66
drop f68
drop f40
drop f42
drop f44
drop f46
drop f48
drop f50
drop f52
drop f54
drop f56
drop f58
drop f60
drop f62
drop f64
drop f66
drop f68
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
xfer b4 f4
rack 1;Rack to 1 at 1 gauge
xfer b3 f4
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
xfer f37 b36
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
xfer b35 f35
rack -1;Rack to -1 at 1 gauge
xfer b36 f35
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
tuck - f38 3
miss - f37 3
knit + f37 3
miss - f37 3
tuck - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
tuck - f3 3
miss - f2 3
knit + f2 3
miss - f2 3
tuck - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
miss + f2 3
knit - f2 3
miss + f2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
miss + f37 3
knit - f37 3
miss + f37 3
knit + b38 3
knit + b39 3
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
xfer b5 f5
rack 1;Rack to 1 at 1 gauge
xfer b4 f5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
xfer f36 b35
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
xfer b34 f34
rack -1;Rack to -1 at 1 gauge
xfer b35 f34
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
tuck - f37 3
miss - f36 3
knit + f36 3
miss - f36 3
tuck - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
tuck - f4 3
miss - f3 3
knit + f3 3
miss - f3 3
tuck - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
miss + f3 3
knit - f3 3
miss + f3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
miss + f36 3
knit - f36 3
miss + f36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
xfer b6 f6
rack 1;Rack to 1 at 1 gauge
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f35 b34
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b33 f33
rack -1;Rack to -1 at 1 gauge
xfer b34 f33
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
tuck - f36 3
miss - f35 3
knit + f35 3
miss - f35 3
tuck - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
tuck - f5 3
miss - f4 3
knit + f4 3
miss - f4 3
tuck - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
miss + f4 3
knit - f4 3
miss + f4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
miss + f35 3
knit - f35 3
miss + f35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
xfer f5 b6
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
xfer b7 f7
rack 1;Rack to 1 at 1 gauge
xfer b6 f7
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b32 f32
rack -1;Rack to -1 at 1 gauge
xfer b33 f32
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
tuck - f35 3
miss - f34 3
knit + f34 3
miss - f34 3
tuck - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
tuck - f6 3
miss - f5 3
knit + f5 3
miss - f5 3
tuck - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
miss + f5 3
knit - f5 3
miss + f5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
miss + f34 3
knit - f34 3
miss + f34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
xfer f6 b7
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
xfer b8 f8
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f33 b32
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
xfer b31 f31
rack -1;Rack to -1 at 1 gauge
xfer b32 f31
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
tuck - f34 3
miss - f33 3
knit + f33 3
miss - f33 3
tuck - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
tuck - f7 3
miss - f6 3
knit + f6 3
miss - f6 3
tuck - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
miss + f6 3
knit - f6 3
miss + f6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
miss + f33 3
knit - f33 3
miss + f33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
xfer f7 b8
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer b8 f9
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
xfer f32 b31
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
xfer b30 f30
rack -1;Rack to -1 at 1 gauge
xfer b31 f30
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
tuck - f33 3
miss - f32 3
knit + f32 3
miss - f32 3
tuck - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
tuck - f8 3
miss - f7 3
knit + f7 3
miss - f7 3
tuck - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
miss + f7 3
knit - f7 3
miss + f7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
miss + f32 3
knit - f32 3
miss + f32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer b9 f10
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
xfer f31 b30
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b29 f29
rack -1;Rack to -1 at 1 gauge
xfer b30 f29
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
tuck - f32 3
miss - f31 3
knit + f31 3
miss - f31 3
tuck - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
tuck - f9 3
miss - f8 3
knit + f8 3
miss - f8 3
tuck - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
miss + f8 3
knit - f8 3
miss + f8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
miss + f31 3
knit - f31 3
miss + f31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
xfer b11 f11
rack 1;Rack to 1 at 1 gauge
xfer b10 f11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
xfer f30 b29
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
xfer b28 f28
rack -1;Rack to -1 at 1 gauge
xfer b29 f28
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
tuck - f31 3
miss - f30 3
knit + f30 3
miss - f30 3
tuck - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
tuck - f10 3
miss - f9 3
knit + f9 3
miss - f9 3
tuck - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
miss + f9 3
knit - f9 3
miss + f9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
miss + f30 3
knit - f30 3
miss + f30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
rack -1;Rack to -1 at 1 gauge
xfer f11 b12
xfer f10 b11
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b12 f12
rack 1;Rack to 1 at 1 gauge
xfer b11 f12
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f29 b28
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b27 f27
rack -1;Rack to -1 at 1 gauge
xfer b28 f27
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
tuck - f30 3
miss - f29 3
knit + f29 3
miss - f29 3
tuck - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
tuck - f11 3
miss - f10 3
knit + f10 3
miss - f10 3
tuck - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
miss + f10 3
knit - f10 3
miss + f10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
miss + f29 3
knit - f29 3
miss + f29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
xfer f11 b12
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
xfer b13 f13
rack 1;Rack to 1 at 1 gauge
xfer b12 f13
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
xfer b26 f26
rack -1;Rack to -1 at 1 gauge
xfer b27 f26
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
tuck - f29 3
miss - f28 3
knit + f28 3
miss - f28 3
tuck - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
tuck - f12 3
miss - f11 3
knit + f11 3
miss - f11 3
tuck - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
miss + f11 3
knit - f11 3
miss + f11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
miss + f28 3
knit - f28 3
miss + f28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
rack -1;Rack to -1 at 1 gauge
xfer f13 b14
xfer f12 b13
xfer f11 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
xfer b14 f14
rack 1;Rack to 1 at 1 gauge
xfer b13 f14
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f27 b26
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b25 f25
rack -1;Rack to -1 at 1 gauge
xfer b26 f25
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
tuck - f28 3
miss - f27 3
knit + f27 3
miss - f27 3
tuck - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
tuck - f13 3
miss - f12 3
knit + f12 3
miss - f12 3
tuck - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
miss + f12 3
knit - f12 3
miss + f12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
miss + f27 3
knit - f27 3
miss + f27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
rack -1;Rack to -1 at 1 gauge
xfer f14 b15
xfer f13 b14
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
xfer b15 f15
rack 1;Rack to 1 at 1 gauge
xfer b14 f15
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
xfer f26 b25
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
xfer b24 f24
rack -1;Rack to -1 at 1 gauge
xfer b25 f24
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
tuck - f27 3
miss - f26 3
knit + f26 3
miss - f26 3
tuck - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
tuck - f14 3
miss - f13 3
knit + f13 3
miss - f13 3
tuck - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
miss + f13 3
knit - f13 3
miss + f13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
miss + f26 3
knit - f26 3
miss + f26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
rack -1;Rack to -1 at 1 gauge
xfer f15 b16
xfer f14 b15
xfer f13 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
xfer b16 f16
rack 1;Rack to 1 at 1 gauge
xfer b15 f16
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
xfer f25 b24
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
xfer b23 f23
rack -1;Rack to -1 at 1 gauge
xfer b24 f23
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
tuck - f26 3
miss - f25 3
knit + f25 3
miss - f25 3
tuck - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
tuck - f15 3
miss - f14 3
knit + f14 3
miss - f14 3
tuck - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
miss + f14 3
knit - f14 3
miss + f14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
miss + f25 3
knit - f25 3
miss + f25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
rack -1;Rack to -1 at 1 gauge
xfer f16 b17
xfer f15 b16
xfer f14 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
xfer b17 f17
rack 1;Rack to 1 at 1 gauge
xfer b16 f17
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
xfer f24 b23
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
xfer b22 f22
rack -1;Rack to -1 at 1 gauge
xfer b23 f22
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
tuck - f25 3
miss - f24 3
knit + f24 3
miss - f24 3
tuck - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
tuck - f16 3
miss - f15 3
knit + f15 3
miss - f15 3
tuck - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
miss + f15 3
knit - f15 3
miss + f15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
miss + f24 3
knit - f24 3
miss + f24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
rack -1;Rack to -1 at 1 gauge
xfer f17 b18
xfer f16 b17
xfer f15 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
xfer b18 f18
rack 1;Rack to 1 at 1 gauge
xfer b17 f18
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
xfer f23 b22
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
xfer b21 f21
rack -1;Rack to -1 at 1 gauge
xfer b22 f21
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
tuck - f24 3
miss - f23 3
knit + f23 3
miss - f23 3
tuck - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
tuck - f17 3
miss - f16 3
knit + f16 3
miss - f16 3
tuck - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
miss + f16 3
knit - f16 3
miss + f16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
miss + f23 3
knit - f23 3
miss + f23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
xfer f17 b18
xfer f16 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
xfer b19 f19
rack 1;Rack to 1 at 1 gauge
xfer b18 f19
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
xfer f22 b21
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b22 f22
xfer b20 f20
rack -1;Rack to -1 at 1 gauge
xfer b21 f20
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
tuck - f23 3
miss - f22 3
knit + f22 3
miss - f22 3
tuck - f21 3
knit - f20 3
knit - f19 3
tuck - f18 3
miss - f17 3
knit + f17 3
miss - f17 3
tuck - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
miss + f17 3
knit - f17 3
miss + f17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
miss + f22 3
knit - f22 3
miss + f22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b19 f19
xfer b18 f18
xfer b21 f21
xfer b20 f20
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
knit - f38 3
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
knit - f37 3
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
knit - f36 3
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
knit - f35 3
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
knit - f34 3
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
knit - f33 3
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
knit - f32 3
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
knit - f31 3
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
knit - f30 3
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
knit - f29 3
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
knit - f28 3
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
knit - f27 3
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
knit - f26 3
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
knit - f25 3
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
knit - f24 3
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
knit - f23 3
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
xfer b22 f22
knit - f22 3
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit - f21 3
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
knit - f20 3
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
knit - f19 3
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
knit - f18 3
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
knit - f17 3
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
knit - f16 3
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
knit - f15 3
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
knit - f14 3
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
knit - f13 3
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
knit - f12 3
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
knit - f11 3
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
knit - f10 3
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
knit - f9 3
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
knit - f8 3
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
knit - f7 3
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
knit - f6 3
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
knit - f5 3
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f4 3
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
knit - f3 3
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
knit - f2 3
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit - f1 3
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
knit - f0 3
;KS: Spare knitting on [f0]
knit + f0 3
outhook 3;Cutting active yarn on 3
