;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 6;Activating carrier 6
;KS: Cast on 37loops from 0to 37
tuck - f36 6
tuck - f34 6
tuck - f32 6
tuck - f30 6
tuck - f28 6
tuck - f26 6
tuck - f24 6
tuck - f22 6
tuck - f20 6
tuck - f18 6
tuck - f16 6
tuck - f14 6
tuck - f12 6
tuck - f10 6
tuck - f8 6
tuck - f6 6
tuck - f4 6
tuck - f2 6
tuck - f0 6
tuck + f1 6
tuck + f3 6
tuck + f5 6
tuck + f7 6
tuck + f9 6
tuck + f11 6
tuck + f13 6
tuck + f15 6
tuck + f17 6
tuck + f19 6
tuck + f21 6
tuck + f23 6
tuck + f25 6
tuck + f27 6
tuck + f29 6
tuck + f31 6
tuck + f33 6
tuck + f35 6
tuck - f36 6
tuck - f34 6
tuck - f32 6
tuck - f30 6
tuck - f28 6
tuck - f26 6
tuck - f24 6
tuck - f22 6
tuck - f20 6
tuck - f18 6
tuck - f16 6
tuck - f14 6
tuck - f12 6
tuck - f10 6
tuck - f8 6
tuck - f6 6
tuck - f4 6
tuck - f2 6
tuck - f0 6
tuck + f1 6
tuck + f3 6
tuck + f5 6
tuck + f7 6
tuck + f9 6
tuck + f11 6
tuck + f13 6
tuck + f15 6
tuck + f17 6
tuck + f19 6
tuck + f21 6
tuck + f23 6
tuck + f25 6
tuck + f27 6
tuck + f29 6
tuck + f31 6
tuck + f33 6
tuck + f35 6
releasehook 6
knit - f36 6
knit - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - f30 6
knit - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - f24 6
knit - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - f18 6
knit - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - f12 6
knit - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - f6 6
knit - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + f12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + f18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + f24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + f30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + f36 6
knit - f36 6
knit - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - f30 6
knit - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - f24 6
knit - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - f18 6
knit - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - f12 6
knit - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - f6 6
knit - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + f12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + f18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + f24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + f30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + f36 6
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer b33 f33
xfer b21 f21
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - f34 6
knit - b33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - f22 6
knit - b21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - f10 6
knit - b9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b9 f9
xfer b21 f21
xfer b33 f33
xfer b45 f45
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer b33 f33
xfer b21 f21
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - f34 6
knit - b33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - f22 6
knit - b21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - f10 6
knit - b9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b9 f9
xfer b21 f21
xfer b33 f33
xfer b45 f45
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer b33 f33
xfer b21 f21
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - f34 6
knit - b33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - f22 6
knit - b21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - f10 6
knit - b9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b9 f9
xfer b21 f21
xfer b33 f33
xfer b45 f45
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer f36 b36
xfer f35 b35
xfer f30 b30
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f18 b18
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f6 b6
xfer f1 b1
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
knit - b35 6
tuck - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
tuck - f26 6
knit - b25 6
knit - b24 6
knit - b23 6
tuck - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
tuck - f14 6
knit - b13 6
knit - b12 6
knit - b11 6
tuck - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
tuck - f2 6
knit - b1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + b1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + b35 6
knit + b36 6
xfer b36 f36
xfer b35 f35
xfer b30 f30
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b18 f18
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b6 f6
xfer b1 f1
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
xfer f32 b31
xfer f21 b20
xfer f20 b19
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f16 b17
xfer f15 b16
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer f36 b36
xfer f35 b35
xfer f34 b34
xfer f30 b30
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f18 b18
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f6 b6
xfer f2 b2
xfer f1 b1
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
knit - b35 6
knit - b34 6
tuck - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
tuck - f27 6
knit - b26 6
knit - b25 6
knit - b24 6
knit - b23 6
knit - b22 6
tuck - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
tuck - f15 6
knit - b14 6
knit - b13 6
knit - b12 6
knit - b11 6
knit - b10 6
tuck - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
tuck - f3 6
knit - b2 6
knit - b1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + b1 6
knit + b2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + b10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + b14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + b22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + b26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + b34 6
knit + b35 6
knit + b36 6
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b30 f30
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b18 f18
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b6 f6
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
xfer f20 b19
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b28 f28
xfer b19 f19
xfer b16 f16
xfer b7 f7
xfer b4 f4
xfer f36 b36
xfer f35 b35
xfer f34 b34
xfer f33 b33
xfer f30 b30
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f18 b18
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f6 b6
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
knit - b35 6
knit - b34 6
knit - b33 6
tuck - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - b27 6
knit - b26 6
knit - b25 6
knit - b24 6
knit - b23 6
knit - b22 6
knit - b21 6
tuck - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - b15 6
knit - b14 6
knit - b13 6
knit - b12 6
knit - b11 6
knit - b10 6
knit - b9 6
tuck - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - b3 6
knit - b2 6
knit - b1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + b1 6
knit + b2 6
knit + b3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + b9 6
knit + b10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + b14 6
knit + b15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + b21 6
knit + b22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + b26 6
knit + b27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + b33 6
knit + b34 6
knit + b35 6
knit + b36 6
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b30 f30
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b18 f18
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b6 f6
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f10 b11
xfer f9 b10
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f24 b24
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f12 b12
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f0 b0
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
tuck - f32 6
knit - b31 6
knit - b30 6
knit - b29 6
tuck - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
tuck - f20 6
knit - b19 6
knit - b18 6
knit - b17 6
tuck - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
tuck - f8 6
knit - b7 6
knit - b6 6
knit - b5 6
tuck - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b24 f24
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b12 f12
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
xfer f26 b25
xfer f15 b14
xfer f14 b13
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f22 b23
xfer f21 b22
xfer f10 b11
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b34 f34
xfer b26 f26
xfer b25 f25
xfer b23 f23
xfer b22 f22
xfer b14 f14
xfer b13 f13
xfer b11 f11
xfer b10 f10
xfer b2 f2
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f24 b24
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f12 b12
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f0 b0
knit - b36 6
knit - f35 6
knit - b34 6
tuck - f33 6
knit - b32 6
knit - b31 6
knit - b30 6
knit - b29 6
knit - b28 6
tuck - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
tuck - f21 6
knit - b20 6
knit - b19 6
knit - b18 6
knit - b17 6
knit - b16 6
tuck - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
tuck - f9 6
knit - b8 6
knit - b7 6
knit - b6 6
knit - b5 6
knit - b4 6
tuck - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + b4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + b8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + b16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + b20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + b28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + b32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b24 f24
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b12 f12
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
xfer f14 b13
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b25 f25
xfer b23 f23
xfer b13 f13
xfer b11 f11
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f24 b24
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f12 b12
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f0 b0
knit - b36 6
knit - f35 6
tuck - f34 6
knit - b33 6
knit - b32 6
knit - b31 6
knit - b30 6
knit - b29 6
knit - b28 6
knit - b27 6
tuck - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
tuck - f22 6
knit - b21 6
knit - b20 6
knit - b19 6
knit - b18 6
knit - b17 6
knit - b16 6
knit - b15 6
tuck - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
tuck - f10 6
knit - b9 6
knit - b8 6
knit - b7 6
knit - b6 6
knit - b5 6
knit - b4 6
knit - b3 6
tuck - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + b3 6
knit + b4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + b8 6
knit + b9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + b15 6
knit + b16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + b20 6
knit + b21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + b27 6
knit + b28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + b32 6
knit + b33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b24 f24
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b12 f12
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer b33 f33
xfer b21 f21
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - f34 6
knit - b33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - f22 6
knit - b21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - f10 6
knit - b9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b9 f9
xfer b21 f21
xfer b33 f33
xfer b45 f45
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer b33 f33
xfer b21 f21
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - f34 6
knit - b33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - f22 6
knit - b21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - f10 6
knit - b9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b9 f9
xfer b21 f21
xfer b33 f33
xfer b45 f45
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer b33 f33
xfer b21 f21
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f45 b45
xfer f33 b33
xfer f21 b21
xfer f9 b9
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - f34 6
knit - b33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - f22 6
knit - b21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - f10 6
knit - b9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b9 f9
xfer b21 f21
xfer b33 f33
xfer b45 f45
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer f36 b36
xfer f35 b35
xfer f30 b30
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f18 b18
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f6 b6
xfer f1 b1
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
knit - b35 6
tuck - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
tuck - f26 6
knit - b25 6
knit - b24 6
knit - b23 6
tuck - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
tuck - f14 6
knit - b13 6
knit - b12 6
knit - b11 6
tuck - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
tuck - f2 6
knit - b1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + b1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + b35 6
knit + b36 6
xfer b36 f36
xfer b35 f35
xfer b30 f30
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b18 f18
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b6 f6
xfer b1 f1
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
xfer f32 b31
xfer f21 b20
xfer f20 b19
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f16 b17
xfer f15 b16
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer f36 b36
xfer f35 b35
xfer f34 b34
xfer f30 b30
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f18 b18
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f6 b6
xfer f2 b2
xfer f1 b1
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
knit - b35 6
knit - b34 6
tuck - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
tuck - f27 6
knit - b26 6
knit - b25 6
knit - b24 6
knit - b23 6
knit - b22 6
tuck - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
tuck - f15 6
knit - b14 6
knit - b13 6
knit - b12 6
knit - b11 6
knit - b10 6
tuck - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
tuck - f3 6
knit - b2 6
knit - b1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + b1 6
knit + b2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + b10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + b14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + b22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + b26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + b34 6
knit + b35 6
knit + b36 6
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b30 f30
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b18 f18
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b6 f6
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
xfer f20 b19
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f16 b17
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
xfer b28 f28
xfer b19 f19
xfer b16 f16
xfer b7 f7
xfer b4 f4
xfer f36 b36
xfer f35 b35
xfer f34 b34
xfer f33 b33
xfer f30 b30
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f18 b18
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f6 b6
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
knit - b35 6
knit - b34 6
knit - b33 6
tuck - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - b27 6
knit - b26 6
knit - b25 6
knit - b24 6
knit - b23 6
knit - b22 6
knit - b21 6
tuck - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - b15 6
knit - b14 6
knit - b13 6
knit - b12 6
knit - b11 6
knit - b10 6
knit - b9 6
tuck - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - b3 6
knit - b2 6
knit - b1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + b1 6
knit + b2 6
knit + b3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + b9 6
knit + b10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + b14 6
knit + b15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + b21 6
knit + b22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + b26 6
knit + b27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + b33 6
knit + b34 6
knit + b35 6
knit + b36 6
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b30 f30
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b18 f18
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b6 f6
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f31 b31
xfer f19 b19
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
xfer b19 f20
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f17 b16
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f28 b28
xfer f16 b16
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
xfer f34 b33
xfer f33 b32
xfer f32 b31
xfer f23 b22
xfer f22 b21
xfer f21 b20
xfer f20 b19
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
xfer f25 b26
xfer f16 b17
xfer f15 b16
xfer f14 b15
xfer f13 b14
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f28 b28
xfer f16 b16
xfer f4 b4
knit - b36 6
tuck - f35 6
knit - f34 6
knit - f33 6
knit - f32 6
knit - f31 6
knit - b30 6
tuck - f29 6
knit - b28 6
knit - f27 6
knit - f26 6
tuck - f25 6
knit - b24 6
tuck - f23 6
knit - f22 6
knit - f21 6
knit - f20 6
knit - f19 6
knit - b18 6
tuck - f17 6
knit - b16 6
knit - f15 6
knit - f14 6
tuck - f13 6
knit - b12 6
tuck - f11 6
knit - f10 6
knit - f9 6
knit - f8 6
knit - f7 6
knit - b6 6
tuck - f5 6
knit - b4 6
knit - f3 6
knit - f2 6
tuck - f1 6
knit - b0 6
xfer b4 f4
xfer b16 f16
xfer b28 f28
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f17 b16
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f31 b32
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f19 b20
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f30 b30
xfer f24 b24
xfer f18 b18
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
knit - f32 6
tuck - f31 6
knit - b30 6
tuck - f29 6
knit - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
knit - f20 6
tuck - f19 6
knit - b18 6
tuck - f17 6
knit - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
knit - f8 6
tuck - f7 6
knit - b6 6
tuck - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + f17 6
knit + b18 6
knit + f19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + f29 6
knit + b30 6
knit + f31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b30 f30
xfer b24 f24
xfer b18 f18
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
xfer f27 b26
xfer f26 b25
xfer f16 b15
xfer f15 b14
xfer f14 b13
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f32 b33
xfer f22 b23
xfer f21 b22
xfer f20 b21
xfer f10 b11
xfer f9 b10
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f24 b24
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f12 b12
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f0 b0
knit - b36 6
knit - f35 6
knit - b34 6
knit - f33 6
tuck - f32 6
knit - b31 6
knit - b30 6
knit - b29 6
tuck - f28 6
knit - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
knit - f21 6
tuck - f20 6
knit - b19 6
knit - b18 6
knit - b17 6
tuck - f16 6
knit - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
knit - f9 6
tuck - f8 6
knit - b7 6
knit - b6 6
knit - b5 6
tuck - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + f8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + f16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + f20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + f28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + f32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b24 f24
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b12 f12
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
xfer f26 b25
xfer f15 b14
xfer f14 b13
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f33 b34
xfer f22 b23
xfer f21 b22
xfer f10 b11
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b34 f34
xfer b26 f26
xfer b25 f25
xfer b23 f23
xfer b22 f22
xfer b14 f14
xfer b13 f13
xfer b11 f11
xfer b10 f10
xfer b2 f2
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f24 b24
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f12 b12
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f0 b0
knit - b36 6
knit - f35 6
knit - b34 6
tuck - f33 6
knit - b32 6
knit - b31 6
knit - b30 6
knit - b29 6
knit - b28 6
tuck - f27 6
knit - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
knit - b22 6
tuck - f21 6
knit - b20 6
knit - b19 6
knit - b18 6
knit - b17 6
knit - b16 6
tuck - f15 6
knit - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
knit - b10 6
tuck - f9 6
knit - b8 6
knit - b7 6
knit - b6 6
knit - b5 6
knit - b4 6
tuck - f3 6
knit - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + b4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + b8 6
knit + f9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + f15 6
knit + b16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + b20 6
knit + f21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + f27 6
knit + b28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + b32 6
knit + f33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b24 f24
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b12 f12
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b0 f0
xfer f37 b37
xfer f25 b25
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
xfer b13 f14
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
xfer f35 b34
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer b34 f34
xfer b22 f22
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
xfer f14 b13
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
xfer f22 b23
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b25 f25
xfer b23 f23
xfer b13 f13
xfer b11 f11
xfer b1 f1
xfer f46 b46
xfer f34 b34
xfer f22 b22
xfer f10 b10
xfer f36 b36
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f24 b24
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f12 b12
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f0 b0
knit - b36 6
knit - f35 6
tuck - f34 6
knit - b33 6
knit - b32 6
knit - b31 6
knit - b30 6
knit - b29 6
knit - b28 6
knit - b27 6
tuck - f26 6
knit - f25 6
knit - b24 6
knit - f23 6
tuck - f22 6
knit - b21 6
knit - b20 6
knit - b19 6
knit - b18 6
knit - b17 6
knit - b16 6
knit - b15 6
tuck - f14 6
knit - f13 6
knit - b12 6
knit - f11 6
tuck - f10 6
knit - b9 6
knit - b8 6
knit - b7 6
knit - b6 6
knit - b5 6
knit - b4 6
knit - b3 6
tuck - f2 6
knit - f1 6
knit - b0 6
xfer b10 f10
xfer b22 f22
xfer b34 f34
xfer b46 f46
knit + b0 6
knit + f1 6
knit + f2 6
knit + b3 6
knit + b4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + b8 6
knit + b9 6
knit + f10 6
knit + f11 6
knit + b12 6
knit + f13 6
knit + f14 6
knit + b15 6
knit + b16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + b20 6
knit + b21 6
knit + f22 6
knit + f23 6
knit + b24 6
knit + f25 6
knit + f26 6
knit + b27 6
knit + b28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + b32 6
knit + b33 6
knit + f34 6
knit + f35 6
knit + b36 6
xfer b36 f36
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b24 f24
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b12 f12
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b0 f0
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
split + b35 f35 6
knit - f35 6
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
split + b34 f34 6
knit - f34 6
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
split + b33 f33 6
knit - f33 6
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
split + b32 f32 6
knit - f32 6
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
split + b31 f31 6
knit - f31 6
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
split + b30 f30 6
knit - f30 6
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
split + b29 f29 6
knit - f29 6
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 6
knit - f28 6
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 6
knit - f27 6
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 6
knit - f26 6
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
split + b25 f25 6
knit - f25 6
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
split + b24 f24 6
knit - f24 6
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 6
knit - f23 6
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 6
knit - f22 6
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 6
knit - f21 6
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
split + b20 f20 6
knit - f20 6
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
split + b19 f19 6
knit - f19 6
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 6
knit - f18 6
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 6
knit - f17 6
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 6
knit - f16 6
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
split + b15 f15 6
knit - f15 6
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
split + b14 f14 6
knit - f14 6
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 6
knit - f13 6
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 6
knit - f12 6
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 6
knit - f11 6
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
split + b10 f10 6
knit - f10 6
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
split + b9 f9 6
knit - f9 6
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 6
knit - f8 6
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 6
knit - f7 6
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 6
knit - f6 6
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 6
knit - f5 6
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 6
knit - f4 6
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 6
knit - f3 6
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 6
knit - f2 6
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 6
knit - f1 6
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 6
knit - f0 6
;KS: Spare knitting on [b35, b34, b33, b32, b31, b30, b29, b28, b27, b26, b25, b24, b23, b22, b21, b20, b19, b18, b17, b16, b15, b14, b13, b12, b11, b10, b9, b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 6
knit + b1 6
knit + b2 6
knit + b3 6
knit + b4 6
knit + b5 6
knit + b6 6
knit + b7 6
knit + b8 6
knit + b9 6
knit + b10 6
knit + b11 6
knit + b12 6
knit + b13 6
knit + b14 6
knit + b15 6
knit + b16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + b20 6
knit + b21 6
knit + b22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + b26 6
knit + b27 6
knit + b28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + b32 6
knit + b33 6
knit + b34 6
knit + b35 6
outhook 6;Cutting active yarn on 6
