;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 13loops from 0to 13
tuck - f12 1
tuck - f10 1
tuck - f8 1
tuck - f6 1
tuck - f4 1
tuck - f2 1
tuck - f0 1
tuck + f1 1
tuck + f3 1
tuck + f5 1
tuck + f7 1
tuck + f9 1
tuck + f11 1
tuck - f12 1
tuck - f10 1
tuck - f8 1
tuck - f6 1
tuck - f4 1
tuck - f2 1
tuck - f0 1
tuck + f1 1
tuck + f3 1
tuck + f5 1
tuck + f7 1
tuck + f9 1
tuck + f11 1
releasehook 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f21 b21
xfer f9 b9
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f21 b21
xfer f9 b9
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b12 1
knit - f11 1
knit - f10 1
knit - b9 1
knit - f8 1
tuck - f7 1
knit - b6 1
tuck - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - b0 1
xfer b9 f9
xfer b21 f21
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f21 b21
xfer f9 b9
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f21 b21
xfer f9 b9
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b12 1
knit - f11 1
knit - f10 1
knit - b9 1
knit - f8 1
tuck - f7 1
knit - b6 1
tuck - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - b0 1
xfer b9 f9
xfer b21 f21
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer f21 b21
xfer f9 b9
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f21 b21
xfer f9 b9
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b12 1
knit - f11 1
knit - f10 1
knit - b9 1
knit - f8 1
tuck - f7 1
knit - b6 1
tuck - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - b0 1
xfer b9 f9
xfer b21 f21
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f4 b4
knit - b12 1
tuck - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
knit - f3 1
knit - f2 1
tuck - f1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer f12 b12
xfer f11 b11
xfer f6 b6
xfer f1 b1
xfer f0 b0
xfer f4 b4
knit - b12 1
knit - b11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
knit - f3 1
tuck - f2 1
knit - b1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + b1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
xfer b12 f12
xfer b11 f11
xfer b6 f6
xfer b1 f1
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f6 b6
xfer f2 b2
xfer f1 b1
xfer f0 b0
xfer f4 b4
knit - b12 1
knit - b11 1
knit - b10 1
tuck - f9 1
knit - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
tuck - f3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + b1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + b10 1
knit + b11 1
knit + b12 1
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b6 f6
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
xfer b4 f4
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f6 b6
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
xfer f4 b4
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
tuck - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b6 f6
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f4 b4
knit - b12 1
tuck - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
knit - f3 1
knit - f2 1
tuck - f1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f4 b4
knit - b12 1
tuck - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
knit - f3 1
knit - f2 1
tuck - f1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f7 b7
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f4 b4
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
xfer f10 b9
xfer f9 b8
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer f12 b12
xfer f6 b6
xfer f0 b0
xfer f4 b4
knit - b12 1
tuck - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - b6 1
tuck - f5 1
knit - b4 1
knit - f3 1
knit - f2 1
tuck - f1 1
knit - b0 1
xfer b4 f4
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f22 b22
xfer f10 b10
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f22 b22
xfer f10 b10
xfer f12 b12
xfer f6 b6
xfer f0 b0
knit - b12 1
knit - f11 1
knit - b10 1
knit - f9 1
knit - f8 1
tuck - f7 1
knit - b6 1
tuck - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - b0 1
xfer b10 f10
xfer b22 f22
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b6 f6
xfer b0 f0
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f22 b22
xfer f10 b10
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer f22 b22
xfer f10 b10
xfer f12 b12
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f0 b0
knit - b12 1
knit - f11 1
knit - b10 1
knit - f9 1
tuck - f8 1
knit - b7 1
knit - b6 1
knit - b5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - b0 1
xfer b10 f10
xfer b22 f22
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b0 f0
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f22 b22
xfer f10 b10
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
xfer b10 f10
xfer b2 f2
xfer b1 f1
xfer f22 b22
xfer f10 b10
xfer f12 b12
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f0 b0
knit - b12 1
knit - f11 1
knit - b10 1
tuck - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
tuck - f3 1
knit - f2 1
knit - f1 1
knit - b0 1
xfer b10 f10
xfer b22 f22
knit + b0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + b12 1
xfer b12 f12
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b0 f0
xfer f13 b13
xfer f1 b1
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer f22 b22
xfer f10 b10
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
xfer b1 f1
xfer f22 b22
xfer f10 b10
xfer f12 b12
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f0 b0
knit - b12 1
knit - f11 1
tuck - f10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
tuck - f2 1
knit - f1 1
knit - b0 1
xfer b10 f10
xfer b22 f22
knit + b0 1
knit + f1 1
knit + f2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + f10 1
knit + f11 1
knit + b12 1
outhook 1;Cutting active yarn on 1
