;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 3;Activating carrier 3
tuck - f116 3
tuck - f114 3
tuck - f112 3
tuck - f110 3
tuck - f108 3
tuck - f106 3
tuck - f104 3
tuck - f102 3
tuck - f100 3
tuck - f98 3
tuck - f96 3
tuck - f94 3
tuck - f92 3
tuck - f90 3
tuck - f88 3
tuck - f87 3
miss + f87 3
tuck - f87 3
miss - f86 3
tuck + f86 3
miss - f86 3
miss - f85 3
tuck + f85 3
miss - f85 3
miss - f84 3
tuck + f84 3
miss - f84 3
miss - f83 3
tuck + f83 3
miss - f83 3
miss - f82 3
tuck + f82 3
miss - f82 3
miss - f81 3
tuck + f81 3
miss - f81 3
miss - f80 3
tuck + f80 3
miss - f80 3
miss - f79 3
tuck + f79 3
miss - f79 3
miss - f78 3
tuck + f78 3
miss - f78 3
miss - f77 3
tuck + f77 3
miss - f77 3
miss - f76 3
tuck + f76 3
miss - f76 3
miss - f75 3
tuck + f75 3
miss - f75 3
miss - f74 3
tuck + f74 3
miss - f74 3
miss - f73 3
tuck + f73 3
miss - f73 3
miss - f72 3
tuck + f72 3
miss - f72 3
miss - f71 3
tuck + f71 3
miss - f71 3
miss - f70 3
tuck + f70 3
miss - f70 3
miss - f69 3
tuck + f69 3
miss - f69 3
miss - f68 3
tuck + f68 3
miss - f68 3
miss - f67 3
tuck + f67 3
miss - f67 3
miss - f66 3
tuck + f66 3
miss - f66 3
miss - f65 3
tuck + f65 3
miss - f65 3
miss - f64 3
tuck + f64 3
miss - f64 3
miss - f63 3
tuck + f63 3
miss - f63 3
miss - f62 3
tuck + f62 3
miss - f62 3
miss - f61 3
tuck + f61 3
miss - f61 3
miss - f60 3
tuck + f60 3
miss - f60 3
miss - f59 3
tuck + f59 3
miss - f59 3
miss - f58 3
tuck + f58 3
miss - f58 3
miss - f57 3
tuck + f57 3
miss - f57 3
miss - f56 3
tuck + f56 3
miss - f56 3
miss - f55 3
tuck + f55 3
miss - f55 3
miss - f54 3
tuck + f54 3
miss - f54 3
miss - f53 3
tuck + f53 3
miss - f53 3
miss - f52 3
tuck + f52 3
miss - f52 3
miss - f51 3
tuck + f51 3
miss - f51 3
miss - f50 3
tuck + f50 3
miss - f50 3
miss - f49 3
tuck + f49 3
miss - f49 3
miss - f48 3
tuck + f48 3
miss - f48 3
miss - f47 3
tuck + f47 3
miss - f47 3
miss - f46 3
tuck + f46 3
miss - f46 3
miss - f45 3
tuck + f45 3
miss - f45 3
miss - f44 3
tuck + f44 3
miss - f44 3
miss - f43 3
tuck + f43 3
miss - f43 3
miss - f42 3
tuck + f42 3
miss - f42 3
miss - f41 3
tuck + f41 3
miss - f41 3
miss - f40 3
tuck + f40 3
miss - f40 3
miss - f39 3
tuck + f39 3
miss - f39 3
miss - f38 3
tuck + f38 3
miss - f38 3
miss - f37 3
tuck + f37 3
miss - f37 3
miss - f36 3
tuck + f36 3
miss - f36 3
miss - f35 3
tuck + f35 3
miss - f35 3
miss - f34 3
tuck + f34 3
miss - f34 3
miss - f33 3
tuck + f33 3
miss - f33 3
miss - f32 3
tuck + f32 3
miss - f32 3
miss - f31 3
tuck + f31 3
miss - f31 3
miss - f30 3
tuck + f30 3
miss - f30 3
miss - f29 3
tuck + f29 3
miss - f29 3
miss - f28 3
tuck + f28 3
miss - f28 3
miss - f27 3
tuck + f27 3
miss - f27 3
miss - f26 3
tuck + f26 3
miss - f26 3
miss - f25 3
tuck + f25 3
miss - f25 3
miss - f24 3
tuck + f24 3
miss - f24 3
miss - f23 3
tuck + f23 3
miss - f23 3
miss - f22 3
tuck + f22 3
miss - f22 3
miss - f21 3
tuck + f21 3
miss - f21 3
miss - f20 3
tuck + f20 3
miss - f20 3
miss - f19 3
tuck + f19 3
miss - f19 3
miss - f18 3
tuck + f18 3
miss - f18 3
miss - f17 3
tuck + f17 3
miss - f17 3
miss - f16 3
tuck + f16 3
miss - f16 3
miss - f15 3
tuck + f15 3
miss - f15 3
miss - f14 3
tuck + f14 3
miss - f14 3
miss - f13 3
tuck + f13 3
miss - f13 3
miss - f12 3
tuck + f12 3
miss - f12 3
miss - f11 3
tuck + f11 3
miss - f11 3
miss - f10 3
tuck + f10 3
miss - f10 3
miss - f9 3
tuck + f9 3
miss - f9 3
miss - f8 3
tuck + f8 3
miss - f8 3
miss - f7 3
tuck + f7 3
miss - f7 3
miss - f6 3
tuck + f6 3
miss - f6 3
miss - f5 3
tuck + f5 3
miss - f5 3
miss - f4 3
tuck + f4 3
miss - f4 3
miss - f3 3
tuck + f3 3
miss - f3 3
miss - f2 3
tuck + f2 3
miss - f2 3
miss - f1 3
tuck + f1 3
miss - f1 3
miss - f0 3
tuck + f0 3
miss - f0 3
;KS: Cast on 103loops from f87to f0
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3
knit + f31 3
knit + f32 3
knit + f33 3
knit + f34 3
knit + f35 3
knit + f36 3
knit + f37 3
knit + f38 3
knit + f39 3
knit + f40 3
knit + f41 3
knit + f42 3
knit + f43 3
knit + f44 3
knit + f45 3
knit + f46 3
knit + f47 3
knit + f48 3
knit + f49 3
knit + f50 3
knit + f51 3
knit + f52 3
knit + f53 3
knit + f54 3
knit + f55 3
knit + f56 3
knit + f57 3
knit + f58 3
knit + f59 3
knit + f60 3
knit + f61 3
knit + f62 3
knit + f63 3
knit + f64 3
knit + f65 3
knit + f66 3
knit + f67 3
knit + f68 3
knit + f69 3
knit + f70 3
knit + f71 3
knit + f72 3
knit + f73 3
knit + f74 3
knit + f75 3
knit + f76 3
knit + f77 3
knit + f78 3
knit + f79 3
knit + f80 3
knit + f81 3
knit + f82 3
knit + f83 3
knit + f84 3
knit + f85 3
knit + f86 3
knit + f87 3
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3
knit + f31 3
knit + f32 3
knit + f33 3
knit + f34 3
knit + f35 3
knit + f36 3
knit + f37 3
knit + f38 3
knit + f39 3
knit + f40 3
knit + f41 3
knit + f42 3
knit + f43 3
knit + f44 3
knit + f45 3
knit + f46 3
knit + f47 3
knit + f48 3
knit + f49 3
knit + f50 3
knit + f51 3
knit + f52 3
knit + f53 3
knit + f54 3
knit + f55 3
knit + f56 3
knit + f57 3
knit + f58 3
knit + f59 3
knit + f60 3
knit + f61 3
knit + f62 3
knit + f63 3
knit + f64 3
knit + f65 3
knit + f66 3
knit + f67 3
knit + f68 3
knit + f69 3
knit + f70 3
knit + f71 3
knit + f72 3
knit + f73 3
knit + f74 3
knit + f75 3
knit + f76 3
knit + f77 3
knit + f78 3
knit + f79 3
knit + f80 3
knit + f81 3
knit + f82 3
knit + f83 3
knit + f84 3
knit + f85 3
knit + f86 3
knit + f87 3
releasehook 3
;no-op. Releasehook with no hooked carriers
drop f88
drop f90
drop f92
drop f94
drop f96
drop f98
drop f100
drop f102
drop f104
drop f106
drop f108
drop f110
drop f112
drop f114
drop f116
drop f88
drop f90
drop f92
drop f94
drop f96
drop f98
drop f100
drop f102
drop f104
drop f106
drop f108
drop f110
drop f112
drop f114
drop f116
drop f88
drop f90
drop f92
drop f94
drop f96
drop f98
drop f100
drop f102
drop f104
drop f106
drop f108
drop f110
drop f112
drop f114
drop f116
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
xfer b4 f4
rack 1;Rack to 1 at 1 gauge
xfer b3 f4
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
xfer f19 b18
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
xfer b17 f17
rack -1;Rack to -1 at 1 gauge
xfer b18 f17
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f25 b26
xfer f24 b25
xfer f23 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
xfer b26 f26
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
xfer f41 b40
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b41 f41
xfer b39 f39
rack -1;Rack to -1 at 1 gauge
xfer b40 f39
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f47 b48
xfer f46 b47
xfer f45 b46
rack 0.0;Rack to 0.0 at 1 gauge
xfer b46 f46
xfer b48 f48
rack 1;Rack to 1 at 1 gauge
xfer b47 f48
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f64 b63
xfer f63 b62
xfer f62 b61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b63 f63
xfer b61 f61
rack -1;Rack to -1 at 1 gauge
xfer b62 f61
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f69 b70
xfer f68 b69
xfer f67 b68
rack 0.0;Rack to 0.0 at 1 gauge
xfer b68 f68
xfer b70 f70
rack 1;Rack to 1 at 1 gauge
xfer b69 f70
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f86 b85
xfer f85 b84
xfer f84 b83
rack 0.0;Rack to 0.0 at 1 gauge
xfer b85 f85
xfer b83 f83
rack -1;Rack to -1 at 1 gauge
xfer b84 f83
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
tuck - f86 3
miss - f85 3
knit + f85 3
miss - f85 3
tuck - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
tuck - f69 3
miss - f68 3
knit + f68 3
miss - f68 3
tuck - f67 3
knit - f66 3
knit - f65 3
tuck - f64 3
miss - f63 3
knit + f63 3
miss - f63 3
tuck - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
tuck - f47 3
miss - f46 3
knit + f46 3
miss - f46 3
tuck - f45 3
knit - f44 3
knit - f43 3
tuck - f42 3
miss - f41 3
knit + f41 3
miss - f41 3
tuck - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
tuck - f25 3
miss - f24 3
knit + f24 3
miss - f24 3
tuck - f23 3
knit - f22 3
knit - f21 3
tuck - f20 3
miss - f19 3
knit + f19 3
miss - f19 3
tuck - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
tuck - f3 3
miss - f2 3
knit + f2 3
miss - f2 3
tuck - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
miss + f2 3
knit - f2 3
miss + f2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
miss + f19 3
knit - f19 3
miss + f19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
miss + f24 3
knit - f24 3
miss + f24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
miss + f41 3
knit - f41 3
miss + f41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
miss + f46 3
knit - f46 3
miss + f46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
miss + f63 3
knit - f63 3
miss + f63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
miss + f68 3
knit - f68 3
miss + f68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
miss + f85 3
knit - f85 3
miss + f85 3
knit + b86 3
knit + b87 3
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
xfer b5 f5
rack 1;Rack to 1 at 1 gauge
xfer b4 f5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
xfer f18 b17
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
xfer b16 f16
rack -1;Rack to -1 at 1 gauge
xfer b17 f16
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
xfer f25 b26
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
xfer b27 f27
rack 1;Rack to 1 at 1 gauge
xfer b26 f27
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
xfer f40 b39
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b40 f40
xfer b38 f38
rack -1;Rack to -1 at 1 gauge
xfer b39 f38
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f48 b49
xfer f47 b48
xfer f46 b47
rack 0.0;Rack to 0.0 at 1 gauge
xfer b47 f47
xfer b49 f49
rack 1;Rack to 1 at 1 gauge
xfer b48 f49
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f63 b62
xfer f62 b61
xfer f61 b60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b62 f62
xfer b60 f60
rack -1;Rack to -1 at 1 gauge
xfer b61 f60
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f70 b71
xfer f69 b70
xfer f68 b69
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
xfer b71 f71
rack 1;Rack to 1 at 1 gauge
xfer b70 f71
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f85 b84
xfer f84 b83
xfer f83 b82
rack 0.0;Rack to 0.0 at 1 gauge
xfer b84 f84
xfer b82 f82
rack -1;Rack to -1 at 1 gauge
xfer b83 f82
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
tuck - f85 3
miss - f84 3
knit + f84 3
miss - f84 3
tuck - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
tuck - f70 3
miss - f69 3
knit + f69 3
miss - f69 3
tuck - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
tuck - f63 3
miss - f62 3
knit + f62 3
miss - f62 3
tuck - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
tuck - f48 3
miss - f47 3
knit + f47 3
miss - f47 3
tuck - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
tuck - f41 3
miss - f40 3
knit + f40 3
miss - f40 3
tuck - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
tuck - f26 3
miss - f25 3
knit + f25 3
miss - f25 3
tuck - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
tuck - f19 3
miss - f18 3
knit + f18 3
miss - f18 3
tuck - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
tuck - f4 3
miss - f3 3
knit + f3 3
miss - f3 3
tuck - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
miss + f3 3
knit - f3 3
miss + f3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
miss + f18 3
knit - f18 3
miss + f18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
miss + f25 3
knit - f25 3
miss + f25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
miss + f40 3
knit - f40 3
miss + f40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
miss + f47 3
knit - f47 3
miss + f47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
miss + f62 3
knit - f62 3
miss + f62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
miss + f69 3
knit - f69 3
miss + f69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
miss + f84 3
knit - f84 3
miss + f84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
xfer b6 f6
rack 1;Rack to 1 at 1 gauge
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
xfer f17 b16
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
xfer b15 f15
rack -1;Rack to -1 at 1 gauge
xfer b16 f15
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f27 b28
xfer f26 b27
xfer f25 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
xfer b28 f28
rack 1;Rack to 1 at 1 gauge
xfer b27 f28
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
xfer f39 b38
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
xfer b37 f37
rack -1;Rack to -1 at 1 gauge
xfer b38 f37
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f49 b50
xfer f48 b49
xfer f47 b48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
xfer b50 f50
rack 1;Rack to 1 at 1 gauge
xfer b49 f50
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f62 b61
xfer f61 b60
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
xfer b59 f59
rack -1;Rack to -1 at 1 gauge
xfer b60 f59
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f71 b72
xfer f70 b71
xfer f69 b70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
xfer b72 f72
rack 1;Rack to 1 at 1 gauge
xfer b71 f72
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f84 b83
xfer f83 b82
xfer f82 b81
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
xfer b81 f81
rack -1;Rack to -1 at 1 gauge
xfer b82 f81
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
tuck - f84 3
miss - f83 3
knit + f83 3
miss - f83 3
tuck - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
tuck - f71 3
miss - f70 3
knit + f70 3
miss - f70 3
tuck - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
tuck - f62 3
miss - f61 3
knit + f61 3
miss - f61 3
tuck - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
tuck - f49 3
miss - f48 3
knit + f48 3
miss - f48 3
tuck - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
tuck - f40 3
miss - f39 3
knit + f39 3
miss - f39 3
tuck - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
tuck - f27 3
miss - f26 3
knit + f26 3
miss - f26 3
tuck - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
tuck - f18 3
miss - f17 3
knit + f17 3
miss - f17 3
tuck - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
tuck - f5 3
miss - f4 3
knit + f4 3
miss - f4 3
tuck - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
miss + f4 3
knit - f4 3
miss + f4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
miss + f17 3
knit - f17 3
miss + f17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
miss + f26 3
knit - f26 3
miss + f26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
miss + f39 3
knit - f39 3
miss + f39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
miss + f48 3
knit - f48 3
miss + f48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
miss + f61 3
knit - f61 3
miss + f61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
miss + f70 3
knit - f70 3
miss + f70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
miss + f83 3
knit - f83 3
miss + f83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
xfer f5 b6
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
xfer b7 f7
rack 1;Rack to 1 at 1 gauge
xfer b6 f7
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
xfer f16 b15
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
xfer b14 f14
rack -1;Rack to -1 at 1 gauge
xfer b15 f14
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b29 f29
rack 1;Rack to 1 at 1 gauge
xfer b28 f29
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
xfer f38 b37
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
xfer b36 f36
rack -1;Rack to -1 at 1 gauge
xfer b37 f36
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f50 b51
xfer f49 b50
xfer f48 b49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
xfer b51 f51
rack 1;Rack to 1 at 1 gauge
xfer b50 f51
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f61 b60
xfer f60 b59
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
xfer b58 f58
rack -1;Rack to -1 at 1 gauge
xfer b59 f58
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f72 b73
xfer f71 b72
xfer f70 b71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
xfer b73 f73
rack 1;Rack to 1 at 1 gauge
xfer b72 f73
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f83 b82
xfer f82 b81
xfer f81 b80
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
xfer b80 f80
rack -1;Rack to -1 at 1 gauge
xfer b81 f80
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
tuck - f83 3
miss - f82 3
knit + f82 3
miss - f82 3
tuck - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
tuck - f72 3
miss - f71 3
knit + f71 3
miss - f71 3
tuck - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
tuck - f61 3
miss - f60 3
knit + f60 3
miss - f60 3
tuck - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
tuck - f50 3
miss - f49 3
knit + f49 3
miss - f49 3
tuck - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
tuck - f39 3
miss - f38 3
knit + f38 3
miss - f38 3
tuck - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
tuck - f28 3
miss - f27 3
knit + f27 3
miss - f27 3
tuck - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
tuck - f17 3
miss - f16 3
knit + f16 3
miss - f16 3
tuck - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
tuck - f6 3
miss - f5 3
knit + f5 3
miss - f5 3
tuck - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
miss + f5 3
knit - f5 3
miss + f5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
miss + f16 3
knit - f16 3
miss + f16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
miss + f27 3
knit - f27 3
miss + f27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
miss + f38 3
knit - f38 3
miss + f38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
miss + f49 3
knit - f49 3
miss + f49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
miss + f60 3
knit - f60 3
miss + f60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
miss + f71 3
knit - f71 3
miss + f71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
miss + f82 3
knit - f82 3
miss + f82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
xfer f6 b7
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
xfer b8 f8
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
xfer f15 b14
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
xfer b13 f13
rack -1;Rack to -1 at 1 gauge
xfer b14 f13
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f29 b30
xfer f28 b29
xfer f27 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
xfer b30 f30
rack 1;Rack to 1 at 1 gauge
xfer b29 f30
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
xfer f37 b36
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
xfer b35 f35
rack -1;Rack to -1 at 1 gauge
xfer b36 f35
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f51 b52
xfer f50 b51
xfer f49 b50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
xfer b52 f52
rack 1;Rack to 1 at 1 gauge
xfer b51 f52
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
xfer f59 b58
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
xfer b57 f57
rack -1;Rack to -1 at 1 gauge
xfer b58 f57
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f73 b74
xfer f72 b73
xfer f71 b72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
xfer b74 f74
rack 1;Rack to 1 at 1 gauge
xfer b73 f74
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
xfer f81 b80
xfer f80 b79
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
xfer b79 f79
rack -1;Rack to -1 at 1 gauge
xfer b80 f79
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
tuck - f82 3
miss - f81 3
knit + f81 3
miss - f81 3
tuck - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
tuck - f73 3
miss - f72 3
knit + f72 3
miss - f72 3
tuck - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
tuck - f60 3
miss - f59 3
knit + f59 3
miss - f59 3
tuck - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
tuck - f51 3
miss - f50 3
knit + f50 3
miss - f50 3
tuck - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
tuck - f38 3
miss - f37 3
knit + f37 3
miss - f37 3
tuck - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
tuck - f29 3
miss - f28 3
knit + f28 3
miss - f28 3
tuck - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
tuck - f16 3
miss - f15 3
knit + f15 3
miss - f15 3
tuck - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
tuck - f7 3
miss - f6 3
knit + f6 3
miss - f6 3
tuck - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
miss + f6 3
knit - f6 3
miss + f6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
miss + f15 3
knit - f15 3
miss + f15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
miss + f28 3
knit - f28 3
miss + f28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
miss + f37 3
knit - f37 3
miss + f37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
miss + f50 3
knit - f50 3
miss + f50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
miss + f59 3
knit - f59 3
miss + f59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
miss + f72 3
knit - f72 3
miss + f72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
miss + f81 3
knit - f81 3
miss + f81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
xfer f7 b8
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer b8 f9
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
xfer f14 b13
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
xfer b12 f12
rack -1;Rack to -1 at 1 gauge
xfer b13 f12
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f29 b30
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b31 f31
rack 1;Rack to 1 at 1 gauge
xfer b30 f31
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
xfer f36 b35
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
xfer b34 f34
rack -1;Rack to -1 at 1 gauge
xfer b35 f34
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f52 b53
xfer f51 b52
xfer f50 b51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
xfer b53 f53
rack 1;Rack to 1 at 1 gauge
xfer b52 f53
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
xfer f58 b57
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
xfer b56 f56
rack -1;Rack to -1 at 1 gauge
xfer b57 f56
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f74 b75
xfer f73 b74
xfer f72 b73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
xfer b75 f75
rack 1;Rack to 1 at 1 gauge
xfer b74 f75
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f81 b80
xfer f80 b79
xfer f79 b78
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
xfer b78 f78
rack -1;Rack to -1 at 1 gauge
xfer b79 f78
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
tuck - f81 3
miss - f80 3
knit + f80 3
miss - f80 3
tuck - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
tuck - f74 3
miss - f73 3
knit + f73 3
miss - f73 3
tuck - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
tuck - f59 3
miss - f58 3
knit + f58 3
miss - f58 3
tuck - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
tuck - f52 3
miss - f51 3
knit + f51 3
miss - f51 3
tuck - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
tuck - f37 3
miss - f36 3
knit + f36 3
miss - f36 3
tuck - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
tuck - f30 3
miss - f29 3
knit + f29 3
miss - f29 3
tuck - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
tuck - f15 3
miss - f14 3
knit + f14 3
miss - f14 3
tuck - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
tuck - f8 3
miss - f7 3
knit + f7 3
miss - f7 3
tuck - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
miss + f7 3
knit - f7 3
miss + f7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
miss + f14 3
knit - f14 3
miss + f14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
miss + f29 3
knit - f29 3
miss + f29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
miss + f36 3
knit - f36 3
miss + f36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
miss + f51 3
knit - f51 3
miss + f51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
miss + f58 3
knit - f58 3
miss + f58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
miss + f73 3
knit - f73 3
miss + f73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
miss + f80 3
knit - f80 3
miss + f80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer b9 f10
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
xfer f13 b12
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
xfer b11 f11
rack -1;Rack to -1 at 1 gauge
xfer b12 f11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f31 b32
xfer f30 b31
xfer f29 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
xfer b32 f32
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f35 b34
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b33 f33
rack -1;Rack to -1 at 1 gauge
xfer b34 f33
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f53 b54
xfer f52 b53
xfer f51 b52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b52 f52
xfer b54 f54
rack 1;Rack to 1 at 1 gauge
xfer b53 f54
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
xfer f57 b56
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b57 f57
xfer b55 f55
rack -1;Rack to -1 at 1 gauge
xfer b56 f55
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f75 b76
xfer f74 b75
xfer f73 b74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b74 f74
xfer b76 f76
rack 1;Rack to 1 at 1 gauge
xfer b75 f76
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f80 b79
xfer f79 b78
xfer f78 b77
rack 0.0;Rack to 0.0 at 1 gauge
xfer b79 f79
xfer b77 f77
rack -1;Rack to -1 at 1 gauge
xfer b78 f77
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
tuck - f80 3
miss - f79 3
knit + f79 3
miss - f79 3
tuck - f78 3
knit - f77 3
knit - f76 3
tuck - f75 3
miss - f74 3
knit + f74 3
miss - f74 3
tuck - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
tuck - f58 3
miss - f57 3
knit + f57 3
miss - f57 3
tuck - f56 3
knit - f55 3
knit - f54 3
tuck - f53 3
miss - f52 3
knit + f52 3
miss - f52 3
tuck - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
tuck - f36 3
miss - f35 3
knit + f35 3
miss - f35 3
tuck - f34 3
knit - f33 3
knit - f32 3
tuck - f31 3
miss - f30 3
knit + f30 3
miss - f30 3
tuck - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
tuck - f14 3
miss - f13 3
knit + f13 3
miss - f13 3
tuck - f12 3
knit - f11 3
knit - f10 3
tuck - f9 3
miss - f8 3
knit + f8 3
miss - f8 3
tuck - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
miss + f8 3
knit - f8 3
miss + f8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
miss + f13 3
knit - f13 3
miss + f13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
miss + f30 3
knit - f30 3
miss + f30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
miss + f35 3
knit - f35 3
miss + f35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
miss + f52 3
knit - f52 3
miss + f52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
miss + f57 3
knit - f57 3
miss + f57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
miss + f74 3
knit - f74 3
miss + f74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
miss + f79 3
knit - f79 3
miss + f79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b1 f1
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
rack 1;Rack to 1 at 1 gauge
xfer b3 f4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
xfer f19 b18
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
rack -1;Rack to -1 at 1 gauge
xfer b18 f17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
rack -1;Rack to -1 at 1 gauge
xfer f25 b26
xfer f24 b25
xfer f23 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b42 f42
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
xfer f41 b40
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
rack -1;Rack to -1 at 1 gauge
xfer b40 f39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b45 f45
rack -1;Rack to -1 at 1 gauge
xfer f47 b48
xfer f46 b47
xfer f45 b46
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
rack 1;Rack to 1 at 1 gauge
xfer b47 f48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b64 f64
rack 1;Rack to 1 at 1 gauge
xfer f64 b63
xfer f63 b62
xfer f62 b61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
rack -1;Rack to -1 at 1 gauge
xfer b62 f61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b67 f67
rack -1;Rack to -1 at 1 gauge
xfer f69 b70
xfer f68 b69
xfer f67 b68
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
rack 1;Rack to 1 at 1 gauge
xfer b69 f70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b86 f86
rack 1;Rack to 1 at 1 gauge
xfer f86 b85
xfer f85 b84
xfer f84 b83
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
rack -1;Rack to -1 at 1 gauge
xfer b84 f83
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
tuck - f86 3
miss - b85 3
knit + b85 3
miss - b85 3
tuck - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
tuck - f69 3
miss - b68 3
knit + b68 3
miss - b68 3
tuck - f67 3
knit - f66 3
knit - f65 3
tuck - f64 3
miss - b63 3
knit + b63 3
miss - b63 3
tuck - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
tuck - f47 3
miss - b46 3
knit + b46 3
miss - b46 3
tuck - f45 3
knit - f44 3
knit - f43 3
tuck - f42 3
miss - b41 3
knit + b41 3
miss - b41 3
tuck - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
tuck - f25 3
miss - b24 3
knit + b24 3
miss - b24 3
tuck - f23 3
knit - f22 3
knit - f21 3
tuck - f20 3
miss - b19 3
knit + b19 3
miss - b19 3
tuck - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
tuck - f3 3
miss - b2 3
knit + b2 3
miss - b2 3
tuck - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
miss + b2 3
knit - b2 3
miss + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
miss + b19 3
knit - b19 3
miss + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
miss + b24 3
knit - b24 3
miss + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
miss + b41 3
knit - b41 3
miss + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
miss + b46 3
knit - b46 3
miss + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
miss + b63 3
knit - b63 3
miss + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
miss + b68 3
knit - b68 3
miss + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
miss + b85 3
knit - b85 3
miss + b85 3
knit + b86 3
knit + b87 3
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b2 f2
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
rack 1;Rack to 1 at 1 gauge
xfer b4 f5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
xfer f18 b17
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
rack -1;Rack to -1 at 1 gauge
xfer b17 f16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
xfer f25 b26
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
rack 1;Rack to 1 at 1 gauge
xfer b26 f27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b41 f41
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
xfer f40 b39
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
rack -1;Rack to -1 at 1 gauge
xfer b39 f38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b46 f46
rack -1;Rack to -1 at 1 gauge
xfer f48 b49
xfer f47 b48
xfer f46 b47
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
rack 1;Rack to 1 at 1 gauge
xfer b48 f49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b63 f63
rack 1;Rack to 1 at 1 gauge
xfer f63 b62
xfer f62 b61
xfer f61 b60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
rack -1;Rack to -1 at 1 gauge
xfer b61 f60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b68 f68
rack -1;Rack to -1 at 1 gauge
xfer f70 b71
xfer f69 b70
xfer f68 b69
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
rack 1;Rack to 1 at 1 gauge
xfer b70 f71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b85 f85
rack 1;Rack to 1 at 1 gauge
xfer f85 b84
xfer f84 b83
xfer f83 b82
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
rack -1;Rack to -1 at 1 gauge
xfer b83 f82
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
tuck - f85 3
miss - b84 3
knit + b84 3
miss - b84 3
tuck - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
tuck - f70 3
miss - b69 3
knit + b69 3
miss - b69 3
tuck - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
tuck - f63 3
miss - b62 3
knit + b62 3
miss - b62 3
tuck - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
tuck - f48 3
miss - b47 3
knit + b47 3
miss - b47 3
tuck - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
tuck - f41 3
miss - b40 3
knit + b40 3
miss - b40 3
tuck - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
tuck - f26 3
miss - b25 3
knit + b25 3
miss - b25 3
tuck - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
tuck - f19 3
miss - b18 3
knit + b18 3
miss - b18 3
tuck - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
tuck - f4 3
miss - b3 3
knit + b3 3
miss - b3 3
tuck - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
miss + b3 3
knit - b3 3
miss + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
miss + b18 3
knit - b18 3
miss + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
miss + b25 3
knit - b25 3
miss + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
miss + b40 3
knit - b40 3
miss + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
miss + b47 3
knit - b47 3
miss + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
miss + b62 3
knit - b62 3
miss + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
miss + b69 3
knit - b69 3
miss + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
miss + b84 3
knit - b84 3
miss + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b3 f3
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
rack 1;Rack to 1 at 1 gauge
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
xfer f17 b16
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
rack -1;Rack to -1 at 1 gauge
xfer b16 f15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
rack -1;Rack to -1 at 1 gauge
xfer f27 b28
xfer f26 b27
xfer f25 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
rack 1;Rack to 1 at 1 gauge
xfer b27 f28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b40 f40
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
xfer f39 b38
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
rack -1;Rack to -1 at 1 gauge
xfer b38 f37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b47 f47
rack -1;Rack to -1 at 1 gauge
xfer f49 b50
xfer f48 b49
xfer f47 b48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
rack 1;Rack to 1 at 1 gauge
xfer b49 f50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b62 f62
rack 1;Rack to 1 at 1 gauge
xfer f62 b61
xfer f61 b60
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
rack -1;Rack to -1 at 1 gauge
xfer b60 f59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
rack -1;Rack to -1 at 1 gauge
xfer f71 b72
xfer f70 b71
xfer f69 b70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
rack 1;Rack to 1 at 1 gauge
xfer b71 f72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b84 f84
rack 1;Rack to 1 at 1 gauge
xfer f84 b83
xfer f83 b82
xfer f82 b81
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
rack -1;Rack to -1 at 1 gauge
xfer b82 f81
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
tuck - f84 3
miss - b83 3
knit + b83 3
miss - b83 3
tuck - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
tuck - f71 3
miss - b70 3
knit + b70 3
miss - b70 3
tuck - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
tuck - f62 3
miss - b61 3
knit + b61 3
miss - b61 3
tuck - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
tuck - f49 3
miss - b48 3
knit + b48 3
miss - b48 3
tuck - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
tuck - f40 3
miss - b39 3
knit + b39 3
miss - b39 3
tuck - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
tuck - f27 3
miss - b26 3
knit + b26 3
miss - b26 3
tuck - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
tuck - f18 3
miss - b17 3
knit + b17 3
miss - b17 3
tuck - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
tuck - f5 3
miss - b4 3
knit + b4 3
miss - b4 3
tuck - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
miss + b4 3
knit - b4 3
miss + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
miss + b17 3
knit - b17 3
miss + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
miss + b26 3
knit - b26 3
miss + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
miss + b39 3
knit - b39 3
miss + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
miss + b48 3
knit - b48 3
miss + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
miss + b61 3
knit - b61 3
miss + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
miss + b70 3
knit - b70 3
miss + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
miss + b83 3
knit - b83 3
miss + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b4 f4
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
xfer f5 b6
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
rack 1;Rack to 1 at 1 gauge
xfer b6 f7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
xfer f16 b15
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
rack -1;Rack to -1 at 1 gauge
xfer b15 f14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
rack 1;Rack to 1 at 1 gauge
xfer b28 f29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
xfer f38 b37
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
rack -1;Rack to -1 at 1 gauge
xfer b37 f36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
rack -1;Rack to -1 at 1 gauge
xfer f50 b51
xfer f49 b50
xfer f48 b49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
rack 1;Rack to 1 at 1 gauge
xfer b50 f51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
rack 1;Rack to 1 at 1 gauge
xfer f61 b60
xfer f60 b59
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
rack -1;Rack to -1 at 1 gauge
xfer b59 f58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
rack -1;Rack to -1 at 1 gauge
xfer f72 b73
xfer f71 b72
xfer f70 b71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
rack 1;Rack to 1 at 1 gauge
xfer b72 f73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
rack 1;Rack to 1 at 1 gauge
xfer f83 b82
xfer f82 b81
xfer f81 b80
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
rack -1;Rack to -1 at 1 gauge
xfer b81 f80
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
tuck - f83 3
miss - b82 3
knit + b82 3
miss - b82 3
tuck - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
tuck - f72 3
miss - b71 3
knit + b71 3
miss - b71 3
tuck - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
tuck - f61 3
miss - b60 3
knit + b60 3
miss - b60 3
tuck - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
tuck - f50 3
miss - b49 3
knit + b49 3
miss - b49 3
tuck - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
tuck - f39 3
miss - b38 3
knit + b38 3
miss - b38 3
tuck - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
tuck - f28 3
miss - b27 3
knit + b27 3
miss - b27 3
tuck - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
tuck - f17 3
miss - b16 3
knit + b16 3
miss - b16 3
tuck - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
tuck - f6 3
miss - b5 3
knit + b5 3
miss - b5 3
tuck - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
miss + b5 3
knit - b5 3
miss + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
miss + b16 3
knit - b16 3
miss + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
miss + b27 3
knit - b27 3
miss + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
miss + b38 3
knit - b38 3
miss + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
miss + b49 3
knit - b49 3
miss + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
miss + b60 3
knit - b60 3
miss + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
miss + b71 3
knit - b71 3
miss + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
miss + b82 3
knit - b82 3
miss + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b5 f5
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
xfer f6 b7
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
xfer f15 b14
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
rack -1;Rack to -1 at 1 gauge
xfer b14 f13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
rack -1;Rack to -1 at 1 gauge
xfer f29 b30
xfer f28 b29
xfer f27 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
rack 1;Rack to 1 at 1 gauge
xfer b29 f30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
xfer f37 b36
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
rack -1;Rack to -1 at 1 gauge
xfer b36 f35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
rack -1;Rack to -1 at 1 gauge
xfer f51 b52
xfer f50 b51
xfer f49 b50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b52 f52
rack 1;Rack to 1 at 1 gauge
xfer b51 f52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
xfer f59 b58
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b57 f57
rack -1;Rack to -1 at 1 gauge
xfer b58 f57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
rack -1;Rack to -1 at 1 gauge
xfer f73 b74
xfer f72 b73
xfer f71 b72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b74 f74
rack 1;Rack to 1 at 1 gauge
xfer b73 f74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
xfer f81 b80
xfer f80 b79
rack 0.0;Rack to 0.0 at 1 gauge
xfer b79 f79
rack -1;Rack to -1 at 1 gauge
xfer b80 f79
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
tuck - f82 3
miss - b81 3
knit + b81 3
miss - b81 3
tuck - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
tuck - f73 3
miss - b72 3
knit + b72 3
miss - b72 3
tuck - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
tuck - f60 3
miss - b59 3
knit + b59 3
miss - b59 3
tuck - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
tuck - f51 3
miss - b50 3
knit + b50 3
miss - b50 3
tuck - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
tuck - f38 3
miss - b37 3
knit + b37 3
miss - b37 3
tuck - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
tuck - f29 3
miss - b28 3
knit + b28 3
miss - b28 3
tuck - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
tuck - f16 3
miss - b15 3
knit + b15 3
miss - b15 3
tuck - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
tuck - f7 3
miss - b6 3
knit + b6 3
miss - b6 3
tuck - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
miss + b6 3
knit - b6 3
miss + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
miss + b15 3
knit - b15 3
miss + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
miss + b28 3
knit - b28 3
miss + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
miss + b37 3
knit - b37 3
miss + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
miss + b50 3
knit - b50 3
miss + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
miss + b59 3
knit - b59 3
miss + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
miss + b72 3
knit - b72 3
miss + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
miss + b81 3
knit - b81 3
miss + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b6 f6
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
xfer f7 b8
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer b8 f9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
xfer f14 b13
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
rack -1;Rack to -1 at 1 gauge
xfer b13 f12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f29 b30
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
rack 1;Rack to 1 at 1 gauge
xfer b30 f31
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
xfer f36 b35
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
rack -1;Rack to -1 at 1 gauge
xfer b35 f34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
rack -1;Rack to -1 at 1 gauge
xfer f52 b53
xfer f51 b52
xfer f50 b51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b53 f53
rack 1;Rack to 1 at 1 gauge
xfer b52 f53
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
xfer f58 b57
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b56 f56
rack -1;Rack to -1 at 1 gauge
xfer b57 f56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
rack -1;Rack to -1 at 1 gauge
xfer f74 b75
xfer f73 b74
xfer f72 b73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b75 f75
rack 1;Rack to 1 at 1 gauge
xfer b74 f75
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
rack 1;Rack to 1 at 1 gauge
xfer f81 b80
xfer f80 b79
xfer f79 b78
rack 0.0;Rack to 0.0 at 1 gauge
xfer b78 f78
rack -1;Rack to -1 at 1 gauge
xfer b79 f78
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
tuck - f81 3
miss - b80 3
knit + b80 3
miss - b80 3
tuck - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
tuck - f74 3
miss - b73 3
knit + b73 3
miss - b73 3
tuck - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
tuck - f59 3
miss - b58 3
knit + b58 3
miss - b58 3
tuck - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
tuck - f52 3
miss - b51 3
knit + b51 3
miss - b51 3
tuck - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
tuck - f37 3
miss - b36 3
knit + b36 3
miss - b36 3
tuck - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
tuck - f30 3
miss - b29 3
knit + b29 3
miss - b29 3
tuck - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
tuck - f15 3
miss - b14 3
knit + b14 3
miss - b14 3
tuck - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
tuck - f8 3
miss - b7 3
knit + b7 3
miss - b7 3
tuck - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
miss + b7 3
knit - b7 3
miss + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
miss + b14 3
knit - b14 3
miss + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
miss + b29 3
knit - b29 3
miss + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
miss + b36 3
knit - b36 3
miss + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
miss + b51 3
knit - b51 3
miss + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
miss + b58 3
knit - b58 3
miss + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
miss + b73 3
knit - b73 3
miss + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
miss + b80 3
knit - b80 3
miss + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b7 f7
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer b9 f10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
xfer f13 b12
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
rack -1;Rack to -1 at 1 gauge
xfer b12 f11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
rack -1;Rack to -1 at 1 gauge
xfer f31 b32
xfer f30 b31
xfer f29 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f35 b34
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
rack -1;Rack to -1 at 1 gauge
xfer b34 f33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
rack -1;Rack to -1 at 1 gauge
xfer f53 b54
xfer f52 b53
xfer f51 b52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b54 f54
rack 1;Rack to 1 at 1 gauge
xfer b53 f54
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
xfer f57 b56
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b55 f55
rack -1;Rack to -1 at 1 gauge
xfer b56 f55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
rack -1;Rack to -1 at 1 gauge
xfer f75 b76
xfer f74 b75
xfer f73 b74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b76 f76
rack 1;Rack to 1 at 1 gauge
xfer b75 f76
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
rack 1;Rack to 1 at 1 gauge
xfer f80 b79
xfer f79 b78
xfer f78 b77
rack 0.0;Rack to 0.0 at 1 gauge
xfer b77 f77
rack -1;Rack to -1 at 1 gauge
xfer b78 f77
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
tuck - f80 3
miss - b79 3
knit + b79 3
miss - b79 3
tuck - f78 3
knit - f77 3
knit - f76 3
tuck - f75 3
miss - b74 3
knit + b74 3
miss - b74 3
tuck - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
tuck - f58 3
miss - b57 3
knit + b57 3
miss - b57 3
tuck - f56 3
knit - f55 3
knit - f54 3
tuck - f53 3
miss - b52 3
knit + b52 3
miss - b52 3
tuck - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
tuck - f36 3
miss - b35 3
knit + b35 3
miss - b35 3
tuck - f34 3
knit - f33 3
knit - f32 3
tuck - f31 3
miss - b30 3
knit + b30 3
miss - b30 3
tuck - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
tuck - f14 3
miss - b13 3
knit + b13 3
miss - b13 3
tuck - f12 3
knit - f11 3
knit - f10 3
tuck - f9 3
miss - b8 3
knit + b8 3
miss - b8 3
tuck - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
miss + b8 3
knit - b8 3
miss + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
miss + b13 3
knit - b13 3
miss + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
miss + b30 3
knit - b30 3
miss + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
miss + b35 3
knit - b35 3
miss + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
miss + b52 3
knit - b52 3
miss + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
miss + b57 3
knit - b57 3
miss + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
miss + b74 3
knit - b74 3
miss + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
miss + b79 3
knit - b79 3
miss + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b74 f74
xfer b57 f57
xfer b52 f52
xfer b35 f35
xfer b30 f30
xfer b13 f13
xfer b8 f8
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
xfer b4 f4
rack 1;Rack to 1 at 1 gauge
xfer b3 f4
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
xfer f19 b18
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
xfer b17 f17
rack -1;Rack to -1 at 1 gauge
xfer b18 f17
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f25 b26
xfer f24 b25
xfer f23 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
xfer b26 f26
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
xfer f41 b40
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b41 f41
xfer b39 f39
rack -1;Rack to -1 at 1 gauge
xfer b40 f39
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f47 b48
xfer f46 b47
xfer f45 b46
rack 0.0;Rack to 0.0 at 1 gauge
xfer b46 f46
xfer b48 f48
rack 1;Rack to 1 at 1 gauge
xfer b47 f48
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f64 b63
xfer f63 b62
xfer f62 b61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b63 f63
xfer b61 f61
rack -1;Rack to -1 at 1 gauge
xfer b62 f61
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f69 b70
xfer f68 b69
xfer f67 b68
rack 0.0;Rack to 0.0 at 1 gauge
xfer b68 f68
xfer b70 f70
rack 1;Rack to 1 at 1 gauge
xfer b69 f70
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f86 b85
xfer f85 b84
xfer f84 b83
rack 0.0;Rack to 0.0 at 1 gauge
xfer b85 f85
xfer b83 f83
rack -1;Rack to -1 at 1 gauge
xfer b84 f83
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
tuck - f86 3
miss - f85 3
knit + f85 3
miss - f85 3
tuck - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
tuck - f69 3
miss - f68 3
knit + f68 3
miss - f68 3
tuck - f67 3
knit - f66 3
knit - f65 3
tuck - f64 3
miss - f63 3
knit + f63 3
miss - f63 3
tuck - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
tuck - f47 3
miss - f46 3
knit + f46 3
miss - f46 3
tuck - f45 3
knit - f44 3
knit - f43 3
tuck - f42 3
miss - f41 3
knit + f41 3
miss - f41 3
tuck - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
tuck - f25 3
miss - f24 3
knit + f24 3
miss - f24 3
tuck - f23 3
knit - f22 3
knit - f21 3
tuck - f20 3
miss - f19 3
knit + f19 3
miss - f19 3
tuck - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
tuck - f3 3
miss - f2 3
knit + f2 3
miss - f2 3
tuck - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
miss + f2 3
knit - f2 3
miss + f2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
miss + f19 3
knit - f19 3
miss + f19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
miss + f24 3
knit - f24 3
miss + f24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
miss + f41 3
knit - f41 3
miss + f41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
miss + f46 3
knit - f46 3
miss + f46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
miss + f63 3
knit - f63 3
miss + f63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
miss + f68 3
knit - f68 3
miss + f68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
miss + f85 3
knit - f85 3
miss + f85 3
knit + b86 3
knit + b87 3
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
xfer b5 f5
rack 1;Rack to 1 at 1 gauge
xfer b4 f5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
xfer f18 b17
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
xfer b16 f16
rack -1;Rack to -1 at 1 gauge
xfer b17 f16
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
xfer f25 b26
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
xfer b27 f27
rack 1;Rack to 1 at 1 gauge
xfer b26 f27
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
xfer f40 b39
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b40 f40
xfer b38 f38
rack -1;Rack to -1 at 1 gauge
xfer b39 f38
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f48 b49
xfer f47 b48
xfer f46 b47
rack 0.0;Rack to 0.0 at 1 gauge
xfer b47 f47
xfer b49 f49
rack 1;Rack to 1 at 1 gauge
xfer b48 f49
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f63 b62
xfer f62 b61
xfer f61 b60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b62 f62
xfer b60 f60
rack -1;Rack to -1 at 1 gauge
xfer b61 f60
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f70 b71
xfer f69 b70
xfer f68 b69
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
xfer b71 f71
rack 1;Rack to 1 at 1 gauge
xfer b70 f71
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f85 b84
xfer f84 b83
xfer f83 b82
rack 0.0;Rack to 0.0 at 1 gauge
xfer b84 f84
xfer b82 f82
rack -1;Rack to -1 at 1 gauge
xfer b83 f82
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
tuck - f85 3
miss - f84 3
knit + f84 3
miss - f84 3
tuck - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
tuck - f70 3
miss - f69 3
knit + f69 3
miss - f69 3
tuck - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
tuck - f63 3
miss - f62 3
knit + f62 3
miss - f62 3
tuck - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
tuck - f48 3
miss - f47 3
knit + f47 3
miss - f47 3
tuck - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
tuck - f41 3
miss - f40 3
knit + f40 3
miss - f40 3
tuck - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
tuck - f26 3
miss - f25 3
knit + f25 3
miss - f25 3
tuck - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
tuck - f19 3
miss - f18 3
knit + f18 3
miss - f18 3
tuck - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
tuck - f4 3
miss - f3 3
knit + f3 3
miss - f3 3
tuck - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
miss + f3 3
knit - f3 3
miss + f3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
miss + f18 3
knit - f18 3
miss + f18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
miss + f25 3
knit - f25 3
miss + f25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
miss + f40 3
knit - f40 3
miss + f40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
miss + f47 3
knit - f47 3
miss + f47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
miss + f62 3
knit - f62 3
miss + f62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
miss + f69 3
knit - f69 3
miss + f69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
miss + f84 3
knit - f84 3
miss + f84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
xfer b6 f6
rack 1;Rack to 1 at 1 gauge
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
xfer f17 b16
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
xfer b15 f15
rack -1;Rack to -1 at 1 gauge
xfer b16 f15
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f27 b28
xfer f26 b27
xfer f25 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
xfer b28 f28
rack 1;Rack to 1 at 1 gauge
xfer b27 f28
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
xfer f39 b38
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
xfer b37 f37
rack -1;Rack to -1 at 1 gauge
xfer b38 f37
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f49 b50
xfer f48 b49
xfer f47 b48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
xfer b50 f50
rack 1;Rack to 1 at 1 gauge
xfer b49 f50
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f62 b61
xfer f61 b60
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
xfer b59 f59
rack -1;Rack to -1 at 1 gauge
xfer b60 f59
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f71 b72
xfer f70 b71
xfer f69 b70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
xfer b72 f72
rack 1;Rack to 1 at 1 gauge
xfer b71 f72
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f84 b83
xfer f83 b82
xfer f82 b81
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
xfer b81 f81
rack -1;Rack to -1 at 1 gauge
xfer b82 f81
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
tuck - f84 3
miss - f83 3
knit + f83 3
miss - f83 3
tuck - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
tuck - f71 3
miss - f70 3
knit + f70 3
miss - f70 3
tuck - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
tuck - f62 3
miss - f61 3
knit + f61 3
miss - f61 3
tuck - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
tuck - f49 3
miss - f48 3
knit + f48 3
miss - f48 3
tuck - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
tuck - f40 3
miss - f39 3
knit + f39 3
miss - f39 3
tuck - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
tuck - f27 3
miss - f26 3
knit + f26 3
miss - f26 3
tuck - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
tuck - f18 3
miss - f17 3
knit + f17 3
miss - f17 3
tuck - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
tuck - f5 3
miss - f4 3
knit + f4 3
miss - f4 3
tuck - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
miss + f4 3
knit - f4 3
miss + f4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
miss + f17 3
knit - f17 3
miss + f17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
miss + f26 3
knit - f26 3
miss + f26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
miss + f39 3
knit - f39 3
miss + f39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
miss + f48 3
knit - f48 3
miss + f48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
miss + f61 3
knit - f61 3
miss + f61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
miss + f70 3
knit - f70 3
miss + f70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
miss + f83 3
knit - f83 3
miss + f83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
xfer f5 b6
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
xfer b7 f7
rack 1;Rack to 1 at 1 gauge
xfer b6 f7
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
xfer f16 b15
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
xfer b14 f14
rack -1;Rack to -1 at 1 gauge
xfer b15 f14
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
xfer b29 f29
rack 1;Rack to 1 at 1 gauge
xfer b28 f29
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
xfer f38 b37
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
xfer b36 f36
rack -1;Rack to -1 at 1 gauge
xfer b37 f36
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f50 b51
xfer f49 b50
xfer f48 b49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
xfer b51 f51
rack 1;Rack to 1 at 1 gauge
xfer b50 f51
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f61 b60
xfer f60 b59
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
xfer b58 f58
rack -1;Rack to -1 at 1 gauge
xfer b59 f58
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f72 b73
xfer f71 b72
xfer f70 b71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
xfer b73 f73
rack 1;Rack to 1 at 1 gauge
xfer b72 f73
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f83 b82
xfer f82 b81
xfer f81 b80
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
xfer b80 f80
rack -1;Rack to -1 at 1 gauge
xfer b81 f80
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
tuck - f83 3
miss - f82 3
knit + f82 3
miss - f82 3
tuck - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
tuck - f72 3
miss - f71 3
knit + f71 3
miss - f71 3
tuck - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
tuck - f61 3
miss - f60 3
knit + f60 3
miss - f60 3
tuck - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
tuck - f50 3
miss - f49 3
knit + f49 3
miss - f49 3
tuck - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
tuck - f39 3
miss - f38 3
knit + f38 3
miss - f38 3
tuck - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
tuck - f28 3
miss - f27 3
knit + f27 3
miss - f27 3
tuck - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
tuck - f17 3
miss - f16 3
knit + f16 3
miss - f16 3
tuck - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
tuck - f6 3
miss - f5 3
knit + f5 3
miss - f5 3
tuck - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
miss + f5 3
knit - f5 3
miss + f5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
miss + f16 3
knit - f16 3
miss + f16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
miss + f27 3
knit - f27 3
miss + f27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
miss + f38 3
knit - f38 3
miss + f38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
miss + f49 3
knit - f49 3
miss + f49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
miss + f60 3
knit - f60 3
miss + f60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
miss + f71 3
knit - f71 3
miss + f71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
miss + f82 3
knit - f82 3
miss + f82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
xfer f6 b7
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
xfer b8 f8
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
xfer f15 b14
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
xfer b13 f13
rack -1;Rack to -1 at 1 gauge
xfer b14 f13
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f29 b30
xfer f28 b29
xfer f27 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
xfer b30 f30
rack 1;Rack to 1 at 1 gauge
xfer b29 f30
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
xfer f37 b36
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
xfer b35 f35
rack -1;Rack to -1 at 1 gauge
xfer b36 f35
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f51 b52
xfer f50 b51
xfer f49 b50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
xfer b52 f52
rack 1;Rack to 1 at 1 gauge
xfer b51 f52
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
xfer f59 b58
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
xfer b57 f57
rack -1;Rack to -1 at 1 gauge
xfer b58 f57
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f73 b74
xfer f72 b73
xfer f71 b72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
xfer b74 f74
rack 1;Rack to 1 at 1 gauge
xfer b73 f74
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
xfer f81 b80
xfer f80 b79
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
xfer b79 f79
rack -1;Rack to -1 at 1 gauge
xfer b80 f79
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
tuck - f82 3
miss - f81 3
knit + f81 3
miss - f81 3
tuck - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
tuck - f73 3
miss - f72 3
knit + f72 3
miss - f72 3
tuck - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
tuck - f60 3
miss - f59 3
knit + f59 3
miss - f59 3
tuck - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
tuck - f51 3
miss - f50 3
knit + f50 3
miss - f50 3
tuck - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
tuck - f38 3
miss - f37 3
knit + f37 3
miss - f37 3
tuck - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
tuck - f29 3
miss - f28 3
knit + f28 3
miss - f28 3
tuck - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
tuck - f16 3
miss - f15 3
knit + f15 3
miss - f15 3
tuck - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
tuck - f7 3
miss - f6 3
knit + f6 3
miss - f6 3
tuck - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
miss + f6 3
knit - f6 3
miss + f6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
miss + f15 3
knit - f15 3
miss + f15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
miss + f28 3
knit - f28 3
miss + f28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
miss + f37 3
knit - f37 3
miss + f37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
miss + f50 3
knit - f50 3
miss + f50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
miss + f59 3
knit - f59 3
miss + f59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
miss + f72 3
knit - f72 3
miss + f72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
miss + f81 3
knit - f81 3
miss + f81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
xfer f7 b8
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer b8 f9
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
xfer f14 b13
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
xfer b12 f12
rack -1;Rack to -1 at 1 gauge
xfer b13 f12
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f29 b30
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
xfer b31 f31
rack 1;Rack to 1 at 1 gauge
xfer b30 f31
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
xfer f36 b35
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
xfer b34 f34
rack -1;Rack to -1 at 1 gauge
xfer b35 f34
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f52 b53
xfer f51 b52
xfer f50 b51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
xfer b53 f53
rack 1;Rack to 1 at 1 gauge
xfer b52 f53
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
xfer f58 b57
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
xfer b56 f56
rack -1;Rack to -1 at 1 gauge
xfer b57 f56
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f74 b75
xfer f73 b74
xfer f72 b73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
xfer b75 f75
rack 1;Rack to 1 at 1 gauge
xfer b74 f75
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f81 b80
xfer f80 b79
xfer f79 b78
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
xfer b78 f78
rack -1;Rack to -1 at 1 gauge
xfer b79 f78
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
tuck - f81 3
miss - f80 3
knit + f80 3
miss - f80 3
tuck - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
tuck - f74 3
miss - f73 3
knit + f73 3
miss - f73 3
tuck - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
tuck - f59 3
miss - f58 3
knit + f58 3
miss - f58 3
tuck - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
tuck - f52 3
miss - f51 3
knit + f51 3
miss - f51 3
tuck - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
tuck - f37 3
miss - f36 3
knit + f36 3
miss - f36 3
tuck - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
tuck - f30 3
miss - f29 3
knit + f29 3
miss - f29 3
tuck - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
tuck - f15 3
miss - f14 3
knit + f14 3
miss - f14 3
tuck - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
tuck - f8 3
miss - f7 3
knit + f7 3
miss - f7 3
tuck - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
miss + f7 3
knit - f7 3
miss + f7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
miss + f14 3
knit - f14 3
miss + f14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
miss + f29 3
knit - f29 3
miss + f29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
miss + f36 3
knit - f36 3
miss + f36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
miss + f51 3
knit - f51 3
miss + f51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
miss + f58 3
knit - f58 3
miss + f58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
miss + f73 3
knit - f73 3
miss + f73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
miss + f80 3
knit - f80 3
miss + f80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer b9 f10
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
xfer f13 b12
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
xfer b11 f11
rack -1;Rack to -1 at 1 gauge
xfer b12 f11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f31 b32
xfer f30 b31
xfer f29 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
xfer b32 f32
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f35 b34
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
xfer b33 f33
rack -1;Rack to -1 at 1 gauge
xfer b34 f33
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f53 b54
xfer f52 b53
xfer f51 b52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b52 f52
xfer b54 f54
rack 1;Rack to 1 at 1 gauge
xfer b53 f54
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
xfer f57 b56
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b57 f57
xfer b55 f55
rack -1;Rack to -1 at 1 gauge
xfer b56 f55
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f75 b76
xfer f74 b75
xfer f73 b74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b74 f74
xfer b76 f76
rack 1;Rack to 1 at 1 gauge
xfer b75 f76
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f80 b79
xfer f79 b78
xfer f78 b77
rack 0.0;Rack to 0.0 at 1 gauge
xfer b79 f79
xfer b77 f77
rack -1;Rack to -1 at 1 gauge
xfer b78 f77
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
tuck - f80 3
miss - f79 3
knit + f79 3
miss - f79 3
tuck - f78 3
knit - f77 3
knit - f76 3
tuck - f75 3
miss - f74 3
knit + f74 3
miss - f74 3
tuck - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
tuck - f58 3
miss - f57 3
knit + f57 3
miss - f57 3
tuck - f56 3
knit - f55 3
knit - f54 3
tuck - f53 3
miss - f52 3
knit + f52 3
miss - f52 3
tuck - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
tuck - f36 3
miss - f35 3
knit + f35 3
miss - f35 3
tuck - f34 3
knit - f33 3
knit - f32 3
tuck - f31 3
miss - f30 3
knit + f30 3
miss - f30 3
tuck - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
tuck - f14 3
miss - f13 3
knit + f13 3
miss - f13 3
tuck - f12 3
knit - f11 3
knit - f10 3
tuck - f9 3
miss - f8 3
knit + f8 3
miss - f8 3
tuck - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
miss + f8 3
knit - f8 3
miss + f8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
miss + f13 3
knit - f13 3
miss + f13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
miss + f30 3
knit - f30 3
miss + f30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
miss + f35 3
knit - f35 3
miss + f35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
miss + f52 3
knit - f52 3
miss + f52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
miss + f57 3
knit - f57 3
miss + f57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
miss + f74 3
knit - f74 3
miss + f74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
miss + f79 3
knit - f79 3
miss + f79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b1 f1
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
xfer f2 b3
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
rack 1;Rack to 1 at 1 gauge
xfer b3 f4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
xfer f19 b18
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
rack -1;Rack to -1 at 1 gauge
xfer b18 f17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
rack -1;Rack to -1 at 1 gauge
xfer f25 b26
xfer f24 b25
xfer f23 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b42 f42
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
xfer f41 b40
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
rack -1;Rack to -1 at 1 gauge
xfer b40 f39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b45 f45
rack -1;Rack to -1 at 1 gauge
xfer f47 b48
xfer f46 b47
xfer f45 b46
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
rack 1;Rack to 1 at 1 gauge
xfer b47 f48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b64 f64
rack 1;Rack to 1 at 1 gauge
xfer f64 b63
xfer f63 b62
xfer f62 b61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
rack -1;Rack to -1 at 1 gauge
xfer b62 f61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b67 f67
rack -1;Rack to -1 at 1 gauge
xfer f69 b70
xfer f68 b69
xfer f67 b68
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
rack 1;Rack to 1 at 1 gauge
xfer b69 f70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b86 f86
rack 1;Rack to 1 at 1 gauge
xfer f86 b85
xfer f85 b84
xfer f84 b83
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
rack -1;Rack to -1 at 1 gauge
xfer b84 f83
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
tuck - f86 3
miss - b85 3
knit + b85 3
miss - b85 3
tuck - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
tuck - f69 3
miss - b68 3
knit + b68 3
miss - b68 3
tuck - f67 3
knit - f66 3
knit - f65 3
tuck - f64 3
miss - b63 3
knit + b63 3
miss - b63 3
tuck - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
tuck - f47 3
miss - b46 3
knit + b46 3
miss - b46 3
tuck - f45 3
knit - f44 3
knit - f43 3
tuck - f42 3
miss - b41 3
knit + b41 3
miss - b41 3
tuck - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
tuck - f25 3
miss - b24 3
knit + b24 3
miss - b24 3
tuck - f23 3
knit - f22 3
knit - f21 3
tuck - f20 3
miss - b19 3
knit + b19 3
miss - b19 3
tuck - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
tuck - f3 3
miss - b2 3
knit + b2 3
miss - b2 3
tuck - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
miss + b2 3
knit - b2 3
miss + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
miss + b19 3
knit - b19 3
miss + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
miss + b24 3
knit - b24 3
miss + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
miss + b41 3
knit - b41 3
miss + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
miss + b46 3
knit - b46 3
miss + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
miss + b63 3
knit - b63 3
miss + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
miss + b68 3
knit - b68 3
miss + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
miss + b85 3
knit - b85 3
miss + b85 3
knit + b86 3
knit + b87 3
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b2 f2
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
xfer f3 b4
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
rack 1;Rack to 1 at 1 gauge
xfer b4 f5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
xfer f18 b17
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
rack -1;Rack to -1 at 1 gauge
xfer b17 f16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
xfer f25 b26
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
rack 1;Rack to 1 at 1 gauge
xfer b26 f27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b41 f41
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
xfer f40 b39
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
rack -1;Rack to -1 at 1 gauge
xfer b39 f38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b46 f46
rack -1;Rack to -1 at 1 gauge
xfer f48 b49
xfer f47 b48
xfer f46 b47
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
rack 1;Rack to 1 at 1 gauge
xfer b48 f49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b63 f63
rack 1;Rack to 1 at 1 gauge
xfer f63 b62
xfer f62 b61
xfer f61 b60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
rack -1;Rack to -1 at 1 gauge
xfer b61 f60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b68 f68
rack -1;Rack to -1 at 1 gauge
xfer f70 b71
xfer f69 b70
xfer f68 b69
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
rack 1;Rack to 1 at 1 gauge
xfer b70 f71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b85 f85
rack 1;Rack to 1 at 1 gauge
xfer f85 b84
xfer f84 b83
xfer f83 b82
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
rack -1;Rack to -1 at 1 gauge
xfer b83 f82
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
tuck - f85 3
miss - b84 3
knit + b84 3
miss - b84 3
tuck - f83 3
knit - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
knit - f71 3
tuck - f70 3
miss - b69 3
knit + b69 3
miss - b69 3
tuck - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
tuck - f63 3
miss - b62 3
knit + b62 3
miss - b62 3
tuck - f61 3
knit - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
knit - f49 3
tuck - f48 3
miss - b47 3
knit + b47 3
miss - b47 3
tuck - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
tuck - f41 3
miss - b40 3
knit + b40 3
miss - b40 3
tuck - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
tuck - f26 3
miss - b25 3
knit + b25 3
miss - b25 3
tuck - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
tuck - f19 3
miss - b18 3
knit + b18 3
miss - b18 3
tuck - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
tuck - f4 3
miss - b3 3
knit + b3 3
miss - b3 3
tuck - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
miss + b3 3
knit - b3 3
miss + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
miss + b18 3
knit - b18 3
miss + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
miss + b25 3
knit - b25 3
miss + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
miss + b40 3
knit - b40 3
miss + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
miss + b47 3
knit - b47 3
miss + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
miss + b62 3
knit - b62 3
miss + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
miss + b69 3
knit - b69 3
miss + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
miss + b84 3
knit - b84 3
miss + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b3 f3
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
xfer f4 b5
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
rack 1;Rack to 1 at 1 gauge
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
xfer f17 b16
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
rack -1;Rack to -1 at 1 gauge
xfer b16 f15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
rack -1;Rack to -1 at 1 gauge
xfer f27 b28
xfer f26 b27
xfer f25 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
rack 1;Rack to 1 at 1 gauge
xfer b27 f28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b40 f40
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
xfer f39 b38
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
rack -1;Rack to -1 at 1 gauge
xfer b38 f37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b47 f47
rack -1;Rack to -1 at 1 gauge
xfer f49 b50
xfer f48 b49
xfer f47 b48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
rack 1;Rack to 1 at 1 gauge
xfer b49 f50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b62 f62
rack 1;Rack to 1 at 1 gauge
xfer f62 b61
xfer f61 b60
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
rack -1;Rack to -1 at 1 gauge
xfer b60 f59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
rack -1;Rack to -1 at 1 gauge
xfer f71 b72
xfer f70 b71
xfer f69 b70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
rack 1;Rack to 1 at 1 gauge
xfer b71 f72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b84 f84
rack 1;Rack to 1 at 1 gauge
xfer f84 b83
xfer f83 b82
xfer f82 b81
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
rack -1;Rack to -1 at 1 gauge
xfer b82 f81
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
tuck - f84 3
miss - b83 3
knit + b83 3
miss - b83 3
tuck - f82 3
knit - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
knit - f72 3
tuck - f71 3
miss - b70 3
knit + b70 3
miss - b70 3
tuck - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
tuck - f62 3
miss - b61 3
knit + b61 3
miss - b61 3
tuck - f60 3
knit - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
knit - f50 3
tuck - f49 3
miss - b48 3
knit + b48 3
miss - b48 3
tuck - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
tuck - f40 3
miss - b39 3
knit + b39 3
miss - b39 3
tuck - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
tuck - f27 3
miss - b26 3
knit + b26 3
miss - b26 3
tuck - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
tuck - f18 3
miss - b17 3
knit + b17 3
miss - b17 3
tuck - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
tuck - f5 3
miss - b4 3
knit + b4 3
miss - b4 3
tuck - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
miss + b4 3
knit - b4 3
miss + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
miss + b17 3
knit - b17 3
miss + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
miss + b26 3
knit - b26 3
miss + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
miss + b39 3
knit - b39 3
miss + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
miss + b48 3
knit - b48 3
miss + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
miss + b61 3
knit - b61 3
miss + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
miss + b70 3
knit - b70 3
miss + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
miss + b83 3
knit - b83 3
miss + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b4 f4
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
xfer f5 b6
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
rack 1;Rack to 1 at 1 gauge
xfer b6 f7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
xfer f16 b15
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
rack -1;Rack to -1 at 1 gauge
xfer b15 f14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
xfer f27 b28
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
rack 1;Rack to 1 at 1 gauge
xfer b28 f29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
xfer f38 b37
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
rack -1;Rack to -1 at 1 gauge
xfer b37 f36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
rack -1;Rack to -1 at 1 gauge
xfer f50 b51
xfer f49 b50
xfer f48 b49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
rack 1;Rack to 1 at 1 gauge
xfer b50 f51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
rack 1;Rack to 1 at 1 gauge
xfer f61 b60
xfer f60 b59
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
rack -1;Rack to -1 at 1 gauge
xfer b59 f58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
rack -1;Rack to -1 at 1 gauge
xfer f72 b73
xfer f71 b72
xfer f70 b71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
rack 1;Rack to 1 at 1 gauge
xfer b72 f73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
rack 1;Rack to 1 at 1 gauge
xfer f83 b82
xfer f82 b81
xfer f81 b80
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
rack -1;Rack to -1 at 1 gauge
xfer b81 f80
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
tuck - f83 3
miss - b82 3
knit + b82 3
miss - b82 3
tuck - f81 3
knit - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
knit - f73 3
tuck - f72 3
miss - b71 3
knit + b71 3
miss - b71 3
tuck - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
tuck - f61 3
miss - b60 3
knit + b60 3
miss - b60 3
tuck - f59 3
knit - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
knit - f51 3
tuck - f50 3
miss - b49 3
knit + b49 3
miss - b49 3
tuck - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
tuck - f39 3
miss - b38 3
knit + b38 3
miss - b38 3
tuck - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
tuck - f28 3
miss - b27 3
knit + b27 3
miss - b27 3
tuck - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
tuck - f17 3
miss - b16 3
knit + b16 3
miss - b16 3
tuck - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
tuck - f6 3
miss - b5 3
knit + b5 3
miss - b5 3
tuck - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f50 b50
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f59 b59
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f72 b72
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f81 b81
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
miss + b5 3
knit - b5 3
miss + b5 3
knit + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
miss + b16 3
knit - b16 3
miss + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
miss + b27 3
knit - b27 3
miss + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
miss + b38 3
knit - b38 3
miss + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
miss + b49 3
knit - b49 3
miss + b49 3
knit + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
knit + b59 3
miss + b60 3
knit - b60 3
miss + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
miss + b71 3
knit - b71 3
miss + b71 3
knit + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
knit + b81 3
miss + b82 3
knit - b82 3
miss + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b50 f50
xfer b59 f59
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b72 f72
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b5 f5
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
xfer f6 b7
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
xfer f15 b14
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
rack -1;Rack to -1 at 1 gauge
xfer b14 f13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
rack -1;Rack to -1 at 1 gauge
xfer f29 b30
xfer f28 b29
xfer f27 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
rack 1;Rack to 1 at 1 gauge
xfer b29 f30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
xfer f37 b36
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
rack -1;Rack to -1 at 1 gauge
xfer b36 f35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
rack -1;Rack to -1 at 1 gauge
xfer f51 b52
xfer f50 b51
xfer f49 b50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b52 f52
rack 1;Rack to 1 at 1 gauge
xfer b51 f52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
xfer f59 b58
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b57 f57
rack -1;Rack to -1 at 1 gauge
xfer b58 f57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
rack -1;Rack to -1 at 1 gauge
xfer f73 b74
xfer f72 b73
xfer f71 b72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b74 f74
rack 1;Rack to 1 at 1 gauge
xfer b73 f74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
xfer f81 b80
xfer f80 b79
rack 0.0;Rack to 0.0 at 1 gauge
xfer b79 f79
rack -1;Rack to -1 at 1 gauge
xfer b80 f79
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
tuck - f82 3
miss - b81 3
knit + b81 3
miss - b81 3
tuck - f80 3
knit - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
knit - f74 3
tuck - f73 3
miss - b72 3
knit + b72 3
miss - b72 3
tuck - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
tuck - f60 3
miss - b59 3
knit + b59 3
miss - b59 3
tuck - f58 3
knit - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
knit - f52 3
tuck - f51 3
miss - b50 3
knit + b50 3
miss - b50 3
tuck - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
tuck - f38 3
miss - b37 3
knit + b37 3
miss - b37 3
tuck - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
tuck - f29 3
miss - b28 3
knit + b28 3
miss - b28 3
tuck - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
tuck - f16 3
miss - b15 3
knit + b15 3
miss - b15 3
tuck - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
tuck - f7 3
miss - b6 3
knit + b6 3
miss - b6 3
tuck - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f51 b51
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f58 b58
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f73 b73
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f80 b80
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
miss + b6 3
knit - b6 3
miss + b6 3
knit + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
miss + b15 3
knit - b15 3
miss + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
miss + b28 3
knit - b28 3
miss + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
miss + b37 3
knit - b37 3
miss + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
miss + b50 3
knit - b50 3
miss + b50 3
knit + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
knit + b58 3
miss + b59 3
knit - b59 3
miss + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
miss + b72 3
knit - b72 3
miss + b72 3
knit + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
knit + b80 3
miss + b81 3
knit - b81 3
miss + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b51 f51
xfer b58 f58
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b73 f73
xfer b80 f80
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b6 f6
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
xfer f7 b8
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
rack 1;Rack to 1 at 1 gauge
xfer b8 f9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
xfer f14 b13
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
rack -1;Rack to -1 at 1 gauge
xfer b13 f12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
xfer f29 b30
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
rack 1;Rack to 1 at 1 gauge
xfer b30 f31
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
xfer f36 b35
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
rack -1;Rack to -1 at 1 gauge
xfer b35 f34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
rack -1;Rack to -1 at 1 gauge
xfer f52 b53
xfer f51 b52
xfer f50 b51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b53 f53
rack 1;Rack to 1 at 1 gauge
xfer b52 f53
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
xfer f58 b57
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b56 f56
rack -1;Rack to -1 at 1 gauge
xfer b57 f56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
rack -1;Rack to -1 at 1 gauge
xfer f74 b75
xfer f73 b74
xfer f72 b73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b75 f75
rack 1;Rack to 1 at 1 gauge
xfer b74 f75
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
rack 1;Rack to 1 at 1 gauge
xfer f81 b80
xfer f80 b79
xfer f79 b78
rack 0.0;Rack to 0.0 at 1 gauge
xfer b78 f78
rack -1;Rack to -1 at 1 gauge
xfer b79 f78
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
tuck - f81 3
miss - b80 3
knit + b80 3
miss - b80 3
tuck - f79 3
knit - f78 3
knit - f77 3
knit - f76 3
knit - f75 3
tuck - f74 3
miss - b73 3
knit + b73 3
miss - b73 3
tuck - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
tuck - f59 3
miss - b58 3
knit + b58 3
miss - b58 3
tuck - f57 3
knit - f56 3
knit - f55 3
knit - f54 3
knit - f53 3
tuck - f52 3
miss - b51 3
knit + b51 3
miss - b51 3
tuck - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
tuck - f37 3
miss - b36 3
knit + b36 3
miss - b36 3
tuck - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
tuck - f30 3
miss - b29 3
knit + b29 3
miss - b29 3
tuck - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
tuck - f15 3
miss - b14 3
knit + b14 3
miss - b14 3
tuck - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
tuck - f8 3
miss - b7 3
knit + b7 3
miss - b7 3
tuck - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f52 b52
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f57 b57
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f74 b74
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f79 b79
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
miss + b7 3
knit - b7 3
miss + b7 3
knit + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
knit + b13 3
miss + b14 3
knit - b14 3
miss + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
miss + b29 3
knit - b29 3
miss + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
miss + b36 3
knit - b36 3
miss + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
miss + b51 3
knit - b51 3
miss + b51 3
knit + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
knit + b57 3
miss + b58 3
knit - b58 3
miss + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
miss + b73 3
knit - b73 3
miss + b73 3
knit + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
knit + b79 3
miss + b80 3
knit - b80 3
miss + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b52 f52
xfer b57 f57
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b74 f74
xfer b79 f79
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b7 f7
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
xfer f8 b9
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
rack 1;Rack to 1 at 1 gauge
xfer b9 f10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
xfer f13 b12
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
rack -1;Rack to -1 at 1 gauge
xfer b12 f11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
rack -1;Rack to -1 at 1 gauge
xfer f31 b32
xfer f30 b31
xfer f29 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
rack 1;Rack to 1 at 1 gauge
xfer b31 f32
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
xfer f35 b34
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
rack -1;Rack to -1 at 1 gauge
xfer b34 f33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
rack -1;Rack to -1 at 1 gauge
xfer f53 b54
xfer f52 b53
xfer f51 b52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b54 f54
rack 1;Rack to 1 at 1 gauge
xfer b53 f54
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
xfer f57 b56
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b55 f55
rack -1;Rack to -1 at 1 gauge
xfer b56 f55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
rack -1;Rack to -1 at 1 gauge
xfer f75 b76
xfer f74 b75
xfer f73 b74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b76 f76
rack 1;Rack to 1 at 1 gauge
xfer b75 f76
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
rack 1;Rack to 1 at 1 gauge
xfer f80 b79
xfer f79 b78
xfer f78 b77
rack 0.0;Rack to 0.0 at 1 gauge
xfer b77 f77
rack -1;Rack to -1 at 1 gauge
xfer b78 f77
rack 0.0;Rack to 0.0 at 1 gauge
knit - f87 3
knit - f86 3
knit - f85 3
knit - f84 3
knit - f83 3
knit - f82 3
knit - f81 3
tuck - f80 3
miss - b79 3
knit + b79 3
miss - b79 3
tuck - f78 3
knit - f77 3
knit - f76 3
tuck - f75 3
miss - b74 3
knit + b74 3
miss - b74 3
tuck - f73 3
knit - f72 3
knit - f71 3
knit - f70 3
knit - f69 3
knit - f68 3
knit - f67 3
knit - f66 3
knit - f65 3
knit - f64 3
knit - f63 3
knit - f62 3
knit - f61 3
knit - f60 3
knit - f59 3
tuck - f58 3
miss - b57 3
knit + b57 3
miss - b57 3
tuck - f56 3
knit - f55 3
knit - f54 3
tuck - f53 3
miss - b52 3
knit + b52 3
miss - b52 3
tuck - f51 3
knit - f50 3
knit - f49 3
knit - f48 3
knit - f47 3
knit - f46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - f39 3
knit - f38 3
knit - f37 3
tuck - f36 3
miss - b35 3
knit + b35 3
miss - b35 3
tuck - f34 3
knit - f33 3
knit - f32 3
tuck - f31 3
miss - b30 3
knit + b30 3
miss - b30 3
tuck - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
tuck - f14 3
miss - b13 3
knit + b13 3
miss - b13 3
tuck - f12 3
knit - f11 3
knit - f10 3
tuck - f9 3
miss - b8 3
knit + b8 3
miss - b8 3
tuck - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
xfer f44 b44
xfer f45 b45
xfer f46 b46
xfer f47 b47
xfer f48 b48
xfer f49 b49
xfer f50 b50
xfer f51 b51
xfer f53 b53
xfer f54 b54
xfer f55 b55
xfer f56 b56
xfer f58 b58
xfer f59 b59
xfer f60 b60
xfer f61 b61
xfer f62 b62
xfer f63 b63
xfer f64 b64
xfer f65 b65
xfer f66 b66
xfer f67 b67
xfer f68 b68
xfer f69 b69
xfer f70 b70
xfer f71 b71
xfer f72 b72
xfer f73 b73
xfer f75 b75
xfer f76 b76
xfer f77 b77
xfer f78 b78
xfer f80 b80
xfer f81 b81
xfer f82 b82
xfer f83 b83
xfer f84 b84
xfer f85 b85
xfer f86 b86
xfer f87 b87
knit + b0 3
knit + b1 3
knit + b2 3
knit + b3 3
knit + b4 3
knit + b5 3
knit + b6 3
knit + b7 3
miss + b8 3
knit - b8 3
miss + b8 3
knit + b9 3
knit + b10 3
knit + b11 3
knit + b12 3
miss + b13 3
knit - b13 3
miss + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
miss + b30 3
knit - b30 3
miss + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
miss + b35 3
knit - b35 3
miss + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
knit + b40 3
knit + b41 3
knit + b42 3
knit + b43 3
knit + b44 3
knit + b45 3
knit + b46 3
knit + b47 3
knit + b48 3
knit + b49 3
knit + b50 3
knit + b51 3
miss + b52 3
knit - b52 3
miss + b52 3
knit + b53 3
knit + b54 3
knit + b55 3
knit + b56 3
miss + b57 3
knit - b57 3
miss + b57 3
knit + b58 3
knit + b59 3
knit + b60 3
knit + b61 3
knit + b62 3
knit + b63 3
knit + b64 3
knit + b65 3
knit + b66 3
knit + b67 3
knit + b68 3
knit + b69 3
knit + b70 3
knit + b71 3
knit + b72 3
knit + b73 3
miss + b74 3
knit - b74 3
miss + b74 3
knit + b75 3
knit + b76 3
knit + b77 3
knit + b78 3
miss + b79 3
knit - b79 3
miss + b79 3
knit + b80 3
knit + b81 3
knit + b82 3
knit + b83 3
knit + b84 3
knit + b85 3
knit + b86 3
knit + b87 3
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b10 f10
xfer b9 f9
xfer b12 f12
xfer b11 f11
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b32 f32
xfer b31 f31
xfer b34 f34
xfer b33 f33
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b51 f51
xfer b50 f50
xfer b49 f49
xfer b48 f48
xfer b47 f47
xfer b46 f46
xfer b45 f45
xfer b44 f44
xfer b54 f54
xfer b53 f53
xfer b56 f56
xfer b55 f55
xfer b65 f65
xfer b64 f64
xfer b63 f63
xfer b62 f62
xfer b61 f61
xfer b60 f60
xfer b59 f59
xfer b58 f58
xfer b73 f73
xfer b72 f72
xfer b71 f71
xfer b70 f70
xfer b69 f69
xfer b68 f68
xfer b67 f67
xfer b66 f66
xfer b76 f76
xfer b75 f75
xfer b78 f78
xfer b77 f77
xfer b87 f87
xfer b86 f86
xfer b85 f85
xfer b84 f84
xfer b83 f83
xfer b82 f82
xfer b81 f81
xfer b80 f80
xfer b79 f79
xfer b74 f74
xfer b57 f57
xfer b52 f52
xfer b35 f35
xfer b30 f30
xfer b13 f13
xfer b8 f8
rack 1;Rack to 1 at 1 gauge
xfer f87 b86
rack 0.0;Rack to 0.0 at 1 gauge
xfer b86 f86
knit - f86 3
rack 1;Rack to 1 at 1 gauge
xfer f86 b85
rack 0.0;Rack to 0.0 at 1 gauge
xfer b85 f85
knit - f85 3
rack 1;Rack to 1 at 1 gauge
xfer f85 b84
rack 0.0;Rack to 0.0 at 1 gauge
xfer b84 f84
knit - f84 3
rack 1;Rack to 1 at 1 gauge
xfer f84 b83
rack 0.0;Rack to 0.0 at 1 gauge
xfer b83 f83
knit - f83 3
rack 1;Rack to 1 at 1 gauge
xfer f83 b82
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
knit - f82 3
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
rack 0.0;Rack to 0.0 at 1 gauge
xfer b81 f81
knit - f81 3
rack 1;Rack to 1 at 1 gauge
xfer f81 b80
rack 0.0;Rack to 0.0 at 1 gauge
xfer b80 f80
knit - f80 3
rack 1;Rack to 1 at 1 gauge
xfer f80 b79
rack 0.0;Rack to 0.0 at 1 gauge
xfer b79 f79
knit - f79 3
rack 1;Rack to 1 at 1 gauge
xfer f79 b78
rack 0.0;Rack to 0.0 at 1 gauge
xfer b78 f78
knit - f78 3
rack 1;Rack to 1 at 1 gauge
xfer f78 b77
rack 0.0;Rack to 0.0 at 1 gauge
xfer b77 f77
knit - f77 3
rack 1;Rack to 1 at 1 gauge
xfer f77 b76
rack 0.0;Rack to 0.0 at 1 gauge
xfer b76 f76
knit - f76 3
rack 1;Rack to 1 at 1 gauge
xfer f76 b75
rack 0.0;Rack to 0.0 at 1 gauge
xfer b75 f75
knit - f75 3
rack 1;Rack to 1 at 1 gauge
xfer f75 b74
rack 0.0;Rack to 0.0 at 1 gauge
xfer b74 f74
knit - f74 3
rack 1;Rack to 1 at 1 gauge
xfer f74 b73
rack 0.0;Rack to 0.0 at 1 gauge
xfer b73 f73
knit - f73 3
rack 1;Rack to 1 at 1 gauge
xfer f73 b72
rack 0.0;Rack to 0.0 at 1 gauge
xfer b72 f72
knit - f72 3
rack 1;Rack to 1 at 1 gauge
xfer f72 b71
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
knit - f71 3
rack 1;Rack to 1 at 1 gauge
xfer f71 b70
rack 0.0;Rack to 0.0 at 1 gauge
xfer b70 f70
knit - f70 3
rack 1;Rack to 1 at 1 gauge
xfer f70 b69
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
knit - f69 3
rack 1;Rack to 1 at 1 gauge
xfer f69 b68
rack 0.0;Rack to 0.0 at 1 gauge
xfer b68 f68
knit - f68 3
rack 1;Rack to 1 at 1 gauge
xfer f68 b67
rack 0.0;Rack to 0.0 at 1 gauge
xfer b67 f67
knit - f67 3
rack 1;Rack to 1 at 1 gauge
xfer f67 b66
rack 0.0;Rack to 0.0 at 1 gauge
xfer b66 f66
knit - f66 3
rack 1;Rack to 1 at 1 gauge
xfer f66 b65
rack 0.0;Rack to 0.0 at 1 gauge
xfer b65 f65
knit - f65 3
rack 1;Rack to 1 at 1 gauge
xfer f65 b64
rack 0.0;Rack to 0.0 at 1 gauge
xfer b64 f64
knit - f64 3
rack 1;Rack to 1 at 1 gauge
xfer f64 b63
rack 0.0;Rack to 0.0 at 1 gauge
xfer b63 f63
knit - f63 3
rack 1;Rack to 1 at 1 gauge
xfer f63 b62
rack 0.0;Rack to 0.0 at 1 gauge
xfer b62 f62
knit - f62 3
rack 1;Rack to 1 at 1 gauge
xfer f62 b61
rack 0.0;Rack to 0.0 at 1 gauge
xfer b61 f61
knit - f61 3
rack 1;Rack to 1 at 1 gauge
xfer f61 b60
rack 0.0;Rack to 0.0 at 1 gauge
xfer b60 f60
knit - f60 3
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
xfer b59 f59
knit - f59 3
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
xfer b58 f58
knit - f58 3
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
xfer b57 f57
knit - f57 3
rack 1;Rack to 1 at 1 gauge
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
xfer b56 f56
knit - f56 3
rack 1;Rack to 1 at 1 gauge
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
xfer b55 f55
knit - f55 3
rack 1;Rack to 1 at 1 gauge
xfer f55 b54
rack 0.0;Rack to 0.0 at 1 gauge
xfer b54 f54
knit - f54 3
rack 1;Rack to 1 at 1 gauge
xfer f54 b53
rack 0.0;Rack to 0.0 at 1 gauge
xfer b53 f53
knit - f53 3
rack 1;Rack to 1 at 1 gauge
xfer f53 b52
rack 0.0;Rack to 0.0 at 1 gauge
xfer b52 f52
knit - f52 3
rack 1;Rack to 1 at 1 gauge
xfer f52 b51
rack 0.0;Rack to 0.0 at 1 gauge
xfer b51 f51
knit - f51 3
rack 1;Rack to 1 at 1 gauge
xfer f51 b50
rack 0.0;Rack to 0.0 at 1 gauge
xfer b50 f50
knit - f50 3
rack 1;Rack to 1 at 1 gauge
xfer f50 b49
rack 0.0;Rack to 0.0 at 1 gauge
xfer b49 f49
knit - f49 3
rack 1;Rack to 1 at 1 gauge
xfer f49 b48
rack 0.0;Rack to 0.0 at 1 gauge
xfer b48 f48
knit - f48 3
rack 1;Rack to 1 at 1 gauge
xfer f48 b47
rack 0.0;Rack to 0.0 at 1 gauge
xfer b47 f47
knit - f47 3
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
rack 0.0;Rack to 0.0 at 1 gauge
xfer b46 f46
knit - f46 3
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
rack 0.0;Rack to 0.0 at 1 gauge
xfer b45 f45
knit - f45 3
rack 1;Rack to 1 at 1 gauge
xfer f45 b44
rack 0.0;Rack to 0.0 at 1 gauge
xfer b44 f44
knit - f44 3
rack 1;Rack to 1 at 1 gauge
xfer f44 b43
rack 0.0;Rack to 0.0 at 1 gauge
xfer b43 f43
knit - f43 3
rack 1;Rack to 1 at 1 gauge
xfer f43 b42
rack 0.0;Rack to 0.0 at 1 gauge
xfer b42 f42
knit - f42 3
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
rack 0.0;Rack to 0.0 at 1 gauge
xfer b41 f41
knit - f41 3
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
rack 0.0;Rack to 0.0 at 1 gauge
xfer b40 f40
knit - f40 3
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
xfer b39 f39
knit - f39 3
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
xfer b38 f38
knit - f38 3
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
xfer b37 f37
knit - f37 3
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
xfer b36 f36
knit - f36 3
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
xfer b35 f35
knit - f35 3
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
knit - f34 3
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
xfer b33 f33
knit - f33 3
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
xfer b32 f32
knit - f32 3
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
xfer b31 f31
knit - f31 3
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
knit - f30 3
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
knit - f29 3
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
knit - f28 3
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
knit - f27 3
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
knit - f26 3
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
knit - f25 3
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
knit - f24 3
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
knit - f23 3
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
xfer b22 f22
knit - f22 3
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit - f21 3
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
knit - f20 3
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
knit - f19 3
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
knit - f18 3
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
knit - f17 3
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
knit - f16 3
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
knit - f15 3
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
knit - f14 3
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
knit - f13 3
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
knit - f12 3
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
knit - f11 3
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
knit - f10 3
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
knit - f9 3
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
knit - f8 3
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
knit - f7 3
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
knit - f6 3
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
knit - f5 3
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f4 3
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
knit - f3 3
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
knit - f2 3
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit - f1 3
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
knit - f0 3
;KS: Spare knitting on [f0]
knit + f0 3
outhook 3;Cutting active yarn on 3
