;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 4;Activating carrier 4
miss - f29 4
tuck + f29 4
miss - f29 4
miss - f28 4
tuck + f28 4
miss - f28 4
miss - f27 4
tuck + f27 4
miss - f27 4
miss - f26 4
tuck + f26 4
miss - f26 4
miss - f25 4
tuck + f25 4
miss - f25 4
miss - f24 4
tuck + f24 4
miss - f24 4
miss - f23 4
tuck + f23 4
miss - f23 4
miss - f22 4
tuck + f22 4
miss - f22 4
miss - f21 4
tuck + f21 4
miss - f21 4
miss - f20 4
tuck + f20 4
miss - f20 4
miss - f19 4
tuck + f19 4
miss - f19 4
miss - f18 4
tuck + f18 4
miss - f18 4
miss - f17 4
tuck + f17 4
miss - f17 4
miss - f16 4
tuck + f16 4
miss - f16 4
miss - f15 4
tuck + f15 4
miss - f15 4
miss - f14 4
tuck + f14 4
miss - f14 4
miss - f13 4
tuck + f13 4
miss - f13 4
miss - f12 4
tuck + f12 4
miss - f12 4
miss - f11 4
tuck + f11 4
miss - f11 4
miss - f10 4
tuck + f10 4
miss - f10 4
miss - f9 4
tuck + f9 4
miss - f9 4
miss - f8 4
tuck + f8 4
miss - f8 4
miss - f7 4
tuck + f7 4
miss - f7 4
miss - f6 4
tuck + f6 4
miss - f6 4
miss - f5 4
tuck + f5 4
miss - f5 4
miss - f4 4
tuck + f4 4
miss - f4 4
miss - f3 4
tuck + f3 4
miss - f3 4
miss - f2 4
tuck + f2 4
miss - f2 4
miss - f1 4
tuck + f1 4
miss - f1 4
miss - f0 4
tuck + f0 4
miss - f0 4
;KS: Cast on 30loops from f29to f0
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
releasehook 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
;no-op. Releasehook with no hooked carriers
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
;no-op. Releasehook with no hooked carriers
inhook 6;Activating carrier 6
miss - b59 6
tuck + b59 6
miss - b59 6
miss - b58 6
tuck + b58 6
miss - b58 6
miss - b57 6
tuck + b57 6
miss - b57 6
miss - b56 6
tuck + b56 6
miss - b56 6
miss - b55 6
tuck + b55 6
miss - b55 6
miss - b54 6
tuck + b54 6
miss - b54 6
miss - b53 6
tuck + b53 6
miss - b53 6
miss - b52 6
tuck + b52 6
miss - b52 6
miss - b51 6
tuck + b51 6
miss - b51 6
miss - b50 6
tuck + b50 6
miss - b50 6
miss - b49 6
tuck + b49 6
miss - b49 6
miss - b48 6
tuck + b48 6
miss - b48 6
miss - b47 6
tuck + b47 6
miss - b47 6
miss - b46 6
tuck + b46 6
miss - b46 6
miss - b45 6
tuck + b45 6
miss - b45 6
miss - b44 6
tuck + b44 6
miss - b44 6
miss - b43 6
tuck + b43 6
miss - b43 6
miss - b42 6
tuck + b42 6
miss - b42 6
miss - b41 6
tuck + b41 6
miss - b41 6
miss - b40 6
tuck + b40 6
miss - b40 6
miss - b39 6
tuck + b39 6
miss - b39 6
miss - b38 6
tuck + b38 6
miss - b38 6
miss - b37 6
tuck + b37 6
miss - b37 6
miss - b36 6
tuck + b36 6
miss - b36 6
miss - b35 6
tuck + b35 6
miss - b35 6
miss - b34 6
tuck + b34 6
miss - b34 6
miss - b33 6
tuck + b33 6
miss - b33 6
miss - b32 6
tuck + b32 6
miss - b32 6
miss - b31 6
tuck + b31 6
miss - b31 6
miss - b30 6
tuck + b30 6
miss - b30 6
miss - b29 6
tuck + b29 6
miss - b29 6
miss - b28 6
tuck + b28 6
miss - b28 6
miss - b27 6
tuck + b27 6
miss - b27 6
miss - b26 6
tuck + b26 6
miss - b26 6
miss - b25 6
tuck + b25 6
miss - b25 6
miss - b24 6
tuck + b24 6
miss - b24 6
miss - b23 6
tuck + b23 6
miss - b23 6
miss - b22 6
tuck + b22 6
miss - b22 6
miss - b21 6
tuck + b21 6
miss - b21 6
miss - b20 6
tuck + b20 6
miss - b20 6
miss - b19 6
tuck + b19 6
miss - b19 6
miss - b18 6
tuck + b18 6
miss - b18 6
miss - b17 6
tuck + b17 6
miss - b17 6
miss - b16 6
tuck + b16 6
miss - b16 6
miss - b15 6
tuck + b15 6
miss - b15 6
;KS: Cast on 75loops from b59to b15
knit + b15 6
knit + b16 6
knit + b17 6
knit + b18 6
knit + b19 6
knit + b20 6
knit + b21 6
knit + b22 6
knit + b23 6
knit + b24 6
knit + b25 6
knit + b26 6
knit + b27 6
knit + b28 6
knit + b29 6
knit + b30 6
knit + b31 6
knit + b32 6
knit + b33 6
knit + b34 6
knit + b35 6
knit + b36 6
knit + b37 6
knit + b38 6
knit + b39 6
knit + b40 6
knit + b41 6
knit + b42 6
knit + b43 6
knit + b44 6
knit + b45 6
knit + b46 6
knit + b47 6
knit + b48 6
knit + b49 6
knit + b50 6
knit + b51 6
knit + b52 6
knit + b53 6
knit + b54 6
knit + b55 6
knit + b56 6
knit + b57 6
knit + b58 6
knit + b59 6
releasehook 6
knit - b59 6
knit - b58 6
knit - b57 6
knit - b56 6
knit - b55 6
knit - b54 6
knit - b53 6
knit - b52 6
knit - b51 6
knit - b50 6
knit - b49 6
knit - b48 6
knit - b47 6
knit - b46 6
knit - b45 6
knit - b44 6
knit - b43 6
knit - b42 6
knit - b41 6
knit - b40 6
knit - b39 6
knit - b38 6
knit - b37 6
knit - b36 6
knit - b35 6
knit - b34 6
knit - b33 6
knit - b32 6
knit - b31 6
knit - b30 6
knit - b29 6
knit - b28 6
knit - b27 6
knit - b26 6
knit - b25 6
knit - b24 6
knit - b23 6
knit - b22 6
knit - b21 6
knit - b20 6
knit - b19 6
knit - b18 6
knit - b17 6
knit - b16 6
knit - b15 6
;no-op. Releasehook with no hooked carriers
;no-op. Releasehook with no hooked carriers
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b11 6
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
xfer b13 f13
drop b11
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b20 6
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
drop b20
xfer b18 f18
xfer b19 f19
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
drop b15
drop b16
drop b17
drop b21
drop b22
drop b23
drop b24
drop b25
drop b26
drop b27
drop b28
drop b29
drop b30
drop b31
drop b32
drop b33
drop b34
drop b35
drop b36
drop b37
drop b38
drop b39
drop b40
drop b41
drop b42
drop b43
drop b44
drop b45
drop b46
drop b47
drop b48
drop b49
drop b50
drop b51
drop b52
drop b53
drop b54
drop b55
drop b56
drop b57
drop b58
drop b59
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b11 6
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
xfer b13 f13
drop b11
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b20 6
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
drop b20
xfer b18 f18
xfer b19 f19
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b11 6
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
xfer b13 f13
drop b11
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b20 6
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
drop b20
xfer b18 f18
xfer b19 f19
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
rack -1;Rack to -1 at 1 gauge
xfer f0 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit + f1 4
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
knit + f2 4
rack -1;Rack to -1 at 1 gauge
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
knit + f3 4
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit + f4 4
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
knit + f5 4
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
knit + f6 4
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
knit + f7 4
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
knit + f8 4
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
knit + f9 4
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
knit + f10 4
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
knit + f11 4
rack -1;Rack to -1 at 1 gauge
xfer f11 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
knit + f12 4
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
knit + f13 4
rack -1;Rack to -1 at 1 gauge
xfer f13 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
knit + f14 4
rack -1;Rack to -1 at 1 gauge
xfer f14 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
knit + f15 4
rack -1;Rack to -1 at 1 gauge
xfer f15 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
knit + f16 4
rack -1;Rack to -1 at 1 gauge
xfer f16 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
knit + f17 4
rack -1;Rack to -1 at 1 gauge
xfer f17 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
knit + f18 4
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
knit + f19 4
rack -1;Rack to -1 at 1 gauge
xfer f19 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
knit + f20 4
rack -1;Rack to -1 at 1 gauge
xfer f20 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit + f21 4
rack -1;Rack to -1 at 1 gauge
xfer f21 b22
rack 0.0;Rack to 0.0 at 1 gauge
xfer b22 f22
knit + f22 4
rack -1;Rack to -1 at 1 gauge
xfer f22 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
knit + f23 4
rack -1;Rack to -1 at 1 gauge
xfer f23 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
knit + f24 4
rack -1;Rack to -1 at 1 gauge
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
knit + f25 4
rack -1;Rack to -1 at 1 gauge
xfer f25 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
knit + f26 4
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
knit + f27 4
rack -1;Rack to -1 at 1 gauge
xfer f27 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
knit + f28 4
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
knit + f29 4
;KS: Spare knitting on [f29]
knit - f29 4
outhook 4;Cutting active yarn on 4
outhook 6;Cutting active yarn on 6
