;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 45loops from 0to 45
tuck - f44 1
tuck - f42 1
tuck - f40 1
tuck - f38 1
tuck - f36 1
tuck - f34 1
tuck - f32 1
tuck - f30 1
tuck - f28 1
tuck - f26 1
tuck - f24 1
tuck - f22 1
tuck - f20 1
tuck - f18 1
tuck - f16 1
tuck - f14 1
tuck - f12 1
tuck - f10 1
tuck - f8 1
tuck - f6 1
tuck - f4 1
tuck - f2 1
tuck - f0 1
tuck + f1 1
tuck + f3 1
tuck + f5 1
tuck + f7 1
tuck + f9 1
tuck + f11 1
tuck + f13 1
tuck + f15 1
tuck + f17 1
tuck + f19 1
tuck + f21 1
tuck + f23 1
tuck + f25 1
tuck + f27 1
tuck + f29 1
tuck + f31 1
tuck + f33 1
tuck + f35 1
tuck + f37 1
tuck + f39 1
tuck + f41 1
tuck + f43 1
tuck - f44 1
tuck - f42 1
tuck - f40 1
tuck - f38 1
tuck - f36 1
tuck - f34 1
tuck - f32 1
tuck - f30 1
tuck - f28 1
tuck - f26 1
tuck - f24 1
tuck - f22 1
tuck - f20 1
tuck - f18 1
tuck - f16 1
tuck - f14 1
tuck - f12 1
tuck - f10 1
tuck - f8 1
tuck - f6 1
tuck - f4 1
tuck - f2 1
tuck - f0 1
tuck + f1 1
tuck + f3 1
tuck + f5 1
tuck + f7 1
tuck + f9 1
tuck + f11 1
tuck + f13 1
tuck + f15 1
tuck + f17 1
tuck + f19 1
tuck + f21 1
tuck + f23 1
tuck + f25 1
tuck + f27 1
tuck + f29 1
tuck + f31 1
tuck + f33 1
tuck + f35 1
tuck + f37 1
tuck + f39 1
tuck + f41 1
tuck + f43 1
releasehook 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
drop f30
drop f31
drop f32
drop f33
drop f34
drop f35
drop f36
drop f37
drop f38
drop f39
drop f40
drop f41
drop f42
drop f43
drop f44
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
;KS: Cast on 30loops from 0to 30
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
;no-op. Releasehook with no hooked carriers
drop b0
drop b1
drop b2
drop b3
drop b4
drop b5
drop b6
drop b7
drop b8
drop b9
drop b10
drop b11
drop b12
drop b13
drop b14
drop b15
drop b16
drop b17
drop b18
drop b19
drop b20
drop b21
drop b22
drop b23
drop b24
drop b25
drop b26
drop b27
drop b28
drop b29
outhook 1
inhook 4;Activating carrier 4
tuck - f29 4
miss + f29 4
tuck - f29 4
miss - f28 4
tuck + f28 4
miss - f28 4
miss - f27 4
tuck + f27 4
miss - f27 4
miss - f26 4
tuck + f26 4
miss - f26 4
miss - f25 4
tuck + f25 4
miss - f25 4
miss - f24 4
tuck + f24 4
miss - f24 4
miss - f23 4
tuck + f23 4
miss - f23 4
miss - f22 4
tuck + f22 4
miss - f22 4
miss - f21 4
tuck + f21 4
miss - f21 4
miss - f20 4
tuck + f20 4
miss - f20 4
miss - f19 4
tuck + f19 4
miss - f19 4
miss - f18 4
tuck + f18 4
miss - f18 4
miss - f17 4
tuck + f17 4
miss - f17 4
miss - f16 4
tuck + f16 4
miss - f16 4
miss - f15 4
tuck + f15 4
miss - f15 4
miss - f14 4
tuck + f14 4
miss - f14 4
miss - f13 4
tuck + f13 4
miss - f13 4
miss - f12 4
tuck + f12 4
miss - f12 4
miss - f11 4
tuck + f11 4
miss - f11 4
miss - f10 4
tuck + f10 4
miss - f10 4
miss - f9 4
tuck + f9 4
miss - f9 4
miss - f8 4
tuck + f8 4
miss - f8 4
miss - f7 4
tuck + f7 4
miss - f7 4
miss - f6 4
tuck + f6 4
miss - f6 4
miss - f5 4
tuck + f5 4
miss - f5 4
miss - f4 4
tuck + f4 4
miss - f4 4
miss - f3 4
tuck + f3 4
miss - f3 4
miss - f2 4
tuck + f2 4
miss - f2 4
miss - f1 4
tuck + f1 4
miss - f1 4
miss - f0 4
tuck + f0 4
miss - f0 4
;KS: Cast on 30loops from f29to f0
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
releasehook 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 4
knit - f28 4
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 4
knit - f27 4
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 4
knit - f26 4
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
split + b25 f25 4
knit - f25 4
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
split + b24 f24 4
knit - f24 4
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 4
knit - f23 4
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 4
knit - f22 4
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 4
knit - f21 4
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
split + b20 f20 4
knit - f20 4
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
split + b19 f19 4
knit - f19 4
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 4
knit - f18 4
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 4
knit - f17 4
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 4
knit - f16 4
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
split + b15 f15 4
knit - f15 4
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
split + b14 f14 4
knit - f14 4
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 4
knit - f13 4
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 4
knit - f12 4
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 4
knit - f11 4
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
split + b10 f10 4
knit - f10 4
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
split + b9 f9 4
knit - f9 4
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 4
knit - f8 4
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 4
knit - f7 4
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 4
knit - f6 4
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 4
knit - f5 4
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 4
knit - f4 4
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 4
knit - f3 4
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 4
knit - f2 4
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 4
knit - f1 4
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 4
knit - f0 4
;KS: Spare knitting on [b28, b27, b26, b25, b24, b23, b22, b21, b20, b19, b18, b17, b16, b15, b14, b13, b12, b11, b10, b9, b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 4
knit + b1 4
knit + b2 4
knit + b3 4
knit + b4 4
knit + b5 4
knit + b6 4
knit + b7 4
knit + b8 4
knit + b9 4
knit + b10 4
knit + b11 4
knit + b12 4
knit + b13 4
knit + b14 4
knit + b15 4
knit + b16 4
knit + b17 4
knit + b18 4
knit + b19 4
knit + b20 4
knit + b21 4
knit + b22 4
knit + b23 4
knit + b24 4
knit + b25 4
knit + b26 4
knit + b27 4
knit + b28 4
outhook 4;Cutting active yarn on 4
