;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 76loops from 0to 76
tuck - f75 1
tuck - f73 1
tuck - f71 1
tuck - f69 1
tuck - f67 1
tuck - f65 1
tuck - f63 1
tuck - f61 1
tuck - f59 1
tuck - f57 1
tuck - f55 1
tuck - f53 1
tuck - f51 1
tuck - f49 1
tuck - f47 1
tuck - f45 1
tuck - f43 1
tuck - f41 1
tuck - f39 1
tuck - f37 1
tuck - f35 1
tuck - f33 1
tuck - f31 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
tuck + f44 1
tuck + f46 1
tuck + f48 1
tuck + f50 1
tuck + f52 1
tuck + f54 1
tuck + f56 1
tuck + f58 1
tuck + f60 1
tuck + f62 1
tuck + f64 1
tuck + f66 1
tuck + f68 1
tuck + f70 1
tuck + f72 1
tuck + f74 1
tuck - f75 1
tuck - f73 1
tuck - f71 1
tuck - f69 1
tuck - f67 1
tuck - f65 1
tuck - f63 1
tuck - f61 1
tuck - f59 1
tuck - f57 1
tuck - f55 1
tuck - f53 1
tuck - f51 1
tuck - f49 1
tuck - f47 1
tuck - f45 1
tuck - f43 1
tuck - f41 1
tuck - f39 1
tuck - f37 1
tuck - f35 1
tuck - f33 1
tuck - f31 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
tuck + f44 1
tuck + f46 1
tuck + f48 1
tuck + f50 1
tuck + f52 1
tuck + f54 1
tuck + f56 1
tuck + f58 1
tuck + f60 1
tuck + f62 1
tuck + f64 1
tuck + f66 1
tuck + f68 1
tuck + f70 1
tuck + f72 1
tuck + f74 1
releasehook 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
xfer f70 b70
xfer f65 b65
xfer f60 b60
xfer f55 b55
xfer f50 b50
xfer f45 b45
xfer f40 b40
xfer f35 b35
xfer f30 b30
xfer f25 b25
xfer f20 b20
xfer f15 b15
xfer f10 b10
xfer f5 b5
rack -1;Rack to -1 at 1 gauge
xfer b70 f69
xfer b65 f64
xfer b60 f59
xfer b55 f54
xfer b50 f49
xfer b45 f44
xfer b40 f39
xfer b35 f34
xfer b30 f29
xfer b25 f24
xfer b20 f19
xfer b15 f14
xfer b10 f9
xfer b5 f4
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f70 1
tuck - f65 1
tuck - f60 1
tuck - f55 1
tuck - f50 1
tuck - f45 1
tuck - f40 1
tuck - f35 1
tuck - f30 1
tuck - f25 1
tuck - f20 1
tuck - f15 1
tuck - f10 1
tuck - f5 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
xfer f70 b70
xfer f65 b65
xfer f60 b60
xfer f55 b55
xfer f50 b50
xfer f45 b45
xfer f40 b40
xfer f35 b35
xfer f30 b30
xfer f25 b25
xfer f20 b20
xfer f15 b15
xfer f10 b10
xfer f5 b5
rack 1;Rack to 1 at 1 gauge
xfer b70 f71
xfer b65 f66
xfer b60 f61
xfer b55 f56
xfer b50 f51
xfer b45 f46
xfer b40 f41
xfer b35 f36
xfer b30 f31
xfer b25 f26
xfer b20 f21
xfer b15 f16
xfer b10 f11
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f70 1
tuck - f65 1
tuck - f60 1
tuck - f55 1
tuck - f50 1
tuck - f45 1
tuck - f40 1
tuck - f35 1
tuck - f30 1
tuck - f25 1
tuck - f20 1
tuck - f15 1
tuck - f10 1
tuck - f5 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
rack 1;Rack to 1 at 1 gauge
xfer f70 b69
xfer f65 b64
xfer f60 b59
xfer f55 b54
xfer f50 b49
xfer f45 b44
xfer f40 b39
xfer f35 b34
xfer f30 b29
xfer f25 b24
xfer f20 b19
xfer f15 b14
xfer f10 b9
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer f69 b69
xfer f64 b64
xfer f59 b59
xfer f54 b54
xfer f49 b49
xfer f44 b44
xfer f39 b39
xfer f34 b34
xfer f29 b29
xfer f24 b24
xfer f19 b19
xfer f14 b14
xfer f9 b9
xfer f4 b4
tuck - f70 1
tuck - f65 1
tuck - f60 1
tuck - f55 1
tuck - f50 1
tuck - f45 1
tuck - f40 1
tuck - f35 1
tuck - f30 1
tuck - f25 1
tuck - f20 1
tuck - f15 1
tuck - f10 1
tuck - f5 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + b9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + b19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + b39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + b44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + b49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + b54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + b59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + b64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + b69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
xfer b69 f69
xfer b64 f64
xfer b59 f59
xfer b54 f54
xfer b49 f49
xfer b44 f44
xfer b39 f39
xfer b34 f34
xfer b29 f29
xfer b24 f24
xfer b19 f19
xfer b14 f14
xfer b9 f9
xfer b4 f4
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
rack -1;Rack to -1 at 1 gauge
xfer f70 b71
xfer f65 b66
xfer f60 b61
xfer f55 b56
xfer f50 b51
xfer f45 b46
xfer f40 b41
xfer f35 b36
xfer f30 b31
xfer f25 b26
xfer f20 b21
xfer f15 b16
xfer f10 b11
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
xfer b66 f66
xfer b61 f61
xfer b56 f56
xfer b51 f51
xfer b46 f46
xfer b41 f41
xfer b36 f36
xfer b31 f31
xfer b26 f26
xfer b21 f21
xfer b16 f16
xfer b11 f11
xfer b6 f6
rack -2;Rack to -2 at 1 gauge
xfer f69 b71
xfer f64 b66
xfer f59 b61
xfer f54 b56
xfer f49 b51
xfer f44 b46
xfer f39 b41
xfer f34 b36
xfer f29 b31
xfer f24 b26
xfer f19 b21
xfer f14 b16
xfer f9 b11
xfer f4 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b71 f71
xfer b66 f66
xfer b61 f61
xfer b56 f56
xfer b51 f51
xfer b46 f46
xfer b41 f41
xfer b36 f36
xfer b31 f31
xfer b26 f26
xfer b21 f21
xfer b16 f16
xfer b11 f11
xfer b6 f6
tuck - f70 1
tuck - f69 1
tuck - f65 1
tuck - f64 1
tuck - f60 1
tuck - f59 1
tuck - f55 1
tuck - f54 1
tuck - f50 1
tuck - f49 1
tuck - f45 1
tuck - f44 1
tuck - f40 1
tuck - f39 1
tuck - f35 1
tuck - f34 1
tuck - f30 1
tuck - f29 1
tuck - f25 1
tuck - f24 1
tuck - f20 1
tuck - f19 1
tuck - f15 1
tuck - f14 1
tuck - f10 1
tuck - f9 1
tuck - f5 1
tuck - f4 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
rack 1;Rack to 1 at 1 gauge
xfer f70 b69
xfer f65 b64
xfer f60 b59
xfer f55 b54
xfer f50 b49
xfer f45 b44
xfer f40 b39
xfer f35 b34
xfer f30 b29
xfer f25 b24
xfer f20 b19
xfer f15 b14
xfer f10 b9
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
xfer b64 f64
xfer b59 f59
xfer b54 f54
xfer b49 f49
xfer b44 f44
xfer b39 f39
xfer b34 f34
xfer b29 f29
xfer b24 f24
xfer b19 f19
xfer b14 f14
xfer b9 f9
xfer b4 f4
rack 2;Rack to 2 at 1 gauge
xfer f71 b69
xfer f66 b64
xfer f61 b59
xfer f56 b54
xfer f51 b49
xfer f46 b44
xfer f41 b39
xfer f36 b34
xfer f31 b29
xfer f26 b24
xfer f21 b19
xfer f16 b14
xfer f11 b9
xfer f6 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b69 f69
xfer b64 f64
xfer b59 f59
xfer b54 f54
xfer b49 f49
xfer b44 f44
xfer b39 f39
xfer b34 f34
xfer b29 f29
xfer b24 f24
xfer b19 f19
xfer b14 f14
xfer b9 f9
xfer b4 f4
tuck - f71 1
tuck - f70 1
tuck - f66 1
tuck - f65 1
tuck - f61 1
tuck - f60 1
tuck - f56 1
tuck - f55 1
tuck - f51 1
tuck - f50 1
tuck - f46 1
tuck - f45 1
tuck - f41 1
tuck - f40 1
tuck - f36 1
tuck - f35 1
tuck - f31 1
tuck - f30 1
tuck - f26 1
tuck - f25 1
tuck - f21 1
tuck - f20 1
tuck - f16 1
tuck - f15 1
tuck - f11 1
tuck - f10 1
tuck - f6 1
tuck - f5 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
knit - f75 1
knit - f74 1
knit - f73 1
knit - f72 1
knit - f71 1
knit - f70 1
knit - f69 1
knit - f68 1
knit - f67 1
knit - f66 1
knit - f65 1
knit - f64 1
knit - f63 1
knit - f62 1
knit - f61 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit + f61 1
knit + f62 1
knit + f63 1
knit + f64 1
knit + f65 1
knit + f66 1
knit + f67 1
knit + f68 1
knit + f69 1
knit + f70 1
knit + f71 1
knit + f72 1
knit + f73 1
knit + f74 1
knit + f75 1
rack 1;Rack to 1 at 1 gauge
xfer f75 b74
rack 0.0;Rack to 0.0 at 1 gauge
split + b74 f74 1
knit - f74 1
rack 1;Rack to 1 at 1 gauge
xfer f74 b73
rack 0.0;Rack to 0.0 at 1 gauge
split + b73 f73 1
knit - f73 1
rack 1;Rack to 1 at 1 gauge
xfer f73 b72
rack 0.0;Rack to 0.0 at 1 gauge
split + b72 f72 1
knit - f72 1
rack 1;Rack to 1 at 1 gauge
xfer f72 b71
rack 0.0;Rack to 0.0 at 1 gauge
split + b71 f71 1
knit - f71 1
rack 1;Rack to 1 at 1 gauge
xfer f71 b70
rack 0.0;Rack to 0.0 at 1 gauge
split + b70 f70 1
knit - f70 1
rack 1;Rack to 1 at 1 gauge
xfer f70 b69
rack 0.0;Rack to 0.0 at 1 gauge
split + b69 f69 1
knit - f69 1
rack 1;Rack to 1 at 1 gauge
xfer f69 b68
rack 0.0;Rack to 0.0 at 1 gauge
split + b68 f68 1
knit - f68 1
rack 1;Rack to 1 at 1 gauge
xfer f68 b67
rack 0.0;Rack to 0.0 at 1 gauge
split + b67 f67 1
knit - f67 1
rack 1;Rack to 1 at 1 gauge
xfer f67 b66
rack 0.0;Rack to 0.0 at 1 gauge
split + b66 f66 1
knit - f66 1
rack 1;Rack to 1 at 1 gauge
xfer f66 b65
rack 0.0;Rack to 0.0 at 1 gauge
split + b65 f65 1
knit - f65 1
rack 1;Rack to 1 at 1 gauge
xfer f65 b64
rack 0.0;Rack to 0.0 at 1 gauge
split + b64 f64 1
knit - f64 1
rack 1;Rack to 1 at 1 gauge
xfer f64 b63
rack 0.0;Rack to 0.0 at 1 gauge
split + b63 f63 1
knit - f63 1
rack 1;Rack to 1 at 1 gauge
xfer f63 b62
rack 0.0;Rack to 0.0 at 1 gauge
split + b62 f62 1
knit - f62 1
rack 1;Rack to 1 at 1 gauge
xfer f62 b61
rack 0.0;Rack to 0.0 at 1 gauge
split + b61 f61 1
knit - f61 1
rack 1;Rack to 1 at 1 gauge
xfer f61 b60
rack 0.0;Rack to 0.0 at 1 gauge
split + b60 f60 1
knit - f60 1
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
split + b59 f59 1
knit - f59 1
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
split + b58 f58 1
knit - f58 1
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
split + b57 f57 1
knit - f57 1
rack 1;Rack to 1 at 1 gauge
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
split + b56 f56 1
knit - f56 1
rack 1;Rack to 1 at 1 gauge
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
split + b55 f55 1
knit - f55 1
rack 1;Rack to 1 at 1 gauge
xfer f55 b54
rack 0.0;Rack to 0.0 at 1 gauge
split + b54 f54 1
knit - f54 1
rack 1;Rack to 1 at 1 gauge
xfer f54 b53
rack 0.0;Rack to 0.0 at 1 gauge
split + b53 f53 1
knit - f53 1
rack 1;Rack to 1 at 1 gauge
xfer f53 b52
rack 0.0;Rack to 0.0 at 1 gauge
split + b52 f52 1
knit - f52 1
rack 1;Rack to 1 at 1 gauge
xfer f52 b51
rack 0.0;Rack to 0.0 at 1 gauge
split + b51 f51 1
knit - f51 1
rack 1;Rack to 1 at 1 gauge
xfer f51 b50
rack 0.0;Rack to 0.0 at 1 gauge
split + b50 f50 1
knit - f50 1
rack 1;Rack to 1 at 1 gauge
xfer f50 b49
rack 0.0;Rack to 0.0 at 1 gauge
split + b49 f49 1
knit - f49 1
rack 1;Rack to 1 at 1 gauge
xfer f49 b48
rack 0.0;Rack to 0.0 at 1 gauge
split + b48 f48 1
knit - f48 1
rack 1;Rack to 1 at 1 gauge
xfer f48 b47
rack 0.0;Rack to 0.0 at 1 gauge
split + b47 f47 1
knit - f47 1
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
rack 0.0;Rack to 0.0 at 1 gauge
split + b46 f46 1
knit - f46 1
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
rack 0.0;Rack to 0.0 at 1 gauge
split + b45 f45 1
knit - f45 1
rack 1;Rack to 1 at 1 gauge
xfer f45 b44
rack 0.0;Rack to 0.0 at 1 gauge
split + b44 f44 1
knit - f44 1
rack 1;Rack to 1 at 1 gauge
xfer f44 b43
rack 0.0;Rack to 0.0 at 1 gauge
split + b43 f43 1
knit - f43 1
rack 1;Rack to 1 at 1 gauge
xfer f43 b42
rack 0.0;Rack to 0.0 at 1 gauge
split + b42 f42 1
knit - f42 1
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
rack 0.0;Rack to 0.0 at 1 gauge
split + b41 f41 1
knit - f41 1
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
rack 0.0;Rack to 0.0 at 1 gauge
split + b40 f40 1
knit - f40 1
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
split + b39 f39 1
knit - f39 1
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
split + b38 f38 1
knit - f38 1
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
split + b37 f37 1
knit - f37 1
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
split + b36 f36 1
knit - f36 1
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
split + b35 f35 1
knit - f35 1
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
split + b34 f34 1
knit - f34 1
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
split + b33 f33 1
knit - f33 1
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
split + b32 f32 1
knit - f32 1
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
split + b31 f31 1
knit - f31 1
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
split + b30 f30 1
knit - f30 1
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
split + b29 f29 1
knit - f29 1
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 1
knit - f28 1
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 1
knit - f27 1
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 1
knit - f26 1
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
split + b25 f25 1
knit - f25 1
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
split + b24 f24 1
knit - f24 1
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 1
knit - f23 1
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 1
knit - f22 1
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 1
knit - f21 1
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
split + b20 f20 1
knit - f20 1
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
split + b19 f19 1
knit - f19 1
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 1
knit - f18 1
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 1
knit - f17 1
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 1
knit - f16 1
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
split + b15 f15 1
knit - f15 1
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
split + b14 f14 1
knit - f14 1
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 1
knit - f13 1
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 1
knit - f12 1
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 1
knit - f11 1
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
split + b10 f10 1
knit - f10 1
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
split + b9 f9 1
knit - f9 1
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 1
knit - f8 1
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 1
knit - f7 1
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 1
knit - f6 1
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 1
knit - f5 1
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 1
knit - f4 1
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 1
knit - f3 1
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 1
knit - f2 1
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 1
knit - f1 1
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 1
knit - f0 1
;KS: Spare knitting on [b74, b73, b72, b71, b70, b69, b68, b67, b66, b65, b64, b63, b62, b61, b60, b59, b58, b57, b56, b55, b54, b53, b52, b51, b50, b49, b48, b47, b46, b45, b44, b43, b42, b41, b40, b39, b38, b37, b36, b35, b34, b33, b32, b31, b30, b29, b28, b27, b26, b25, b24, b23, b22, b21, b20, b19, b18, b17, b16, b15, b14, b13, b12, b11, b10, b9, b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
knit + b44 1
knit + b45 1
knit + b46 1
knit + b47 1
knit + b48 1
knit + b49 1
knit + b50 1
knit + b51 1
knit + b52 1
knit + b53 1
knit + b54 1
knit + b55 1
knit + b56 1
knit + b57 1
knit + b58 1
knit + b59 1
knit + b60 1
knit + b61 1
knit + b62 1
knit + b63 1
knit + b64 1
knit + b65 1
knit + b66 1
knit + b67 1
knit + b68 1
knit + b69 1
knit + b70 1
knit + b71 1
knit + b72 1
knit + b73 1
knit + b74 1
outhook 1;Cutting active yarn on 1
