;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 2;Activating carrier 2
tuck - f29 2
tuck - f27 2
tuck - f25 2
tuck - f23 2
tuck - f21 2
tuck - f19 2
tuck - f17 2
tuck - f15 2
tuck - f13 2
tuck - f11 2
tuck - f9 2
tuck - f7 2
tuck - f5 2
tuck - f3 2
tuck - f1 2
tuck + f0 2
tuck + f2 2
tuck + f4 2
tuck + f6 2
tuck + f8 2
tuck + f10 2
tuck + f12 2
tuck + f14 2
tuck + f16 2
tuck + f18 2
tuck + f20 2
tuck + f22 2
tuck + f24 2
tuck + f26 2
tuck + f28 2
tuck - f29 2
tuck - f27 2
tuck - f25 2
tuck - f23 2
tuck - f21 2
tuck - f19 2
tuck - f17 2
tuck - f15 2
tuck - f13 2
tuck - f11 2
tuck - f9 2
tuck - f7 2
tuck - f5 2
tuck - f3 2
tuck - f1 2
tuck + f0 2
tuck + f2 2
tuck + f4 2
tuck + f6 2
tuck + f8 2
tuck + f10 2
tuck + f12 2
tuck + f14 2
tuck + f16 2
tuck + f18 2
tuck + f20 2
tuck + f22 2
tuck + f24 2
tuck + f26 2
tuck + f28 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
knit - f28 2
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
knit - f27 2
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
knit - f26 2
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
knit - f25 2
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
knit - f24 2
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
knit - f23 2
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
xfer b22 f22
knit - f22 2
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit - f21 2
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b20 f20
knit - f20 2
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
knit - f19 2
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
knit - f18 2
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
knit - f17 2
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
knit - f16 2
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
knit - f15 2
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
knit - f14 2
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
knit - f13 2
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
knit - f12 2
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
knit - f11 2
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
knit - f10 2
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
knit - f9 2
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
knit - f8 2
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
knit - f7 2
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
knit - f6 2
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
knit - f5 2
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f4 2
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
knit - f3 2
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
knit - f2 2
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit - f1 2
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
knit - f0 2
;KS: Spare knitting on [f0]
knit + f0 2
releasehook 2;Release inserting hook before cutting all yarns
outhook 2;Cutting active yarn on 2
