;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 50loops from 11to 61
tuck - f60 1
tuck - f58 1
tuck - f56 1
tuck - f54 1
tuck - f52 1
tuck - f50 1
tuck - f48 1
tuck - f46 1
tuck - f44 1
tuck - f42 1
tuck - f40 1
tuck - f38 1
tuck - f36 1
tuck - f34 1
tuck - f32 1
tuck - f30 1
tuck - f28 1
tuck - f26 1
tuck - f24 1
tuck - f22 1
tuck - f20 1
tuck - f18 1
tuck - f16 1
tuck - f14 1
tuck - f12 1
tuck + f11 1
tuck + f13 1
tuck + f15 1
tuck + f17 1
tuck + f19 1
tuck + f21 1
tuck + f23 1
tuck + f25 1
tuck + f27 1
tuck + f29 1
tuck + f31 1
tuck + f33 1
tuck + f35 1
tuck + f37 1
tuck + f39 1
tuck + f41 1
tuck + f43 1
tuck + f45 1
tuck + f47 1
tuck + f49 1
tuck + f51 1
tuck + f53 1
tuck + f55 1
tuck + f57 1
tuck + f59 1
tuck - f60 1
tuck - f58 1
tuck - f56 1
tuck - f54 1
tuck - f52 1
tuck - f50 1
tuck - f48 1
tuck - f46 1
tuck - f44 1
tuck - f42 1
tuck - f40 1
tuck - f38 1
tuck - f36 1
tuck - f34 1
tuck - f32 1
tuck - f30 1
tuck - f28 1
tuck - f26 1
tuck - f24 1
tuck - f22 1
tuck - f20 1
tuck - f18 1
tuck - f16 1
tuck - f14 1
tuck - f12 1
tuck + f11 1
tuck + f13 1
tuck + f15 1
tuck + f17 1
tuck + f19 1
tuck + f21 1
tuck + f23 1
tuck + f25 1
tuck + f27 1
tuck + f29 1
tuck + f31 1
tuck + f33 1
tuck + f35 1
tuck + f37 1
tuck + f39 1
tuck + f41 1
tuck + f43 1
tuck + f45 1
tuck + f47 1
tuck + f49 1
tuck + f51 1
tuck + f53 1
tuck + f55 1
tuck + f57 1
tuck + f59 1
releasehook 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f55 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f50 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f55 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
rack -1;Rack to -1 at 1 gauge
xfer f55 b56
xfer f50 b51
xfer f45 b46
xfer f40 b41
xfer f35 b36
xfer f30 b31
xfer f25 b26
xfer f20 b21
xfer f15 b16
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b56 f56
xfer b51 f51
xfer b46 f46
xfer b41 f41
xfer b36 f36
xfer b31 f31
xfer b26 f26
xfer b21 f21
xfer b16 f16
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
inhook 2;Activating carrier 2
xfer f60 b60
xfer f58 b58
xfer f56 b56
xfer f53 b53
xfer f51 b51
xfer f48 b48
xfer f46 b46
xfer f43 b43
xfer f41 b41
xfer f38 b38
xfer f36 b36
xfer f33 b33
xfer f31 b31
xfer f28 b28
xfer f26 b26
xfer f23 b23
xfer f21 b21
xfer f18 b18
xfer f16 b16
xfer f13 b13
xfer f11 b11
tuck - f71 2
tuck - f66 2
tuck - f61 2
tuck - f55 2
tuck - f50 2
tuck - f45 2
tuck - f40 2
tuck - f35 2
tuck - f30 2
tuck - f25 2
tuck - f20 2
tuck - f15 2
tuck - f10 2
tuck - f5 2
tuck - f0 2
xfer b11 f11
xfer b13 f13
xfer b16 f16
xfer b18 f18
xfer b21 f21
xfer b23 f23
xfer b26 f26
xfer b28 f28
xfer b31 f31
xfer b33 f33
xfer b36 f36
xfer b38 f38
xfer b41 f41
xfer b43 f43
xfer b46 f46
xfer b48 f48
xfer b51 f51
xfer b53 f53
xfer b56 f56
xfer b58 f58
xfer b60 f60
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
xfer f59 b59
xfer f57 b57
xfer f54 b54
xfer f52 b52
xfer f49 b49
xfer f47 b47
xfer f44 b44
xfer f42 b42
xfer f39 b39
xfer f37 b37
xfer f34 b34
xfer f32 b32
xfer f29 b29
xfer f27 b27
xfer f24 b24
xfer f22 b22
xfer f19 b19
xfer f17 b17
xfer f14 b14
xfer f12 b12
tuck + f0 2
tuck + f5 2
tuck + f10 2
tuck + f15 2
tuck + f20 2
tuck + f25 2
tuck + f30 2
tuck + f35 2
tuck + f40 2
tuck + f45 2
tuck + f50 2
tuck + f55 2
tuck + f61 2
tuck + f66 2
tuck + f71 2
xfer b59 f59
xfer b57 f57
xfer b54 f54
xfer b52 f52
xfer b49 f49
xfer b47 f47
xfer b44 f44
xfer b42 f42
xfer b39 f39
xfer b37 f37
xfer b34 f34
xfer b32 f32
xfer b29 f29
xfer b27 f27
xfer b24 f24
xfer b22 f22
xfer b19 f19
xfer b17 f17
xfer b14 f14
xfer b12 f12
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
xfer f60 b60
xfer f58 b58
xfer f56 b56
xfer f53 b53
xfer f51 b51
xfer f48 b48
xfer f46 b46
xfer f43 b43
xfer f41 b41
xfer f38 b38
xfer f36 b36
xfer f33 b33
xfer f31 b31
xfer f28 b28
xfer f26 b26
xfer f23 b23
xfer f21 b21
xfer f18 b18
xfer f16 b16
xfer f13 b13
xfer f11 b11
tuck - f71 2
tuck - f66 2
tuck - f61 2
tuck - f55 2
tuck - f50 2
tuck - f45 2
tuck - f40 2
tuck - f35 2
tuck - f30 2
tuck - f25 2
tuck - f20 2
tuck - f15 2
tuck - f10 2
tuck - f5 2
tuck - f0 2
xfer b11 f11
xfer b13 f13
xfer b16 f16
xfer b18 f18
xfer b21 f21
xfer b23 f23
xfer b26 f26
xfer b28 f28
xfer b31 f31
xfer b33 f33
xfer b36 f36
xfer b38 f38
xfer b41 f41
xfer b43 f43
xfer b46 f46
xfer b48 f48
xfer b51 f51
xfer b53 f53
xfer b56 f56
xfer b58 f58
xfer b60 f60
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
xfer f59 b59
xfer f57 b57
xfer f54 b54
xfer f52 b52
xfer f49 b49
xfer f47 b47
xfer f44 b44
xfer f42 b42
xfer f39 b39
xfer f37 b37
xfer f34 b34
xfer f32 b32
xfer f29 b29
xfer f27 b27
xfer f24 b24
xfer f22 b22
xfer f19 b19
xfer f17 b17
xfer f14 b14
xfer f12 b12
tuck + f0 2
tuck + f5 2
tuck + f10 2
tuck + f15 2
tuck + f20 2
tuck + f25 2
tuck + f30 2
tuck + f35 2
tuck + f40 2
tuck + f45 2
tuck + f50 2
tuck + f55 2
tuck + f61 2
tuck + f66 2
tuck + f71 2
xfer b59 f59
xfer b57 f57
xfer b54 f54
xfer b52 f52
xfer b49 f49
xfer b47 f47
xfer b44 f44
xfer b42 f42
xfer b39 f39
xfer b37 f37
xfer b34 f34
xfer b32 f32
xfer b29 f29
xfer b27 f27
xfer b24 f24
xfer b22 f22
xfer b19 f19
xfer b17 f17
xfer b14 f14
xfer b12 f12
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
xfer f60 b60
xfer f58 b58
xfer f56 b56
xfer f53 b53
xfer f51 b51
xfer f48 b48
xfer f46 b46
xfer f43 b43
xfer f41 b41
xfer f38 b38
xfer f36 b36
xfer f33 b33
xfer f31 b31
xfer f28 b28
xfer f26 b26
xfer f23 b23
xfer f21 b21
xfer f18 b18
xfer f16 b16
xfer f13 b13
xfer f11 b11
tuck - f71 2
tuck - f66 2
tuck - f61 2
tuck - f55 2
tuck - f50 2
tuck - f45 2
tuck - f40 2
tuck - f35 2
tuck - f30 2
tuck - f25 2
tuck - f20 2
tuck - f15 2
tuck - f10 2
tuck - f5 2
tuck - f0 2
xfer b11 f11
xfer b13 f13
xfer b16 f16
xfer b18 f18
xfer b21 f21
xfer b23 f23
xfer b26 f26
xfer b28 f28
xfer b31 f31
xfer b33 f33
xfer b36 f36
xfer b38 f38
xfer b41 f41
xfer b43 f43
xfer b46 f46
xfer b48 f48
xfer b51 f51
xfer b53 f53
xfer b56 f56
xfer b58 f58
xfer b60 f60
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
xfer f59 b59
xfer f57 b57
xfer f54 b54
xfer f52 b52
xfer f49 b49
xfer f47 b47
xfer f44 b44
xfer f42 b42
xfer f39 b39
xfer f37 b37
xfer f34 b34
xfer f32 b32
xfer f29 b29
xfer f27 b27
xfer f24 b24
xfer f22 b22
xfer f19 b19
xfer f17 b17
xfer f14 b14
xfer f12 b12
tuck + f0 2
tuck + f5 2
tuck + f10 2
tuck + f15 2
tuck + f20 2
tuck + f25 2
tuck + f30 2
tuck + f35 2
tuck + f40 2
tuck + f45 2
tuck + f50 2
tuck + f55 2
tuck + f61 2
tuck + f66 2
tuck + f71 2
xfer b59 f59
xfer b57 f57
xfer b54 f54
xfer b52 f52
xfer b49 f49
xfer b47 f47
xfer b44 f44
xfer b42 f42
xfer b39 f39
xfer b37 f37
xfer b34 f34
xfer b32 f32
xfer b29 f29
xfer b27 f27
xfer b24 f24
xfer b22 f22
xfer b19 f19
xfer b17 f17
xfer b14 f14
xfer b12 f12
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
knit - f60 1
knit - f59 1
knit - f58 1
knit - f57 1
knit - f56 1
knit - f54 1
knit - f53 1
knit - f52 1
knit - f51 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f51 1
knit + f52 1
knit + f53 1
knit + f54 1
knit + f56 1
knit + f57 1
knit + f58 1
knit + f59 1
knit + f60 1
xfer f60 b60
xfer f58 b58
xfer f56 b56
xfer f53 b53
xfer f51 b51
xfer f48 b48
xfer f46 b46
xfer f43 b43
xfer f41 b41
xfer f38 b38
xfer f36 b36
xfer f33 b33
xfer f31 b31
xfer f28 b28
xfer f26 b26
xfer f23 b23
xfer f21 b21
xfer f18 b18
xfer f16 b16
xfer f13 b13
xfer f11 b11
tuck - f71 2
tuck - f66 2
tuck - f61 2
tuck - f55 2
tuck - f50 2
tuck - f45 2
tuck - f40 2
tuck - f35 2
tuck - f30 2
tuck - f25 2
tuck - f20 2
tuck - f15 2
tuck - f10 2
tuck - f5 2
tuck - f0 2
xfer b11 f11
xfer b13 f13
xfer b16 f16
xfer b18 f18
xfer b21 f21
xfer b23 f23
xfer b26 f26
xfer b28 f28
xfer b31 f31
xfer b33 f33
xfer b36 f36
xfer b38 f38
xfer b41 f41
xfer b43 f43
xfer b46 f46
xfer b48 f48
xfer b51 f51
xfer b53 f53
xfer b56 f56
xfer b58 f58
xfer b60 f60
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
xfer f59 b59
xfer f57 b57
xfer f54 b54
xfer f52 b52
xfer f49 b49
xfer f47 b47
xfer f44 b44
xfer f42 b42
xfer f39 b39
xfer f37 b37
xfer f34 b34
xfer f32 b32
xfer f29 b29
xfer f27 b27
xfer f24 b24
xfer f22 b22
xfer f19 b19
xfer f17 b17
xfer f14 b14
xfer f12 b12
tuck + f0 2
tuck + f5 2
tuck + f10 2
tuck + f15 2
tuck + f20 2
tuck + f25 2
tuck + f30 2
tuck + f35 2
tuck + f40 2
tuck + f45 2
tuck + f50 2
tuck + f55 2
tuck + f61 2
tuck + f66 2
tuck + f71 2
xfer b59 f59
xfer b57 f57
xfer b54 f54
xfer b52 f52
xfer b49 f49
xfer b47 f47
xfer b44 f44
xfer b42 f42
xfer b39 f39
xfer b37 f37
xfer b34 f34
xfer b32 f32
xfer b29 f29
xfer b27 f27
xfer b24 f24
xfer b22 f22
xfer b19 f19
xfer b17 f17
xfer b14 f14
xfer b12 f12
drop f0
drop f5
drop f10
drop f15
drop f20
drop f25
drop f30
drop f35
drop f40
drop f45
drop f50
drop f55
drop f61
drop f66
drop f71
rack 1;Rack to 1 at 1 gauge
xfer f60 b59
rack 0.0;Rack to 0.0 at 1 gauge
split + b59 f59 1
knit - f59 1
rack 1;Rack to 1 at 1 gauge
xfer f59 b58
rack 0.0;Rack to 0.0 at 1 gauge
split + b58 f58 1
knit - f58 1
rack 1;Rack to 1 at 1 gauge
xfer f58 b57
rack 0.0;Rack to 0.0 at 1 gauge
split + b57 f57 1
knit - f57 1
rack 1;Rack to 1 at 1 gauge
xfer f57 b56
rack 0.0;Rack to 0.0 at 1 gauge
split + b56 f56 1
knit - f56 1
rack 1;Rack to 1 at 1 gauge
xfer f56 b55
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b55 f54
rack 0.0;Rack to 0.0 at 1 gauge
knit - f54 1
rack 1;Rack to 1 at 1 gauge
xfer f54 b53
rack 0.0;Rack to 0.0 at 1 gauge
split + b53 f53 1
knit - f53 1
rack 1;Rack to 1 at 1 gauge
xfer f53 b52
rack 0.0;Rack to 0.0 at 1 gauge
split + b52 f52 1
knit - f52 1
rack 1;Rack to 1 at 1 gauge
xfer f52 b51
rack 0.0;Rack to 0.0 at 1 gauge
split + b51 f51 1
knit - f51 1
rack 1;Rack to 1 at 1 gauge
xfer f51 b50
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b50 f49
rack 0.0;Rack to 0.0 at 1 gauge
knit - f49 1
rack 1;Rack to 1 at 1 gauge
xfer f49 b48
rack 0.0;Rack to 0.0 at 1 gauge
split + b48 f48 1
knit - f48 1
rack 1;Rack to 1 at 1 gauge
xfer f48 b47
rack 0.0;Rack to 0.0 at 1 gauge
split + b47 f47 1
knit - f47 1
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
rack 0.0;Rack to 0.0 at 1 gauge
split + b46 f46 1
knit - f46 1
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b45 f44
rack 0.0;Rack to 0.0 at 1 gauge
knit - f44 1
rack 1;Rack to 1 at 1 gauge
xfer f44 b43
rack 0.0;Rack to 0.0 at 1 gauge
split + b43 f43 1
knit - f43 1
rack 1;Rack to 1 at 1 gauge
xfer f43 b42
rack 0.0;Rack to 0.0 at 1 gauge
split + b42 f42 1
knit - f42 1
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
rack 0.0;Rack to 0.0 at 1 gauge
split + b41 f41 1
knit - f41 1
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b40 f39
rack 0.0;Rack to 0.0 at 1 gauge
knit - f39 1
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
split + b38 f38 1
knit - f38 1
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
split + b37 f37 1
knit - f37 1
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
split + b36 f36 1
knit - f36 1
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b35 f34
rack 0.0;Rack to 0.0 at 1 gauge
knit - f34 1
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
split + b33 f33 1
knit - f33 1
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
split + b32 f32 1
knit - f32 1
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
split + b31 f31 1
knit - f31 1
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b30 f29
rack 0.0;Rack to 0.0 at 1 gauge
knit - f29 1
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 1
knit - f28 1
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 1
knit - f27 1
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 1
knit - f26 1
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b25 f24
rack 0.0;Rack to 0.0 at 1 gauge
knit - f24 1
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 1
knit - f23 1
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 1
knit - f22 1
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 1
knit - f21 1
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b20 f19
rack 0.0;Rack to 0.0 at 1 gauge
knit - f19 1
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 1
knit - f18 1
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 1
knit - f17 1
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 1
knit - f16 1
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b15 f14
rack 0.0;Rack to 0.0 at 1 gauge
knit - f14 1
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 1
knit - f13 1
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 1
knit - f12 1
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 1
knit - f11 1
;KS: Spare knitting on [b59, b58, b57, b56, b53, b52, b51, b48, b47, b46, b43, b42, b41, b38, b37, b36, b33, b32, b31, b28, b27, b26, b23, b22, b21, b18, b17, b16, b13, b12, b11]
knit + b11 1
knit + b12 1
knit + b13 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b41 1
knit + b42 1
knit + b43 1
knit + b46 1
knit + b47 1
knit + b48 1
knit + b51 1
knit + b52 1
knit + b53 1
knit + b56 1
knit + b57 1
knit + b58 1
knit + b59 1
releasehook 2;Release inserting hook before cutting all yarns
outhook 1;Cutting active yarn on 1
outhook 2;Cutting active yarn on 2
