;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 30loops from 0to 30
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
releasehook 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 0
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f0 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
tuck - f0 1
;KS: 1
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 2
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
tuck - f2 1
knit - f1 1
knit - f0 1
;KS: 3
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 4
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
tuck - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 5
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 6
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
tuck - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 7
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 8
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
tuck - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 9
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 10
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
tuck - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 11
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 12
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
tuck - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 13
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 14
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f14 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
tuck - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 15
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 16
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f16 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
tuck - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 17
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 18
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b19 f19
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
tuck - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 19
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 20
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f20 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
tuck - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 21
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 22
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f22 b23
rack 0.0;Rack to 0.0 at 1 gauge
xfer b23 f23
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
tuck - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 23
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 24
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
xfer b25 f25
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
tuck - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 25
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 26
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
xfer b27 f27
knit - f29 1
knit - f28 1
knit - f27 1
tuck - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 27
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: 28
;KS: goodby
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
xfer b29 f29
knit - f29 1
tuck - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
;KS: 29
;KS: hello
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
;KS: row
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 1
knit - f28 1
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 1
knit - f27 1
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 1
knit - f26 1
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
split + b25 f25 1
knit - f25 1
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
split + b24 f24 1
knit - f24 1
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 1
knit - f23 1
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 1
knit - f22 1
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 1
knit - f21 1
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
split + b20 f20 1
knit - f20 1
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
split + b19 f19 1
knit - f19 1
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 1
knit - f18 1
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 1
knit - f17 1
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 1
knit - f16 1
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
split + b15 f15 1
knit - f15 1
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
split + b14 f14 1
knit - f14 1
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 1
knit - f13 1
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 1
knit - f12 1
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 1
knit - f11 1
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
split + b10 f10 1
knit - f10 1
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
split + b9 f9 1
knit - f9 1
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 1
knit - f8 1
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 1
knit - f7 1
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 1
knit - f6 1
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 1
knit - f5 1
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 1
knit - f4 1
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 1
knit - f3 1
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 1
knit - f2 1
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 1
knit - f1 1
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 1
knit - f0 1
;KS: Spare knitting on [b28, b27, b26, b25, b24, b23, b22, b21, b20, b19, b18, b17, b16, b15, b14, b13, b12, b11, b10, b9, b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
outhook 1;Cutting active yarn on 1
