;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 3;Activating carrier 3
tuck - f31 3
miss + f31 3
tuck - f31 3
miss - f30 3
tuck + f30 3
miss - f30 3
miss - f29 3
tuck + f29 3
miss - f29 3
miss - f28 3
tuck + f28 3
miss - f28 3
miss - f27 3
tuck + f27 3
miss - f27 3
miss - f26 3
tuck + f26 3
miss - f26 3
miss - f25 3
tuck + f25 3
miss - f25 3
miss - f24 3
tuck + f24 3
miss - f24 3
miss - f23 3
tuck + f23 3
miss - f23 3
miss - f22 3
tuck + f22 3
miss - f22 3
miss - f21 3
tuck + f21 3
miss - f21 3
miss - f20 3
tuck + f20 3
miss - f20 3
miss - f19 3
tuck + f19 3
miss - f19 3
miss - f18 3
tuck + f18 3
miss - f18 3
miss - f17 3
tuck + f17 3
miss - f17 3
miss - f16 3
tuck + f16 3
miss - f16 3
miss - f15 3
tuck + f15 3
miss - f15 3
miss - f14 3
tuck + f14 3
miss - f14 3
miss - f13 3
tuck + f13 3
miss - f13 3
miss - f12 3
tuck + f12 3
miss - f12 3
miss - f11 3
tuck + f11 3
miss - f11 3
miss - f10 3
tuck + f10 3
miss - f10 3
miss - f9 3
tuck + f9 3
miss - f9 3
miss - f8 3
tuck + f8 3
miss - f8 3
miss - f7 3
tuck + f7 3
miss - f7 3
miss - f6 3
tuck + f6 3
miss - f6 3
miss - f5 3
tuck + f5 3
miss - f5 3
miss - f4 3
tuck + f4 3
miss - f4 3
miss - f3 3
tuck + f3 3
miss - f3 3
miss - f2 3
tuck + f2 3
miss - f2 3
miss - f1 3
tuck + f1 3
miss - f1 3
miss - f0 3
tuck + f0 3
miss - f0 3
;KS: Cast on 32loops from f31to f0
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3
knit + f31 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f4 3
knit - f3 3
knit - f2 3
knit - f1 3
knit - f0 3
knit + f0 3
knit + f1 3
knit + f2 3
knit + f3 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + f29 3
knit + f30 3
knit + f31 3
releasehook 3
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
xfer f28 b27
xfer f26 b25
xfer f24 b23
xfer f22 b21
xfer f20 b19
xfer f18 b17
xfer f16 b15
xfer f14 b13
xfer f12 b11
xfer f10 b9
xfer f8 b7
xfer f6 b5
xfer f4 b3
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
inhook 9;Activating carrier 9
tuck - b35 9
drop b35
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
releasehook 9
xfer b3 f3
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
tuck + b1 3
knit + f3 3
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
knit + b1 9
tuck + f3 9
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
split - f3 b3 3
rack -2;Rack to -2 at 1 gauge
xfer b3 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b3 3
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
tuck - f3 9
knit - b1 9
xfer b5 f5
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b4 f5
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
tuck + b3 3
knit + f5 3
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
knit + b3 9
tuck + f5 9
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
split - f5 b5 3
rack -2;Rack to -2 at 1 gauge
xfer b5 f3
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b5 3
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
tuck - f5 9
knit - b3 9
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b7 f7
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b6 f7
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
tuck + b5 3
knit + f7 3
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
knit + b5 9
tuck + f7 9
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
split - f7 b7 3
rack -2;Rack to -2 at 1 gauge
xfer b7 f5
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b7 3
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
tuck - f7 9
knit - b5 9
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b9 f9
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b8 f9
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
tuck + b7 3
knit + f9 3
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
knit + b7 9
tuck + f9 9
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
split - f9 b9 3
rack -2;Rack to -2 at 1 gauge
xfer b9 f7
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b9 3
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
tuck - f9 9
knit - b7 9
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b11 f11
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b10 f11
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
tuck + b9 3
knit + f11 3
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
knit + b9 9
tuck + f11 9
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
split - f11 b11 3
rack -2;Rack to -2 at 1 gauge
xfer b11 f9
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b11 3
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
tuck - f11 9
knit - b9 9
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b13 f13
rack -1;Rack to -1 at 1 gauge
xfer f11 b12
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b12 f13
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
tuck + b11 3
knit + f13 3
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
knit + b11 9
tuck + f13 9
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
split - f13 b13 3
rack -2;Rack to -2 at 1 gauge
xfer b13 f11
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b13 3
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
tuck - f13 9
knit - b11 9
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b15 f15
rack -1;Rack to -1 at 1 gauge
xfer f13 b14
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b14 f15
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
tuck + b13 3
knit + f15 3
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
knit + b13 9
tuck + f15 9
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
split - f15 b15 3
rack -2;Rack to -2 at 1 gauge
xfer b15 f13
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b15 3
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
tuck - f15 9
knit - b13 9
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b17 f17
rack -1;Rack to -1 at 1 gauge
xfer f15 b16
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b16 f17
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
tuck + b15 3
knit + f17 3
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
knit + b15 9
tuck + f17 9
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b21 3
knit - f21 3
rack 0.0;Reset rack from all_needle
split - f17 b17 3
rack -2;Rack to -2 at 1 gauge
xfer b17 f15
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b17 3
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b19 9
tuck - f19 9
rack 0.0;Reset rack from all_needle
tuck - f17 9
knit - b15 9
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b19 f19
rack -1;Rack to -1 at 1 gauge
xfer f17 b18
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b18 f19
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
tuck + b17 3
knit + f19 3
rack 0.25;All Needle racking 0.0 to right
knit + f21 3
tuck + b21 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
knit + b17 9
tuck + f19 9
rack 0.25;All Needle racking 0.0 to right
tuck + f21 9
knit + b21 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b23 3
knit - f23 3
rack 0.0;Reset rack from all_needle
split - f19 b19 3
rack -2;Rack to -2 at 1 gauge
xfer b19 f17
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b19 3
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b21 9
tuck - f21 9
rack 0.0;Reset rack from all_needle
tuck - f19 9
knit - b17 9
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b21 f21
rack -1;Rack to -1 at 1 gauge
xfer f19 b20
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b20 f21
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
tuck + b19 3
knit + f21 3
rack 0.25;All Needle racking 0.0 to right
knit + f23 3
tuck + b23 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
knit + b19 9
tuck + f21 9
rack 0.25;All Needle racking 0.0 to right
tuck + f23 9
knit + b23 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
knit - f31 3
rack 0.25;All Needle racking 0.0 to right
tuck - b29 3
knit - f29 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b27 3
knit - f27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b25 3
knit - f25 3
rack 0.0;Reset rack from all_needle
split - f21 b21 3
rack -2;Rack to -2 at 1 gauge
xfer b21 f19
rack 0.0;Rack to 0.0 at 1 gauge
tuck - b21 3
rack 0.25;All Needle racking 0.0 to right
tuck - b19 3
knit - f19 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b17 3
knit - f17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b15 3
knit - f15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b13 3
knit - f13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b11 3
knit - f11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b9 3
knit - f9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b7 3
knit - f7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b5 3
knit - f5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b3 3
knit - f3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b1 3
knit - f1 3
rack 0.0;Reset rack from all_needle
knit - f0 3
rack 0.25;All Needle racking 0.0 to right
knit - b29 9
tuck - f29 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b27 9
tuck - f27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b25 9
tuck - f25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b23 9
tuck - f23 9
rack 0.0;Reset rack from all_needle
tuck - f21 9
knit - b19 9
rack 0.25;All Needle racking 0.0 to right
knit - b17 9
tuck - f17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b15 9
tuck - f15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b13 9
tuck - f13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b11 9
tuck - f11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b9 9
tuck - f9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b7 9
tuck - f7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b5 9
tuck - f5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b3 9
tuck - f3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - b1 9
tuck - f1 9
rack 0.0;Reset rack from all_needle
xfer b23 f23
rack -1;Rack to -1 at 1 gauge
xfer f21 b22
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b22 f23
rack 0.0;Rack to 0.0 at 1 gauge
knit + f0 3
rack 0.25;All Needle racking 0.0 to right
knit + f1 3
tuck + b1 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f3 3
tuck + b3 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f5 3
tuck + b5 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f7 3
tuck + b7 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f9 3
tuck + b9 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f11 3
tuck + b11 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f13 3
tuck + b13 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f15 3
tuck + b15 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f17 3
tuck + b17 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f19 3
tuck + b19 3
rack 0.0;Reset rack from all_needle
tuck + b21 3
knit + f23 3
rack 0.25;All Needle racking 0.0 to right
knit + f25 3
tuck + b25 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f27 3
tuck + b27 3
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f29 3
tuck + b29 3
rack 0.0;Reset rack from all_needle
knit + f31 3
rack 0.25;All Needle racking 0.0 to right
tuck + f1 9
knit + b1 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f3 9
knit + b3 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f5 9
knit + b5 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f7 9
knit + b7 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f9 9
knit + b9 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f11 9
knit + b11 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f13 9
knit + b13 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f15 9
knit + b15 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f17 9
knit + b17 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f19 9
knit + b19 9
rack 0.0;Reset rack from all_needle
knit + b21 9
tuck + f23 9
rack 0.25;All Needle racking 0.0 to right
tuck + f25 9
knit + b25 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f27 9
knit + b27 9
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f29 9
knit + b29 9
rack 0.0;Reset rack from all_needle
outhook 9
rack 1;Rack to 1 at 1 gauge
xfer b29 f30
xfer b27 f28
xfer b25 f26
xfer b21 f22
xfer b19 f20
xfer b17 f18
xfer b15 f16
xfer b13 f14
xfer b11 f12
xfer b9 f10
xfer b7 f8
xfer b5 f6
xfer b3 f4
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
knit - f31 3
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
xfer b30 f30
knit - f30 3
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
knit - f29 3
xfer b29 f29
knit - f29 3
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
xfer b28 f28
knit - f28 3
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
knit - f27 3
xfer b27 f27
knit - f27 3
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
xfer b26 f26
knit - f26 3
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
knit - f25 3
xfer b25 f25
knit - f25 3
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
xfer b24 f24
knit - f23 3
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
knit - f22 3
xfer b22 f22
knit - f22 3
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
knit - f20 3
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
knit - f19 3
xfer b19 f19
knit - f19 3
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
knit - f18 3
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
knit - f17 3
xfer b17 f17
knit - f17 3
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
knit - f16 3
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
knit - f15 3
xfer b15 f15
knit - f15 3
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
knit - f14 3
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
knit - f13 3
xfer b13 f13
knit - f13 3
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
knit - f12 3
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
knit - f11 3
xfer b11 f11
knit - f11 3
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
knit - f10 3
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
knit - f9 3
xfer b9 f9
knit - f9 3
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
knit - f8 3
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
knit - f7 3
xfer b7 f7
knit - f7 3
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
knit - f6 3
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
knit - f5 3
xfer b5 f5
knit - f5 3
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
knit - f4 3
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
knit - f3 3
xfer b3 f3
knit - f3 3
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
knit - f2 3
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
knit - f1 3
xfer b1 f1
knit - f1 3
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
knit - f0 3
tuck + b0 3
tuck + b1 3
tuck + b2 3
tuck + b3 3
tuck + b4 3
tuck + b5 3
tuck + b6 3
tuck + b7 3
tuck + b8 3
tuck + b9 3
tuck + b10 3
tuck + b11 3
tuck + b12 3
tuck + b13 3
tuck + b14 3
tuck + b15 3
tuck + b16 3
tuck + b17 3
tuck + b18 3
tuck + b19 3
tuck + b20 3
tuck + b21 3
tuck + b22 3
tuck + b23 3
tuck + b24 3
tuck + b25 3
tuck + b26 3
tuck + b27 3
tuck + b28 3
tuck + b29 3
tuck + b30 3
tuck + b31 3
tuck + b32 3
tuck + b33 3
tuck + b34 3
tuck + b35 3
tuck + b36 3
tuck + b37 3
tuck + b38 3
outhook 3;Cutting active yarn on 3
