;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 5;Activating carrier 5
;KS: Cast on 16loops from 0to 16
tuck - f15 5
tuck - f13 5
tuck - f11 5
tuck - f9 5
tuck - f7 5
tuck - f5 5
tuck - f3 5
tuck - f1 5
tuck + f0 5
tuck + f2 5
tuck + f4 5
tuck + f6 5
tuck + f8 5
tuck + f10 5
tuck + f12 5
tuck + f14 5
tuck - f15 5
tuck - f13 5
tuck - f11 5
tuck - f9 5
tuck - f7 5
tuck - f5 5
tuck - f3 5
tuck - f1 5
tuck + f0 5
tuck + f2 5
tuck + f4 5
tuck + f6 5
tuck + f8 5
tuck + f10 5
tuck + f12 5
tuck + f14 5
releasehook 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
miss - f15 5
tuck - f14 5
miss - f13 5
tuck - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
tuck - f7 5
miss - f6 5
tuck - f5 5
miss - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
inhook 8;Activating carrier 8
knit - f15 8
knit - f14 8
knit - f13 8
knit - f12 8
tuck - f11 8
miss - f10 8
tuck - f9 8
miss - f8 8
knit - f7 8
knit - f6 8
knit - f5 8
knit - f4 8
tuck - f3 8
miss - f2 8
tuck - f1 8
miss - f0 8
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
tuck + f4 5
miss + f5 5
tuck + f6 5
miss + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
tuck + f12 5
miss + f13 5
tuck + f14 5
miss + f15 5
miss + f0 8
tuck + f1 8
miss + f2 8
tuck + f3 8
knit + f4 8
knit + f5 8
knit + f6 8
knit + f7 8
tuck + f8 8
miss + f9 8
tuck + f10 8
miss + f11 8
knit + f12 8
knit + f13 8
knit + f14 8
knit + f15 8
miss - f15 5
tuck - f14 5
miss - f13 5
tuck - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
tuck - f7 5
miss - f6 5
tuck - f5 5
miss - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit - f15 8
knit - f14 8
knit - f13 8
knit - f12 8
tuck - f11 8
miss - f10 8
tuck - f9 8
miss - f8 8
knit - f7 8
knit - f6 8
knit - f5 8
knit - f4 8
tuck - f3 8
miss - f2 8
tuck - f1 8
miss - f0 8
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
tuck + f4 5
miss + f5 5
tuck + f6 5
miss + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
tuck + f12 5
miss + f13 5
tuck + f14 5
miss + f15 5
miss + f0 8
tuck + f1 8
miss + f2 8
tuck + f3 8
knit + f4 8
knit + f5 8
knit + f6 8
knit + f7 8
tuck + f8 8
miss + f9 8
tuck + f10 8
miss + f11 8
knit + f12 8
knit + f13 8
knit + f14 8
knit + f15 8
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
tuck - f11 5
miss - f10 5
tuck - f9 5
miss - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
tuck - f3 5
miss - f2 5
tuck - f1 5
miss - f0 5
miss - f15 8
tuck - f14 8
miss - f13 8
tuck - f12 8
knit - f11 8
knit - f10 8
knit - f9 8
knit - f8 8
tuck - f7 8
miss - f6 8
tuck - f5 8
miss - f4 8
knit - f3 8
knit - f2 8
knit - f1 8
knit - f0 8
miss + f0 5
tuck + f1 5
miss + f2 5
tuck + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
tuck + f8 5
miss + f9 5
tuck + f10 5
miss + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f0 8
knit + f1 8
knit + f2 8
knit + f3 8
tuck + f4 8
miss + f5 8
tuck + f6 8
miss + f7 8
knit + f8 8
knit + f9 8
knit + f10 8
knit + f11 8
tuck + f12 8
miss + f13 8
tuck + f14 8
miss + f15 8
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
tuck - f11 5
miss - f10 5
tuck - f9 5
miss - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
tuck - f3 5
miss - f2 5
tuck - f1 5
miss - f0 5
miss - f15 8
tuck - f14 8
miss - f13 8
tuck - f12 8
knit - f11 8
knit - f10 8
knit - f9 8
knit - f8 8
tuck - f7 8
miss - f6 8
tuck - f5 8
miss - f4 8
knit - f3 8
knit - f2 8
knit - f1 8
knit - f0 8
miss + f0 5
tuck + f1 5
miss + f2 5
tuck + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
tuck + f8 5
miss + f9 5
tuck + f10 5
miss + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f0 8
knit + f1 8
knit + f2 8
knit + f3 8
tuck + f4 8
miss + f5 8
tuck + f6 8
miss + f7 8
knit + f8 8
knit + f9 8
knit + f10 8
knit + f11 8
tuck + f12 8
miss + f13 8
tuck + f14 8
miss + f15 8
miss - f15 5
tuck - f14 5
miss - f13 5
tuck - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
tuck - f7 5
miss - f6 5
tuck - f5 5
miss - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit - f15 8
knit - f14 8
knit - f13 8
knit - f12 8
tuck - f11 8
miss - f10 8
tuck - f9 8
miss - f8 8
knit - f7 8
knit - f6 8
knit - f5 8
knit - f4 8
tuck - f3 8
miss - f2 8
tuck - f1 8
miss - f0 8
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
tuck + f4 5
miss + f5 5
tuck + f6 5
miss + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
tuck + f12 5
miss + f13 5
tuck + f14 5
miss + f15 5
miss + f0 8
tuck + f1 8
miss + f2 8
tuck + f3 8
knit + f4 8
knit + f5 8
knit + f6 8
knit + f7 8
tuck + f8 8
miss + f9 8
tuck + f10 8
miss + f11 8
knit + f12 8
knit + f13 8
knit + f14 8
knit + f15 8
miss - f15 5
tuck - f14 5
miss - f13 5
tuck - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
tuck - f7 5
miss - f6 5
tuck - f5 5
miss - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit - f15 8
knit - f14 8
knit - f13 8
knit - f12 8
tuck - f11 8
miss - f10 8
tuck - f9 8
miss - f8 8
knit - f7 8
knit - f6 8
knit - f5 8
knit - f4 8
tuck - f3 8
miss - f2 8
tuck - f1 8
miss - f0 8
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
tuck + f4 5
miss + f5 5
tuck + f6 5
miss + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
tuck + f12 5
miss + f13 5
tuck + f14 5
miss + f15 5
miss + f0 8
tuck + f1 8
miss + f2 8
tuck + f3 8
knit + f4 8
knit + f5 8
knit + f6 8
knit + f7 8
tuck + f8 8
miss + f9 8
tuck + f10 8
miss + f11 8
knit + f12 8
knit + f13 8
knit + f14 8
knit + f15 8
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
tuck - f11 5
miss - f10 5
tuck - f9 5
miss - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
tuck - f3 5
miss - f2 5
tuck - f1 5
miss - f0 5
miss - f15 8
tuck - f14 8
miss - f13 8
tuck - f12 8
knit - f11 8
knit - f10 8
knit - f9 8
knit - f8 8
tuck - f7 8
miss - f6 8
tuck - f5 8
miss - f4 8
knit - f3 8
knit - f2 8
knit - f1 8
knit - f0 8
miss + f0 5
tuck + f1 5
miss + f2 5
tuck + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
tuck + f8 5
miss + f9 5
tuck + f10 5
miss + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f0 8
knit + f1 8
knit + f2 8
knit + f3 8
tuck + f4 8
miss + f5 8
tuck + f6 8
miss + f7 8
knit + f8 8
knit + f9 8
knit + f10 8
knit + f11 8
tuck + f12 8
miss + f13 8
tuck + f14 8
miss + f15 8
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
tuck - f11 5
miss - f10 5
tuck - f9 5
miss - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
tuck - f3 5
miss - f2 5
tuck - f1 5
miss - f0 5
miss - f15 8
tuck - f14 8
miss - f13 8
tuck - f12 8
knit - f11 8
knit - f10 8
knit - f9 8
knit - f8 8
tuck - f7 8
miss - f6 8
tuck - f5 8
miss - f4 8
knit - f3 8
knit - f2 8
knit - f1 8
knit - f0 8
miss + f0 5
tuck + f1 5
miss + f2 5
tuck + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
tuck + f8 5
miss + f9 5
tuck + f10 5
miss + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f0 8
knit + f1 8
knit + f2 8
knit + f3 8
tuck + f4 8
miss + f5 8
tuck + f6 8
miss + f7 8
knit + f8 8
knit + f9 8
knit + f10 8
knit + f11 8
tuck + f12 8
miss + f13 8
tuck + f14 8
miss + f15 8
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
rack -1;Rack to -1 at 1 gauge
xfer f0 b1
rack 0.0;Rack to 0.0 at 1 gauge
split - b1 f1 5
knit + f1 5
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
split - b2 f2 5
knit + f2 5
rack -1;Rack to -1 at 1 gauge
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
split - b3 f3 5
knit + f3 5
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
split - b4 f4 5
knit + f4 5
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
split - b5 f5 5
knit + f5 5
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
split - b6 f6 5
knit + f6 5
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
split - b7 f7 5
knit + f7 5
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
split - b8 f8 5
knit + f8 5
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
split - b9 f9 5
knit + f9 5
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
split - b10 f10 5
knit + f10 5
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
split - b11 f11 5
knit + f11 5
rack -1;Rack to -1 at 1 gauge
xfer f11 b12
rack 0.0;Rack to 0.0 at 1 gauge
split - b12 f12 5
knit + f12 5
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
split - b13 f13 5
knit + f13 5
rack -1;Rack to -1 at 1 gauge
xfer f13 b14
rack 0.0;Rack to 0.0 at 1 gauge
split - b14 f14 5
knit + f14 5
rack -1;Rack to -1 at 1 gauge
xfer f14 b15
rack 0.0;Rack to 0.0 at 1 gauge
split - b15 f15 5
knit + f15 5
;KS: Spare knitting on [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15]
knit - b15 5
knit - b14 5
knit - b13 5
knit - b12 5
knit - b11 5
knit - b10 5
knit - b9 5
knit - b8 5
knit - b7 5
knit - b6 5
knit - b5 5
knit - b4 5
knit - b3 5
knit - b2 5
knit - b1 5
releasehook 8;Release inserting hook before cutting all yarns
outhook 5;Cutting active yarn on 5
outhook 8;Cutting active yarn on 8
