;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 2;Activating carrier 2
;KS: Cast on 20loops from 0to 20
tuck - f38 2
tuck - f34 2
tuck - f30 2
tuck - f26 2
tuck - f22 2
tuck - f18 2
tuck - f14 2
tuck - f10 2
tuck - f6 2
tuck - f2 2
tuck + f0 2
tuck + f4 2
tuck + f8 2
tuck + f12 2
tuck + f16 2
tuck + f20 2
tuck + f24 2
tuck + f28 2
tuck + f32 2
tuck + f36 2
tuck - f38 2
tuck - f34 2
tuck - f30 2
tuck - f26 2
tuck - f22 2
tuck - f18 2
tuck - f14 2
tuck - f10 2
tuck - f6 2
tuck - f2 2
tuck + f0 2
tuck + f4 2
tuck + f8 2
tuck + f12 2
tuck + f16 2
tuck + f20 2
tuck + f24 2
tuck + f28 2
tuck + f32 2
tuck + f36 2
releasehook 2
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f20 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f20 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
inhook 3;Activating carrier 3
tuck - b96 3
tuck - b92 3
tuck - b88 3
tuck - b84 3
tuck - b80 3
tuck - b76 3
tuck - b72 3
tuck - b68 3
tuck - b64 3
tuck - b60 3
tuck - b56 3
tuck - b52 3
tuck - b48 3
tuck - b44 3
tuck - b40 3
tuck - b36 3
tuck - b32 3
tuck - b28 3
tuck - b24 3
tuck - b20 3
drop b20
drop b24
drop b28
drop b32
drop b36
drop b40
drop b44
drop b48
drop b52
drop b56
drop b60
drop b64
drop b68
drop b72
drop b76
drop b80
drop b84
drop b88
drop b92
drop b96
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
knit - b38 2
knit - b36 2
knit - b34 2
knit - b32 2
knit - b30 2
knit - b28 2
knit - b26 2
knit - b24 2
knit - b22 2
knit - b20 2
knit - b18 2
knit - b16 2
knit - b14 2
knit - b12 2
knit - b10 2
knit - b8 2
knit - b6 2
knit - b4 2
knit - b2 2
knit - b0 2
knit + b0 2
knit + b2 2
knit + b4 2
knit + b6 2
knit + b8 2
knit + b10 2
knit + b12 2
knit + b14 2
knit + b16 2
knit + b18 2
knit + b20 2
knit + b22 2
knit + b24 2
knit + b26 2
knit + b28 2
knit + b30 2
knit + b32 2
knit + b34 2
knit + b36 2
knit + b38 2
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
knit - b38 2
knit - b36 2
knit - b34 2
knit - b32 2
knit - b30 2
knit - b28 2
knit - b26 2
knit - b24 2
knit - b22 2
knit - b20 2
knit - b18 2
knit - b16 2
knit - b14 2
knit - b12 2
knit - b10 2
knit - b8 2
knit - b6 2
knit - b4 2
knit - b2 2
knit - b0 2
knit + b0 2
knit + b2 2
knit + b4 2
knit + b6 2
knit + b8 2
knit + b10 2
knit + b12 2
knit + b14 2
knit + b16 2
knit + b18 2
knit + b20 2
knit + b22 2
knit + b24 2
knit + b26 2
knit + b28 2
knit + b30 2
knit + b32 2
knit + b34 2
knit + b36 2
knit + b38 2
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
knit - b38 2
knit - b36 2
knit - b34 2
knit - b32 2
knit - b30 2
knit - b28 2
knit - b26 2
knit - b24 2
knit - b22 2
knit - b20 2
knit - b18 2
knit - b16 2
knit - b14 2
knit - b12 2
knit - b10 2
knit - b8 2
knit - b6 2
knit - b4 2
knit - b2 2
knit - b0 2
knit + b0 2
knit + b2 2
knit + b4 2
knit + b6 2
knit + b8 2
knit + b10 2
knit + b12 2
knit + b14 2
knit + b16 2
knit + b18 2
knit + b20 2
knit + b22 2
knit + b24 2
knit + b26 2
knit + b28 2
knit + b30 2
knit + b32 2
knit + b34 2
knit + b36 2
knit + b38 2
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
knit - b38 2
knit - b36 2
knit - b34 2
knit - b32 2
knit - b30 2
knit - b28 2
knit - b26 2
knit - b24 2
knit - b22 2
knit - b20 2
knit - b18 2
knit - b16 2
knit - b14 2
knit - b12 2
knit - b10 2
knit - b8 2
knit - b6 2
knit - b4 2
knit - b2 2
knit - b0 2
knit + b0 2
knit + b2 2
knit + b4 2
knit + b6 2
knit + b8 2
knit + b10 2
knit + b12 2
knit + b14 2
knit + b16 2
knit + b18 2
knit + b20 2
knit + b22 2
knit + b24 2
knit + b26 2
knit + b28 2
knit + b30 2
knit + b32 2
knit + b34 2
knit + b36 2
knit + b38 2
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
knit - b38 2
knit - b36 2
knit - b34 2
knit - b32 2
knit - b30 2
knit - b28 2
knit - b26 2
knit - b24 2
knit - b22 2
knit - b20 2
knit - b18 2
knit - b16 2
knit - b14 2
knit - b12 2
knit - b10 2
knit - b8 2
knit - b6 2
knit - b4 2
knit - b2 2
knit - b0 2
knit + b0 2
knit + b2 2
knit + b4 2
knit + b6 2
knit + b8 2
knit + b10 2
knit + b12 2
knit + b14 2
knit + b16 2
knit + b18 2
knit + b20 2
knit + b22 2
knit + b24 2
knit + b26 2
knit + b28 2
knit + b30 2
knit + b32 2
knit + b34 2
knit + b36 2
knit + b38 2
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
knit - b38 2
knit - b36 2
knit - b34 2
knit - b32 2
knit - b30 2
knit - b28 2
knit - b26 2
knit - b24 2
knit - b22 2
knit - b20 2
knit - b18 2
knit - b16 2
knit - b14 2
knit - b12 2
knit - b10 2
knit - b8 2
knit - b6 2
knit - b4 2
knit - b2 2
knit - b0 2
knit + b0 2
knit + b2 2
knit + b4 2
knit + b6 2
knit + b8 2
knit + b10 2
knit + b12 2
knit + b14 2
knit + b16 2
knit + b18 2
knit + b20 2
knit + b22 2
knit + b24 2
knit + b26 2
knit + b28 2
knit + b30 2
knit + b32 2
knit + b34 2
knit + b36 2
knit + b38 2
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f38 2
knit - f36 2
knit - f34 2
knit - f32 2
knit - f30 2
knit - f28 2
knit - f26 2
knit - f24 2
knit - f22 2
knit - f18 2
knit - f16 2
knit - f14 2
knit - f12 2
knit - f10 2
knit - f8 2
knit - f6 2
knit - f4 2
knit - f2 2
knit - f0 2
tuck - f20 3
knit + f0 2
knit + f2 2
knit + f4 2
knit + f6 2
knit + f8 2
knit + f10 2
knit + f12 2
knit + f14 2
knit + f16 2
knit + f18 2
knit + f20 2
knit + f22 2
knit + f24 2
knit + f26 2
knit + f28 2
knit + f30 2
knit + f32 2
knit + f34 2
knit + f36 2
knit + f38 2
rack 2;Rack to 1 at 2 gauge
xfer f38 b36
rack 0.0;Rack to 0.0 at 2 gauge
xfer b36 f36
knit - f36 2
rack 2;Rack to 1 at 2 gauge
xfer f36 b34
rack 0.0;Rack to 0.0 at 2 gauge
xfer b34 f34
knit - f34 2
rack 2;Rack to 1 at 2 gauge
xfer f34 b32
rack 0.0;Rack to 0.0 at 2 gauge
xfer b32 f32
knit - f32 2
rack 2;Rack to 1 at 2 gauge
xfer f32 b30
rack 0.0;Rack to 0.0 at 2 gauge
xfer b30 f30
knit - f30 2
rack 2;Rack to 1 at 2 gauge
xfer f30 b28
rack 0.0;Rack to 0.0 at 2 gauge
xfer b28 f28
knit - f28 2
rack 2;Rack to 1 at 2 gauge
xfer f28 b26
rack 0.0;Rack to 0.0 at 2 gauge
xfer b26 f26
knit - f26 2
rack 2;Rack to 1 at 2 gauge
xfer f26 b24
rack 0.0;Rack to 0.0 at 2 gauge
xfer b24 f24
knit - f24 2
rack 2;Rack to 1 at 2 gauge
xfer f24 b22
rack 0.0;Rack to 0.0 at 2 gauge
xfer b22 f22
knit - f22 2
rack 2;Rack to 1 at 2 gauge
xfer f22 b20
rack 0.0;Rack to 0.0 at 2 gauge
xfer b20 f20
knit - f20 2
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
xfer b18 f18
knit - f18 2
rack 2;Rack to 1 at 2 gauge
xfer f18 b16
rack 0.0;Rack to 0.0 at 2 gauge
xfer b16 f16
knit - f16 2
rack 2;Rack to 1 at 2 gauge
xfer f16 b14
rack 0.0;Rack to 0.0 at 2 gauge
xfer b14 f14
knit - f14 2
rack 2;Rack to 1 at 2 gauge
xfer f14 b12
rack 0.0;Rack to 0.0 at 2 gauge
xfer b12 f12
knit - f12 2
rack 2;Rack to 1 at 2 gauge
xfer f12 b10
rack 0.0;Rack to 0.0 at 2 gauge
xfer b10 f10
knit - f10 2
rack 2;Rack to 1 at 2 gauge
xfer f10 b8
rack 0.0;Rack to 0.0 at 2 gauge
xfer b8 f8
knit - f8 2
rack 2;Rack to 1 at 2 gauge
xfer f8 b6
rack 0.0;Rack to 0.0 at 2 gauge
xfer b6 f6
knit - f6 2
rack 2;Rack to 1 at 2 gauge
xfer f6 b4
rack 0.0;Rack to 0.0 at 2 gauge
xfer b4 f4
knit - f4 2
rack 2;Rack to 1 at 2 gauge
xfer f4 b2
rack 0.0;Rack to 0.0 at 2 gauge
xfer b2 f2
knit - f2 2
rack 2;Rack to 1 at 2 gauge
xfer f2 b0
rack 0.0;Rack to 0.0 at 2 gauge
xfer b0 f0
knit - f0 2
;KS: Spare knitting on [f0]
knit + f0 2
releasehook 3;Release inserting hook before cutting all yarns
outhook 2;Cutting active yarn on 2
outhook 3;Cutting active yarn on 3
