;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 44loops from 0to 44
tuck - f43 1
tuck - f41 1
tuck - f39 1
tuck - f37 1
tuck - f35 1
tuck - f33 1
tuck - f31 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
tuck - f43 1
tuck - f41 1
tuck - f39 1
tuck - f37 1
tuck - f35 1
tuck - f33 1
tuck - f31 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
releasehook 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f35 b35
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f33 b34
xfer f21 b22
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b22 f22
xfer b10 f10
xfer b33 f33
xfer b21 f21
xfer b9 f9
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f33 b34
xfer f21 b22
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b22 f22
xfer b10 f10
xfer b33 f33
xfer b21 f21
xfer b9 f9
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f33 b34
xfer f21 b22
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b22 f22
xfer b10 f10
xfer b33 f33
xfer b21 f21
xfer b9 f9
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
xfer f22 b21
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f33 b34
xfer f21 b22
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b34 f34
xfer b22 f22
xfer b10 f10
xfer b33 f33
xfer b21 f21
xfer b9 f9
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - f34 1
knit - f33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f0 b0
xfer f1 b1
xfer f2 b2
xfer f3 b3
xfer f4 b4
xfer f5 b5
xfer f6 b6
xfer f7 b7
xfer f8 b8
xfer f9 b9
xfer f10 b10
xfer f11 b11
xfer f12 b12
xfer f13 b13
xfer f14 b14
xfer f15 b15
xfer f16 b16
xfer f17 b17
xfer f18 b18
xfer f19 b19
xfer f20 b20
xfer f21 b21
xfer f22 b22
xfer f23 b23
xfer f24 b24
xfer f25 b25
xfer f26 b26
xfer f27 b27
xfer f28 b28
xfer f29 b29
xfer f30 b30
xfer f31 b31
xfer f32 b32
xfer f33 b33
xfer f34 b34
xfer f35 b35
xfer f36 b36
xfer f37 b37
xfer f38 b38
xfer f39 b39
xfer f40 b40
xfer f41 b41
xfer f42 b42
xfer f43 b43
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
knit + b43 1
xfer b43 f43
xfer b42 f42
xfer b41 f41
xfer b40 f40
xfer b39 f39
xfer b38 f38
xfer b37 f37
xfer b36 f36
xfer b35 f35
xfer b34 f34
xfer b33 f33
xfer b32 f32
xfer b31 f31
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
rack 1;Rack to 1 at 1 gauge
xfer f43 b42
rack 0.0;Rack to 0.0 at 1 gauge
split + b42 f42 1
knit - f42 1
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
rack 0.0;Rack to 0.0 at 1 gauge
split + b41 f41 1
knit - f41 1
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
rack 0.0;Rack to 0.0 at 1 gauge
split + b40 f40 1
knit - f40 1
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
split + b39 f39 1
knit - f39 1
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
split + b38 f38 1
knit - f38 1
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
split + b37 f37 1
knit - f37 1
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
split + b36 f36 1
knit - f36 1
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
split + b35 f35 1
knit - f35 1
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
split + b34 f34 1
knit - f34 1
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
split + b33 f33 1
knit - f33 1
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
split + b32 f32 1
knit - f32 1
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
split + b31 f31 1
knit - f31 1
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
split + b30 f30 1
knit - f30 1
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
split + b29 f29 1
knit - f29 1
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 1
knit - f28 1
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 1
knit - f27 1
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 1
knit - f26 1
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
split + b25 f25 1
knit - f25 1
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
split + b24 f24 1
knit - f24 1
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 1
knit - f23 1
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 1
knit - f22 1
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 1
knit - f21 1
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
split + b20 f20 1
knit - f20 1
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
split + b19 f19 1
knit - f19 1
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 1
knit - f18 1
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 1
knit - f17 1
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 1
knit - f16 1
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
split + b15 f15 1
knit - f15 1
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
split + b14 f14 1
knit - f14 1
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 1
knit - f13 1
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 1
knit - f12 1
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 1
knit - f11 1
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
split + b10 f10 1
knit - f10 1
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
split + b9 f9 1
knit - f9 1
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 1
knit - f8 1
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 1
knit - f7 1
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 1
knit - f6 1
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 1
knit - f5 1
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 1
knit - f4 1
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 1
knit - f3 1
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 1
knit - f2 1
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 1
knit - f1 1
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 1
knit - f0 1
;KS: Spare knitting on [b42, b41, b40, b39, b38, b37, b36, b35, b34, b33, b32, b31, b30, b29, b28, b27, b26, b25, b24, b23, b22, b21, b20, b19, b18, b17, b16, b15, b14, b13, b12, b11, b10, b9, b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit + b31 1
knit + b32 1
knit + b33 1
knit + b34 1
knit + b35 1
knit + b36 1
knit + b37 1
knit + b38 1
knit + b39 1
knit + b40 1
knit + b41 1
knit + b42 1
outhook 1;Cutting active yarn on 1
