;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
tuck - f98 1
miss + f98 1
tuck - f98 1
miss - f96 1
tuck + f96 1
miss - f96 1
miss - f94 1
tuck + f94 1
miss - f94 1
miss - f92 1
tuck + f92 1
miss - f92 1
miss - f90 1
tuck + f90 1
miss - f90 1
miss - f88 1
tuck + f88 1
miss - f88 1
miss - f86 1
tuck + f86 1
miss - f86 1
miss - f84 1
tuck + f84 1
miss - f84 1
miss - f82 1
tuck + f82 1
miss - f82 1
miss - f80 1
tuck + f80 1
miss - f80 1
miss - f78 1
tuck + f78 1
miss - f78 1
miss - f76 1
tuck + f76 1
miss - f76 1
miss - f74 1
tuck + f74 1
miss - f74 1
miss - f72 1
tuck + f72 1
miss - f72 1
miss - f70 1
tuck + f70 1
miss - f70 1
miss - f68 1
tuck + f68 1
miss - f68 1
miss - f66 1
tuck + f66 1
miss - f66 1
miss - f64 1
tuck + f64 1
miss - f64 1
miss - f62 1
tuck + f62 1
miss - f62 1
miss - f60 1
tuck + f60 1
miss - f60 1
miss - f58 1
tuck + f58 1
miss - f58 1
miss - f56 1
tuck + f56 1
miss - f56 1
miss - f54 1
tuck + f54 1
miss - f54 1
miss - f52 1
tuck + f52 1
miss - f52 1
miss - f50 1
tuck + f50 1
miss - f50 1
miss - f48 1
tuck + f48 1
miss - f48 1
miss - f46 1
tuck + f46 1
miss - f46 1
miss - f44 1
tuck + f44 1
miss - f44 1
miss - f42 1
tuck + f42 1
miss - f42 1
miss - f40 1
tuck + f40 1
miss - f40 1
miss - f38 1
tuck + f38 1
miss - f38 1
miss - f36 1
tuck + f36 1
miss - f36 1
miss - f34 1
tuck + f34 1
miss - f34 1
miss - f32 1
tuck + f32 1
miss - f32 1
miss - f30 1
tuck + f30 1
miss - f30 1
miss - f28 1
tuck + f28 1
miss - f28 1
miss - f26 1
tuck + f26 1
miss - f26 1
miss - f24 1
tuck + f24 1
miss - f24 1
miss - f22 1
tuck + f22 1
miss - f22 1
miss - f20 1
tuck + f20 1
miss - f20 1
miss - f18 1
tuck + f18 1
miss - f18 1
miss - f16 1
tuck + f16 1
miss - f16 1
miss - f14 1
tuck + f14 1
miss - f14 1
miss - f12 1
tuck + f12 1
miss - f12 1
miss - f10 1
tuck + f10 1
miss - f10 1
miss - f8 1
tuck + f8 1
miss - f8 1
miss - f6 1
tuck + f6 1
miss - f6 1
miss - f4 1
tuck + f4 1
miss - f4 1
miss - f2 1
tuck + f2 1
miss - f2 1
miss - f0 1
tuck + f0 1
miss - f0 1
;KS: Cast on 50loops from f98to f0
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit + f64 1
knit + f66 1
knit + f68 1
knit + f70 1
knit + f72 1
knit + f74 1
knit + f76 1
knit + f78 1
knit + f80 1
knit + f82 1
knit + f84 1
knit + f86 1
knit + f88 1
knit + f90 1
knit + f92 1
knit + f94 1
knit + f96 1
knit + f98 1
knit - f98 1
knit - f96 1
knit - f94 1
knit - f92 1
knit - f90 1
knit - f88 1
knit - f86 1
knit - f84 1
knit - f82 1
knit - f80 1
knit - f78 1
knit - f76 1
knit - f74 1
knit - f72 1
knit - f70 1
knit - f68 1
knit - f66 1
knit - f64 1
knit - f62 1
knit - f60 1
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit + f64 1
knit + f66 1
knit + f68 1
knit + f70 1
knit + f72 1
knit + f74 1
knit + f76 1
knit + f78 1
knit + f80 1
knit + f82 1
knit + f84 1
knit + f86 1
knit + f88 1
knit + f90 1
knit + f92 1
knit + f94 1
knit + f96 1
knit + f98 1
releasehook 1
rack -1;Rack to -1 at 1 gauge
xfer f96 b97
xfer f92 b93
xfer f88 b89
xfer f84 b85
xfer f80 b81
xfer f76 b77
xfer f72 b73
xfer f68 b69
xfer f64 b65
xfer f60 b61
xfer f56 b57
xfer f52 b53
xfer f48 b49
xfer f44 b45
xfer f40 b41
xfer f36 b37
xfer f32 b33
xfer f28 b29
xfer f24 b25
xfer f20 b21
xfer f16 b17
xfer f12 b13
xfer f8 b9
xfer f4 b5
xfer f0 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b97 f97
xfer b93 f93
xfer b89 f89
xfer b85 f85
xfer b81 f81
xfer b77 f77
xfer b73 f73
xfer b69 f69
xfer b65 f65
xfer b61 f61
xfer b57 f57
xfer b53 f53
xfer b49 f49
xfer b45 f45
xfer b41 f41
xfer b37 f37
xfer b33 f33
xfer b29 f29
xfer b25 f25
xfer b21 f21
xfer b17 f17
xfer b13 f13
xfer b9 f9
xfer b5 f5
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f98 b97
xfer f94 b93
xfer f90 b89
xfer f86 b85
xfer f82 b81
xfer f78 b77
xfer f74 b73
xfer f70 b69
xfer f66 b65
xfer f62 b61
xfer f58 b57
xfer f54 b53
xfer f50 b49
xfer f46 b45
xfer f42 b41
xfer f38 b37
xfer f34 b33
xfer f30 b29
xfer f26 b25
xfer f22 b21
xfer f18 b17
xfer f14 b13
xfer f10 b9
xfer f6 b5
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f97 1
knit - b97 1
knit - f93 1
knit - b93 1
knit - f89 1
knit - b89 1
knit - f85 1
knit - b85 1
knit - f81 1
knit - b81 1
knit - f77 1
knit - b77 1
knit - f73 1
knit - b73 1
knit - f69 1
knit - b69 1
knit - f65 1
knit - b65 1
knit - f61 1
knit - b61 1
knit - f57 1
knit - b57 1
knit - f53 1
knit - b53 1
knit - f49 1
knit - b49 1
knit - f45 1
knit - b45 1
knit - f41 1
knit - b41 1
knit - f37 1
knit - b37 1
knit - f33 1
knit - b33 1
knit - f29 1
knit - b29 1
knit - f25 1
knit - b25 1
knit - f21 1
knit - b21 1
knit - f17 1
knit - b17 1
knit - f13 1
knit - b13 1
knit - f9 1
knit - b9 1
knit - f5 1
knit - b5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f9 b10
xfer f17 b18
xfer f25 b26
xfer f33 b34
xfer f41 b42
xfer f49 b50
xfer f57 b58
xfer f65 b66
xfer f73 b74
xfer f81 b82
xfer f89 b90
xfer f97 b98
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b5 f5
xfer b9 f9
xfer b10 f10
xfer b13 f13
xfer b17 f17
xfer b18 f18
xfer b21 f21
xfer b25 f25
xfer b26 f26
xfer b29 f29
xfer b33 f33
xfer b34 f34
xfer b37 f37
xfer b41 f41
xfer b42 f42
xfer b45 f45
xfer b49 f49
xfer b50 f50
xfer b53 f53
xfer b57 f57
xfer b58 f58
xfer b61 f61
xfer b65 f65
xfer b66 f66
xfer b69 f69
xfer b73 f73
xfer b74 f74
xfer b77 f77
xfer b81 f81
xfer b82 f82
xfer b85 f85
xfer b89 f89
xfer b90 f90
xfer b93 f93
xfer b97 f97
xfer b98 f98
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f9 b8
xfer f13 b12
xfer f18 b17
xfer f25 b24
xfer f29 b28
xfer f34 b33
xfer f41 b40
xfer f45 b44
xfer f50 b49
xfer f57 b56
xfer f61 b60
xfer f66 b65
xfer f73 b72
xfer f77 b76
xfer f82 b81
xfer f89 b88
xfer f93 b92
xfer f98 b97
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b8 1
knit + f10 1
knit + b12 1
knit + f17 1
knit + b17 1
knit + f21 1
knit + b24 1
knit + f26 1
knit + b28 1
knit + f33 1
knit + b33 1
knit + f37 1
knit + b40 1
knit + f42 1
knit + b44 1
knit + f49 1
knit + b49 1
knit + f53 1
knit + b56 1
knit + f58 1
knit + b60 1
knit + f65 1
knit + b65 1
knit + f69 1
knit + b72 1
knit + f74 1
knit + b76 1
knit + f81 1
knit + b81 1
knit + f85 1
knit + b88 1
knit + f90 1
knit + b92 1
knit + f97 1
knit + b97 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f97 b98
xfer f85 b86
xfer f74 b75
xfer f65 b66
xfer f53 b54
xfer f42 b43
xfer f33 b34
xfer f21 b22
xfer f10 b11
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b98 f98
xfer b97 f97
xfer b92 f92
xfer b88 f88
xfer b86 f86
xfer b81 f81
xfer b76 f76
xfer b75 f75
xfer b72 f72
xfer b66 f66
xfer b65 f65
xfer b60 f60
xfer b56 f56
xfer b54 f54
xfer b49 f49
xfer b44 f44
xfer b43 f43
xfer b40 f40
xfer b34 f34
xfer b33 f33
xfer b28 f28
xfer b24 f24
xfer b22 f22
xfer b17 f17
xfer b12 f12
xfer b11 f11
xfer b8 f8
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f97 b96
xfer f90 b89
xfer f86 b85
xfer f76 b75
xfer f72 b71
xfer f66 b65
xfer f60 b59
xfer f56 b55
xfer f49 b48
xfer f43 b42
xfer f37 b36
xfer f33 b32
xfer f26 b25
xfer f22 b21
xfer f12 b11
xfer f8 b7
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f98 1
knit - b96 1
knit - f92 1
knit - b89 1
knit - f88 1
knit - b85 1
knit - f81 1
knit - f75 1
knit - b75 1
knit - b71 1
knit - f69 1
knit - f65 1
knit - b65 1
knit - b59 1
knit - f58 1
knit - b55 1
knit - f54 1
knit - b48 1
knit - f44 1
knit - b42 1
knit - f40 1
knit - b36 1
knit - f34 1
knit - b32 1
knit - f28 1
knit - b25 1
knit - f24 1
knit - b21 1
knit - f17 1
knit - f11 1
knit - b11 1
knit - b7 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f11 b12
xfer f24 b25
xfer f34 b35
xfer f44 b45
xfer f58 b59
xfer f69 b70
xfer f81 b82
xfer f92 b93
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b7 f7
xfer b11 f11
xfer b12 f12
xfer b21 f21
xfer b25 f25
xfer b32 f32
xfer b35 f35
xfer b36 f36
xfer b42 f42
xfer b45 f45
xfer b48 f48
xfer b55 f55
xfer b59 f59
xfer b65 f65
xfer b70 f70
xfer b71 f71
xfer b75 f75
xfer b82 f82
xfer b85 f85
xfer b89 f89
xfer b93 f93
xfer b96 f96
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f7 b6
xfer f12 b11
xfer f21 b20
xfer f28 b27
xfer f35 b34
xfer f40 b39
xfer f45 b44
xfer f54 b53
xfer f59 b58
xfer f70 b69
xfer f75 b74
xfer f85 b84
xfer f89 b88
xfer f96 b95
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b6 1
knit + f11 1
knit + b11 1
knit + f17 1
knit + b20 1
knit + f25 1
knit + b27 1
knit + f32 1
knit + b34 1
knit + f36 1
knit + b39 1
knit + f42 1
knit + b44 1
knit + f48 1
knit + b53 1
knit + f55 1
knit + b58 1
knit + f65 1
knit + b69 1
knit + f71 1
knit + b74 1
knit + f82 1
knit + b84 1
knit + f88 1
knit + b88 1
knit + f93 1
knit + b95 1
knit + f98 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f93 b94
xfer f82 b83
xfer f65 b66
xfer f48 b49
xfer f36 b37
xfer f25 b26
xfer f11 b12
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b95 f95
xfer b94 f94
xfer b88 f88
xfer b84 f84
xfer b83 f83
xfer b74 f74
xfer b69 f69
xfer b66 f66
xfer b58 f58
xfer b53 f53
xfer b49 f49
xfer b44 f44
xfer b39 f39
xfer b37 f37
xfer b34 f34
xfer b27 f27
xfer b26 f26
xfer b20 f20
xfer b12 f12
xfer b11 f11
xfer b6 f6
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f98 b97
xfer f94 b93
xfer f84 b83
xfer f74 b73
xfer f69 b68
xfer f58 b57
xfer f53 b52
xfer f44 b43
xfer f39 b38
xfer f34 b33
xfer f27 b26
xfer f20 b19
xfer f12 b11
xfer f6 b5
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - b97 1
knit - f95 1
knit - b93 1
knit - f88 1
knit - f83 1
knit - b83 1
knit - b73 1
knit - f71 1
knit - b68 1
knit - f66 1
knit - b57 1
knit - f55 1
knit - b52 1
knit - f49 1
knit - b43 1
knit - f42 1
knit - b38 1
knit - f37 1
knit - b33 1
knit - f32 1
knit - f26 1
knit - b26 1
knit - b19 1
knit - f17 1
knit - f11 1
knit - b11 1
knit - f5 1
knit - b5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f11 b12
xfer f26 b27
xfer f37 b38
xfer f49 b50
xfer f66 b67
xfer f83 b84
xfer f95 b96
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b5 f5
xfer b11 f11
xfer b12 f12
xfer b19 f19
xfer b26 f26
xfer b27 f27
xfer b33 f33
xfer b38 f38
xfer b43 f43
xfer b50 f50
xfer b52 f52
xfer b57 f57
xfer b67 f67
xfer b68 f68
xfer b73 f73
xfer b83 f83
xfer b84 f84
xfer b93 f93
xfer b96 f96
xfer b97 f97
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f11 b10
xfer f17 b16
xfer f26 b25
xfer f32 b31
xfer f38 b37
xfer f43 b42
xfer f52 b51
xfer f57 b56
xfer f68 b67
xfer f73 b72
xfer f84 b83
xfer f93 b92
xfer f97 b96
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b10 1
knit + f12 1
knit + b16 1
knit + f19 1
knit + b25 1
knit + f27 1
knit + b31 1
knit + f33 1
knit + b37 1
knit + f42 1
knit + b42 1
knit + f50 1
knit + b51 1
knit + f55 1
knit + b56 1
knit + f67 1
knit + b67 1
knit + f71 1
knit + b72 1
knit + f83 1
knit + b83 1
knit + f88 1
knit + b92 1
knit + f96 1
knit + b96 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f88 b89
xfer f71 b72
xfer f55 b56
xfer f42 b43
xfer f27 b28
xfer f12 b13
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b96 f96
xfer b92 f92
xfer b89 f89
xfer b83 f83
xfer b72 f72
xfer b67 f67
xfer b56 f56
xfer b51 f51
xfer b43 f43
xfer b42 f42
xfer b37 f37
xfer b31 f31
xfer b28 f28
xfer b25 f25
xfer b16 f16
xfer b13 f13
xfer b10 f10
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f92 b91
xfer f83 b82
xfer f67 b66
xfer f51 b50
xfer f43 b42
xfer f37 b36
xfer f31 b30
xfer f25 b24
xfer f16 b15
xfer f10 b9
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f96 1
knit - b91 1
knit - f89 1
knit - b82 1
knit - f72 1
knit - b66 1
knit - f56 1
knit - f50 1
knit - b50 1
knit - f42 1
knit - b42 1
knit - b36 1
knit - f33 1
knit - b30 1
knit - f28 1
knit - b24 1
knit - f19 1
knit - b15 1
knit - f13 1
knit - b9 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f13 b14
xfer f28 b29
xfer f42 b43
xfer f56 b57
xfer f89 b90
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b9 f9
xfer b14 f14
xfer b15 f15
xfer b24 f24
xfer b29 f29
xfer b30 f30
xfer b36 f36
xfer b42 f42
xfer b43 f43
xfer b50 f50
xfer b57 f57
xfer b66 f66
xfer b82 f82
xfer b90 f90
xfer b91 f91
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f9 b8
xfer f15 b14
xfer f24 b23
xfer f30 b29
xfer f36 b35
xfer f43 b42
xfer f57 b56
xfer f72 b71
xfer f90 b89
xfer f96 b95
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b8 1
knit + f14 1
knit + b14 1
knit + f19 1
knit + b23 1
knit + f29 1
knit + b29 1
knit + f33 1
knit + b35 1
knit + f42 1
knit + b42 1
knit + f50 1
knit + b56 1
knit + f66 1
knit + b71 1
knit + f82 1
knit + b89 1
knit + f91 1
knit + b95 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f91 b92
xfer f66 b67
xfer f42 b43
xfer f29 b30
xfer f14 b15
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b95 f95
xfer b92 f92
xfer b89 f89
xfer b71 f71
xfer b67 f67
xfer b56 f56
xfer b43 f43
xfer b42 f42
xfer b35 f35
xfer b30 f30
xfer b29 f29
xfer b23 f23
xfer b15 f15
xfer b14 f14
xfer b8 f8
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f95 b94
xfer f89 b88
xfer f71 b70
xfer f56 b55
xfer f43 b42
xfer f35 b34
xfer f30 b29
xfer f23 b22
xfer f15 b14
xfer f8 b7
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - b94 1
knit - f92 1
knit - b88 1
knit - f82 1
knit - b70 1
knit - f67 1
knit - b55 1
knit - f50 1
knit - f42 1
knit - b42 1
knit - b34 1
knit - f33 1
knit - f29 1
knit - b29 1
knit - b22 1
knit - f19 1
knit - f14 1
knit - b14 1
knit - b7 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f14 b15
xfer f29 b30
xfer f42 b43
xfer f67 b68
xfer f92 b93
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b7 f7
xfer b14 f14
xfer b15 f15
xfer b22 f22
xfer b29 f29
xfer b30 f30
xfer b34 f34
xfer b42 f42
xfer b43 f43
xfer b55 f55
xfer b68 f68
xfer b70 f70
xfer b88 f88
xfer b93 f93
xfer b94 f94
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f7 b6
xfer f15 b14
xfer f22 b21
xfer f30 b29
xfer f34 b33
xfer f43 b42
xfer f55 b54
xfer f70 b69
xfer f88 b87
xfer f94 b93
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b6 1
knit + f14 1
knit + b14 1
knit + f19 1
knit + b21 1
knit + f29 1
knit + b29 1
knit + f33 1
knit + b33 1
knit + f42 1
knit + b42 1
knit + f50 1
knit + b54 1
knit + f68 1
knit + b69 1
knit + f82 1
knit + b87 1
knit + f93 1
knit + b93 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f93 b94
xfer f68 b69
xfer f42 b43
xfer f29 b30
xfer f14 b15
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b94 f94
xfer b93 f93
xfer b87 f87
xfer b69 f69
xfer b54 f54
xfer b43 f43
xfer b42 f42
xfer b33 f33
xfer b30 f30
xfer b29 f29
xfer b21 f21
xfer b15 f15
xfer b14 f14
xfer b6 f6
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f94 b93
xfer f87 b86
xfer f69 b68
xfer f50 b49
xfer f42 b41
xfer f30 b29
xfer f21 b20
xfer f15 b14
xfer f6 b5
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f93 1
knit - b93 1
knit - b86 1
knit - f82 1
knit - b68 1
knit - f54 1
knit - b49 1
knit - f43 1
knit - b41 1
knit - f33 1
knit - f29 1
knit - b29 1
knit - b20 1
knit - f19 1
knit - f14 1
knit - b14 1
knit - f5 1
knit - b5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f14 b15
xfer f29 b30
xfer f43 b44
xfer f82 b83
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b5 f5
xfer b14 f14
xfer b15 f15
xfer b20 f20
xfer b29 f29
xfer b30 f30
xfer b41 f41
xfer b44 f44
xfer b49 f49
xfer b68 f68
xfer b83 f83
xfer b86 f86
xfer b93 f93
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f14 b13
xfer f19 b18
xfer f29 b28
xfer f33 b32
xfer f44 b43
xfer f54 b53
xfer f83 b82
xfer f93 b92
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b13 1
knit + f15 1
knit + b18 1
knit + f20 1
knit + b28 1
knit + f30 1
knit + b32 1
knit + f41 1
knit + b43 1
knit + f49 1
knit + b53 1
knit + f68 1
knit + b82 1
knit + f86 1
knit + b92 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f86 b87
xfer f49 b50
xfer f30 b31
xfer f15 b16
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b92 f92
xfer b87 f87
xfer b82 f82
xfer b53 f53
xfer b50 f50
xfer b43 f43
xfer b32 f32
xfer b31 f31
xfer b28 f28
xfer b18 f18
xfer b16 f16
xfer b13 f13
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f92 b91
xfer f82 b81
xfer f53 b52
xfer f43 b42
xfer f32 b31
xfer f28 b27
xfer f18 b17
xfer f13 b12
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - b91 1
knit - f87 1
knit - b81 1
knit - f68 1
knit - b52 1
knit - f50 1
knit - b42 1
knit - f41 1
knit - f31 1
knit - b31 1
knit - b27 1
knit - f20 1
knit - b17 1
knit - f16 1
knit - b12 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f16 b17
xfer f31 b32
xfer f50 b51
xfer f87 b88
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b12 f12
xfer b17 f17
xfer b27 f27
xfer b31 f31
xfer b32 f32
xfer b42 f42
xfer b51 f51
xfer b52 f52
xfer b81 f81
xfer b88 f88
xfer b91 f91
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f12 b11
xfer f20 b19
xfer f31 b30
xfer f41 b40
xfer f51 b50
xfer f68 b67
xfer f88 b87
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b11 1
knit + f17 1
knit + b19 1
knit + f27 1
knit + b30 1
knit + f32 1
knit + b40 1
knit + f42 1
knit + b50 1
knit + f52 1
knit + b67 1
knit + f81 1
knit + b87 1
knit + f91 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f91 b92
xfer f52 b53
xfer f32 b33
xfer f17 b18
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b92 f92
xfer b87 f87
xfer b67 f67
xfer b53 f53
xfer b50 f50
xfer b40 f40
xfer b33 f33
xfer b30 f30
xfer b19 f19
xfer b18 f18
xfer b11 f11
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f87 b86
xfer f67 b66
xfer f50 b49
xfer f40 b39
xfer f30 b29
xfer f19 b18
xfer f11 b10
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f92 1
knit - b86 1
knit - f81 1
knit - b66 1
knit - f53 1
knit - b49 1
knit - f42 1
knit - b39 1
knit - f33 1
knit - b29 1
knit - f27 1
knit - f18 1
knit - b18 1
knit - b10 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f18 b19
xfer f33 b34
xfer f53 b54
xfer f92 b93
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b10 f10
xfer b18 f18
xfer b19 f19
xfer b29 f29
xfer b34 f34
xfer b39 f39
xfer b49 f49
xfer b54 f54
xfer b66 f66
xfer b86 f86
xfer b93 f93
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f10 b9
xfer f19 b18
xfer f29 b28
xfer f39 b38
xfer f49 b48
xfer f66 b65
xfer f86 b85
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b9 1
knit + f18 1
knit + b18 1
knit + f27 1
knit + b28 1
knit + f34 1
knit + b38 1
knit + f42 1
knit + b48 1
knit + f54 1
knit + b65 1
knit + f81 1
knit + b85 1
knit + f93 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f93 b94
xfer f54 b55
xfer f34 b35
xfer f18 b19
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b94 f94
xfer b85 f85
xfer b65 f65
xfer b55 f55
xfer b48 f48
xfer b38 f38
xfer b35 f35
xfer b28 f28
xfer b19 f19
xfer b18 f18
xfer b9 f9
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f85 b84
xfer f65 b64
xfer f48 b47
xfer f38 b37
xfer f28 b27
xfer f19 b18
xfer f9 b8
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f94 1
knit - b84 1
knit - f81 1
knit - b64 1
knit - f55 1
knit - b47 1
knit - f42 1
knit - b37 1
knit - f35 1
knit - f27 1
knit - b27 1
knit - f18 1
knit - b18 1
knit - b8 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f18 b19
xfer f35 b36
xfer f55 b56
xfer f94 b95
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b8 f8
xfer b18 f18
xfer b19 f19
xfer b27 f27
xfer b36 f36
xfer b37 f37
xfer b47 f47
xfer b56 f56
xfer b64 f64
xfer b84 f84
xfer b95 f95
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f8 b7
xfer f19 b18
xfer f36 b35
xfer f42 b41
xfer f56 b55
xfer f81 b80
xfer f95 b94
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b7 1
knit + f18 1
knit + b18 1
knit + f27 1
knit + b35 1
knit + f37 1
knit + b41 1
knit + f47 1
knit + b55 1
knit + f64 1
knit + b80 1
knit + f84 1
knit + b94 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f64 b65
xfer f37 b38
xfer f18 b19
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b94 f94
xfer b80 f80
xfer b65 f65
xfer b55 f55
xfer b41 f41
xfer b38 f38
xfer b35 f35
xfer b19 f19
xfer b18 f18
xfer b7 f7
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f94 b93
xfer f80 b79
xfer f55 b54
xfer f41 b40
xfer f35 b34
xfer f19 b18
xfer f7 b6
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - b93 1
knit - f84 1
knit - b79 1
knit - f65 1
knit - b54 1
knit - f47 1
knit - b40 1
knit - f38 1
knit - b34 1
knit - f27 1
knit - f18 1
knit - b18 1
knit - b6 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f18 b19
xfer f38 b39
xfer f65 b66
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b6 f6
xfer b18 f18
xfer b19 f19
xfer b34 f34
xfer b39 f39
xfer b40 f40
xfer b54 f54
xfer b66 f66
xfer b79 f79
xfer b93 f93
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f6 b5
xfer f19 b18
xfer f34 b33
xfer f40 b39
xfer f54 b53
xfer f79 b78
xfer f93 b92
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b5 1
knit + f18 1
knit + b18 1
knit + f27 1
knit + b33 1
knit + f39 1
knit + b39 1
knit + f47 1
knit + b53 1
knit + f66 1
knit + b78 1
knit + f84 1
knit + b92 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f66 b67
xfer f39 b40
xfer f18 b19
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b92 f92
xfer b78 f78
xfer b67 f67
xfer b53 f53
xfer b40 f40
xfer b39 f39
xfer b33 f33
xfer b19 f19
xfer b18 f18
xfer b5 f5
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f84 b83
xfer f67 b66
xfer f47 b46
xfer f39 b38
xfer f27 b26
xfer f18 b17
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f92 1
knit - b83 1
knit - f78 1
knit - b66 1
knit - f53 1
knit - b46 1
knit - f40 1
knit - b38 1
knit - f33 1
knit - b26 1
knit - f19 1
knit - b17 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f19 b20
xfer f40 b41
xfer f78 b79
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b17 f17
xfer b20 f20
xfer b26 f26
xfer b38 f38
xfer b41 f41
xfer b46 f46
xfer b66 f66
xfer b79 f79
xfer b83 f83
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f17 b16
xfer f26 b25
xfer f38 b37
xfer f46 b45
xfer f66 b65
xfer f83 b82
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b16 1
knit + f20 1
knit + b25 1
knit + f33 1
knit + b37 1
knit + f41 1
knit + b45 1
knit + f53 1
knit + b65 1
knit + f79 1
knit + b82 1
knit + f92 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f79 b80
xfer f41 b42
xfer f20 b21
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b82 f82
xfer b80 f80
xfer b65 f65
xfer b45 f45
xfer b42 f42
xfer b37 f37
xfer b25 f25
xfer b21 f21
xfer b16 f16
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
xfer f65 b64
xfer f45 b44
xfer f37 b36
xfer f25 b24
xfer f16 b15
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f92 1
knit - b81 1
knit - f80 1
knit - b64 1
knit - f53 1
knit - b44 1
knit - f42 1
knit - b36 1
knit - f33 1
knit - b24 1
knit - f21 1
knit - b15 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
xfer f21 b22
xfer f42 b43
xfer f80 b81
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b15 f15
xfer b22 f22
xfer b24 f24
xfer b36 f36
xfer b43 f43
xfer b44 f44
xfer b64 f64
xfer b81 f81
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f15 b14
xfer f24 b23
xfer f36 b35
xfer f44 b43
xfer f64 b63
xfer f92 b91
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit + f1 1
knit + b1 1
knit + f5 1
knit + b14 1
knit + f22 1
knit + b23 1
knit + f33 1
knit + b35 1
knit + f43 1
knit + b43 1
knit + f53 1
knit + b63 1
knit + f81 1
knit + b91 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f81 b82
xfer f43 b44
xfer f22 b23
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b91 f91
xfer b82 f82
xfer b63 f63
xfer b44 f44
xfer b43 f43
xfer b35 f35
xfer b23 f23
xfer b14 f14
xfer b2 f2
xfer b1 f1
rack 1;Rack to 1 at 1 gauge
xfer f82 b81
xfer f53 b52
xfer f43 b42
xfer f33 b32
xfer f14 b13
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f91 1
knit - b81 1
knit - f63 1
knit - b52 1
knit - f44 1
knit - b42 1
knit - f35 1
knit - b32 1
knit - f23 1
knit - b13 1
knit - f5 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
outhook 1;Cutting active yarn on 1
