;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
miss - f30 1
tuck + f30 1
miss - f30 1
miss - f29 1
tuck + f29 1
miss - f29 1
miss - f28 1
tuck + f28 1
miss - f28 1
miss - f27 1
tuck + f27 1
miss - f27 1
miss - f26 1
tuck + f26 1
miss - f26 1
miss - f25 1
tuck + f25 1
miss - f25 1
miss - f24 1
tuck + f24 1
miss - f24 1
miss - f23 1
tuck + f23 1
miss - f23 1
miss - f22 1
tuck + f22 1
miss - f22 1
miss - f21 1
tuck + f21 1
miss - f21 1
miss - f20 1
tuck + f20 1
miss - f20 1
miss - f19 1
tuck + f19 1
miss - f19 1
miss - f18 1
tuck + f18 1
miss - f18 1
miss - f17 1
tuck + f17 1
miss - f17 1
miss - f16 1
tuck + f16 1
miss - f16 1
miss - f15 1
tuck + f15 1
miss - f15 1
miss - f14 1
tuck + f14 1
miss - f14 1
miss - f13 1
tuck + f13 1
miss - f13 1
miss - f12 1
tuck + f12 1
miss - f12 1
miss - f11 1
tuck + f11 1
miss - f11 1
miss - f10 1
tuck + f10 1
miss - f10 1
miss - f9 1
tuck + f9 1
miss - f9 1
miss - f8 1
tuck + f8 1
miss - f8 1
miss - f7 1
tuck + f7 1
miss - f7 1
miss - f6 1
tuck + f6 1
miss - f6 1
miss - f5 1
tuck + f5 1
miss - f5 1
miss - f4 1
tuck + f4 1
miss - f4 1
miss - f3 1
tuck + f3 1
miss - f3 1
miss - f2 1
tuck + f2 1
miss - f2 1
miss - f1 1
tuck + f1 1
miss - f1 1
;KS: Cast on 30loops from f30to f1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
releasehook 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
;no-op. Releasehook with no hooked carriers
miss + b1 1
tuck - b1 1
miss + b1 1
miss + b2 1
tuck - b2 1
miss + b2 1
miss + b3 1
tuck - b3 1
miss + b3 1
miss + b4 1
tuck - b4 1
miss + b4 1
miss + b5 1
tuck - b5 1
miss + b5 1
miss + b6 1
tuck - b6 1
miss + b6 1
miss + b7 1
tuck - b7 1
miss + b7 1
miss + b8 1
tuck - b8 1
miss + b8 1
miss + b9 1
tuck - b9 1
miss + b9 1
miss + b10 1
tuck - b10 1
miss + b10 1
miss + b11 1
tuck - b11 1
miss + b11 1
miss + b12 1
tuck - b12 1
miss + b12 1
miss + b13 1
tuck - b13 1
miss + b13 1
miss + b14 1
tuck - b14 1
miss + b14 1
miss + b15 1
tuck - b15 1
miss + b15 1
miss + b16 1
tuck - b16 1
miss + b16 1
miss + b17 1
tuck - b17 1
miss + b17 1
miss + b18 1
tuck - b18 1
miss + b18 1
miss + b19 1
tuck - b19 1
miss + b19 1
miss + b20 1
tuck - b20 1
miss + b20 1
miss + b21 1
tuck - b21 1
miss + b21 1
miss + b22 1
tuck - b22 1
miss + b22 1
miss + b23 1
tuck - b23 1
miss + b23 1
miss + b24 1
tuck - b24 1
miss + b24 1
miss + b25 1
tuck - b25 1
miss + b25 1
miss + b26 1
tuck - b26 1
miss + b26 1
miss + b27 1
tuck - b27 1
miss + b27 1
miss + b28 1
tuck - b28 1
miss + b28 1
miss + b29 1
tuck - b29 1
miss + b29 1
miss + b30 1
tuck - b30 1
miss + b30 1
;KS: Cast on 60loops from b1to b30
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
;no-op. Releasehook with no hooked carriers
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
;no-op. Releasehook with no hooked carriers
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
rack -1;Rack to -1 at 1 gauge
xfer b1 f0
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b3 f2
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b5 f4
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b7 f6
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b9 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b11 f10
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b13 f12
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b15 f14
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b17 f16
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b19 f18
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b21 f20
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b23 f22
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b25 f24
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b27 f26
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer b29 f28
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit - f29 1
knit - b29 1
knit - f27 1
knit - b27 1
knit - f25 1
knit - b25 1
knit - f23 1
knit - b23 1
knit - f21 1
knit - b21 1
knit - f19 1
knit - b19 1
knit - f17 1
knit - b17 1
knit - f15 1
knit - b15 1
knit - f13 1
knit - b13 1
knit - f11 1
knit - b11 1
knit - f9 1
knit - b9 1
knit - f7 1
knit - b7 1
knit - f5 1
knit - b5 1
knit - f3 1
knit - b3 1
knit - f1 1
knit - b1 1
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
knit + f0 1
knit + f2 1
knit + b2 1
knit + f4 1
knit + b4 1
knit + f6 1
knit + b6 1
knit + f8 1
knit + b8 1
knit + f10 1
knit + b10 1
knit + f12 1
knit + b12 1
knit + f14 1
knit + b14 1
knit + f16 1
knit + b16 1
knit + f18 1
knit + b18 1
knit + f20 1
knit + b20 1
knit + f22 1
knit + b22 1
knit + f24 1
knit + b24 1
knit + f26 1
knit + b26 1
knit + f28 1
knit + b28 1
knit + b30 1
rack 0.0;Reset rack from all_needle
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b29 f30
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b27 f28
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b25 f26
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b23 f24
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f22 b23
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b21 f22
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f20 b21
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b19 f20
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b17 f18
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f16 b17
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b15 f16
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f14 b15
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b13 f14
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b11 f12
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b9 f10
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b7 f8
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b5 f6
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b3 f4
rack 0.0;Rack to 0.0 at 1 gauge
rack -1;Rack to -1 at 1 gauge
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer b1 f2
rack 0.0;Rack to 0.0 at 1 gauge
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + b30 1
outhook 1;Cutting active yarn on 1
