;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 80loops from 0to 80
tuck - f158 1
tuck - f154 1
tuck - f150 1
tuck - f146 1
tuck - f142 1
tuck - f138 1
tuck - f134 1
tuck - f130 1
tuck - f126 1
tuck - f122 1
tuck - f118 1
tuck - f114 1
tuck - f110 1
tuck - f106 1
tuck - f102 1
tuck - f98 1
tuck - f94 1
tuck - f90 1
tuck - f86 1
tuck - f82 1
tuck - f78 1
tuck - f74 1
tuck - f70 1
tuck - f66 1
tuck - f62 1
tuck - f58 1
tuck - f54 1
tuck - f50 1
tuck - f46 1
tuck - f42 1
tuck - f38 1
tuck - f34 1
tuck - f30 1
tuck - f26 1
tuck - f22 1
tuck - f18 1
tuck - f14 1
tuck - f10 1
tuck - f6 1
tuck - f2 1
tuck + f0 1
tuck + f4 1
tuck + f8 1
tuck + f12 1
tuck + f16 1
tuck + f20 1
tuck + f24 1
tuck + f28 1
tuck + f32 1
tuck + f36 1
tuck + f40 1
tuck + f44 1
tuck + f48 1
tuck + f52 1
tuck + f56 1
tuck + f60 1
tuck + f64 1
tuck + f68 1
tuck + f72 1
tuck + f76 1
tuck + f80 1
tuck + f84 1
tuck + f88 1
tuck + f92 1
tuck + f96 1
tuck + f100 1
tuck + f104 1
tuck + f108 1
tuck + f112 1
tuck + f116 1
tuck + f120 1
tuck + f124 1
tuck + f128 1
tuck + f132 1
tuck + f136 1
tuck + f140 1
tuck + f144 1
tuck + f148 1
tuck + f152 1
tuck + f156 1
tuck - f158 1
tuck - f154 1
tuck - f150 1
tuck - f146 1
tuck - f142 1
tuck - f138 1
tuck - f134 1
tuck - f130 1
tuck - f126 1
tuck - f122 1
tuck - f118 1
tuck - f114 1
tuck - f110 1
tuck - f106 1
tuck - f102 1
tuck - f98 1
tuck - f94 1
tuck - f90 1
tuck - f86 1
tuck - f82 1
tuck - f78 1
tuck - f74 1
tuck - f70 1
tuck - f66 1
tuck - f62 1
tuck - f58 1
tuck - f54 1
tuck - f50 1
tuck - f46 1
tuck - f42 1
tuck - f38 1
tuck - f34 1
tuck - f30 1
tuck - f26 1
tuck - f22 1
tuck - f18 1
tuck - f14 1
tuck - f10 1
tuck - f6 1
tuck - f2 1
tuck + f0 1
tuck + f4 1
tuck + f8 1
tuck + f12 1
tuck + f16 1
tuck + f20 1
tuck + f24 1
tuck + f28 1
tuck + f32 1
tuck + f36 1
tuck + f40 1
tuck + f44 1
tuck + f48 1
tuck + f52 1
tuck + f56 1
tuck + f60 1
tuck + f64 1
tuck + f68 1
tuck + f72 1
tuck + f76 1
tuck + f80 1
tuck + f84 1
tuck + f88 1
tuck + f92 1
tuck + f96 1
tuck + f100 1
tuck + f104 1
tuck + f108 1
tuck + f112 1
tuck + f116 1
tuck + f120 1
tuck + f124 1
tuck + f128 1
tuck + f132 1
tuck + f136 1
tuck + f140 1
tuck + f144 1
tuck + f148 1
tuck + f152 1
tuck + f156 1
releasehook 1
knit - f158 1
knit - f156 1
knit - f154 1
knit - f152 1
knit - f150 1
knit - f148 1
knit - f146 1
knit - f144 1
knit - f142 1
knit - f140 1
knit - f138 1
knit - f136 1
knit - f134 1
knit - f132 1
knit - f130 1
knit - f128 1
knit - f126 1
knit - f124 1
knit - f122 1
knit - f120 1
knit - f118 1
knit - f116 1
knit - f114 1
knit - f112 1
knit - f110 1
knit - f108 1
knit - f106 1
knit - f104 1
knit - f102 1
knit - f100 1
knit - f98 1
knit - f96 1
knit - f94 1
knit - f92 1
knit - f90 1
knit - f88 1
knit - f86 1
knit - f84 1
knit - f82 1
knit - f80 1
knit - f78 1
knit - f76 1
knit - f74 1
knit - f72 1
knit - f70 1
knit - f68 1
knit - f66 1
knit - f64 1
knit - f62 1
knit - f60 1
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit + f64 1
knit + f66 1
knit + f68 1
knit + f70 1
knit + f72 1
knit + f74 1
knit + f76 1
knit + f78 1
knit + f80 1
knit + f82 1
knit + f84 1
knit + f86 1
knit + f88 1
knit + f90 1
knit + f92 1
knit + f94 1
knit + f96 1
knit + f98 1
knit + f100 1
knit + f102 1
knit + f104 1
knit + f106 1
knit + f108 1
knit + f110 1
knit + f112 1
knit + f114 1
knit + f116 1
knit + f118 1
knit + f120 1
knit + f122 1
knit + f124 1
knit + f126 1
knit + f128 1
knit + f130 1
knit + f132 1
knit + f134 1
knit + f136 1
knit + f138 1
knit + f140 1
knit + f142 1
knit + f144 1
knit + f146 1
knit + f148 1
knit + f150 1
knit + f152 1
knit + f154 1
knit + f156 1
knit + f158 1
knit - f158 1
knit - f156 1
knit - f154 1
knit - f152 1
knit - f150 1
knit - f148 1
knit - f146 1
knit - f144 1
knit - f142 1
knit - f140 1
knit - f138 1
knit - f136 1
knit - f134 1
knit - f132 1
knit - f130 1
knit - f128 1
knit - f126 1
knit - f124 1
knit - f122 1
knit - f120 1
knit - f118 1
knit - f116 1
knit - f114 1
knit - f112 1
knit - f110 1
knit - f108 1
knit - f106 1
knit - f104 1
knit - f102 1
knit - f100 1
knit - f98 1
knit - f96 1
knit - f94 1
knit - f92 1
knit - f90 1
knit - f88 1
knit - f86 1
knit - f84 1
knit - f82 1
knit - f80 1
knit - f78 1
knit - f76 1
knit - f74 1
knit - f72 1
knit - f70 1
knit - f68 1
knit - f66 1
knit - f64 1
knit - f62 1
knit - f60 1
knit - f58 1
knit - f56 1
knit - f54 1
knit - f52 1
knit - f50 1
knit - f48 1
knit - f46 1
knit - f44 1
knit - f42 1
knit - f40 1
knit - f38 1
knit - f36 1
knit - f34 1
knit - f32 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
knit + f0 1
knit + f2 1
knit + f4 1
knit + f6 1
knit + f8 1
knit + f10 1
knit + f12 1
knit + f14 1
knit + f16 1
knit + f18 1
knit + f20 1
knit + f22 1
knit + f24 1
knit + f26 1
knit + f28 1
knit + f30 1
knit + f32 1
knit + f34 1
knit + f36 1
knit + f38 1
knit + f40 1
knit + f42 1
knit + f44 1
knit + f46 1
knit + f48 1
knit + f50 1
knit + f52 1
knit + f54 1
knit + f56 1
knit + f58 1
knit + f60 1
knit + f62 1
knit + f64 1
knit + f66 1
knit + f68 1
knit + f70 1
knit + f72 1
knit + f74 1
knit + f76 1
knit + f78 1
knit + f80 1
knit + f82 1
knit + f84 1
knit + f86 1
knit + f88 1
knit + f90 1
knit + f92 1
knit + f94 1
knit + f96 1
knit + f98 1
knit + f100 1
knit + f102 1
knit + f104 1
knit + f106 1
knit + f108 1
knit + f110 1
knit + f112 1
knit + f114 1
knit + f116 1
knit + f118 1
knit + f120 1
knit + f122 1
knit + f124 1
knit + f126 1
knit + f128 1
knit + f130 1
knit + f132 1
knit + f134 1
knit + f136 1
knit + f138 1
knit + f140 1
knit + f142 1
knit + f144 1
knit + f146 1
knit + f148 1
knit + f150 1
knit + f152 1
knit + f154 1
knit + f156 1
knit + f158 1
rack 2;Rack to 1 at 2 gauge
xfer f158 b156
xfer f154 b152
xfer f150 b148
xfer f146 b144
xfer f142 b140
xfer f138 b136
xfer f134 b132
xfer f130 b128
xfer f126 b124
xfer f122 b120
xfer f118 b116
xfer f114 b112
xfer f110 b108
xfer f106 b104
xfer f102 b100
xfer f98 b96
xfer f94 b92
xfer f90 b88
xfer f86 b84
xfer f82 b80
xfer f78 b76
xfer f74 b72
xfer f70 b68
xfer f66 b64
xfer f62 b60
xfer f58 b56
xfer f54 b52
xfer f50 b48
xfer f46 b44
xfer f42 b40
xfer f38 b36
xfer f34 b32
xfer f30 b28
xfer f26 b24
xfer f22 b20
xfer f18 b16
xfer f14 b12
xfer f10 b8
xfer f6 b4
xfer f2 b0
rack 0.0;Rack to 0.0 at 2 gauge
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
knit - f156 1
knit - f152 1
knit - f148 1
knit - f144 1
knit - f140 1
knit - f136 1
knit - f132 1
knit - f128 1
knit - f124 1
knit - f120 1
knit - f116 1
knit - f112 1
knit - f108 1
knit - f104 1
knit - f100 1
knit - f96 1
knit - f92 1
knit - f88 1
knit - f84 1
knit - f80 1
knit - f76 1
knit - f72 1
knit - f68 1
knit - f64 1
knit - f60 1
knit - f56 1
knit - f52 1
knit - f48 1
knit - f44 1
knit - f40 1
knit - f36 1
knit - f32 1
knit - f28 1
knit - f24 1
knit - f20 1
knit - f16 1
knit - f12 1
knit - f8 1
knit - f4 1
knit - f0 1
knit + b0 1
knit + b4 1
knit + b8 1
knit + b12 1
knit + b16 1
knit + b20 1
knit + b24 1
knit + b28 1
knit + b32 1
knit + b36 1
knit + b40 1
knit + b44 1
knit + b48 1
knit + b52 1
knit + b56 1
knit + b60 1
knit + b64 1
knit + b68 1
knit + b72 1
knit + b76 1
knit + b80 1
knit + b84 1
knit + b88 1
knit + b92 1
knit + b96 1
knit + b100 1
knit + b104 1
knit + b108 1
knit + b112 1
knit + b116 1
knit + b120 1
knit + b124 1
knit + b128 1
knit + b132 1
knit + b136 1
knit + b140 1
knit + b144 1
knit + b148 1
knit + b152 1
knit + b156 1
rack 2;Rack to 1 at 2 gauge
xfer f156 b154
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b154 f152
rack 0.0;Rack to 0.0 at 2 gauge
knit - f152 1
rack 2;Rack to 1 at 2 gauge
xfer f152 b150
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b150 f148
rack 0.0;Rack to 0.0 at 2 gauge
knit - f148 1
rack 2;Rack to 1 at 2 gauge
xfer f148 b146
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b146 f144
rack 0.0;Rack to 0.0 at 2 gauge
knit - f144 1
rack 2;Rack to 1 at 2 gauge
xfer f144 b142
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b142 f140
rack 0.0;Rack to 0.0 at 2 gauge
knit - f140 1
rack 2;Rack to 1 at 2 gauge
xfer f140 b138
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b138 f136
rack 0.0;Rack to 0.0 at 2 gauge
knit - f136 1
rack 2;Rack to 1 at 2 gauge
xfer f136 b134
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b134 f132
rack 0.0;Rack to 0.0 at 2 gauge
knit - f132 1
rack 2;Rack to 1 at 2 gauge
xfer f132 b130
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b130 f128
rack 0.0;Rack to 0.0 at 2 gauge
knit - f128 1
rack 2;Rack to 1 at 2 gauge
xfer f128 b126
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b126 f124
rack 0.0;Rack to 0.0 at 2 gauge
knit - f124 1
rack 2;Rack to 1 at 2 gauge
xfer f124 b122
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b122 f120
rack 0.0;Rack to 0.0 at 2 gauge
knit - f120 1
rack 2;Rack to 1 at 2 gauge
xfer f120 b118
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b118 f116
rack 0.0;Rack to 0.0 at 2 gauge
knit - f116 1
rack 2;Rack to 1 at 2 gauge
xfer f116 b114
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b114 f112
rack 0.0;Rack to 0.0 at 2 gauge
knit - f112 1
rack 2;Rack to 1 at 2 gauge
xfer f112 b110
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b110 f108
rack 0.0;Rack to 0.0 at 2 gauge
knit - f108 1
rack 2;Rack to 1 at 2 gauge
xfer f108 b106
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b106 f104
rack 0.0;Rack to 0.0 at 2 gauge
knit - f104 1
rack 2;Rack to 1 at 2 gauge
xfer f104 b102
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b102 f100
rack 0.0;Rack to 0.0 at 2 gauge
knit - f100 1
rack 2;Rack to 1 at 2 gauge
xfer f100 b98
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b98 f96
rack 0.0;Rack to 0.0 at 2 gauge
knit - f96 1
rack 2;Rack to 1 at 2 gauge
xfer f96 b94
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b94 f92
rack 0.0;Rack to 0.0 at 2 gauge
knit - f92 1
rack 2;Rack to 1 at 2 gauge
xfer f92 b90
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b90 f88
rack 0.0;Rack to 0.0 at 2 gauge
knit - f88 1
rack 2;Rack to 1 at 2 gauge
xfer f88 b86
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b86 f84
rack 0.0;Rack to 0.0 at 2 gauge
knit - f84 1
rack 2;Rack to 1 at 2 gauge
xfer f84 b82
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b82 f80
rack 0.0;Rack to 0.0 at 2 gauge
knit - f80 1
rack 2;Rack to 1 at 2 gauge
xfer f80 b78
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b78 f76
rack 0.0;Rack to 0.0 at 2 gauge
knit - f76 1
rack 2;Rack to 1 at 2 gauge
xfer f76 b74
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b74 f72
rack 0.0;Rack to 0.0 at 2 gauge
knit - f72 1
rack 2;Rack to 1 at 2 gauge
xfer f72 b70
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b70 f68
rack 0.0;Rack to 0.0 at 2 gauge
knit - f68 1
rack 2;Rack to 1 at 2 gauge
xfer f68 b66
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b66 f64
rack 0.0;Rack to 0.0 at 2 gauge
knit - f64 1
rack 2;Rack to 1 at 2 gauge
xfer f64 b62
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b62 f60
rack 0.0;Rack to 0.0 at 2 gauge
knit - f60 1
rack 2;Rack to 1 at 2 gauge
xfer f60 b58
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b58 f56
rack 0.0;Rack to 0.0 at 2 gauge
knit - f56 1
rack 2;Rack to 1 at 2 gauge
xfer f56 b54
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b54 f52
rack 0.0;Rack to 0.0 at 2 gauge
knit - f52 1
rack 2;Rack to 1 at 2 gauge
xfer f52 b50
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b50 f48
rack 0.0;Rack to 0.0 at 2 gauge
knit - f48 1
rack 2;Rack to 1 at 2 gauge
xfer f48 b46
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b46 f44
rack 0.0;Rack to 0.0 at 2 gauge
knit - f44 1
rack 2;Rack to 1 at 2 gauge
xfer f44 b42
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b42 f40
rack 0.0;Rack to 0.0 at 2 gauge
knit - f40 1
rack 2;Rack to 1 at 2 gauge
xfer f40 b38
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b38 f36
rack 0.0;Rack to 0.0 at 2 gauge
knit - f36 1
rack 2;Rack to 1 at 2 gauge
xfer f36 b34
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b34 f32
rack 0.0;Rack to 0.0 at 2 gauge
knit - f32 1
rack 2;Rack to 1 at 2 gauge
xfer f32 b30
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b30 f28
rack 0.0;Rack to 0.0 at 2 gauge
knit - f28 1
rack 2;Rack to 1 at 2 gauge
xfer f28 b26
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b26 f24
rack 0.0;Rack to 0.0 at 2 gauge
knit - f24 1
rack 2;Rack to 1 at 2 gauge
xfer f24 b22
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b22 f20
rack 0.0;Rack to 0.0 at 2 gauge
knit - f20 1
rack 2;Rack to 1 at 2 gauge
xfer f20 b18
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b18 f16
rack 0.0;Rack to 0.0 at 2 gauge
knit - f16 1
rack 2;Rack to 1 at 2 gauge
xfer f16 b14
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b14 f12
rack 0.0;Rack to 0.0 at 2 gauge
knit - f12 1
rack 2;Rack to 1 at 2 gauge
xfer f12 b10
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b10 f8
rack 0.0;Rack to 0.0 at 2 gauge
knit - f8 1
rack 2;Rack to 1 at 2 gauge
xfer f8 b6
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b6 f4
rack 0.0;Rack to 0.0 at 2 gauge
knit - f4 1
rack 2;Rack to 1 at 2 gauge
xfer f4 b2
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer b2 f0
rack 0.0;Rack to 0.0 at 2 gauge
knit - f0 1
;KS: Spare knitting on [f0]
knit + f0 1
rack 2;Rack to 1 at 2 gauge
xfer b0 f2
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f2 b4
rack 0.0;Rack to 0.0 at 2 gauge
knit + b4 1
rack 2;Rack to 1 at 2 gauge
xfer b4 f6
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f6 b8
rack 0.0;Rack to 0.0 at 2 gauge
knit + b8 1
rack 2;Rack to 1 at 2 gauge
xfer b8 f10
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f10 b12
rack 0.0;Rack to 0.0 at 2 gauge
knit + b12 1
rack 2;Rack to 1 at 2 gauge
xfer b12 f14
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f14 b16
rack 0.0;Rack to 0.0 at 2 gauge
knit + b16 1
rack 2;Rack to 1 at 2 gauge
xfer b16 f18
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f18 b20
rack 0.0;Rack to 0.0 at 2 gauge
knit + b20 1
rack 2;Rack to 1 at 2 gauge
xfer b20 f22
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f22 b24
rack 0.0;Rack to 0.0 at 2 gauge
knit + b24 1
rack 2;Rack to 1 at 2 gauge
xfer b24 f26
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f26 b28
rack 0.0;Rack to 0.0 at 2 gauge
knit + b28 1
rack 2;Rack to 1 at 2 gauge
xfer b28 f30
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f30 b32
rack 0.0;Rack to 0.0 at 2 gauge
knit + b32 1
rack 2;Rack to 1 at 2 gauge
xfer b32 f34
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f34 b36
rack 0.0;Rack to 0.0 at 2 gauge
knit + b36 1
rack 2;Rack to 1 at 2 gauge
xfer b36 f38
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f38 b40
rack 0.0;Rack to 0.0 at 2 gauge
knit + b40 1
rack 2;Rack to 1 at 2 gauge
xfer b40 f42
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f42 b44
rack 0.0;Rack to 0.0 at 2 gauge
knit + b44 1
rack 2;Rack to 1 at 2 gauge
xfer b44 f46
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f46 b48
rack 0.0;Rack to 0.0 at 2 gauge
knit + b48 1
rack 2;Rack to 1 at 2 gauge
xfer b48 f50
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f50 b52
rack 0.0;Rack to 0.0 at 2 gauge
knit + b52 1
rack 2;Rack to 1 at 2 gauge
xfer b52 f54
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f54 b56
rack 0.0;Rack to 0.0 at 2 gauge
knit + b56 1
rack 2;Rack to 1 at 2 gauge
xfer b56 f58
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f58 b60
rack 0.0;Rack to 0.0 at 2 gauge
knit + b60 1
rack 2;Rack to 1 at 2 gauge
xfer b60 f62
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f62 b64
rack 0.0;Rack to 0.0 at 2 gauge
knit + b64 1
rack 2;Rack to 1 at 2 gauge
xfer b64 f66
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f66 b68
rack 0.0;Rack to 0.0 at 2 gauge
knit + b68 1
rack 2;Rack to 1 at 2 gauge
xfer b68 f70
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f70 b72
rack 0.0;Rack to 0.0 at 2 gauge
knit + b72 1
rack 2;Rack to 1 at 2 gauge
xfer b72 f74
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f74 b76
rack 0.0;Rack to 0.0 at 2 gauge
knit + b76 1
rack 2;Rack to 1 at 2 gauge
xfer b76 f78
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f78 b80
rack 0.0;Rack to 0.0 at 2 gauge
knit + b80 1
rack 2;Rack to 1 at 2 gauge
xfer b80 f82
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f82 b84
rack 0.0;Rack to 0.0 at 2 gauge
knit + b84 1
rack 2;Rack to 1 at 2 gauge
xfer b84 f86
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f86 b88
rack 0.0;Rack to 0.0 at 2 gauge
knit + b88 1
rack 2;Rack to 1 at 2 gauge
xfer b88 f90
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f90 b92
rack 0.0;Rack to 0.0 at 2 gauge
knit + b92 1
rack 2;Rack to 1 at 2 gauge
xfer b92 f94
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f94 b96
rack 0.0;Rack to 0.0 at 2 gauge
knit + b96 1
rack 2;Rack to 1 at 2 gauge
xfer b96 f98
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f98 b100
rack 0.0;Rack to 0.0 at 2 gauge
knit + b100 1
rack 2;Rack to 1 at 2 gauge
xfer b100 f102
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f102 b104
rack 0.0;Rack to 0.0 at 2 gauge
knit + b104 1
rack 2;Rack to 1 at 2 gauge
xfer b104 f106
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f106 b108
rack 0.0;Rack to 0.0 at 2 gauge
knit + b108 1
rack 2;Rack to 1 at 2 gauge
xfer b108 f110
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f110 b112
rack 0.0;Rack to 0.0 at 2 gauge
knit + b112 1
rack 2;Rack to 1 at 2 gauge
xfer b112 f114
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f114 b116
rack 0.0;Rack to 0.0 at 2 gauge
knit + b116 1
rack 2;Rack to 1 at 2 gauge
xfer b116 f118
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f118 b120
rack 0.0;Rack to 0.0 at 2 gauge
knit + b120 1
rack 2;Rack to 1 at 2 gauge
xfer b120 f122
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f122 b124
rack 0.0;Rack to 0.0 at 2 gauge
knit + b124 1
rack 2;Rack to 1 at 2 gauge
xfer b124 f126
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f126 b128
rack 0.0;Rack to 0.0 at 2 gauge
knit + b128 1
rack 2;Rack to 1 at 2 gauge
xfer b128 f130
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f130 b132
rack 0.0;Rack to 0.0 at 2 gauge
knit + b132 1
rack 2;Rack to 1 at 2 gauge
xfer b132 f134
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f134 b136
rack 0.0;Rack to 0.0 at 2 gauge
knit + b136 1
rack 2;Rack to 1 at 2 gauge
xfer b136 f138
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f138 b140
rack 0.0;Rack to 0.0 at 2 gauge
knit + b140 1
rack 2;Rack to 1 at 2 gauge
xfer b140 f142
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f142 b144
rack 0.0;Rack to 0.0 at 2 gauge
knit + b144 1
rack 2;Rack to 1 at 2 gauge
xfer b144 f146
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f146 b148
rack 0.0;Rack to 0.0 at 2 gauge
knit + b148 1
rack 2;Rack to 1 at 2 gauge
xfer b148 f150
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f150 b152
rack 0.0;Rack to 0.0 at 2 gauge
knit + b152 1
rack 2;Rack to 1 at 2 gauge
xfer b152 f154
rack 0.0;Rack to 0.0 at 2 gauge
rack -2;Rack to -1 at 2 gauge
xfer f154 b156
rack 0.0;Rack to 0.0 at 2 gauge
knit + b156 1
;KS: Spare knitting on [b156]
knit - b156 1
outhook 1;Cutting active yarn on 1
