;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
miss - f19 1
tuck + f19 1
miss - f19 1
miss - f18 1
tuck + f18 1
miss - f18 1
miss - f17 1
tuck + f17 1
miss - f17 1
miss - f16 1
tuck + f16 1
miss - f16 1
miss - f15 1
tuck + f15 1
miss - f15 1
miss - f14 1
tuck + f14 1
miss - f14 1
miss - f13 1
tuck + f13 1
miss - f13 1
miss - f12 1
tuck + f12 1
miss - f12 1
miss - f11 1
tuck + f11 1
miss - f11 1
miss - f10 1
tuck + f10 1
miss - f10 1
miss - f9 1
tuck + f9 1
miss - f9 1
miss - f8 1
tuck + f8 1
miss - f8 1
miss - f7 1
tuck + f7 1
miss - f7 1
miss - f6 1
tuck + f6 1
miss - f6 1
miss - f5 1
tuck + f5 1
miss - f5 1
miss - f4 1
tuck + f4 1
miss - f4 1
miss - f3 1
tuck + f3 1
miss - f3 1
miss - f2 1
tuck + f2 1
miss - f2 1
miss - f1 1
tuck + f1 1
miss - f1 1
miss - f0 1
tuck + f0 1
miss - f0 1
;KS: Cast on 20loops from f19to f0
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
releasehook 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
miss + f20 1
tuck - f20 1
miss + f20 1
miss + f21 1
tuck - f21 1
miss + f21 1
miss + f22 1
tuck - f22 1
miss + f22 1
;KS: Cast on 23loops from f20to f22
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
xfer f21 b20
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b21 f21
xfer b20 f20
xfer b19 f19
knit - f21 1
knit - f20 1
knit - f19 1
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
xfer f20 b19
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
xfer b18 f18
xfer b19 f19
xfer b20 f20
knit - f20 1
knit - f19 1
knit - f18 1
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
xfer f19 b18
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
xfer b17 f17
xfer b18 f18
xfer b19 f19
knit - f19 1
knit - f18 1
knit - f17 1
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
xfer f18 b17
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
xfer b16 f16
xfer b17 f17
xfer b18 f18
knit - f18 1
knit - f17 1
knit - f16 1
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
xfer f17 b16
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
xfer b15 f15
xfer b16 f16
xfer b17 f17
knit - f17 1
knit - f16 1
knit - f15 1
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
xfer f16 b15
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
xfer b14 f14
xfer b15 f15
xfer b16 f16
knit - f16 1
knit - f15 1
knit - f14 1
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
xfer f15 b14
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
xfer b13 f13
xfer b14 f14
xfer b15 f15
knit - f15 1
knit - f14 1
knit - f13 1
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
xfer f14 b13
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
xfer b12 f12
xfer b13 f13
xfer b14 f14
knit - f14 1
knit - f13 1
knit - f12 1
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
xfer f13 b12
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
xfer b11 f11
xfer b12 f12
xfer b13 f13
knit - f13 1
knit - f12 1
knit - f11 1
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
xfer f12 b11
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
xfer b10 f10
xfer b11 f11
xfer b12 f12
knit - f12 1
knit - f11 1
knit - f10 1
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
xfer f11 b10
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
xfer b9 f9
xfer b10 f10
xfer b11 f11
knit - f11 1
knit - f10 1
knit - f9 1
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
xfer f10 b9
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
xfer b8 f8
xfer b9 f9
xfer b10 f10
knit - f10 1
knit - f9 1
knit - f8 1
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
xfer f9 b8
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
xfer b7 f7
xfer b8 f8
xfer b9 f9
knit - f9 1
knit - f8 1
knit - f7 1
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
xfer f8 b7
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
xfer b6 f6
xfer b7 f7
xfer b8 f8
knit - f8 1
knit - f7 1
knit - f6 1
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
xfer f7 b6
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
xfer b5 f5
xfer b6 f6
xfer b7 f7
knit - f7 1
knit - f6 1
knit - f5 1
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
xfer f6 b5
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
xfer b4 f4
xfer b5 f5
xfer b6 f6
knit - f6 1
knit - f5 1
knit - f4 1
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
xfer f5 b4
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
xfer b3 f3
xfer b4 f4
xfer b5 f5
knit - f5 1
knit - f4 1
knit - f3 1
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
xfer f4 b3
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
xfer b2 f2
xfer b3 f3
xfer b4 f4
knit - f4 1
knit - f3 1
knit - f2 1
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
xfer f3 b2
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
xfer b2 f2
xfer b3 f3
knit - f3 1
knit - f2 1
knit - f1 1
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
xfer f2 b1
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
xfer b1 f1
xfer b2 f2
knit - f2 1
knit - f1 1
knit - f0 1
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
xfer b1 f1
knit - f1 1
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
xfer b0 f0
knit - f0 1
outhook 1;Cutting active yarn on 1
