;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 5;Activating carrier 5
;KS: Cast on 56loops from 0to 56
tuck - f55 5
tuck - f53 5
tuck - f51 5
tuck - f49 5
tuck - f47 5
tuck - f45 5
tuck - f43 5
tuck - f41 5
tuck - f39 5
tuck - f37 5
tuck - f35 5
tuck - f33 5
tuck - f31 5
tuck - f29 5
tuck - f27 5
tuck - f25 5
tuck - f23 5
tuck - f21 5
tuck - f19 5
tuck - f17 5
tuck - f15 5
tuck - f13 5
tuck - f11 5
tuck - f9 5
tuck - f7 5
tuck - f5 5
tuck - f3 5
tuck - f1 5
tuck + f0 5
tuck + f2 5
tuck + f4 5
tuck + f6 5
tuck + f8 5
tuck + f10 5
tuck + f12 5
tuck + f14 5
tuck + f16 5
tuck + f18 5
tuck + f20 5
tuck + f22 5
tuck + f24 5
tuck + f26 5
tuck + f28 5
tuck + f30 5
tuck + f32 5
tuck + f34 5
tuck + f36 5
tuck + f38 5
tuck + f40 5
tuck + f42 5
tuck + f44 5
tuck + f46 5
tuck + f48 5
tuck + f50 5
tuck + f52 5
tuck + f54 5
tuck - f55 5
tuck - f53 5
tuck - f51 5
tuck - f49 5
tuck - f47 5
tuck - f45 5
tuck - f43 5
tuck - f41 5
tuck - f39 5
tuck - f37 5
tuck - f35 5
tuck - f33 5
tuck - f31 5
tuck - f29 5
tuck - f27 5
tuck - f25 5
tuck - f23 5
tuck - f21 5
tuck - f19 5
tuck - f17 5
tuck - f15 5
tuck - f13 5
tuck - f11 5
tuck - f9 5
tuck - f7 5
tuck - f5 5
tuck - f3 5
tuck - f1 5
tuck + f0 5
tuck + f2 5
tuck + f4 5
tuck + f6 5
tuck + f8 5
tuck + f10 5
tuck + f12 5
tuck + f14 5
tuck + f16 5
tuck + f18 5
tuck + f20 5
tuck + f22 5
tuck + f24 5
tuck + f26 5
tuck + f28 5
tuck + f30 5
tuck + f32 5
tuck + f34 5
tuck + f36 5
tuck + f38 5
tuck + f40 5
tuck + f42 5
tuck + f44 5
tuck + f46 5
tuck + f48 5
tuck + f50 5
tuck + f52 5
tuck + f54 5
releasehook 5
knit - f55 5
knit - f54 5
knit - f53 5
knit - f52 5
knit - f51 5
knit - f50 5
knit - f49 5
knit - f48 5
knit - f47 5
knit - f46 5
knit - f45 5
knit - f44 5
knit - f43 5
knit - f42 5
knit - f41 5
knit - f40 5
knit - f39 5
knit - f38 5
knit - f37 5
knit - f36 5
knit - f35 5
knit - f34 5
knit - f33 5
knit - f32 5
knit - f31 5
knit - f30 5
knit - f29 5
knit - f28 5
knit - f27 5
knit - f26 5
knit - f25 5
knit - f24 5
knit - f23 5
knit - f22 5
knit - f21 5
knit - f20 5
knit - f19 5
knit - f18 5
knit - f17 5
knit - f16 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f16 5
knit + f17 5
knit + f18 5
knit + f19 5
knit + f20 5
knit + f21 5
knit + f22 5
knit + f23 5
knit + f24 5
knit + f25 5
knit + f26 5
knit + f27 5
knit + f28 5
knit + f29 5
knit + f30 5
knit + f31 5
knit + f32 5
knit + f33 5
knit + f34 5
knit + f35 5
knit + f36 5
knit + f37 5
knit + f38 5
knit + f39 5
knit + f40 5
knit + f41 5
knit + f42 5
knit + f43 5
knit + f44 5
knit + f45 5
knit + f46 5
knit + f47 5
knit + f48 5
knit + f49 5
knit + f50 5
knit + f51 5
knit + f52 5
knit + f53 5
knit + f54 5
knit + f55 5
knit - f55 5
knit - f54 5
knit - f53 5
knit - f52 5
knit - f51 5
knit - f50 5
knit - f49 5
knit - f48 5
knit - f47 5
knit - f46 5
knit - f45 5
knit - f44 5
knit - f43 5
knit - f42 5
knit - f41 5
knit - f40 5
knit - f39 5
knit - f38 5
knit - f37 5
knit - f36 5
knit - f35 5
knit - f34 5
knit - f33 5
knit - f32 5
knit - f31 5
knit - f30 5
knit - f29 5
knit - f28 5
knit - f27 5
knit - f26 5
knit - f25 5
knit - f24 5
knit - f23 5
knit - f22 5
knit - f21 5
knit - f20 5
knit - f19 5
knit - f18 5
knit - f17 5
knit - f16 5
knit - f15 5
knit - f14 5
knit - f13 5
knit - f12 5
knit - f11 5
knit - f10 5
knit - f9 5
knit - f8 5
knit - f7 5
knit - f6 5
knit - f5 5
knit - f4 5
knit - f3 5
knit - f2 5
knit - f1 5
knit - f0 5
knit + f0 5
knit + f1 5
knit + f2 5
knit + f3 5
knit + f4 5
knit + f5 5
knit + f6 5
knit + f7 5
knit + f8 5
knit + f9 5
knit + f10 5
knit + f11 5
knit + f12 5
knit + f13 5
knit + f14 5
knit + f15 5
knit + f16 5
knit + f17 5
knit + f18 5
knit + f19 5
knit + f20 5
knit + f21 5
knit + f22 5
knit + f23 5
knit + f24 5
knit + f25 5
knit + f26 5
knit + f27 5
knit + f28 5
knit + f29 5
knit + f30 5
knit + f31 5
knit + f32 5
knit + f33 5
knit + f34 5
knit + f35 5
knit + f36 5
knit + f37 5
knit + f38 5
knit + f39 5
knit + f40 5
knit + f41 5
knit + f42 5
knit + f43 5
knit + f44 5
knit + f45 5
knit + f46 5
knit + f47 5
knit + f48 5
knit + f49 5
knit + f50 5
knit + f51 5
knit + f52 5
knit + f53 5
knit + f54 5
knit + f55 5
xfer f55 b55
xfer f53 b53
xfer f51 b51
xfer f49 b49
xfer f47 b47
xfer f45 b45
xfer f43 b43
xfer f41 b41
xfer f39 b39
xfer f37 b37
xfer f35 b35
xfer f33 b33
xfer f31 b31
xfer f29 b29
xfer f27 b27
xfer f25 b25
xfer f23 b23
xfer f21 b21
xfer f19 b19
xfer f17 b17
xfer f15 b15
xfer f13 b13
xfer f11 b11
xfer f9 b9
xfer f7 b7
xfer f5 b5
xfer f3 b3
xfer f1 b1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - f38 5
knit - f36 5
knit - f34 5
knit - f32 5
knit - f30 5
knit - f28 5
knit - f26 5
knit - f24 5
knit - f22 5
knit - f20 5
knit - f18 5
knit - f16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + f16 5
knit + f18 5
knit + f20 5
knit + f22 5
knit + f24 5
knit + f26 5
knit + f28 5
knit + f30 5
knit + f32 5
knit + f34 5
knit + f36 5
knit + f38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
inhook 8;Activating carrier 8
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - b39 8
knit - b37 8
knit - b35 8
knit - b33 8
knit - b31 8
knit - b29 8
knit - b27 8
knit - b25 8
knit - b23 8
knit - b21 8
knit - b19 8
knit - b17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + b17 8
knit + b19 8
knit + b21 8
knit + b23 8
knit + b25 8
knit + b27 8
knit + b29 8
knit + b31 8
knit + b33 8
knit + b35 8
knit + b37 8
knit + b39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b47 f47
xfer b45 f45
xfer b43 f43
xfer b41 f41
xfer b39 f39
xfer b37 f37
xfer b35 f35
xfer b33 f33
xfer b31 f31
xfer b29 f29
xfer b27 f27
xfer b25 f25
xfer b23 f23
xfer b21 f21
xfer b19 f19
xfer b17 f17
xfer b15 f15
xfer b13 f13
xfer b11 f11
xfer b9 f9
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
xfer f55 b55
xfer f53 b53
xfer f51 b51
xfer f49 b49
xfer f47 b47
xfer f45 b45
xfer f43 b43
xfer f41 b41
xfer f39 b39
xfer f37 b37
xfer f35 b35
xfer f33 b33
xfer f31 b31
xfer f29 b29
xfer f27 b27
xfer f25 b25
xfer f23 b23
xfer f21 b21
xfer f19 b19
xfer f17 b17
xfer f15 b15
xfer f13 b13
xfer f11 b11
xfer f9 b9
xfer f7 b7
xfer f5 b5
xfer f3 b3
xfer f1 b1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - f38 5
knit - f36 5
knit - f34 5
knit - f32 5
knit - f30 5
knit - f28 5
knit - f26 5
knit - f24 5
knit - f22 5
knit - f20 5
knit - f18 5
knit - f16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - b39 8
knit - b37 8
knit - b35 8
knit - b33 8
knit - b31 8
knit - b29 8
knit - b27 8
knit - b25 8
knit - b23 8
knit - b21 8
knit - b19 8
knit - b17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + f16 5
knit + f18 5
knit + f20 5
knit + f22 5
knit + f24 5
knit + f26 5
knit + f28 5
knit + f30 5
knit + f32 5
knit + f34 5
knit + f36 5
knit + f38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + b17 8
knit + b19 8
knit + b21 8
knit + b23 8
knit + b25 8
knit + b27 8
knit + b29 8
knit + b31 8
knit + b33 8
knit + b35 8
knit + b37 8
knit + b39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - f38 5
knit - f36 5
knit - f34 5
knit - f32 5
knit - f30 5
knit - f28 5
knit - f26 5
knit - f24 5
knit - f22 5
knit - f20 5
knit - f18 5
knit - f16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - b39 8
knit - b37 8
knit - b35 8
knit - b33 8
knit - b31 8
knit - b29 8
knit - b27 8
knit - b25 8
knit - b23 8
knit - b21 8
knit - b19 8
knit - b17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + f16 5
knit + f18 5
knit + f20 5
knit + f22 5
knit + f24 5
knit + f26 5
knit + f28 5
knit + f30 5
knit + f32 5
knit + f34 5
knit + f36 5
knit + f38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + b17 8
knit + b19 8
knit + b21 8
knit + b23 8
knit + b25 8
knit + b27 8
knit + b29 8
knit + b31 8
knit + b33 8
knit + b35 8
knit + b37 8
knit + b39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b47 f47
xfer b45 f45
xfer b43 f43
xfer b41 f41
xfer b39 f39
xfer b37 f37
xfer b35 f35
xfer b33 f33
xfer b31 f31
xfer b29 f29
xfer b27 f27
xfer b25 f25
xfer b23 f23
xfer b21 f21
xfer b19 f19
xfer b17 f17
xfer b15 f15
xfer b13 f13
xfer b11 f11
xfer b9 f9
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
xfer f46 b46
xfer f44 b44
xfer f42 b42
xfer f40 b40
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f55 b55
xfer f53 b53
xfer f51 b51
xfer f49 b49
xfer f31 b31
xfer f29 b29
xfer f27 b27
xfer f25 b25
xfer f7 b7
xfer f5 b5
xfer f3 b3
xfer f1 b1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [648 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [649 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [650 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [651 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [652 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [653 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [654 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [655 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [660 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [661 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [662 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [663 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [664 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [665 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [666 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [667 on yarn 8] from s1 relative to s0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - f30 5
knit - f28 5
knit - f26 5
knit - f24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [695 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [694 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [693 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [692 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [691 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [690 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [689 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [688 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [683 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [682 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [681 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [680 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [679 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [678 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [677 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [676 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [648 on yarn 8]
xfer b11 f11;return loops [649 on yarn 8]
xfer b13 f13;return loops [650 on yarn 8]
xfer b15 f15;return loops [651 on yarn 8]
xfer b17 f17;return loops [652 on yarn 8]
xfer b19 f19;return loops [653 on yarn 8]
xfer b21 f21;return loops [654 on yarn 8]
xfer b23 f23;return loops [655 on yarn 8]
xfer b33 f33;return loops [660 on yarn 8]
xfer b35 f35;return loops [661 on yarn 8]
xfer b37 f37;return loops [662 on yarn 8]
xfer b39 f39;return loops [663 on yarn 8]
xfer b41 f41;return loops [664 on yarn 8]
xfer b43 f43;return loops [665 on yarn 8]
xfer b45 f45;return loops [666 on yarn 8]
xfer b47 f47;return loops [667 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - b31 8
knit - b29 8
knit - b27 8
knit - b25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [723 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [722 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [721 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [720 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [719 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [718 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [717 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [716 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [711 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [710 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [709 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [708 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [707 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [706 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [705 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [704 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [695 on yarn 5]
xfer f10 b10;return loops [694 on yarn 5]
xfer f12 b12;return loops [693 on yarn 5]
xfer f14 b14;return loops [692 on yarn 5]
xfer f16 b16;return loops [691 on yarn 5]
xfer f18 b18;return loops [690 on yarn 5]
xfer f20 b20;return loops [689 on yarn 5]
xfer f22 b22;return loops [688 on yarn 5]
xfer f32 b32;return loops [683 on yarn 5]
xfer f34 b34;return loops [682 on yarn 5]
xfer f36 b36;return loops [681 on yarn 5]
xfer f38 b38;return loops [680 on yarn 5]
xfer f40 b40;return loops [679 on yarn 5]
xfer f42 b42;return loops [678 on yarn 5]
xfer f44 b44;return loops [677 on yarn 5]
xfer f46 b46;return loops [676 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + f24 5
knit + f26 5
knit + f28 5
knit + f30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [732 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [733 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [734 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [735 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [736 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [737 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [738 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [739 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [744 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [745 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [746 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [747 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [748 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [749 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [750 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [751 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [723 on yarn 8]
xfer b11 f11;return loops [722 on yarn 8]
xfer b13 f13;return loops [721 on yarn 8]
xfer b15 f15;return loops [720 on yarn 8]
xfer b17 f17;return loops [719 on yarn 8]
xfer b19 f19;return loops [718 on yarn 8]
xfer b21 f21;return loops [717 on yarn 8]
xfer b23 f23;return loops [716 on yarn 8]
xfer b33 f33;return loops [711 on yarn 8]
xfer b35 f35;return loops [710 on yarn 8]
xfer b37 f37;return loops [709 on yarn 8]
xfer b39 f39;return loops [708 on yarn 8]
xfer b41 f41;return loops [707 on yarn 8]
xfer b43 f43;return loops [706 on yarn 8]
xfer b45 f45;return loops [705 on yarn 8]
xfer b47 f47;return loops [704 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + b25 8
knit + b27 8
knit + b29 8
knit + b31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [760 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [761 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [762 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [763 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [764 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [765 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [766 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [767 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [772 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [773 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [774 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [775 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [776 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [777 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [778 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [779 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [732 on yarn 5]
xfer f10 b10;return loops [733 on yarn 5]
xfer f12 b12;return loops [734 on yarn 5]
xfer f14 b14;return loops [735 on yarn 5]
xfer f16 b16;return loops [736 on yarn 5]
xfer f18 b18;return loops [737 on yarn 5]
xfer f20 b20;return loops [738 on yarn 5]
xfer f22 b22;return loops [739 on yarn 5]
xfer f32 b32;return loops [744 on yarn 5]
xfer f34 b34;return loops [745 on yarn 5]
xfer f36 b36;return loops [746 on yarn 5]
xfer f38 b38;return loops [747 on yarn 5]
xfer f40 b40;return loops [748 on yarn 5]
xfer f42 b42;return loops [749 on yarn 5]
xfer f44 b44;return loops [750 on yarn 5]
xfer f46 b46;return loops [751 on yarn 5]
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - f30 5
knit - f28 5
knit - f26 5
knit - f24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [807 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [806 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [805 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [804 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [803 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [802 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [801 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [800 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [795 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [794 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [793 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [792 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [791 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [790 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [789 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [788 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [760 on yarn 8]
xfer b11 f11;return loops [761 on yarn 8]
xfer b13 f13;return loops [762 on yarn 8]
xfer b15 f15;return loops [763 on yarn 8]
xfer b17 f17;return loops [764 on yarn 8]
xfer b19 f19;return loops [765 on yarn 8]
xfer b21 f21;return loops [766 on yarn 8]
xfer b23 f23;return loops [767 on yarn 8]
xfer b33 f33;return loops [772 on yarn 8]
xfer b35 f35;return loops [773 on yarn 8]
xfer b37 f37;return loops [774 on yarn 8]
xfer b39 f39;return loops [775 on yarn 8]
xfer b41 f41;return loops [776 on yarn 8]
xfer b43 f43;return loops [777 on yarn 8]
xfer b45 f45;return loops [778 on yarn 8]
xfer b47 f47;return loops [779 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - b31 8
knit - b29 8
knit - b27 8
knit - b25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [835 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [834 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [833 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [832 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [831 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [830 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [829 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [828 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [823 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [822 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [821 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [820 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [819 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [818 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [817 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [816 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [807 on yarn 5]
xfer f10 b10;return loops [806 on yarn 5]
xfer f12 b12;return loops [805 on yarn 5]
xfer f14 b14;return loops [804 on yarn 5]
xfer f16 b16;return loops [803 on yarn 5]
xfer f18 b18;return loops [802 on yarn 5]
xfer f20 b20;return loops [801 on yarn 5]
xfer f22 b22;return loops [800 on yarn 5]
xfer f32 b32;return loops [795 on yarn 5]
xfer f34 b34;return loops [794 on yarn 5]
xfer f36 b36;return loops [793 on yarn 5]
xfer f38 b38;return loops [792 on yarn 5]
xfer f40 b40;return loops [791 on yarn 5]
xfer f42 b42;return loops [790 on yarn 5]
xfer f44 b44;return loops [789 on yarn 5]
xfer f46 b46;return loops [788 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + f24 5
knit + f26 5
knit + f28 5
knit + f30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [844 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [845 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [846 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [847 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [848 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [849 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [850 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [851 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [856 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [857 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [858 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [859 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [860 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [861 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [862 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [863 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [835 on yarn 8]
xfer b11 f11;return loops [834 on yarn 8]
xfer b13 f13;return loops [833 on yarn 8]
xfer b15 f15;return loops [832 on yarn 8]
xfer b17 f17;return loops [831 on yarn 8]
xfer b19 f19;return loops [830 on yarn 8]
xfer b21 f21;return loops [829 on yarn 8]
xfer b23 f23;return loops [828 on yarn 8]
xfer b33 f33;return loops [823 on yarn 8]
xfer b35 f35;return loops [822 on yarn 8]
xfer b37 f37;return loops [821 on yarn 8]
xfer b39 f39;return loops [820 on yarn 8]
xfer b41 f41;return loops [819 on yarn 8]
xfer b43 f43;return loops [818 on yarn 8]
xfer b45 f45;return loops [817 on yarn 8]
xfer b47 f47;return loops [816 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + b25 8
knit + b27 8
knit + b29 8
knit + b31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [872 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [873 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [874 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [875 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [876 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [877 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [878 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [879 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [884 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [885 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [886 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [887 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [888 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [889 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [890 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [891 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [844 on yarn 5]
xfer f10 b10;return loops [845 on yarn 5]
xfer f12 b12;return loops [846 on yarn 5]
xfer f14 b14;return loops [847 on yarn 5]
xfer f16 b16;return loops [848 on yarn 5]
xfer f18 b18;return loops [849 on yarn 5]
xfer f20 b20;return loops [850 on yarn 5]
xfer f22 b22;return loops [851 on yarn 5]
xfer f32 b32;return loops [856 on yarn 5]
xfer f34 b34;return loops [857 on yarn 5]
xfer f36 b36;return loops [858 on yarn 5]
xfer f38 b38;return loops [859 on yarn 5]
xfer f40 b40;return loops [860 on yarn 5]
xfer f42 b42;return loops [861 on yarn 5]
xfer f44 b44;return loops [862 on yarn 5]
xfer f46 b46;return loops [863 on yarn 5]
xfer b46 f46
xfer b44 f44
xfer b42 f42
xfer b40 f40
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [872 on yarn 8]
xfer b11 f11;return loops [873 on yarn 8]
xfer b13 f13;return loops [874 on yarn 8]
xfer b15 f15;return loops [875 on yarn 8]
xfer b17 f17;return loops [876 on yarn 8]
xfer b19 f19;return loops [877 on yarn 8]
xfer b21 f21;return loops [878 on yarn 8]
xfer b23 f23;return loops [879 on yarn 8]
xfer b33 f33;return loops [884 on yarn 8]
xfer b35 f35;return loops [885 on yarn 8]
xfer b37 f37;return loops [886 on yarn 8]
xfer b39 f39;return loops [887 on yarn 8]
xfer b41 f41;return loops [888 on yarn 8]
xfer b43 f43;return loops [889 on yarn 8]
xfer b45 f45;return loops [890 on yarn 8]
xfer b47 f47;return loops [891 on yarn 8]
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b31 f31
xfer b29 f29
xfer b27 f27
xfer b25 f25
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
xfer f54 b54
xfer f52 b52
xfer f50 b50
xfer f48 b48
xfer f46 b46
xfer f44 b44
xfer f42 b42
xfer f40 b40
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [868 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [869 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [870 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [871 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [872 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [873 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [874 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [875 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [876 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [877 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [878 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [879 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [880 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [881 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [882 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [883 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [884 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [885 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [886 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [887 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [888 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [889 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [890 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [891 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [892 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [893 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [894 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [895 on yarn 8] from s1 relative to s0
knit - b54 5
knit - b52 5
knit - b50 5
knit - b48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - b6 5
knit - b4 5
knit - b2 5
knit - b0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [923 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [922 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [921 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [920 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [919 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [918 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [917 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [916 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [915 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [914 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [913 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [912 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [911 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [910 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [909 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [908 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [907 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [906 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [905 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [904 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [903 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [902 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [901 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [900 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [899 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [898 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [897 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [896 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [868 on yarn 8]
xfer b3 f3;return loops [869 on yarn 8]
xfer b5 f5;return loops [870 on yarn 8]
xfer b7 f7;return loops [871 on yarn 8]
xfer b9 f9;return loops [872 on yarn 8]
xfer b11 f11;return loops [873 on yarn 8]
xfer b13 f13;return loops [874 on yarn 8]
xfer b15 f15;return loops [875 on yarn 8]
xfer b17 f17;return loops [876 on yarn 8]
xfer b19 f19;return loops [877 on yarn 8]
xfer b21 f21;return loops [878 on yarn 8]
xfer b23 f23;return loops [879 on yarn 8]
xfer b25 f25;return loops [880 on yarn 8]
xfer b27 f27;return loops [881 on yarn 8]
xfer b29 f29;return loops [882 on yarn 8]
xfer b31 f31;return loops [883 on yarn 8]
xfer b33 f33;return loops [884 on yarn 8]
xfer b35 f35;return loops [885 on yarn 8]
xfer b37 f37;return loops [886 on yarn 8]
xfer b39 f39;return loops [887 on yarn 8]
xfer b41 f41;return loops [888 on yarn 8]
xfer b43 f43;return loops [889 on yarn 8]
xfer b45 f45;return loops [890 on yarn 8]
xfer b47 f47;return loops [891 on yarn 8]
xfer b49 f49;return loops [892 on yarn 8]
xfer b51 f51;return loops [893 on yarn 8]
xfer b53 f53;return loops [894 on yarn 8]
xfer b55 f55;return loops [895 on yarn 8]
knit - f55 8
knit - f53 8
knit - f51 8
knit - f49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - f7 8
knit - f5 8
knit - f3 8
knit - f1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [951 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [950 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [949 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [948 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [947 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [946 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [945 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [944 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [943 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [942 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [941 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [940 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [939 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [938 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [937 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [936 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [935 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [934 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [933 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [932 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [931 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [930 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [929 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [928 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [927 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [926 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [925 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [924 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [923 on yarn 5]
xfer f2 b2;return loops [922 on yarn 5]
xfer f4 b4;return loops [921 on yarn 5]
xfer f6 b6;return loops [920 on yarn 5]
xfer f8 b8;return loops [919 on yarn 5]
xfer f10 b10;return loops [918 on yarn 5]
xfer f12 b12;return loops [917 on yarn 5]
xfer f14 b14;return loops [916 on yarn 5]
xfer f16 b16;return loops [915 on yarn 5]
xfer f18 b18;return loops [914 on yarn 5]
xfer f20 b20;return loops [913 on yarn 5]
xfer f22 b22;return loops [912 on yarn 5]
xfer f24 b24;return loops [911 on yarn 5]
xfer f26 b26;return loops [910 on yarn 5]
xfer f28 b28;return loops [909 on yarn 5]
xfer f30 b30;return loops [908 on yarn 5]
xfer f32 b32;return loops [907 on yarn 5]
xfer f34 b34;return loops [906 on yarn 5]
xfer f36 b36;return loops [905 on yarn 5]
xfer f38 b38;return loops [904 on yarn 5]
xfer f40 b40;return loops [903 on yarn 5]
xfer f42 b42;return loops [902 on yarn 5]
xfer f44 b44;return loops [901 on yarn 5]
xfer f46 b46;return loops [900 on yarn 5]
xfer f48 b48;return loops [899 on yarn 5]
xfer f50 b50;return loops [898 on yarn 5]
xfer f52 b52;return loops [897 on yarn 5]
xfer f54 b54;return loops [896 on yarn 5]
knit + b0 5
knit + b2 5
knit + b4 5
knit + b6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + b48 5
knit + b50 5
knit + b52 5
knit + b54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [952 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [953 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [954 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [955 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [956 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [957 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [958 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [959 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [960 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [961 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [962 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [963 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [964 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [965 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [966 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [967 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [968 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [969 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [970 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [971 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [972 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [973 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [974 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [975 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [976 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [977 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [978 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [979 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [951 on yarn 8]
xfer b3 f3;return loops [950 on yarn 8]
xfer b5 f5;return loops [949 on yarn 8]
xfer b7 f7;return loops [948 on yarn 8]
xfer b9 f9;return loops [947 on yarn 8]
xfer b11 f11;return loops [946 on yarn 8]
xfer b13 f13;return loops [945 on yarn 8]
xfer b15 f15;return loops [944 on yarn 8]
xfer b17 f17;return loops [943 on yarn 8]
xfer b19 f19;return loops [942 on yarn 8]
xfer b21 f21;return loops [941 on yarn 8]
xfer b23 f23;return loops [940 on yarn 8]
xfer b25 f25;return loops [939 on yarn 8]
xfer b27 f27;return loops [938 on yarn 8]
xfer b29 f29;return loops [937 on yarn 8]
xfer b31 f31;return loops [936 on yarn 8]
xfer b33 f33;return loops [935 on yarn 8]
xfer b35 f35;return loops [934 on yarn 8]
xfer b37 f37;return loops [933 on yarn 8]
xfer b39 f39;return loops [932 on yarn 8]
xfer b41 f41;return loops [931 on yarn 8]
xfer b43 f43;return loops [930 on yarn 8]
xfer b45 f45;return loops [929 on yarn 8]
xfer b47 f47;return loops [928 on yarn 8]
xfer b49 f49;return loops [927 on yarn 8]
xfer b51 f51;return loops [926 on yarn 8]
xfer b53 f53;return loops [925 on yarn 8]
xfer b55 f55;return loops [924 on yarn 8]
knit + f1 8
knit + f3 8
knit + f5 8
knit + f7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + f49 8
knit + f51 8
knit + f53 8
knit + f55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [980 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [981 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [982 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [983 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [984 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [985 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [986 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [987 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [988 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [989 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [990 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [991 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [992 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [993 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [994 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [995 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [996 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [997 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [998 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [999 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1000 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1001 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1002 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1003 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1004 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1005 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1006 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1007 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [952 on yarn 5]
xfer f2 b2;return loops [953 on yarn 5]
xfer f4 b4;return loops [954 on yarn 5]
xfer f6 b6;return loops [955 on yarn 5]
xfer f8 b8;return loops [956 on yarn 5]
xfer f10 b10;return loops [957 on yarn 5]
xfer f12 b12;return loops [958 on yarn 5]
xfer f14 b14;return loops [959 on yarn 5]
xfer f16 b16;return loops [960 on yarn 5]
xfer f18 b18;return loops [961 on yarn 5]
xfer f20 b20;return loops [962 on yarn 5]
xfer f22 b22;return loops [963 on yarn 5]
xfer f24 b24;return loops [964 on yarn 5]
xfer f26 b26;return loops [965 on yarn 5]
xfer f28 b28;return loops [966 on yarn 5]
xfer f30 b30;return loops [967 on yarn 5]
xfer f32 b32;return loops [968 on yarn 5]
xfer f34 b34;return loops [969 on yarn 5]
xfer f36 b36;return loops [970 on yarn 5]
xfer f38 b38;return loops [971 on yarn 5]
xfer f40 b40;return loops [972 on yarn 5]
xfer f42 b42;return loops [973 on yarn 5]
xfer f44 b44;return loops [974 on yarn 5]
xfer f46 b46;return loops [975 on yarn 5]
xfer f48 b48;return loops [976 on yarn 5]
xfer f50 b50;return loops [977 on yarn 5]
xfer f52 b52;return loops [978 on yarn 5]
xfer f54 b54;return loops [979 on yarn 5]
knit - b54 5
knit - b52 5
knit - b50 5
knit - b48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - b6 5
knit - b4 5
knit - b2 5
knit - b0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [1035 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [1034 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [1033 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [1032 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [1031 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1030 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1029 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1028 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1027 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1026 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1025 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1024 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1023 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1022 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1021 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1020 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1019 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1018 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1017 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1016 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1015 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1014 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1013 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1012 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [1011 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [1010 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [1009 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [1008 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [980 on yarn 8]
xfer b3 f3;return loops [981 on yarn 8]
xfer b5 f5;return loops [982 on yarn 8]
xfer b7 f7;return loops [983 on yarn 8]
xfer b9 f9;return loops [984 on yarn 8]
xfer b11 f11;return loops [985 on yarn 8]
xfer b13 f13;return loops [986 on yarn 8]
xfer b15 f15;return loops [987 on yarn 8]
xfer b17 f17;return loops [988 on yarn 8]
xfer b19 f19;return loops [989 on yarn 8]
xfer b21 f21;return loops [990 on yarn 8]
xfer b23 f23;return loops [991 on yarn 8]
xfer b25 f25;return loops [992 on yarn 8]
xfer b27 f27;return loops [993 on yarn 8]
xfer b29 f29;return loops [994 on yarn 8]
xfer b31 f31;return loops [995 on yarn 8]
xfer b33 f33;return loops [996 on yarn 8]
xfer b35 f35;return loops [997 on yarn 8]
xfer b37 f37;return loops [998 on yarn 8]
xfer b39 f39;return loops [999 on yarn 8]
xfer b41 f41;return loops [1000 on yarn 8]
xfer b43 f43;return loops [1001 on yarn 8]
xfer b45 f45;return loops [1002 on yarn 8]
xfer b47 f47;return loops [1003 on yarn 8]
xfer b49 f49;return loops [1004 on yarn 8]
xfer b51 f51;return loops [1005 on yarn 8]
xfer b53 f53;return loops [1006 on yarn 8]
xfer b55 f55;return loops [1007 on yarn 8]
knit - f55 8
knit - f53 8
knit - f51 8
knit - f49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - f7 8
knit - f5 8
knit - f3 8
knit - f1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1063 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1062 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1061 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1060 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1059 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1058 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1057 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1056 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1055 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1054 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1053 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1052 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1051 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1050 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1049 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1048 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1047 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1046 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1045 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1044 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1043 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1042 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1041 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1040 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1039 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1038 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1037 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1036 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [1035 on yarn 5]
xfer f2 b2;return loops [1034 on yarn 5]
xfer f4 b4;return loops [1033 on yarn 5]
xfer f6 b6;return loops [1032 on yarn 5]
xfer f8 b8;return loops [1031 on yarn 5]
xfer f10 b10;return loops [1030 on yarn 5]
xfer f12 b12;return loops [1029 on yarn 5]
xfer f14 b14;return loops [1028 on yarn 5]
xfer f16 b16;return loops [1027 on yarn 5]
xfer f18 b18;return loops [1026 on yarn 5]
xfer f20 b20;return loops [1025 on yarn 5]
xfer f22 b22;return loops [1024 on yarn 5]
xfer f24 b24;return loops [1023 on yarn 5]
xfer f26 b26;return loops [1022 on yarn 5]
xfer f28 b28;return loops [1021 on yarn 5]
xfer f30 b30;return loops [1020 on yarn 5]
xfer f32 b32;return loops [1019 on yarn 5]
xfer f34 b34;return loops [1018 on yarn 5]
xfer f36 b36;return loops [1017 on yarn 5]
xfer f38 b38;return loops [1016 on yarn 5]
xfer f40 b40;return loops [1015 on yarn 5]
xfer f42 b42;return loops [1014 on yarn 5]
xfer f44 b44;return loops [1013 on yarn 5]
xfer f46 b46;return loops [1012 on yarn 5]
xfer f48 b48;return loops [1011 on yarn 5]
xfer f50 b50;return loops [1010 on yarn 5]
xfer f52 b52;return loops [1009 on yarn 5]
xfer f54 b54;return loops [1008 on yarn 5]
knit + b0 5
knit + b2 5
knit + b4 5
knit + b6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + b48 5
knit + b50 5
knit + b52 5
knit + b54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [1064 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [1065 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [1066 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [1067 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [1068 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1069 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1070 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1071 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1072 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1073 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1074 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1075 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1076 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1077 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1078 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1079 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1080 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1081 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1082 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1083 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1084 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1085 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1086 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1087 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [1088 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [1089 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [1090 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [1091 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1063 on yarn 8]
xfer b3 f3;return loops [1062 on yarn 8]
xfer b5 f5;return loops [1061 on yarn 8]
xfer b7 f7;return loops [1060 on yarn 8]
xfer b9 f9;return loops [1059 on yarn 8]
xfer b11 f11;return loops [1058 on yarn 8]
xfer b13 f13;return loops [1057 on yarn 8]
xfer b15 f15;return loops [1056 on yarn 8]
xfer b17 f17;return loops [1055 on yarn 8]
xfer b19 f19;return loops [1054 on yarn 8]
xfer b21 f21;return loops [1053 on yarn 8]
xfer b23 f23;return loops [1052 on yarn 8]
xfer b25 f25;return loops [1051 on yarn 8]
xfer b27 f27;return loops [1050 on yarn 8]
xfer b29 f29;return loops [1049 on yarn 8]
xfer b31 f31;return loops [1048 on yarn 8]
xfer b33 f33;return loops [1047 on yarn 8]
xfer b35 f35;return loops [1046 on yarn 8]
xfer b37 f37;return loops [1045 on yarn 8]
xfer b39 f39;return loops [1044 on yarn 8]
xfer b41 f41;return loops [1043 on yarn 8]
xfer b43 f43;return loops [1042 on yarn 8]
xfer b45 f45;return loops [1041 on yarn 8]
xfer b47 f47;return loops [1040 on yarn 8]
xfer b49 f49;return loops [1039 on yarn 8]
xfer b51 f51;return loops [1038 on yarn 8]
xfer b53 f53;return loops [1037 on yarn 8]
xfer b55 f55;return loops [1036 on yarn 8]
knit + f1 8
knit + f3 8
knit + f5 8
knit + f7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + f49 8
knit + f51 8
knit + f53 8
knit + f55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1092 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1093 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1094 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1095 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1096 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1097 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1098 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1099 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1100 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1101 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1102 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1103 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1104 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1105 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1106 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1107 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1108 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1109 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1110 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1111 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1112 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1113 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1114 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1115 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1116 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1117 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1118 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1119 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [1064 on yarn 5]
xfer f2 b2;return loops [1065 on yarn 5]
xfer f4 b4;return loops [1066 on yarn 5]
xfer f6 b6;return loops [1067 on yarn 5]
xfer f8 b8;return loops [1068 on yarn 5]
xfer f10 b10;return loops [1069 on yarn 5]
xfer f12 b12;return loops [1070 on yarn 5]
xfer f14 b14;return loops [1071 on yarn 5]
xfer f16 b16;return loops [1072 on yarn 5]
xfer f18 b18;return loops [1073 on yarn 5]
xfer f20 b20;return loops [1074 on yarn 5]
xfer f22 b22;return loops [1075 on yarn 5]
xfer f24 b24;return loops [1076 on yarn 5]
xfer f26 b26;return loops [1077 on yarn 5]
xfer f28 b28;return loops [1078 on yarn 5]
xfer f30 b30;return loops [1079 on yarn 5]
xfer f32 b32;return loops [1080 on yarn 5]
xfer f34 b34;return loops [1081 on yarn 5]
xfer f36 b36;return loops [1082 on yarn 5]
xfer f38 b38;return loops [1083 on yarn 5]
xfer f40 b40;return loops [1084 on yarn 5]
xfer f42 b42;return loops [1085 on yarn 5]
xfer f44 b44;return loops [1086 on yarn 5]
xfer f46 b46;return loops [1087 on yarn 5]
xfer f48 b48;return loops [1088 on yarn 5]
xfer f50 b50;return loops [1089 on yarn 5]
xfer f52 b52;return loops [1090 on yarn 5]
xfer f54 b54;return loops [1091 on yarn 5]
xfer b54 f54
xfer b52 f52
xfer b50 f50
xfer b48 f48
xfer b46 f46
xfer b44 f44
xfer b42 f42
xfer b40 f40
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1092 on yarn 8]
xfer b3 f3;return loops [1093 on yarn 8]
xfer b5 f5;return loops [1094 on yarn 8]
xfer b7 f7;return loops [1095 on yarn 8]
xfer b9 f9;return loops [1096 on yarn 8]
xfer b11 f11;return loops [1097 on yarn 8]
xfer b13 f13;return loops [1098 on yarn 8]
xfer b15 f15;return loops [1099 on yarn 8]
xfer b17 f17;return loops [1100 on yarn 8]
xfer b19 f19;return loops [1101 on yarn 8]
xfer b21 f21;return loops [1102 on yarn 8]
xfer b23 f23;return loops [1103 on yarn 8]
xfer b25 f25;return loops [1104 on yarn 8]
xfer b27 f27;return loops [1105 on yarn 8]
xfer b29 f29;return loops [1106 on yarn 8]
xfer b31 f31;return loops [1107 on yarn 8]
xfer b33 f33;return loops [1108 on yarn 8]
xfer b35 f35;return loops [1109 on yarn 8]
xfer b37 f37;return loops [1110 on yarn 8]
xfer b39 f39;return loops [1111 on yarn 8]
xfer b41 f41;return loops [1112 on yarn 8]
xfer b43 f43;return loops [1113 on yarn 8]
xfer b45 f45;return loops [1114 on yarn 8]
xfer b47 f47;return loops [1115 on yarn 8]
xfer b49 f49;return loops [1116 on yarn 8]
xfer b51 f51;return loops [1117 on yarn 8]
xfer b53 f53;return loops [1118 on yarn 8]
xfer b55 f55;return loops [1119 on yarn 8]
xfer f54 b54
xfer f52 b52
xfer f50 b50
xfer f48 b48
xfer f46 b46
xfer f44 b44
xfer f42 b42
xfer f40 b40
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1092 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1093 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1094 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1095 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1096 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1097 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1098 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1099 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1100 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1101 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1102 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1103 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1104 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1105 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1106 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1107 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1108 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1109 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1110 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1111 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1112 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1113 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1114 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1115 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1116 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1117 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1118 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1119 on yarn 8] from s1 relative to s0
knit - b54 5
knit - b52 5
knit - b50 5
knit - b48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - b6 5
knit - b4 5
knit - b2 5
knit - b0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [1147 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [1146 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [1145 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [1144 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [1143 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1142 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1141 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1140 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1139 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1138 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1137 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1136 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1135 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1134 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1133 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1132 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1131 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1130 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1129 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1128 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1127 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1126 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1125 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1124 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [1123 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [1122 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [1121 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [1120 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1092 on yarn 8]
xfer b3 f3;return loops [1093 on yarn 8]
xfer b5 f5;return loops [1094 on yarn 8]
xfer b7 f7;return loops [1095 on yarn 8]
xfer b9 f9;return loops [1096 on yarn 8]
xfer b11 f11;return loops [1097 on yarn 8]
xfer b13 f13;return loops [1098 on yarn 8]
xfer b15 f15;return loops [1099 on yarn 8]
xfer b17 f17;return loops [1100 on yarn 8]
xfer b19 f19;return loops [1101 on yarn 8]
xfer b21 f21;return loops [1102 on yarn 8]
xfer b23 f23;return loops [1103 on yarn 8]
xfer b25 f25;return loops [1104 on yarn 8]
xfer b27 f27;return loops [1105 on yarn 8]
xfer b29 f29;return loops [1106 on yarn 8]
xfer b31 f31;return loops [1107 on yarn 8]
xfer b33 f33;return loops [1108 on yarn 8]
xfer b35 f35;return loops [1109 on yarn 8]
xfer b37 f37;return loops [1110 on yarn 8]
xfer b39 f39;return loops [1111 on yarn 8]
xfer b41 f41;return loops [1112 on yarn 8]
xfer b43 f43;return loops [1113 on yarn 8]
xfer b45 f45;return loops [1114 on yarn 8]
xfer b47 f47;return loops [1115 on yarn 8]
xfer b49 f49;return loops [1116 on yarn 8]
xfer b51 f51;return loops [1117 on yarn 8]
xfer b53 f53;return loops [1118 on yarn 8]
xfer b55 f55;return loops [1119 on yarn 8]
knit - f55 8
knit - f53 8
knit - f51 8
knit - f49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - f7 8
knit - f5 8
knit - f3 8
knit - f1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1175 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1174 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1173 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1172 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1171 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1170 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1169 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1168 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1167 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1166 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1165 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1164 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1163 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1162 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1161 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1160 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1159 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1158 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1157 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1156 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1155 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1154 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1153 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1152 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1151 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1150 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1149 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1148 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [1147 on yarn 5]
xfer f2 b2;return loops [1146 on yarn 5]
xfer f4 b4;return loops [1145 on yarn 5]
xfer f6 b6;return loops [1144 on yarn 5]
xfer f8 b8;return loops [1143 on yarn 5]
xfer f10 b10;return loops [1142 on yarn 5]
xfer f12 b12;return loops [1141 on yarn 5]
xfer f14 b14;return loops [1140 on yarn 5]
xfer f16 b16;return loops [1139 on yarn 5]
xfer f18 b18;return loops [1138 on yarn 5]
xfer f20 b20;return loops [1137 on yarn 5]
xfer f22 b22;return loops [1136 on yarn 5]
xfer f24 b24;return loops [1135 on yarn 5]
xfer f26 b26;return loops [1134 on yarn 5]
xfer f28 b28;return loops [1133 on yarn 5]
xfer f30 b30;return loops [1132 on yarn 5]
xfer f32 b32;return loops [1131 on yarn 5]
xfer f34 b34;return loops [1130 on yarn 5]
xfer f36 b36;return loops [1129 on yarn 5]
xfer f38 b38;return loops [1128 on yarn 5]
xfer f40 b40;return loops [1127 on yarn 5]
xfer f42 b42;return loops [1126 on yarn 5]
xfer f44 b44;return loops [1125 on yarn 5]
xfer f46 b46;return loops [1124 on yarn 5]
xfer f48 b48;return loops [1123 on yarn 5]
xfer f50 b50;return loops [1122 on yarn 5]
xfer f52 b52;return loops [1121 on yarn 5]
xfer f54 b54;return loops [1120 on yarn 5]
knit + b0 5
knit + b2 5
knit + b4 5
knit + b6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + b48 5
knit + b50 5
knit + b52 5
knit + b54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [1176 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [1177 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [1178 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [1179 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [1180 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1181 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1182 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1183 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1184 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1185 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1186 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1187 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1188 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1189 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1190 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1191 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1192 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1193 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1194 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1195 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1196 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1197 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1198 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1199 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [1200 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [1201 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [1202 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [1203 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1175 on yarn 8]
xfer b3 f3;return loops [1174 on yarn 8]
xfer b5 f5;return loops [1173 on yarn 8]
xfer b7 f7;return loops [1172 on yarn 8]
xfer b9 f9;return loops [1171 on yarn 8]
xfer b11 f11;return loops [1170 on yarn 8]
xfer b13 f13;return loops [1169 on yarn 8]
xfer b15 f15;return loops [1168 on yarn 8]
xfer b17 f17;return loops [1167 on yarn 8]
xfer b19 f19;return loops [1166 on yarn 8]
xfer b21 f21;return loops [1165 on yarn 8]
xfer b23 f23;return loops [1164 on yarn 8]
xfer b25 f25;return loops [1163 on yarn 8]
xfer b27 f27;return loops [1162 on yarn 8]
xfer b29 f29;return loops [1161 on yarn 8]
xfer b31 f31;return loops [1160 on yarn 8]
xfer b33 f33;return loops [1159 on yarn 8]
xfer b35 f35;return loops [1158 on yarn 8]
xfer b37 f37;return loops [1157 on yarn 8]
xfer b39 f39;return loops [1156 on yarn 8]
xfer b41 f41;return loops [1155 on yarn 8]
xfer b43 f43;return loops [1154 on yarn 8]
xfer b45 f45;return loops [1153 on yarn 8]
xfer b47 f47;return loops [1152 on yarn 8]
xfer b49 f49;return loops [1151 on yarn 8]
xfer b51 f51;return loops [1150 on yarn 8]
xfer b53 f53;return loops [1149 on yarn 8]
xfer b55 f55;return loops [1148 on yarn 8]
knit + f1 8
knit + f3 8
knit + f5 8
knit + f7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + f49 8
knit + f51 8
knit + f53 8
knit + f55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1204 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1205 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1206 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1207 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1208 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1209 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1210 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1211 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1212 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1213 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1214 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1215 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1216 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1217 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1218 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1219 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1220 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1221 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1222 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1223 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1224 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1225 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1226 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1227 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1228 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1229 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1230 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1231 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [1176 on yarn 5]
xfer f2 b2;return loops [1177 on yarn 5]
xfer f4 b4;return loops [1178 on yarn 5]
xfer f6 b6;return loops [1179 on yarn 5]
xfer f8 b8;return loops [1180 on yarn 5]
xfer f10 b10;return loops [1181 on yarn 5]
xfer f12 b12;return loops [1182 on yarn 5]
xfer f14 b14;return loops [1183 on yarn 5]
xfer f16 b16;return loops [1184 on yarn 5]
xfer f18 b18;return loops [1185 on yarn 5]
xfer f20 b20;return loops [1186 on yarn 5]
xfer f22 b22;return loops [1187 on yarn 5]
xfer f24 b24;return loops [1188 on yarn 5]
xfer f26 b26;return loops [1189 on yarn 5]
xfer f28 b28;return loops [1190 on yarn 5]
xfer f30 b30;return loops [1191 on yarn 5]
xfer f32 b32;return loops [1192 on yarn 5]
xfer f34 b34;return loops [1193 on yarn 5]
xfer f36 b36;return loops [1194 on yarn 5]
xfer f38 b38;return loops [1195 on yarn 5]
xfer f40 b40;return loops [1196 on yarn 5]
xfer f42 b42;return loops [1197 on yarn 5]
xfer f44 b44;return loops [1198 on yarn 5]
xfer f46 b46;return loops [1199 on yarn 5]
xfer f48 b48;return loops [1200 on yarn 5]
xfer f50 b50;return loops [1201 on yarn 5]
xfer f52 b52;return loops [1202 on yarn 5]
xfer f54 b54;return loops [1203 on yarn 5]
knit - b54 5
knit - b52 5
knit - b50 5
knit - b48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - b6 5
knit - b4 5
knit - b2 5
knit - b0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [1259 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [1258 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [1257 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [1256 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [1255 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1254 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1253 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1252 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1251 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1250 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1249 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1248 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1247 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1246 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1245 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1244 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1243 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1242 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1241 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1240 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1239 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1238 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1237 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1236 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [1235 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [1234 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [1233 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [1232 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1204 on yarn 8]
xfer b3 f3;return loops [1205 on yarn 8]
xfer b5 f5;return loops [1206 on yarn 8]
xfer b7 f7;return loops [1207 on yarn 8]
xfer b9 f9;return loops [1208 on yarn 8]
xfer b11 f11;return loops [1209 on yarn 8]
xfer b13 f13;return loops [1210 on yarn 8]
xfer b15 f15;return loops [1211 on yarn 8]
xfer b17 f17;return loops [1212 on yarn 8]
xfer b19 f19;return loops [1213 on yarn 8]
xfer b21 f21;return loops [1214 on yarn 8]
xfer b23 f23;return loops [1215 on yarn 8]
xfer b25 f25;return loops [1216 on yarn 8]
xfer b27 f27;return loops [1217 on yarn 8]
xfer b29 f29;return loops [1218 on yarn 8]
xfer b31 f31;return loops [1219 on yarn 8]
xfer b33 f33;return loops [1220 on yarn 8]
xfer b35 f35;return loops [1221 on yarn 8]
xfer b37 f37;return loops [1222 on yarn 8]
xfer b39 f39;return loops [1223 on yarn 8]
xfer b41 f41;return loops [1224 on yarn 8]
xfer b43 f43;return loops [1225 on yarn 8]
xfer b45 f45;return loops [1226 on yarn 8]
xfer b47 f47;return loops [1227 on yarn 8]
xfer b49 f49;return loops [1228 on yarn 8]
xfer b51 f51;return loops [1229 on yarn 8]
xfer b53 f53;return loops [1230 on yarn 8]
xfer b55 f55;return loops [1231 on yarn 8]
knit - f55 8
knit - f53 8
knit - f51 8
knit - f49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - f7 8
knit - f5 8
knit - f3 8
knit - f1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1287 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1286 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1285 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1284 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1283 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1282 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1281 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1280 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1279 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1278 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1277 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1276 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1275 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1274 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1273 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1272 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1271 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1270 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1269 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1268 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1267 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1266 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1265 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1264 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1263 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1262 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1261 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1260 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [1259 on yarn 5]
xfer f2 b2;return loops [1258 on yarn 5]
xfer f4 b4;return loops [1257 on yarn 5]
xfer f6 b6;return loops [1256 on yarn 5]
xfer f8 b8;return loops [1255 on yarn 5]
xfer f10 b10;return loops [1254 on yarn 5]
xfer f12 b12;return loops [1253 on yarn 5]
xfer f14 b14;return loops [1252 on yarn 5]
xfer f16 b16;return loops [1251 on yarn 5]
xfer f18 b18;return loops [1250 on yarn 5]
xfer f20 b20;return loops [1249 on yarn 5]
xfer f22 b22;return loops [1248 on yarn 5]
xfer f24 b24;return loops [1247 on yarn 5]
xfer f26 b26;return loops [1246 on yarn 5]
xfer f28 b28;return loops [1245 on yarn 5]
xfer f30 b30;return loops [1244 on yarn 5]
xfer f32 b32;return loops [1243 on yarn 5]
xfer f34 b34;return loops [1242 on yarn 5]
xfer f36 b36;return loops [1241 on yarn 5]
xfer f38 b38;return loops [1240 on yarn 5]
xfer f40 b40;return loops [1239 on yarn 5]
xfer f42 b42;return loops [1238 on yarn 5]
xfer f44 b44;return loops [1237 on yarn 5]
xfer f46 b46;return loops [1236 on yarn 5]
xfer f48 b48;return loops [1235 on yarn 5]
xfer f50 b50;return loops [1234 on yarn 5]
xfer f52 b52;return loops [1233 on yarn 5]
xfer f54 b54;return loops [1232 on yarn 5]
knit + b0 5
knit + b2 5
knit + b4 5
knit + b6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + b48 5
knit + b50 5
knit + b52 5
knit + b54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b0 f0;peel loops [1288 on yarn 5] from s0 relative to s1
xfer b2 f2;peel loops [1289 on yarn 5] from s0 relative to s1
xfer b4 f4;peel loops [1290 on yarn 5] from s0 relative to s1
xfer b6 f6;peel loops [1291 on yarn 5] from s0 relative to s1
xfer b8 f8;peel loops [1292 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1293 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1294 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1295 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1296 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1297 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1298 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1299 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1300 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1301 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1302 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1303 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1304 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1305 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1306 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1307 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1308 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1309 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1310 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1311 on yarn 5] from s0 relative to s1
xfer b48 f48;peel loops [1312 on yarn 5] from s0 relative to s1
xfer b50 f50;peel loops [1313 on yarn 5] from s0 relative to s1
xfer b52 f52;peel loops [1314 on yarn 5] from s0 relative to s1
xfer b54 f54;peel loops [1315 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1287 on yarn 8]
xfer b3 f3;return loops [1286 on yarn 8]
xfer b5 f5;return loops [1285 on yarn 8]
xfer b7 f7;return loops [1284 on yarn 8]
xfer b9 f9;return loops [1283 on yarn 8]
xfer b11 f11;return loops [1282 on yarn 8]
xfer b13 f13;return loops [1281 on yarn 8]
xfer b15 f15;return loops [1280 on yarn 8]
xfer b17 f17;return loops [1279 on yarn 8]
xfer b19 f19;return loops [1278 on yarn 8]
xfer b21 f21;return loops [1277 on yarn 8]
xfer b23 f23;return loops [1276 on yarn 8]
xfer b25 f25;return loops [1275 on yarn 8]
xfer b27 f27;return loops [1274 on yarn 8]
xfer b29 f29;return loops [1273 on yarn 8]
xfer b31 f31;return loops [1272 on yarn 8]
xfer b33 f33;return loops [1271 on yarn 8]
xfer b35 f35;return loops [1270 on yarn 8]
xfer b37 f37;return loops [1269 on yarn 8]
xfer b39 f39;return loops [1268 on yarn 8]
xfer b41 f41;return loops [1267 on yarn 8]
xfer b43 f43;return loops [1266 on yarn 8]
xfer b45 f45;return loops [1265 on yarn 8]
xfer b47 f47;return loops [1264 on yarn 8]
xfer b49 f49;return loops [1263 on yarn 8]
xfer b51 f51;return loops [1262 on yarn 8]
xfer b53 f53;return loops [1261 on yarn 8]
xfer b55 f55;return loops [1260 on yarn 8]
knit + f1 8
knit + f3 8
knit + f5 8
knit + f7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + f49 8
knit + f51 8
knit + f53 8
knit + f55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f1 b1;peel loops [1316 on yarn 8] from s1 relative to s0
xfer f3 b3;peel loops [1317 on yarn 8] from s1 relative to s0
xfer f5 b5;peel loops [1318 on yarn 8] from s1 relative to s0
xfer f7 b7;peel loops [1319 on yarn 8] from s1 relative to s0
xfer f9 b9;peel loops [1320 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1321 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1322 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1323 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1324 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1325 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1326 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1327 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1328 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1329 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1330 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1331 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1332 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1333 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1334 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1335 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1336 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1337 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1338 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1339 on yarn 8] from s1 relative to s0
xfer f49 b49;peel loops [1340 on yarn 8] from s1 relative to s0
xfer f51 b51;peel loops [1341 on yarn 8] from s1 relative to s0
xfer f53 b53;peel loops [1342 on yarn 8] from s1 relative to s0
xfer f55 b55;peel loops [1343 on yarn 8] from s1 relative to s0
xfer f0 b0;return loops [1288 on yarn 5]
xfer f2 b2;return loops [1289 on yarn 5]
xfer f4 b4;return loops [1290 on yarn 5]
xfer f6 b6;return loops [1291 on yarn 5]
xfer f8 b8;return loops [1292 on yarn 5]
xfer f10 b10;return loops [1293 on yarn 5]
xfer f12 b12;return loops [1294 on yarn 5]
xfer f14 b14;return loops [1295 on yarn 5]
xfer f16 b16;return loops [1296 on yarn 5]
xfer f18 b18;return loops [1297 on yarn 5]
xfer f20 b20;return loops [1298 on yarn 5]
xfer f22 b22;return loops [1299 on yarn 5]
xfer f24 b24;return loops [1300 on yarn 5]
xfer f26 b26;return loops [1301 on yarn 5]
xfer f28 b28;return loops [1302 on yarn 5]
xfer f30 b30;return loops [1303 on yarn 5]
xfer f32 b32;return loops [1304 on yarn 5]
xfer f34 b34;return loops [1305 on yarn 5]
xfer f36 b36;return loops [1306 on yarn 5]
xfer f38 b38;return loops [1307 on yarn 5]
xfer f40 b40;return loops [1308 on yarn 5]
xfer f42 b42;return loops [1309 on yarn 5]
xfer f44 b44;return loops [1310 on yarn 5]
xfer f46 b46;return loops [1311 on yarn 5]
xfer f48 b48;return loops [1312 on yarn 5]
xfer f50 b50;return loops [1313 on yarn 5]
xfer f52 b52;return loops [1314 on yarn 5]
xfer f54 b54;return loops [1315 on yarn 5]
xfer b54 f54
xfer b52 f52
xfer b50 f50
xfer b48 f48
xfer b46 f46
xfer b44 f44
xfer b42 f42
xfer b40 f40
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
xfer b6 f6
xfer b4 f4
xfer b2 f2
xfer b0 f0
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b1 f1;return loops [1316 on yarn 8]
xfer b3 f3;return loops [1317 on yarn 8]
xfer b5 f5;return loops [1318 on yarn 8]
xfer b7 f7;return loops [1319 on yarn 8]
xfer b9 f9;return loops [1320 on yarn 8]
xfer b11 f11;return loops [1321 on yarn 8]
xfer b13 f13;return loops [1322 on yarn 8]
xfer b15 f15;return loops [1323 on yarn 8]
xfer b17 f17;return loops [1324 on yarn 8]
xfer b19 f19;return loops [1325 on yarn 8]
xfer b21 f21;return loops [1326 on yarn 8]
xfer b23 f23;return loops [1327 on yarn 8]
xfer b25 f25;return loops [1328 on yarn 8]
xfer b27 f27;return loops [1329 on yarn 8]
xfer b29 f29;return loops [1330 on yarn 8]
xfer b31 f31;return loops [1331 on yarn 8]
xfer b33 f33;return loops [1332 on yarn 8]
xfer b35 f35;return loops [1333 on yarn 8]
xfer b37 f37;return loops [1334 on yarn 8]
xfer b39 f39;return loops [1335 on yarn 8]
xfer b41 f41;return loops [1336 on yarn 8]
xfer b43 f43;return loops [1337 on yarn 8]
xfer b45 f45;return loops [1338 on yarn 8]
xfer b47 f47;return loops [1339 on yarn 8]
xfer b49 f49;return loops [1340 on yarn 8]
xfer b51 f51;return loops [1341 on yarn 8]
xfer b53 f53;return loops [1342 on yarn 8]
xfer b55 f55;return loops [1343 on yarn 8]
xfer f46 b46
xfer f44 b44
xfer f42 b42
xfer f40 b40
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f55 b55
xfer f53 b53
xfer f51 b51
xfer f49 b49
xfer f7 b7
xfer f5 b5
xfer f3 b3
xfer f1 b1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [1320 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1321 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1322 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1323 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1324 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1325 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1326 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1327 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1328 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1329 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1330 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1331 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1332 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1333 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1334 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1335 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1336 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1337 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1338 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1339 on yarn 8] from s1 relative to s0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [1367 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1366 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1365 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1364 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1363 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1362 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1361 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1360 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1359 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1358 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1357 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1356 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1355 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1354 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1353 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1352 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1351 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1350 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1349 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1348 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [1320 on yarn 8]
xfer b11 f11;return loops [1321 on yarn 8]
xfer b13 f13;return loops [1322 on yarn 8]
xfer b15 f15;return loops [1323 on yarn 8]
xfer b17 f17;return loops [1324 on yarn 8]
xfer b19 f19;return loops [1325 on yarn 8]
xfer b21 f21;return loops [1326 on yarn 8]
xfer b23 f23;return loops [1327 on yarn 8]
xfer b25 f25;return loops [1328 on yarn 8]
xfer b27 f27;return loops [1329 on yarn 8]
xfer b29 f29;return loops [1330 on yarn 8]
xfer b31 f31;return loops [1331 on yarn 8]
xfer b33 f33;return loops [1332 on yarn 8]
xfer b35 f35;return loops [1333 on yarn 8]
xfer b37 f37;return loops [1334 on yarn 8]
xfer b39 f39;return loops [1335 on yarn 8]
xfer b41 f41;return loops [1336 on yarn 8]
xfer b43 f43;return loops [1337 on yarn 8]
xfer b45 f45;return loops [1338 on yarn 8]
xfer b47 f47;return loops [1339 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [1395 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1394 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1393 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1392 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1391 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1390 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1389 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1388 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1387 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1386 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1385 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1384 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1383 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1382 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1381 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1380 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1379 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1378 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1377 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1376 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [1367 on yarn 5]
xfer f10 b10;return loops [1366 on yarn 5]
xfer f12 b12;return loops [1365 on yarn 5]
xfer f14 b14;return loops [1364 on yarn 5]
xfer f16 b16;return loops [1363 on yarn 5]
xfer f18 b18;return loops [1362 on yarn 5]
xfer f20 b20;return loops [1361 on yarn 5]
xfer f22 b22;return loops [1360 on yarn 5]
xfer f24 b24;return loops [1359 on yarn 5]
xfer f26 b26;return loops [1358 on yarn 5]
xfer f28 b28;return loops [1357 on yarn 5]
xfer f30 b30;return loops [1356 on yarn 5]
xfer f32 b32;return loops [1355 on yarn 5]
xfer f34 b34;return loops [1354 on yarn 5]
xfer f36 b36;return loops [1353 on yarn 5]
xfer f38 b38;return loops [1352 on yarn 5]
xfer f40 b40;return loops [1351 on yarn 5]
xfer f42 b42;return loops [1350 on yarn 5]
xfer f44 b44;return loops [1349 on yarn 5]
xfer f46 b46;return loops [1348 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [1404 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1405 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1406 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1407 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1408 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1409 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1410 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1411 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1412 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1413 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1414 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1415 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1416 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1417 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1418 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1419 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1420 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1421 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1422 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1423 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [1395 on yarn 8]
xfer b11 f11;return loops [1394 on yarn 8]
xfer b13 f13;return loops [1393 on yarn 8]
xfer b15 f15;return loops [1392 on yarn 8]
xfer b17 f17;return loops [1391 on yarn 8]
xfer b19 f19;return loops [1390 on yarn 8]
xfer b21 f21;return loops [1389 on yarn 8]
xfer b23 f23;return loops [1388 on yarn 8]
xfer b25 f25;return loops [1387 on yarn 8]
xfer b27 f27;return loops [1386 on yarn 8]
xfer b29 f29;return loops [1385 on yarn 8]
xfer b31 f31;return loops [1384 on yarn 8]
xfer b33 f33;return loops [1383 on yarn 8]
xfer b35 f35;return loops [1382 on yarn 8]
xfer b37 f37;return loops [1381 on yarn 8]
xfer b39 f39;return loops [1380 on yarn 8]
xfer b41 f41;return loops [1379 on yarn 8]
xfer b43 f43;return loops [1378 on yarn 8]
xfer b45 f45;return loops [1377 on yarn 8]
xfer b47 f47;return loops [1376 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [1432 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1433 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1434 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1435 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1436 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1437 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1438 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1439 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1440 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1441 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1442 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1443 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1444 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1445 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1446 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1447 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1448 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1449 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1450 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1451 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [1404 on yarn 5]
xfer f10 b10;return loops [1405 on yarn 5]
xfer f12 b12;return loops [1406 on yarn 5]
xfer f14 b14;return loops [1407 on yarn 5]
xfer f16 b16;return loops [1408 on yarn 5]
xfer f18 b18;return loops [1409 on yarn 5]
xfer f20 b20;return loops [1410 on yarn 5]
xfer f22 b22;return loops [1411 on yarn 5]
xfer f24 b24;return loops [1412 on yarn 5]
xfer f26 b26;return loops [1413 on yarn 5]
xfer f28 b28;return loops [1414 on yarn 5]
xfer f30 b30;return loops [1415 on yarn 5]
xfer f32 b32;return loops [1416 on yarn 5]
xfer f34 b34;return loops [1417 on yarn 5]
xfer f36 b36;return loops [1418 on yarn 5]
xfer f38 b38;return loops [1419 on yarn 5]
xfer f40 b40;return loops [1420 on yarn 5]
xfer f42 b42;return loops [1421 on yarn 5]
xfer f44 b44;return loops [1422 on yarn 5]
xfer f46 b46;return loops [1423 on yarn 5]
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - b46 5
knit - b44 5
knit - b42 5
knit - b40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - b14 5
knit - b12 5
knit - b10 5
knit - b8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [1479 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1478 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1477 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1476 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1475 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1474 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1473 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1472 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1471 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1470 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1469 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1468 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1467 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1466 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1465 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1464 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1463 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1462 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1461 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1460 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [1432 on yarn 8]
xfer b11 f11;return loops [1433 on yarn 8]
xfer b13 f13;return loops [1434 on yarn 8]
xfer b15 f15;return loops [1435 on yarn 8]
xfer b17 f17;return loops [1436 on yarn 8]
xfer b19 f19;return loops [1437 on yarn 8]
xfer b21 f21;return loops [1438 on yarn 8]
xfer b23 f23;return loops [1439 on yarn 8]
xfer b25 f25;return loops [1440 on yarn 8]
xfer b27 f27;return loops [1441 on yarn 8]
xfer b29 f29;return loops [1442 on yarn 8]
xfer b31 f31;return loops [1443 on yarn 8]
xfer b33 f33;return loops [1444 on yarn 8]
xfer b35 f35;return loops [1445 on yarn 8]
xfer b37 f37;return loops [1446 on yarn 8]
xfer b39 f39;return loops [1447 on yarn 8]
xfer b41 f41;return loops [1448 on yarn 8]
xfer b43 f43;return loops [1449 on yarn 8]
xfer b45 f45;return loops [1450 on yarn 8]
xfer b47 f47;return loops [1451 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - f47 8
knit - f45 8
knit - f43 8
knit - f41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - f15 8
knit - f13 8
knit - f11 8
knit - f9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [1507 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1506 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1505 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1504 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1503 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1502 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1501 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1500 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1499 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1498 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1497 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1496 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1495 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1494 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1493 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1492 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1491 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1490 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1489 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1488 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [1479 on yarn 5]
xfer f10 b10;return loops [1478 on yarn 5]
xfer f12 b12;return loops [1477 on yarn 5]
xfer f14 b14;return loops [1476 on yarn 5]
xfer f16 b16;return loops [1475 on yarn 5]
xfer f18 b18;return loops [1474 on yarn 5]
xfer f20 b20;return loops [1473 on yarn 5]
xfer f22 b22;return loops [1472 on yarn 5]
xfer f24 b24;return loops [1471 on yarn 5]
xfer f26 b26;return loops [1470 on yarn 5]
xfer f28 b28;return loops [1469 on yarn 5]
xfer f30 b30;return loops [1468 on yarn 5]
xfer f32 b32;return loops [1467 on yarn 5]
xfer f34 b34;return loops [1466 on yarn 5]
xfer f36 b36;return loops [1465 on yarn 5]
xfer f38 b38;return loops [1464 on yarn 5]
xfer f40 b40;return loops [1463 on yarn 5]
xfer f42 b42;return loops [1462 on yarn 5]
xfer f44 b44;return loops [1461 on yarn 5]
xfer f46 b46;return loops [1460 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + b8 5
knit + b10 5
knit + b12 5
knit + b14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + b40 5
knit + b42 5
knit + b44 5
knit + b46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b8 f8;peel loops [1516 on yarn 5] from s0 relative to s1
xfer b10 f10;peel loops [1517 on yarn 5] from s0 relative to s1
xfer b12 f12;peel loops [1518 on yarn 5] from s0 relative to s1
xfer b14 f14;peel loops [1519 on yarn 5] from s0 relative to s1
xfer b16 f16;peel loops [1520 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1521 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1522 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1523 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1524 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1525 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1526 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1527 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1528 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1529 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1530 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1531 on yarn 5] from s0 relative to s1
xfer b40 f40;peel loops [1532 on yarn 5] from s0 relative to s1
xfer b42 f42;peel loops [1533 on yarn 5] from s0 relative to s1
xfer b44 f44;peel loops [1534 on yarn 5] from s0 relative to s1
xfer b46 f46;peel loops [1535 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [1507 on yarn 8]
xfer b11 f11;return loops [1506 on yarn 8]
xfer b13 f13;return loops [1505 on yarn 8]
xfer b15 f15;return loops [1504 on yarn 8]
xfer b17 f17;return loops [1503 on yarn 8]
xfer b19 f19;return loops [1502 on yarn 8]
xfer b21 f21;return loops [1501 on yarn 8]
xfer b23 f23;return loops [1500 on yarn 8]
xfer b25 f25;return loops [1499 on yarn 8]
xfer b27 f27;return loops [1498 on yarn 8]
xfer b29 f29;return loops [1497 on yarn 8]
xfer b31 f31;return loops [1496 on yarn 8]
xfer b33 f33;return loops [1495 on yarn 8]
xfer b35 f35;return loops [1494 on yarn 8]
xfer b37 f37;return loops [1493 on yarn 8]
xfer b39 f39;return loops [1492 on yarn 8]
xfer b41 f41;return loops [1491 on yarn 8]
xfer b43 f43;return loops [1490 on yarn 8]
xfer b45 f45;return loops [1489 on yarn 8]
xfer b47 f47;return loops [1488 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + f9 8
knit + f11 8
knit + f13 8
knit + f15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + f41 8
knit + f43 8
knit + f45 8
knit + f47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f9 b9;peel loops [1544 on yarn 8] from s1 relative to s0
xfer f11 b11;peel loops [1545 on yarn 8] from s1 relative to s0
xfer f13 b13;peel loops [1546 on yarn 8] from s1 relative to s0
xfer f15 b15;peel loops [1547 on yarn 8] from s1 relative to s0
xfer f17 b17;peel loops [1548 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1549 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1550 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1551 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1552 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1553 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1554 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1555 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1556 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1557 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1558 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1559 on yarn 8] from s1 relative to s0
xfer f41 b41;peel loops [1560 on yarn 8] from s1 relative to s0
xfer f43 b43;peel loops [1561 on yarn 8] from s1 relative to s0
xfer f45 b45;peel loops [1562 on yarn 8] from s1 relative to s0
xfer f47 b47;peel loops [1563 on yarn 8] from s1 relative to s0
xfer f8 b8;return loops [1516 on yarn 5]
xfer f10 b10;return loops [1517 on yarn 5]
xfer f12 b12;return loops [1518 on yarn 5]
xfer f14 b14;return loops [1519 on yarn 5]
xfer f16 b16;return loops [1520 on yarn 5]
xfer f18 b18;return loops [1521 on yarn 5]
xfer f20 b20;return loops [1522 on yarn 5]
xfer f22 b22;return loops [1523 on yarn 5]
xfer f24 b24;return loops [1524 on yarn 5]
xfer f26 b26;return loops [1525 on yarn 5]
xfer f28 b28;return loops [1526 on yarn 5]
xfer f30 b30;return loops [1527 on yarn 5]
xfer f32 b32;return loops [1528 on yarn 5]
xfer f34 b34;return loops [1529 on yarn 5]
xfer f36 b36;return loops [1530 on yarn 5]
xfer f38 b38;return loops [1531 on yarn 5]
xfer f40 b40;return loops [1532 on yarn 5]
xfer f42 b42;return loops [1533 on yarn 5]
xfer f44 b44;return loops [1534 on yarn 5]
xfer f46 b46;return loops [1535 on yarn 5]
xfer b46 f46
xfer b44 f44
xfer b42 f42
xfer b40 f40
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
xfer b14 f14
xfer b12 f12
xfer b10 f10
xfer b8 f8
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b9 f9;return loops [1544 on yarn 8]
xfer b11 f11;return loops [1545 on yarn 8]
xfer b13 f13;return loops [1546 on yarn 8]
xfer b15 f15;return loops [1547 on yarn 8]
xfer b17 f17;return loops [1548 on yarn 8]
xfer b19 f19;return loops [1549 on yarn 8]
xfer b21 f21;return loops [1550 on yarn 8]
xfer b23 f23;return loops [1551 on yarn 8]
xfer b25 f25;return loops [1552 on yarn 8]
xfer b27 f27;return loops [1553 on yarn 8]
xfer b29 f29;return loops [1554 on yarn 8]
xfer b31 f31;return loops [1555 on yarn 8]
xfer b33 f33;return loops [1556 on yarn 8]
xfer b35 f35;return loops [1557 on yarn 8]
xfer b37 f37;return loops [1558 on yarn 8]
xfer b39 f39;return loops [1559 on yarn 8]
xfer b41 f41;return loops [1560 on yarn 8]
xfer b43 f43;return loops [1561 on yarn 8]
xfer b45 f45;return loops [1562 on yarn 8]
xfer b47 f47;return loops [1563 on yarn 8]
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f55 b55
xfer f53 b53
xfer f51 b51
xfer f49 b49
xfer f47 b47
xfer f45 b45
xfer f43 b43
xfer f41 b41
xfer f15 b15
xfer f13 b13
xfer f11 b11
xfer f9 b9
xfer f7 b7
xfer f5 b5
xfer f3 b3
xfer f1 b1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f17 b17;peel loops [1548 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1549 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1550 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1551 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1552 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1553 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1554 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1555 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1556 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1557 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1558 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1559 on yarn 8] from s1 relative to s0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b16 f16;peel loops [1587 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1586 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1585 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1584 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1583 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1582 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1581 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1580 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1579 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1578 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1577 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1576 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b17 f17;return loops [1548 on yarn 8]
xfer b19 f19;return loops [1549 on yarn 8]
xfer b21 f21;return loops [1550 on yarn 8]
xfer b23 f23;return loops [1551 on yarn 8]
xfer b25 f25;return loops [1552 on yarn 8]
xfer b27 f27;return loops [1553 on yarn 8]
xfer b29 f29;return loops [1554 on yarn 8]
xfer b31 f31;return loops [1555 on yarn 8]
xfer b33 f33;return loops [1556 on yarn 8]
xfer b35 f35;return loops [1557 on yarn 8]
xfer b37 f37;return loops [1558 on yarn 8]
xfer b39 f39;return loops [1559 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f17 b17;peel loops [1615 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1614 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1613 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1612 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1611 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1610 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1609 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1608 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1607 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1606 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1605 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1604 on yarn 8] from s1 relative to s0
xfer f16 b16;return loops [1587 on yarn 5]
xfer f18 b18;return loops [1586 on yarn 5]
xfer f20 b20;return loops [1585 on yarn 5]
xfer f22 b22;return loops [1584 on yarn 5]
xfer f24 b24;return loops [1583 on yarn 5]
xfer f26 b26;return loops [1582 on yarn 5]
xfer f28 b28;return loops [1581 on yarn 5]
xfer f30 b30;return loops [1580 on yarn 5]
xfer f32 b32;return loops [1579 on yarn 5]
xfer f34 b34;return loops [1578 on yarn 5]
xfer f36 b36;return loops [1577 on yarn 5]
xfer f38 b38;return loops [1576 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b16 f16;peel loops [1632 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1633 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1634 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1635 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1636 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1637 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1638 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1639 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1640 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1641 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1642 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1643 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b17 f17;return loops [1615 on yarn 8]
xfer b19 f19;return loops [1614 on yarn 8]
xfer b21 f21;return loops [1613 on yarn 8]
xfer b23 f23;return loops [1612 on yarn 8]
xfer b25 f25;return loops [1611 on yarn 8]
xfer b27 f27;return loops [1610 on yarn 8]
xfer b29 f29;return loops [1609 on yarn 8]
xfer b31 f31;return loops [1608 on yarn 8]
xfer b33 f33;return loops [1607 on yarn 8]
xfer b35 f35;return loops [1606 on yarn 8]
xfer b37 f37;return loops [1605 on yarn 8]
xfer b39 f39;return loops [1604 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f17 b17;peel loops [1660 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1661 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1662 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1663 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1664 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1665 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1666 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1667 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1668 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1669 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1670 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1671 on yarn 8] from s1 relative to s0
xfer f16 b16;return loops [1632 on yarn 5]
xfer f18 b18;return loops [1633 on yarn 5]
xfer f20 b20;return loops [1634 on yarn 5]
xfer f22 b22;return loops [1635 on yarn 5]
xfer f24 b24;return loops [1636 on yarn 5]
xfer f26 b26;return loops [1637 on yarn 5]
xfer f28 b28;return loops [1638 on yarn 5]
xfer f30 b30;return loops [1639 on yarn 5]
xfer f32 b32;return loops [1640 on yarn 5]
xfer f34 b34;return loops [1641 on yarn 5]
xfer f36 b36;return loops [1642 on yarn 5]
xfer f38 b38;return loops [1643 on yarn 5]
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - b38 5
knit - b36 5
knit - b34 5
knit - b32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - b22 5
knit - b20 5
knit - b18 5
knit - b16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b16 f16;peel loops [1699 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1698 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1697 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1696 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1695 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1694 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1693 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1692 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1691 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1690 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1689 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1688 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b17 f17;return loops [1660 on yarn 8]
xfer b19 f19;return loops [1661 on yarn 8]
xfer b21 f21;return loops [1662 on yarn 8]
xfer b23 f23;return loops [1663 on yarn 8]
xfer b25 f25;return loops [1664 on yarn 8]
xfer b27 f27;return loops [1665 on yarn 8]
xfer b29 f29;return loops [1666 on yarn 8]
xfer b31 f31;return loops [1667 on yarn 8]
xfer b33 f33;return loops [1668 on yarn 8]
xfer b35 f35;return loops [1669 on yarn 8]
xfer b37 f37;return loops [1670 on yarn 8]
xfer b39 f39;return loops [1671 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - f39 8
knit - f37 8
knit - f35 8
knit - f33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - f23 8
knit - f21 8
knit - f19 8
knit - f17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f17 b17;peel loops [1727 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1726 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1725 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1724 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1723 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1722 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1721 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1720 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1719 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1718 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1717 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1716 on yarn 8] from s1 relative to s0
xfer f16 b16;return loops [1699 on yarn 5]
xfer f18 b18;return loops [1698 on yarn 5]
xfer f20 b20;return loops [1697 on yarn 5]
xfer f22 b22;return loops [1696 on yarn 5]
xfer f24 b24;return loops [1695 on yarn 5]
xfer f26 b26;return loops [1694 on yarn 5]
xfer f28 b28;return loops [1693 on yarn 5]
xfer f30 b30;return loops [1692 on yarn 5]
xfer f32 b32;return loops [1691 on yarn 5]
xfer f34 b34;return loops [1690 on yarn 5]
xfer f36 b36;return loops [1689 on yarn 5]
xfer f38 b38;return loops [1688 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + b16 5
knit + b18 5
knit + b20 5
knit + b22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + b32 5
knit + b34 5
knit + b36 5
knit + b38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b16 f16;peel loops [1744 on yarn 5] from s0 relative to s1
xfer b18 f18;peel loops [1745 on yarn 5] from s0 relative to s1
xfer b20 f20;peel loops [1746 on yarn 5] from s0 relative to s1
xfer b22 f22;peel loops [1747 on yarn 5] from s0 relative to s1
xfer b24 f24;peel loops [1748 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1749 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1750 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1751 on yarn 5] from s0 relative to s1
xfer b32 f32;peel loops [1752 on yarn 5] from s0 relative to s1
xfer b34 f34;peel loops [1753 on yarn 5] from s0 relative to s1
xfer b36 f36;peel loops [1754 on yarn 5] from s0 relative to s1
xfer b38 f38;peel loops [1755 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b17 f17;return loops [1727 on yarn 8]
xfer b19 f19;return loops [1726 on yarn 8]
xfer b21 f21;return loops [1725 on yarn 8]
xfer b23 f23;return loops [1724 on yarn 8]
xfer b25 f25;return loops [1723 on yarn 8]
xfer b27 f27;return loops [1722 on yarn 8]
xfer b29 f29;return loops [1721 on yarn 8]
xfer b31 f31;return loops [1720 on yarn 8]
xfer b33 f33;return loops [1719 on yarn 8]
xfer b35 f35;return loops [1718 on yarn 8]
xfer b37 f37;return loops [1717 on yarn 8]
xfer b39 f39;return loops [1716 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + f17 8
knit + f19 8
knit + f21 8
knit + f23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + f33 8
knit + f35 8
knit + f37 8
knit + f39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f17 b17;peel loops [1772 on yarn 8] from s1 relative to s0
xfer f19 b19;peel loops [1773 on yarn 8] from s1 relative to s0
xfer f21 b21;peel loops [1774 on yarn 8] from s1 relative to s0
xfer f23 b23;peel loops [1775 on yarn 8] from s1 relative to s0
xfer f25 b25;peel loops [1776 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1777 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1778 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1779 on yarn 8] from s1 relative to s0
xfer f33 b33;peel loops [1780 on yarn 8] from s1 relative to s0
xfer f35 b35;peel loops [1781 on yarn 8] from s1 relative to s0
xfer f37 b37;peel loops [1782 on yarn 8] from s1 relative to s0
xfer f39 b39;peel loops [1783 on yarn 8] from s1 relative to s0
xfer f16 b16;return loops [1744 on yarn 5]
xfer f18 b18;return loops [1745 on yarn 5]
xfer f20 b20;return loops [1746 on yarn 5]
xfer f22 b22;return loops [1747 on yarn 5]
xfer f24 b24;return loops [1748 on yarn 5]
xfer f26 b26;return loops [1749 on yarn 5]
xfer f28 b28;return loops [1750 on yarn 5]
xfer f30 b30;return loops [1751 on yarn 5]
xfer f32 b32;return loops [1752 on yarn 5]
xfer f34 b34;return loops [1753 on yarn 5]
xfer f36 b36;return loops [1754 on yarn 5]
xfer f38 b38;return loops [1755 on yarn 5]
xfer b38 f38
xfer b36 f36
xfer b34 f34
xfer b32 f32
xfer b30 f30
xfer b28 f28
xfer b26 f26
xfer b24 f24
xfer b22 f22
xfer b20 f20
xfer b18 f18
xfer b16 f16
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
;Peel sheet 1 relative to 1
xfer b17 f17;return loops [1772 on yarn 8]
xfer b19 f19;return loops [1773 on yarn 8]
xfer b21 f21;return loops [1774 on yarn 8]
xfer b23 f23;return loops [1775 on yarn 8]
xfer b25 f25;return loops [1776 on yarn 8]
xfer b27 f27;return loops [1777 on yarn 8]
xfer b29 f29;return loops [1778 on yarn 8]
xfer b31 f31;return loops [1779 on yarn 8]
xfer b33 f33;return loops [1780 on yarn 8]
xfer b35 f35;return loops [1781 on yarn 8]
xfer b37 f37;return loops [1782 on yarn 8]
xfer b39 f39;return loops [1783 on yarn 8]
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b47 f47
xfer b45 f45
xfer b43 f43
xfer b41 f41
xfer b15 f15
xfer b13 f13
xfer b11 f11
xfer b9 f9
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f55 b55
xfer f53 b53
xfer f51 b51
xfer f49 b49
xfer f47 b47
xfer f45 b45
xfer f43 b43
xfer f41 b41
xfer f39 b39
xfer f37 b37
xfer f35 b35
xfer f33 b33
xfer f23 b23
xfer f21 b21
xfer f19 b19
xfer f17 b17
xfer f15 b15
xfer f13 b13
xfer f11 b11
xfer f9 b9
xfer f7 b7
xfer f5 b5
xfer f3 b3
xfer f1 b1
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f25 b25;peel loops [1776 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1777 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1778 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1779 on yarn 8] from s1 relative to s0
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - f38 5
knit - f36 5
knit - f34 5
knit - f32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - f22 5
knit - f20 5
knit - f18 5
knit - f16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b24 f24;peel loops [1807 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1806 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1805 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1804 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b25 f25;return loops [1776 on yarn 8]
xfer b27 f27;return loops [1777 on yarn 8]
xfer b29 f29;return loops [1778 on yarn 8]
xfer b31 f31;return loops [1779 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - b39 8
knit - b37 8
knit - b35 8
knit - b33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - b23 8
knit - b21 8
knit - b19 8
knit - b17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f25 b25;peel loops [1835 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1834 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1833 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1832 on yarn 8] from s1 relative to s0
xfer f24 b24;return loops [1807 on yarn 5]
xfer f26 b26;return loops [1806 on yarn 5]
xfer f28 b28;return loops [1805 on yarn 5]
xfer f30 b30;return loops [1804 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + f16 5
knit + f18 5
knit + f20 5
knit + f22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + f32 5
knit + f34 5
knit + f36 5
knit + f38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b24 f24;peel loops [1860 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1861 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1862 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1863 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b25 f25;return loops [1835 on yarn 8]
xfer b27 f27;return loops [1834 on yarn 8]
xfer b29 f29;return loops [1833 on yarn 8]
xfer b31 f31;return loops [1832 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + b17 8
knit + b19 8
knit + b21 8
knit + b23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + b33 8
knit + b35 8
knit + b37 8
knit + b39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f25 b25;peel loops [1888 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1889 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1890 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1891 on yarn 8] from s1 relative to s0
xfer f24 b24;return loops [1860 on yarn 5]
xfer f26 b26;return loops [1861 on yarn 5]
xfer f28 b28;return loops [1862 on yarn 5]
xfer f30 b30;return loops [1863 on yarn 5]
knit - f54 5
knit - f52 5
knit - f50 5
knit - f48 5
knit - f46 5
knit - f44 5
knit - f42 5
knit - f40 5
knit - f38 5
knit - f36 5
knit - f34 5
knit - f32 5
knit - b30 5
knit - b28 5
knit - b26 5
knit - b24 5
knit - f22 5
knit - f20 5
knit - f18 5
knit - f16 5
knit - f14 5
knit - f12 5
knit - f10 5
knit - f8 5
knit - f6 5
knit - f4 5
knit - f2 5
knit - f0 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b24 f24;peel loops [1919 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1918 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1917 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1916 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b25 f25;return loops [1888 on yarn 8]
xfer b27 f27;return loops [1889 on yarn 8]
xfer b29 f29;return loops [1890 on yarn 8]
xfer b31 f31;return loops [1891 on yarn 8]
knit - b55 8
knit - b53 8
knit - b51 8
knit - b49 8
knit - b47 8
knit - b45 8
knit - b43 8
knit - b41 8
knit - b39 8
knit - b37 8
knit - b35 8
knit - b33 8
knit - f31 8
knit - f29 8
knit - f27 8
knit - f25 8
knit - b23 8
knit - b21 8
knit - b19 8
knit - b17 8
knit - b15 8
knit - b13 8
knit - b11 8
knit - b9 8
knit - b7 8
knit - b5 8
knit - b3 8
knit - b1 8
;Resetting to sheet s0:g2 of 2
;Peel sheet 0 relative to 0
;Peel sheet 1 relative to 0
xfer f25 b25;peel loops [1947 on yarn 8] from s1 relative to s0
xfer f27 b27;peel loops [1946 on yarn 8] from s1 relative to s0
xfer f29 b29;peel loops [1945 on yarn 8] from s1 relative to s0
xfer f31 b31;peel loops [1944 on yarn 8] from s1 relative to s0
xfer f24 b24;return loops [1919 on yarn 5]
xfer f26 b26;return loops [1918 on yarn 5]
xfer f28 b28;return loops [1917 on yarn 5]
xfer f30 b30;return loops [1916 on yarn 5]
knit + f0 5
knit + f2 5
knit + f4 5
knit + f6 5
knit + f8 5
knit + f10 5
knit + f12 5
knit + f14 5
knit + f16 5
knit + f18 5
knit + f20 5
knit + f22 5
knit + b24 5
knit + b26 5
knit + b28 5
knit + b30 5
knit + f32 5
knit + f34 5
knit + f36 5
knit + f38 5
knit + f40 5
knit + f42 5
knit + f44 5
knit + f46 5
knit + f48 5
knit + f50 5
knit + f52 5
knit + f54 5
;Resetting to sheet s1:g2 of 2
;Peel sheet 0 relative to 1
xfer b24 f24;peel loops [1972 on yarn 5] from s0 relative to s1
xfer b26 f26;peel loops [1973 on yarn 5] from s0 relative to s1
xfer b28 f28;peel loops [1974 on yarn 5] from s0 relative to s1
xfer b30 f30;peel loops [1975 on yarn 5] from s0 relative to s1
;Peel sheet 1 relative to 1
xfer b25 f25;return loops [1947 on yarn 8]
xfer b27 f27;return loops [1946 on yarn 8]
xfer b29 f29;return loops [1945 on yarn 8]
xfer b31 f31;return loops [1944 on yarn 8]
knit + b1 8
knit + b3 8
knit + b5 8
knit + b7 8
knit + b9 8
knit + b11 8
knit + b13 8
knit + b15 8
knit + b17 8
knit + b19 8
knit + b21 8
knit + b23 8
knit + f25 8
knit + f27 8
knit + f29 8
knit + f31 8
knit + b33 8
knit + b35 8
knit + b37 8
knit + b39 8
knit + b41 8
knit + b43 8
knit + b45 8
knit + b47 8
knit + b49 8
knit + b51 8
knit + b53 8
knit + b55 8
xfer b55 f55
xfer b53 f53
xfer b51 f51
xfer b49 f49
xfer b47 f47
xfer b45 f45
xfer b43 f43
xfer b41 f41
xfer b39 f39
xfer b37 f37
xfer b35 f35
xfer b33 f33
xfer b23 f23
xfer b21 f21
xfer b19 f19
xfer b17 f17
xfer b15 f15
xfer b13 f13
xfer b11 f11
xfer b9 f9
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
rack 2;Rack to 1 at 2 gauge
xfer f55 b53
rack 0.0;Rack to 0.0 at 2 gauge
split + b53 f53 5
knit - f53 5
rack 2;Rack to 1 at 2 gauge
xfer f53 b51
rack 0.0;Rack to 0.0 at 2 gauge
split + b51 f51 5
knit - f51 5
rack 2;Rack to 1 at 2 gauge
xfer f51 b49
rack 0.0;Rack to 0.0 at 2 gauge
split + b49 f49 5
knit - f49 5
rack 2;Rack to 1 at 2 gauge
xfer f49 b47
rack 0.0;Rack to 0.0 at 2 gauge
split + b47 f47 5
knit - f47 5
rack 2;Rack to 1 at 2 gauge
xfer f47 b45
rack 0.0;Rack to 0.0 at 2 gauge
split + b45 f45 5
knit - f45 5
rack 2;Rack to 1 at 2 gauge
xfer f45 b43
rack 0.0;Rack to 0.0 at 2 gauge
split + b43 f43 5
knit - f43 5
rack 2;Rack to 1 at 2 gauge
xfer f43 b41
rack 0.0;Rack to 0.0 at 2 gauge
split + b41 f41 5
knit - f41 5
rack 2;Rack to 1 at 2 gauge
xfer f41 b39
rack 0.0;Rack to 0.0 at 2 gauge
split + b39 f39 5
knit - f39 5
rack 2;Rack to 1 at 2 gauge
xfer f39 b37
rack 0.0;Rack to 0.0 at 2 gauge
split + b37 f37 5
knit - f37 5
rack 2;Rack to 1 at 2 gauge
xfer f37 b35
rack 0.0;Rack to 0.0 at 2 gauge
split + b35 f35 5
knit - f35 5
rack 2;Rack to 1 at 2 gauge
xfer f35 b33
rack 0.0;Rack to 0.0 at 2 gauge
split + b33 f33 5
knit - f33 5
rack 2;Rack to 1 at 2 gauge
xfer f33 b31
rack 0.0;Rack to 0.0 at 2 gauge
split + b31 f31 5
knit - f31 5
rack 2;Rack to 1 at 2 gauge
xfer f31 b29
rack 0.0;Rack to 0.0 at 2 gauge
split + b29 f29 5
knit - f29 5
rack 2;Rack to 1 at 2 gauge
xfer f29 b27
rack 0.0;Rack to 0.0 at 2 gauge
split + b27 f27 5
knit - f27 5
rack 2;Rack to 1 at 2 gauge
xfer f27 b25
rack 0.0;Rack to 0.0 at 2 gauge
split + b25 f25 5
knit - f25 5
rack 2;Rack to 1 at 2 gauge
xfer f25 b23
rack 0.0;Rack to 0.0 at 2 gauge
split + b23 f23 5
knit - f23 5
rack 2;Rack to 1 at 2 gauge
xfer f23 b21
rack 0.0;Rack to 0.0 at 2 gauge
split + b21 f21 5
knit - f21 5
rack 2;Rack to 1 at 2 gauge
xfer f21 b19
rack 0.0;Rack to 0.0 at 2 gauge
split + b19 f19 5
knit - f19 5
rack 2;Rack to 1 at 2 gauge
xfer f19 b17
rack 0.0;Rack to 0.0 at 2 gauge
split + b17 f17 5
knit - f17 5
rack 2;Rack to 1 at 2 gauge
xfer f17 b15
rack 0.0;Rack to 0.0 at 2 gauge
split + b15 f15 5
knit - f15 5
rack 2;Rack to 1 at 2 gauge
xfer f15 b13
rack 0.0;Rack to 0.0 at 2 gauge
split + b13 f13 5
knit - f13 5
rack 2;Rack to 1 at 2 gauge
xfer f13 b11
rack 0.0;Rack to 0.0 at 2 gauge
split + b11 f11 5
knit - f11 5
rack 2;Rack to 1 at 2 gauge
xfer f11 b9
rack 0.0;Rack to 0.0 at 2 gauge
split + b9 f9 5
knit - f9 5
rack 2;Rack to 1 at 2 gauge
xfer f9 b7
rack 0.0;Rack to 0.0 at 2 gauge
split + b7 f7 5
knit - f7 5
rack 2;Rack to 1 at 2 gauge
xfer f7 b5
rack 0.0;Rack to 0.0 at 2 gauge
split + b5 f5 5
knit - f5 5
rack 2;Rack to 1 at 2 gauge
xfer f5 b3
rack 0.0;Rack to 0.0 at 2 gauge
split + b3 f3 5
knit - f3 5
rack 2;Rack to 1 at 2 gauge
xfer f3 b1
rack 0.0;Rack to 0.0 at 2 gauge
split + b1 f1 5
knit - f1 5
;KS: Spare knitting on [b53, b51, b49, b47, b45, b43, b41, b39, b37, b35, b33, b31, b29, b27, b25, b23, b21, b19, b17, b15, b13, b11, b9, b7, b5, b3, b1]
knit + b1 5
knit + b3 5
knit + b5 5
knit + b7 5
knit + b9 5
knit + b11 5
knit + b13 5
knit + b15 5
knit + b17 5
knit + b19 5
knit + b21 5
knit + b23 5
knit + b25 5
knit + b27 5
knit + b29 5
knit + b31 5
knit + b33 5
knit + b35 5
knit + b37 5
knit + b39 5
knit + b41 5
knit + b43 5
knit + b45 5
knit + b47 5
knit + b49 5
knit + b51 5
knit + b53 5
releasehook 8;Release inserting hook before cutting all yarns
outhook 5;Cutting active yarn on 5
outhook 8;Cutting active yarn on 8
