;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 2;Activating carrier 2
;KS: Cast on 68loops from 0to 68
tuck - f67 2
tuck - f65 2
tuck - f63 2
tuck - f61 2
tuck - f59 2
tuck - f57 2
tuck - f55 2
tuck - f53 2
tuck - f51 2
tuck - f49 2
tuck - f47 2
tuck - f45 2
tuck - f43 2
tuck - f41 2
tuck - f39 2
tuck - f37 2
tuck - f35 2
tuck - f33 2
tuck - f31 2
tuck - f29 2
tuck - f27 2
tuck - f25 2
tuck - f23 2
tuck - f21 2
tuck - f19 2
tuck - f17 2
tuck - f15 2
tuck - f13 2
tuck - f11 2
tuck - f9 2
tuck - f7 2
tuck - f5 2
tuck - f3 2
tuck - f1 2
tuck + f0 2
tuck + f2 2
tuck + f4 2
tuck + f6 2
tuck + f8 2
tuck + f10 2
tuck + f12 2
tuck + f14 2
tuck + f16 2
tuck + f18 2
tuck + f20 2
tuck + f22 2
tuck + f24 2
tuck + f26 2
tuck + f28 2
tuck + f30 2
tuck + f32 2
tuck + f34 2
tuck + f36 2
tuck + f38 2
tuck + f40 2
tuck + f42 2
tuck + f44 2
tuck + f46 2
tuck + f48 2
tuck + f50 2
tuck + f52 2
tuck + f54 2
tuck + f56 2
tuck + f58 2
tuck + f60 2
tuck + f62 2
tuck + f64 2
tuck + f66 2
tuck - f67 2
tuck - f65 2
tuck - f63 2
tuck - f61 2
tuck - f59 2
tuck - f57 2
tuck - f55 2
tuck - f53 2
tuck - f51 2
tuck - f49 2
tuck - f47 2
tuck - f45 2
tuck - f43 2
tuck - f41 2
tuck - f39 2
tuck - f37 2
tuck - f35 2
tuck - f33 2
tuck - f31 2
tuck - f29 2
tuck - f27 2
tuck - f25 2
tuck - f23 2
tuck - f21 2
tuck - f19 2
tuck - f17 2
tuck - f15 2
tuck - f13 2
tuck - f11 2
tuck - f9 2
tuck - f7 2
tuck - f5 2
tuck - f3 2
tuck - f1 2
tuck + f0 2
tuck + f2 2
tuck + f4 2
tuck + f6 2
tuck + f8 2
tuck + f10 2
tuck + f12 2
tuck + f14 2
tuck + f16 2
tuck + f18 2
tuck + f20 2
tuck + f22 2
tuck + f24 2
tuck + f26 2
tuck + f28 2
tuck + f30 2
tuck + f32 2
tuck + f34 2
tuck + f36 2
tuck + f38 2
tuck + f40 2
tuck + f42 2
tuck + f44 2
tuck + f46 2
tuck + f48 2
tuck + f50 2
tuck + f52 2
tuck + f54 2
tuck + f56 2
tuck + f58 2
tuck + f60 2
tuck + f62 2
tuck + f64 2
tuck + f66 2
releasehook 2
knit - f67 2
knit - f66 2
knit - f65 2
knit - f64 2
knit - f63 2
knit - f62 2
knit - f61 2
knit - f60 2
knit - f59 2
knit - f58 2
knit - f57 2
knit - f56 2
knit - f55 2
knit - f54 2
knit - f53 2
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
knit + f53 2
knit + f54 2
knit + f55 2
knit + f56 2
knit + f57 2
knit + f58 2
knit + f59 2
knit + f60 2
knit + f61 2
knit + f62 2
knit + f63 2
knit + f64 2
knit + f65 2
knit + f66 2
knit + f67 2
knit - f67 2
knit - f66 2
knit - f65 2
knit - f64 2
knit - f63 2
knit - f62 2
knit - f61 2
knit - f60 2
knit - f59 2
knit - f58 2
knit - f57 2
knit - f56 2
knit - f55 2
knit - f54 2
knit - f53 2
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
knit + f53 2
knit + f54 2
knit + f55 2
knit + f56 2
knit + f57 2
knit + f58 2
knit + f59 2
knit + f60 2
knit + f61 2
knit + f62 2
knit + f63 2
knit + f64 2
knit + f65 2
knit + f66 2
knit + f67 2
knit - f67 2
knit - f66 2
knit - f65 2
knit - f64 2
knit - f63 2
knit - f62 2
knit - f61 2
knit - f60 2
knit - f59 2
knit - f58 2
knit - f57 2
knit - f56 2
knit - f55 2
knit - f54 2
knit - f53 2
drop f53
drop f54
drop f55
drop f56
drop f57
drop f58
drop f59
drop f60
drop f61
drop f62
drop f63
drop f64
drop f65
drop f66
drop f67
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
knit - f52 2
knit - f51 2
knit - f50 2
knit - f49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + f13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + f39 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
knit + f47 2
knit + f48 2
knit + f49 2
knit + f50 2
knit + f51 2
knit + f52 2
xfer f52 b52
xfer f50 b50
xfer f48 b48
xfer f46 b46
xfer f44 b44
xfer f42 b42
xfer f40 b40
xfer f38 b38
xfer f36 b36
xfer f34 b34
xfer f32 b32
xfer f30 b30
xfer f28 b28
xfer f26 b26
xfer f24 b24
xfer f22 b22
xfer f20 b20
xfer f18 b18
xfer f16 b16
xfer f14 b14
xfer f12 b12
xfer f10 b10
xfer f8 b8
xfer f6 b6
xfer f4 b4
xfer f2 b2
xfer f0 b0
rack 1;Rack to 1 at 1 gauge
xfer f51 b50
xfer f49 b48
xfer f47 b46
xfer f45 b44
xfer f43 b42
xfer f41 b40
xfer f39 b38
xfer f37 b36
xfer f35 b34
xfer f33 b32
xfer f31 b30
xfer f29 b28
xfer f27 b26
xfer f25 b24
xfer f23 b22
xfer f21 b20
xfer f19 b18
xfer f17 b16
xfer f15 b14
xfer f13 b12
xfer f11 b10
xfer f9 b8
xfer f7 b6
xfer f5 b4
xfer f3 b2
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
inhook 1;Activating carrier 1
tuck - f52 1
miss + f52 1
tuck - f52 1
miss - b51 1
tuck + b51 1
miss - b51 1
miss - f50 1
tuck + f50 1
miss - f50 1
miss - b49 1
tuck + b49 1
miss - b49 1
miss - f48 1
tuck + f48 1
miss - f48 1
miss - b47 1
tuck + b47 1
miss - b47 1
miss - f46 1
tuck + f46 1
miss - f46 1
miss - b45 1
tuck + b45 1
miss - b45 1
miss - f44 1
tuck + f44 1
miss - f44 1
miss - b43 1
tuck + b43 1
miss - b43 1
miss - f42 1
tuck + f42 1
miss - f42 1
miss - b41 1
tuck + b41 1
miss - b41 1
miss - f40 1
tuck + f40 1
miss - f40 1
miss - b39 1
tuck + b39 1
miss - b39 1
miss - f38 1
tuck + f38 1
miss - f38 1
miss - b37 1
tuck + b37 1
miss - b37 1
miss - f36 1
tuck + f36 1
miss - f36 1
miss - b35 1
tuck + b35 1
miss - b35 1
miss - f34 1
tuck + f34 1
miss - f34 1
miss - b33 1
tuck + b33 1
miss - b33 1
miss - f32 1
tuck + f32 1
miss - f32 1
miss - b31 1
tuck + b31 1
miss - b31 1
miss - f30 1
tuck + f30 1
miss - f30 1
miss - b29 1
tuck + b29 1
miss - b29 1
miss - f28 1
tuck + f28 1
miss - f28 1
miss - b27 1
tuck + b27 1
miss - b27 1
miss - f26 1
tuck + f26 1
miss - f26 1
miss - b25 1
tuck + b25 1
miss - b25 1
miss - f24 1
tuck + f24 1
miss - f24 1
miss - b23 1
tuck + b23 1
miss - b23 1
miss - f22 1
tuck + f22 1
miss - f22 1
miss - b21 1
tuck + b21 1
miss - b21 1
miss - f20 1
tuck + f20 1
miss - f20 1
miss - b19 1
tuck + b19 1
miss - b19 1
miss - f18 1
tuck + f18 1
miss - f18 1
miss - b17 1
tuck + b17 1
miss - b17 1
miss - f16 1
tuck + f16 1
miss - f16 1
miss - b15 1
tuck + b15 1
miss - b15 1
miss - f14 1
tuck + f14 1
miss - f14 1
miss - b13 1
tuck + b13 1
miss - b13 1
miss - f12 1
tuck + f12 1
miss - f12 1
miss - b11 1
tuck + b11 1
miss - b11 1
miss - f10 1
tuck + f10 1
miss - f10 1
miss - b9 1
tuck + b9 1
miss - b9 1
miss - f8 1
tuck + f8 1
miss - f8 1
miss - b7 1
tuck + b7 1
miss - b7 1
miss - f6 1
tuck + f6 1
miss - f6 1
miss - b5 1
tuck + b5 1
miss - b5 1
miss - f4 1
tuck + f4 1
miss - f4 1
miss - b3 1
tuck + b3 1
miss - b3 1
miss - f2 1
tuck + f2 1
miss - f2 1
miss - b1 1
tuck + b1 1
miss - b1 1
miss - f0 1
tuck + f0 1
miss - f0 1
;KS: Cast on 80loops from f52to f0
releasehook 1
tuck - f51 2
tuck - f49 2
tuck - f47 2
tuck - f45 2
tuck - f43 2
tuck - f41 2
tuck - f39 2
tuck - f37 2
tuck - f35 2
tuck - f33 2
tuck - f31 2
tuck - f29 2
tuck - f27 2
tuck - f25 2
tuck - f23 2
tuck - f21 2
tuck - f19 2
tuck - f17 2
tuck - f15 2
tuck - f13 2
tuck - f11 2
tuck - f9 2
tuck - f7 2
tuck - f5 2
tuck - f3 2
tuck - f1 2
drop f1
drop f3
drop f5
drop f7
drop f9
drop f11
drop f13
drop f15
drop f17
drop f19
drop f21
drop f23
drop f25
drop f27
drop f29
drop f31
drop f33
drop f35
drop f37
drop f39
drop f41
drop f43
drop f45
drop f47
drop f49
drop f51
xfer b51 f51
xfer b49 f49
xfer b47 f47
xfer b45 f45
xfer b43 f43
xfer b41 f41
xfer b39 f39
xfer b37 f37
xfer b35 f35
xfer b33 f33
xfer b31 f31
xfer b29 f29
xfer b27 f27
xfer b25 f25
xfer b23 f23
xfer b21 f21
xfer b19 f19
xfer b17 f17
xfer b15 f15
xfer b13 f13
xfer b11 f11
xfer b9 f9
xfer b7 f7
xfer b5 f5
xfer b3 f3
xfer b1 f1
drop b0
drop b2
drop b4
drop b6
drop b8
drop b10
drop b12
drop b14
drop b16
drop b18
drop b20
drop b22
drop b24
drop b26
drop b28
drop b30
drop b32
drop b34
drop b36
drop b38
drop b40
drop b42
drop b44
drop b46
drop b48
drop b50
drop b52
outhook 2
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f35 b35
xfer f17 b17
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer f52 b52
xfer f51 b51
xfer f50 b50
xfer f49 b49
xfer f48 b48
xfer f47 b47
xfer f46 b46
xfer f45 b45
xfer f43 b43
xfer f42 b42
xfer f41 b41
xfer f40 b40
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
xfer f0 b0
knit - b52 1
knit - b51 1
knit - b50 1
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - b0 1
xfer b0 f0
xfer b1 f1
xfer b2 f2
xfer b3 f3
xfer b4 f4
xfer b5 f5
xfer b6 f6
xfer b7 f7
xfer b9 f9
xfer b10 f10
xfer b11 f11
xfer b12 f12
xfer b13 f13
xfer b14 f14
xfer b15 f15
xfer b16 f16
xfer b18 f18
xfer b19 f19
xfer b20 f20
xfer b21 f21
xfer b22 f22
xfer b23 f23
xfer b24 f24
xfer b25 f25
xfer b27 f27
xfer b28 f28
xfer b29 f29
xfer b30 f30
xfer b31 f31
xfer b32 f32
xfer b33 f33
xfer b34 f34
xfer b36 f36
xfer b37 f37
xfer b38 f38
xfer b39 f39
xfer b40 f40
xfer b41 f41
xfer b42 f42
xfer b43 f43
xfer b45 f45
xfer b46 f46
xfer b47 f47
xfer b48 f48
xfer b49 f49
xfer b50 f50
xfer b51 f51
xfer b52 f52
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit + f50 1
knit + f51 1
knit + f52 1
xfer b35 f35
xfer b17 f17
;KS: [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f19, f20, f21, f22, f23, f24, f25, f26, f27, f28, f29, f30, f31, f32, f33, f34, f35, f36, f37, f38, f39, f40, f41, f42, f43, f44, f45, f46, f47, f48, f49, f50, f51, f52]
outhook 1;Cutting active yarn on 1
