;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 1;Activating carrier 1
;KS: Cast on 50loops from 0to 50
tuck - f49 1
tuck - f47 1
tuck - f45 1
tuck - f43 1
tuck - f41 1
tuck - f39 1
tuck - f37 1
tuck - f35 1
tuck - f33 1
tuck - f31 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
tuck + f44 1
tuck + f46 1
tuck + f48 1
tuck - f49 1
tuck - f47 1
tuck - f45 1
tuck - f43 1
tuck - f41 1
tuck - f39 1
tuck - f37 1
tuck - f35 1
tuck - f33 1
tuck - f31 1
tuck - f29 1
tuck - f27 1
tuck - f25 1
tuck - f23 1
tuck - f21 1
tuck - f19 1
tuck - f17 1
tuck - f15 1
tuck - f13 1
tuck - f11 1
tuck - f9 1
tuck - f7 1
tuck - f5 1
tuck - f3 1
tuck - f1 1
tuck + f0 1
tuck + f2 1
tuck + f4 1
tuck + f6 1
tuck + f8 1
tuck + f10 1
tuck + f12 1
tuck + f14 1
tuck + f16 1
tuck + f18 1
tuck + f20 1
tuck + f22 1
tuck + f24 1
tuck + f26 1
tuck + f28 1
tuck + f30 1
tuck + f32 1
tuck + f34 1
tuck + f36 1
tuck + f38 1
tuck + f40 1
tuck + f42 1
tuck + f44 1
tuck + f46 1
tuck + f48 1
releasehook 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f2 b2
xfer f5 b5
xfer f8 b8
xfer f11 b11
xfer f14 b14
xfer f17 b17
xfer f20 b20
xfer f23 b23
xfer f26 b26
xfer f29 b29
xfer f32 b32
xfer f35 b35
xfer f38 b38
xfer f41 b41
xfer f44 b44
rack 1;Rack to 1 at 1 gauge
xfer b2 f3
xfer b5 f6
xfer b8 f9
xfer b11 f12
xfer b14 f15
xfer b17 f18
xfer b20 f21
xfer b23 f24
xfer b26 f27
xfer b29 f30
xfer b32 f33
xfer b35 f36
xfer b38 f39
xfer b41 f42
xfer b44 f45
rack 0.0;Rack to 0.0 at 1 gauge
tuck + f2 1
tuck + f5 1
tuck + f8 1
tuck + f11 1
tuck + f14 1
tuck + f17 1
tuck + f20 1
tuck + f23 1
tuck + f26 1
tuck + f29 1
tuck + f32 1
tuck + f35 1
tuck + f38 1
tuck + f41 1
tuck + f44 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
xfer f44 b44
xfer f41 b41
xfer f38 b38
xfer f35 b35
xfer f32 b32
xfer f29 b29
xfer f26 b26
xfer f23 b23
xfer f20 b20
xfer f17 b17
xfer f14 b14
xfer f11 b11
xfer f8 b8
xfer f5 b5
xfer f2 b2
rack -1;Rack to -1 at 1 gauge
xfer b44 f43
xfer b41 f40
xfer b38 f37
xfer b35 f34
xfer b32 f31
xfer b29 f28
xfer b26 f25
xfer b23 f22
xfer b20 f19
xfer b17 f16
xfer b14 f13
xfer b11 f10
xfer b8 f7
xfer b5 f4
xfer b2 f1
rack 0.0;Rack to 0.0 at 1 gauge
tuck - f44 1
tuck - f41 1
tuck - f38 1
tuck - f35 1
tuck - f32 1
tuck - f29 1
tuck - f26 1
tuck - f23 1
tuck - f20 1
tuck - f17 1
tuck - f14 1
tuck - f11 1
tuck - f8 1
tuck - f5 1
tuck - f2 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + f43 1
knit + f44 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
knit + f49 1
knit - f49 1
knit - f48 1
knit - f47 1
knit - f46 1
knit - f45 1
knit - f44 1
knit - f43 1
knit - f42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - f37 1
knit - f36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
rack -1;Rack to -1 at 1 gauge
xfer f0 b1
rack 0.0;Rack to 0.0 at 1 gauge
split - b1 f1 1
knit + f1 1
rack -1;Rack to -1 at 1 gauge
xfer f1 b2
rack 0.0;Rack to 0.0 at 1 gauge
split - b2 f2 1
knit + f2 1
rack -1;Rack to -1 at 1 gauge
xfer f2 b3
rack 0.0;Rack to 0.0 at 1 gauge
split - b3 f3 1
knit + f3 1
rack -1;Rack to -1 at 1 gauge
xfer f3 b4
rack 0.0;Rack to 0.0 at 1 gauge
split - b4 f4 1
knit + f4 1
rack -1;Rack to -1 at 1 gauge
xfer f4 b5
rack 0.0;Rack to 0.0 at 1 gauge
split - b5 f5 1
knit + f5 1
rack -1;Rack to -1 at 1 gauge
xfer f5 b6
rack 0.0;Rack to 0.0 at 1 gauge
split - b6 f6 1
knit + f6 1
rack -1;Rack to -1 at 1 gauge
xfer f6 b7
rack 0.0;Rack to 0.0 at 1 gauge
split - b7 f7 1
knit + f7 1
rack -1;Rack to -1 at 1 gauge
xfer f7 b8
rack 0.0;Rack to 0.0 at 1 gauge
split - b8 f8 1
knit + f8 1
rack -1;Rack to -1 at 1 gauge
xfer f8 b9
rack 0.0;Rack to 0.0 at 1 gauge
split - b9 f9 1
knit + f9 1
rack -1;Rack to -1 at 1 gauge
xfer f9 b10
rack 0.0;Rack to 0.0 at 1 gauge
split - b10 f10 1
knit + f10 1
rack -1;Rack to -1 at 1 gauge
xfer f10 b11
rack 0.0;Rack to 0.0 at 1 gauge
split - b11 f11 1
knit + f11 1
rack -1;Rack to -1 at 1 gauge
xfer f11 b12
rack 0.0;Rack to 0.0 at 1 gauge
split - b12 f12 1
knit + f12 1
rack -1;Rack to -1 at 1 gauge
xfer f12 b13
rack 0.0;Rack to 0.0 at 1 gauge
split - b13 f13 1
knit + f13 1
rack -1;Rack to -1 at 1 gauge
xfer f13 b14
rack 0.0;Rack to 0.0 at 1 gauge
split - b14 f14 1
knit + f14 1
rack -1;Rack to -1 at 1 gauge
xfer f14 b15
rack 0.0;Rack to 0.0 at 1 gauge
split - b15 f15 1
knit + f15 1
rack -1;Rack to -1 at 1 gauge
xfer f15 b16
rack 0.0;Rack to 0.0 at 1 gauge
split - b16 f16 1
knit + f16 1
rack -1;Rack to -1 at 1 gauge
xfer f16 b17
rack 0.0;Rack to 0.0 at 1 gauge
split - b17 f17 1
knit + f17 1
rack -1;Rack to -1 at 1 gauge
xfer f17 b18
rack 0.0;Rack to 0.0 at 1 gauge
split - b18 f18 1
knit + f18 1
rack -1;Rack to -1 at 1 gauge
xfer f18 b19
rack 0.0;Rack to 0.0 at 1 gauge
split - b19 f19 1
knit + f19 1
rack -1;Rack to -1 at 1 gauge
xfer f19 b20
rack 0.0;Rack to 0.0 at 1 gauge
split - b20 f20 1
knit + f20 1
rack -1;Rack to -1 at 1 gauge
xfer f20 b21
rack 0.0;Rack to 0.0 at 1 gauge
split - b21 f21 1
knit + f21 1
rack -1;Rack to -1 at 1 gauge
xfer f21 b22
rack 0.0;Rack to 0.0 at 1 gauge
split - b22 f22 1
knit + f22 1
rack -1;Rack to -1 at 1 gauge
xfer f22 b23
rack 0.0;Rack to 0.0 at 1 gauge
split - b23 f23 1
knit + f23 1
rack -1;Rack to -1 at 1 gauge
xfer f23 b24
rack 0.0;Rack to 0.0 at 1 gauge
split - b24 f24 1
knit + f24 1
rack -1;Rack to -1 at 1 gauge
xfer f24 b25
rack 0.0;Rack to 0.0 at 1 gauge
split - b25 f25 1
knit + f25 1
rack -1;Rack to -1 at 1 gauge
xfer f25 b26
rack 0.0;Rack to 0.0 at 1 gauge
split - b26 f26 1
knit + f26 1
rack -1;Rack to -1 at 1 gauge
xfer f26 b27
rack 0.0;Rack to 0.0 at 1 gauge
split - b27 f27 1
knit + f27 1
rack -1;Rack to -1 at 1 gauge
xfer f27 b28
rack 0.0;Rack to 0.0 at 1 gauge
split - b28 f28 1
knit + f28 1
rack -1;Rack to -1 at 1 gauge
xfer f28 b29
rack 0.0;Rack to 0.0 at 1 gauge
split - b29 f29 1
knit + f29 1
rack -1;Rack to -1 at 1 gauge
xfer f29 b30
rack 0.0;Rack to 0.0 at 1 gauge
split - b30 f30 1
knit + f30 1
rack -1;Rack to -1 at 1 gauge
xfer f30 b31
rack 0.0;Rack to 0.0 at 1 gauge
split - b31 f31 1
knit + f31 1
rack -1;Rack to -1 at 1 gauge
xfer f31 b32
rack 0.0;Rack to 0.0 at 1 gauge
split - b32 f32 1
knit + f32 1
rack -1;Rack to -1 at 1 gauge
xfer f32 b33
rack 0.0;Rack to 0.0 at 1 gauge
split - b33 f33 1
knit + f33 1
rack -1;Rack to -1 at 1 gauge
xfer f33 b34
rack 0.0;Rack to 0.0 at 1 gauge
split - b34 f34 1
knit + f34 1
rack -1;Rack to -1 at 1 gauge
xfer f34 b35
rack 0.0;Rack to 0.0 at 1 gauge
split - b35 f35 1
knit + f35 1
rack -1;Rack to -1 at 1 gauge
xfer f35 b36
rack 0.0;Rack to 0.0 at 1 gauge
split - b36 f36 1
knit + f36 1
rack -1;Rack to -1 at 1 gauge
xfer f36 b37
rack 0.0;Rack to 0.0 at 1 gauge
split - b37 f37 1
knit + f37 1
rack -1;Rack to -1 at 1 gauge
xfer f37 b38
rack 0.0;Rack to 0.0 at 1 gauge
split - b38 f38 1
knit + f38 1
rack -1;Rack to -1 at 1 gauge
xfer f38 b39
rack 0.0;Rack to 0.0 at 1 gauge
split - b39 f39 1
knit + f39 1
rack -1;Rack to -1 at 1 gauge
xfer f39 b40
rack 0.0;Rack to 0.0 at 1 gauge
split - b40 f40 1
knit + f40 1
rack -1;Rack to -1 at 1 gauge
xfer f40 b41
rack 0.0;Rack to 0.0 at 1 gauge
split - b41 f41 1
knit + f41 1
rack -1;Rack to -1 at 1 gauge
xfer f41 b42
rack 0.0;Rack to 0.0 at 1 gauge
split - b42 f42 1
knit + f42 1
rack -1;Rack to -1 at 1 gauge
xfer f42 b43
rack 0.0;Rack to 0.0 at 1 gauge
split - b43 f43 1
knit + f43 1
rack -1;Rack to -1 at 1 gauge
xfer f43 b44
rack 0.0;Rack to 0.0 at 1 gauge
split - b44 f44 1
knit + f44 1
rack -1;Rack to -1 at 1 gauge
xfer f44 b45
rack 0.0;Rack to 0.0 at 1 gauge
split - b45 f45 1
knit + f45 1
rack -1;Rack to -1 at 1 gauge
xfer f45 b46
rack 0.0;Rack to 0.0 at 1 gauge
split - b46 f46 1
knit + f46 1
rack -1;Rack to -1 at 1 gauge
xfer f46 b47
rack 0.0;Rack to 0.0 at 1 gauge
split - b47 f47 1
knit + f47 1
rack -1;Rack to -1 at 1 gauge
xfer f47 b48
rack 0.0;Rack to 0.0 at 1 gauge
split - b48 f48 1
knit + f48 1
rack -1;Rack to -1 at 1 gauge
xfer f48 b49
rack 0.0;Rack to 0.0 at 1 gauge
split - b49 f49 1
knit + f49 1
;KS: Spare knitting on [b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b20, b21, b22, b23, b24, b25, b26, b27, b28, b29, b30, b31, b32, b33, b34, b35, b36, b37, b38, b39, b40, b41, b42, b43, b44, b45, b46, b47, b48, b49]
knit - b49 1
knit - b48 1
knit - b47 1
knit - b46 1
knit - b45 1
knit - b44 1
knit - b43 1
knit - b42 1
knit - b41 1
knit - b40 1
knit - b39 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
outhook 1;Cutting active yarn on 1
