;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;;Machine: SWG091N2
;;Gauge: 13
;;Width: 540
;;Position: Right
inhook 4;Activating carrier 4
;KS: Cast on 50loops from 0to 50
tuck - f49 4
tuck - f47 4
tuck - f45 4
tuck - f43 4
tuck - f41 4
tuck - f39 4
tuck - f37 4
tuck - f35 4
tuck - f33 4
tuck - f31 4
tuck - f29 4
tuck - f27 4
tuck - f25 4
tuck - f23 4
tuck - f21 4
tuck - f19 4
tuck - f17 4
tuck - f15 4
tuck - f13 4
tuck - f11 4
tuck - f9 4
tuck - f7 4
tuck - f5 4
tuck - f3 4
tuck - f1 4
tuck + f0 4
tuck + f2 4
tuck + f4 4
tuck + f6 4
tuck + f8 4
tuck + f10 4
tuck + f12 4
tuck + f14 4
tuck + f16 4
tuck + f18 4
tuck + f20 4
tuck + f22 4
tuck + f24 4
tuck + f26 4
tuck + f28 4
tuck + f30 4
tuck + f32 4
tuck + f34 4
tuck + f36 4
tuck + f38 4
tuck + f40 4
tuck + f42 4
tuck + f44 4
tuck + f46 4
tuck + f48 4
tuck - f49 4
tuck - f47 4
tuck - f45 4
tuck - f43 4
tuck - f41 4
tuck - f39 4
tuck - f37 4
tuck - f35 4
tuck - f33 4
tuck - f31 4
tuck - f29 4
tuck - f27 4
tuck - f25 4
tuck - f23 4
tuck - f21 4
tuck - f19 4
tuck - f17 4
tuck - f15 4
tuck - f13 4
tuck - f11 4
tuck - f9 4
tuck - f7 4
tuck - f5 4
tuck - f3 4
tuck - f1 4
tuck + f0 4
tuck + f2 4
tuck + f4 4
tuck + f6 4
tuck + f8 4
tuck + f10 4
tuck + f12 4
tuck + f14 4
tuck + f16 4
tuck + f18 4
tuck + f20 4
tuck + f22 4
tuck + f24 4
tuck + f26 4
tuck + f28 4
tuck + f30 4
tuck + f32 4
tuck + f34 4
tuck + f36 4
tuck + f38 4
tuck + f40 4
tuck + f42 4
tuck + f44 4
tuck + f46 4
tuck + f48 4
releasehook 4
knit - f49 4
knit - f48 4
knit - f47 4
knit - f46 4
knit - f45 4
knit - f44 4
knit - f43 4
knit - f42 4
knit - f41 4
knit - f40 4
knit - f39 4
knit - f38 4
knit - f37 4
knit - f36 4
knit - f35 4
knit - f34 4
knit - f33 4
knit - f32 4
knit - f31 4
knit - f30 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit + f30 4
knit + f31 4
knit + f32 4
knit + f33 4
knit + f34 4
knit + f35 4
knit + f36 4
knit + f37 4
knit + f38 4
knit + f39 4
knit + f40 4
knit + f41 4
knit + f42 4
knit + f43 4
knit + f44 4
knit + f45 4
knit + f46 4
knit + f47 4
knit + f48 4
knit + f49 4
knit - f49 4
knit - f48 4
knit - f47 4
knit - f46 4
knit - f45 4
knit - f44 4
knit - f43 4
knit - f42 4
knit - f41 4
knit - f40 4
knit - f39 4
knit - f38 4
knit - f37 4
knit - f36 4
knit - f35 4
knit - f34 4
knit - f33 4
knit - f32 4
knit - f31 4
knit - f30 4
knit - f29 4
knit - f28 4
knit - f27 4
knit - f26 4
knit - f25 4
knit - f24 4
knit - f23 4
knit - f22 4
knit - f21 4
knit - f20 4
knit - f19 4
knit - f18 4
knit - f17 4
knit - f16 4
knit - f15 4
knit - f14 4
knit - f13 4
knit - f12 4
knit - f11 4
knit - f10 4
knit - f9 4
knit - f8 4
knit - f7 4
knit - f6 4
knit - f5 4
knit - f4 4
knit - f3 4
knit - f2 4
knit - f1 4
knit - f0 4
knit + f0 4
knit + f1 4
knit + f2 4
knit + f3 4
knit + f4 4
knit + f5 4
knit + f6 4
knit + f7 4
knit + f8 4
knit + f9 4
knit + f10 4
knit + f11 4
knit + f12 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit + f30 4
knit + f31 4
knit + f32 4
knit + f33 4
knit + f34 4
knit + f35 4
knit + f36 4
knit + f37 4
knit + f38 4
knit + f39 4
knit + f40 4
knit + f41 4
knit + f42 4
knit + f43 4
knit + f44 4
knit + f45 4
knit + f46 4
knit + f47 4
knit + f48 4
knit + f49 4
rack 1;Rack to 1 at 1 gauge
xfer f49 b48
xfer f47 b46
xfer f45 b44
xfer f43 b42
xfer f41 b40
xfer f39 b38
xfer f37 b36
xfer f35 b34
xfer f33 b32
xfer f31 b30
xfer f29 b28
xfer f27 b26
xfer f25 b24
xfer f23 b22
xfer f21 b20
xfer f19 b18
xfer f17 b16
xfer f15 b14
xfer f13 b12
xfer f11 b10
xfer f9 b8
xfer f7 b6
xfer f5 b4
xfer f3 b2
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b48 4
knit - f48 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b46 4
knit - f46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b44 4
knit - f44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b42 4
knit - f42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b40 4
knit - f40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b38 4
knit - f38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b36 4
knit - f36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b34 4
knit - f34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b32 4
knit - f32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b30 4
knit - f30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b28 4
knit - f28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b26 4
knit - f26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b24 4
knit - f24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b22 4
knit - f22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b20 4
knit - f20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b18 4
knit - f18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b16 4
knit - f16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b14 4
knit - f14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b12 4
knit - f12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b10 4
knit - f10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b8 4
knit - f8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b6 4
knit - f6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b4 4
knit - f4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b2 4
knit - f2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck - b0 4
knit - f0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f0 4
knit + b0 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f2 4
knit + b2 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f4 4
knit + b4 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f6 4
knit + b6 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f8 4
knit + b8 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f10 4
knit + b10 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f12 4
knit + b12 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f14 4
knit + b14 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f16 4
knit + b16 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f18 4
knit + b18 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f20 4
knit + b20 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f22 4
knit + b22 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f24 4
knit + b24 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f26 4
knit + b26 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f28 4
knit + b28 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f30 4
knit + b30 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f32 4
knit + b32 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f34 4
knit + b34 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f36 4
knit + b36 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f38 4
knit + b38 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f40 4
knit + b40 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f42 4
knit + b42 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f44 4
knit + b44 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f46 4
knit + b46 4
rack 0.0;Reset rack from all_needle
rack 0.25;All Needle racking 0.0 to right
tuck + f48 4
knit + b48 4
rack 0.0;Reset rack from all_needle
rack 1;Rack to 1 at 1 gauge
xfer b48 f49
xfer b46 f47
xfer b44 f45
xfer b42 f43
xfer b40 f41
xfer b38 f39
xfer b36 f37
xfer b34 f35
xfer b32 f33
xfer b30 f31
xfer b28 f29
xfer b26 f27
xfer b24 f25
xfer b22 f23
xfer b20 f21
xfer b18 f19
xfer b16 f17
xfer b14 f15
xfer b12 f13
xfer b10 f11
xfer b8 f9
xfer b6 f7
xfer b4 f5
xfer b2 f3
xfer b0 f1
rack 0.0;Rack to 0.0 at 1 gauge
rack 1;Rack to 1 at 1 gauge
xfer f49 b48
rack 0.0;Rack to 0.0 at 1 gauge
split + b48 f48 4
knit - f48 4
rack 1;Rack to 1 at 1 gauge
xfer f48 b47
rack 0.0;Rack to 0.0 at 1 gauge
split + b47 f47 4
knit - f47 4
rack 1;Rack to 1 at 1 gauge
xfer f47 b46
rack 0.0;Rack to 0.0 at 1 gauge
split + b46 f46 4
knit - f46 4
rack 1;Rack to 1 at 1 gauge
xfer f46 b45
rack 0.0;Rack to 0.0 at 1 gauge
split + b45 f45 4
knit - f45 4
rack 1;Rack to 1 at 1 gauge
xfer f45 b44
rack 0.0;Rack to 0.0 at 1 gauge
split + b44 f44 4
knit - f44 4
rack 1;Rack to 1 at 1 gauge
xfer f44 b43
rack 0.0;Rack to 0.0 at 1 gauge
split + b43 f43 4
knit - f43 4
rack 1;Rack to 1 at 1 gauge
xfer f43 b42
rack 0.0;Rack to 0.0 at 1 gauge
split + b42 f42 4
knit - f42 4
rack 1;Rack to 1 at 1 gauge
xfer f42 b41
rack 0.0;Rack to 0.0 at 1 gauge
split + b41 f41 4
knit - f41 4
rack 1;Rack to 1 at 1 gauge
xfer f41 b40
rack 0.0;Rack to 0.0 at 1 gauge
split + b40 f40 4
knit - f40 4
rack 1;Rack to 1 at 1 gauge
xfer f40 b39
rack 0.0;Rack to 0.0 at 1 gauge
split + b39 f39 4
knit - f39 4
rack 1;Rack to 1 at 1 gauge
xfer f39 b38
rack 0.0;Rack to 0.0 at 1 gauge
split + b38 f38 4
knit - f38 4
rack 1;Rack to 1 at 1 gauge
xfer f38 b37
rack 0.0;Rack to 0.0 at 1 gauge
split + b37 f37 4
knit - f37 4
rack 1;Rack to 1 at 1 gauge
xfer f37 b36
rack 0.0;Rack to 0.0 at 1 gauge
split + b36 f36 4
knit - f36 4
rack 1;Rack to 1 at 1 gauge
xfer f36 b35
rack 0.0;Rack to 0.0 at 1 gauge
split + b35 f35 4
knit - f35 4
rack 1;Rack to 1 at 1 gauge
xfer f35 b34
rack 0.0;Rack to 0.0 at 1 gauge
split + b34 f34 4
knit - f34 4
rack 1;Rack to 1 at 1 gauge
xfer f34 b33
rack 0.0;Rack to 0.0 at 1 gauge
split + b33 f33 4
knit - f33 4
rack 1;Rack to 1 at 1 gauge
xfer f33 b32
rack 0.0;Rack to 0.0 at 1 gauge
split + b32 f32 4
knit - f32 4
rack 1;Rack to 1 at 1 gauge
xfer f32 b31
rack 0.0;Rack to 0.0 at 1 gauge
split + b31 f31 4
knit - f31 4
rack 1;Rack to 1 at 1 gauge
xfer f31 b30
rack 0.0;Rack to 0.0 at 1 gauge
split + b30 f30 4
knit - f30 4
rack 1;Rack to 1 at 1 gauge
xfer f30 b29
rack 0.0;Rack to 0.0 at 1 gauge
split + b29 f29 4
knit - f29 4
rack 1;Rack to 1 at 1 gauge
xfer f29 b28
rack 0.0;Rack to 0.0 at 1 gauge
split + b28 f28 4
knit - f28 4
rack 1;Rack to 1 at 1 gauge
xfer f28 b27
rack 0.0;Rack to 0.0 at 1 gauge
split + b27 f27 4
knit - f27 4
rack 1;Rack to 1 at 1 gauge
xfer f27 b26
rack 0.0;Rack to 0.0 at 1 gauge
split + b26 f26 4
knit - f26 4
rack 1;Rack to 1 at 1 gauge
xfer f26 b25
rack 0.0;Rack to 0.0 at 1 gauge
split + b25 f25 4
knit - f25 4
rack 1;Rack to 1 at 1 gauge
xfer f25 b24
rack 0.0;Rack to 0.0 at 1 gauge
split + b24 f24 4
knit - f24 4
rack 1;Rack to 1 at 1 gauge
xfer f24 b23
rack 0.0;Rack to 0.0 at 1 gauge
split + b23 f23 4
knit - f23 4
rack 1;Rack to 1 at 1 gauge
xfer f23 b22
rack 0.0;Rack to 0.0 at 1 gauge
split + b22 f22 4
knit - f22 4
rack 1;Rack to 1 at 1 gauge
xfer f22 b21
rack 0.0;Rack to 0.0 at 1 gauge
split + b21 f21 4
knit - f21 4
rack 1;Rack to 1 at 1 gauge
xfer f21 b20
rack 0.0;Rack to 0.0 at 1 gauge
split + b20 f20 4
knit - f20 4
rack 1;Rack to 1 at 1 gauge
xfer f20 b19
rack 0.0;Rack to 0.0 at 1 gauge
split + b19 f19 4
knit - f19 4
rack 1;Rack to 1 at 1 gauge
xfer f19 b18
rack 0.0;Rack to 0.0 at 1 gauge
split + b18 f18 4
knit - f18 4
rack 1;Rack to 1 at 1 gauge
xfer f18 b17
rack 0.0;Rack to 0.0 at 1 gauge
split + b17 f17 4
knit - f17 4
rack 1;Rack to 1 at 1 gauge
xfer f17 b16
rack 0.0;Rack to 0.0 at 1 gauge
split + b16 f16 4
knit - f16 4
rack 1;Rack to 1 at 1 gauge
xfer f16 b15
rack 0.0;Rack to 0.0 at 1 gauge
split + b15 f15 4
knit - f15 4
rack 1;Rack to 1 at 1 gauge
xfer f15 b14
rack 0.0;Rack to 0.0 at 1 gauge
split + b14 f14 4
knit - f14 4
rack 1;Rack to 1 at 1 gauge
xfer f14 b13
rack 0.0;Rack to 0.0 at 1 gauge
split + b13 f13 4
knit - f13 4
rack 1;Rack to 1 at 1 gauge
xfer f13 b12
rack 0.0;Rack to 0.0 at 1 gauge
split + b12 f12 4
knit - f12 4
rack 1;Rack to 1 at 1 gauge
xfer f12 b11
rack 0.0;Rack to 0.0 at 1 gauge
split + b11 f11 4
knit - f11 4
rack 1;Rack to 1 at 1 gauge
xfer f11 b10
rack 0.0;Rack to 0.0 at 1 gauge
split + b10 f10 4
knit - f10 4
rack 1;Rack to 1 at 1 gauge
xfer f10 b9
rack 0.0;Rack to 0.0 at 1 gauge
split + b9 f9 4
knit - f9 4
rack 1;Rack to 1 at 1 gauge
xfer f9 b8
rack 0.0;Rack to 0.0 at 1 gauge
split + b8 f8 4
knit - f8 4
rack 1;Rack to 1 at 1 gauge
xfer f8 b7
rack 0.0;Rack to 0.0 at 1 gauge
split + b7 f7 4
knit - f7 4
rack 1;Rack to 1 at 1 gauge
xfer f7 b6
rack 0.0;Rack to 0.0 at 1 gauge
split + b6 f6 4
knit - f6 4
rack 1;Rack to 1 at 1 gauge
xfer f6 b5
rack 0.0;Rack to 0.0 at 1 gauge
split + b5 f5 4
knit - f5 4
rack 1;Rack to 1 at 1 gauge
xfer f5 b4
rack 0.0;Rack to 0.0 at 1 gauge
split + b4 f4 4
knit - f4 4
rack 1;Rack to 1 at 1 gauge
xfer f4 b3
rack 0.0;Rack to 0.0 at 1 gauge
split + b3 f3 4
knit - f3 4
rack 1;Rack to 1 at 1 gauge
xfer f3 b2
rack 0.0;Rack to 0.0 at 1 gauge
split + b2 f2 4
knit - f2 4
rack 1;Rack to 1 at 1 gauge
xfer f2 b1
rack 0.0;Rack to 0.0 at 1 gauge
split + b1 f1 4
knit - f1 4
rack 1;Rack to 1 at 1 gauge
xfer f1 b0
rack 0.0;Rack to 0.0 at 1 gauge
split + b0 f0 4
knit - f0 4
;KS: Spare knitting on [b48, b47, b46, b45, b44, b43, b42, b41, b40, b39, b38, b37, b36, b35, b34, b33, b32, b31, b30, b29, b28, b27, b26, b25, b24, b23, b22, b21, b20, b19, b18, b17, b16, b15, b14, b13, b12, b11, b10, b9, b8, b7, b6, b5, b4, b3, b2, b1, b0]
knit + b0 4
knit + b1 4
knit + b2 4
knit + b3 4
knit + b4 4
knit + b5 4
knit + b6 4
knit + b7 4
knit + b8 4
knit + b9 4
knit + b10 4
knit + b11 4
knit + b12 4
knit + b13 4
knit + b14 4
knit + b15 4
knit + b16 4
knit + b17 4
knit + b18 4
knit + b19 4
knit + b20 4
knit + b21 4
knit + b22 4
knit + b23 4
knit + b24 4
knit + b25 4
knit + b26 4
knit + b27 4
knit + b28 4
knit + b29 4
knit + b30 4
knit + b31 4
knit + b32 4
knit + b33 4
knit + b34 4
knit + b35 4
knit + b36 4
knit + b37 4
knit + b38 4
knit + b39 4
knit + b40 4
knit + b41 4
knit + b42 4
knit + b43 4
knit + b44 4
knit + b45 4
knit + b46 4
knit + b47 4
knit + b48 4
outhook 4;Cutting active yarn on 4
